#!/usr/bin/env python3
"""Iteration-free E1(x), Ei(x) for v12-d perf (generate-don't-transcribe; gate = 1e-12 rel + 1e-13 abs vs scipy).
  E1, x in (0,1]:  E1 = -ln x + A(x)            A = E1+ln x is ENTIRE  (poly in t)
  E1, x in [1,8] : E1 = e^-x/x * RB1(x)         RB1 = rational; B = x e^x E1 (x=0 log-branch ⇒ rational, not poly)
  E1, x in [8,40]: E1 = e^-x/x * RB2(x)
  Ei, x in (0,2]:  Ei =  ln x + C(x)            C = Ei-ln x is ENTIRE; weight capped near Ei's zero (~0.3725)
  Ei, x in [2,8] : Ei = e^x/x  * RD1(x)         RD = rational; D = x e^-x Ei
  Ei, x in [8,40]: Ei = e^x/x  * RD2(x)
beyond x=40 the asymptotic series is already <1e-16 relative (fast)."""
import sys
import numpy as np
from numpy.polynomial import chebyshev as Ch
from scipy import special

HI = 40.0


def cheb_nodes(a, b, n):
    k = np.arange(n)
    return 0.5 * (a + b) + 0.5 * (b - a) * np.cos((2 * k + 1) * np.pi / (2 * n))


def poly_fit(x, f, scale, a, b, deg, npass=25):
    t = (2 * x - (a + b)) / (b - a)
    w0 = 1.0 / scale
    w = w0.copy()
    best = None
    for _ in range(npass):
        c = Ch.chebfit(t, f, deg, w=w)
        r = np.abs(Ch.chebval(t, c) - f) / scale
        if best is None or r.max() < best[1]:
            best = (c, r.max())
        g = np.clip((r / max(r.max(), 1e-300)) ** 0.5, 0.3, 1.0)
        w = w0 * (0.4 + 0.6 * g / g.mean())
    return Ch.cheb2poly(best[0]), best[1]  # monomial-in-t coeffs


def rat_fit(x, f, scale, a, b, m, n, npass=60):
    t = (2 * x - (a + b)) / (b - a)
    ac = np.arccos(np.clip(t, -1, 1))
    TP = np.cos(np.outer(ac, np.arange(m + 1)))
    TQ = np.cos(np.outer(ac, np.arange(1, n + 1)))
    w = 1.0 / scale
    best = None
    for _ in range(npass):
        A = np.hstack([TP * w[:, None], -(f * w)[:, None] * TQ])
        sol, *_ = np.linalg.lstsq(A, f * w, rcond=None)
        p, qj = sol[:m + 1], sol[m + 1:]
        Qv = 1.0 + TQ @ qj
        r = np.abs((TP @ p) / Qv - f) / scale
        if best is None or r.max() < best[1]:
            best = ((p, np.concatenate([[1.0], qj])), r.max())
        w = (1.0 / scale) / np.abs(Qv) * np.clip((r / max(r.max(), 1e-300)) ** 0.5, 0.25, 1.0)
    (p, q), e = best
    return Ch.cheb2poly(p), Ch.cheb2poly(q), e  # monomial-in-t


def arr(name, c):
    print(f"inline constexpr double k{name}[] = {{{', '.join(f'{v:.17e}' for v in c)}}};")


print("// GENERATED by gen_expint_poly.py — iteration-free E1/Ei (v12-d perf). Coeffs are monomial in t=map(x,[a,b]).")
print("#pragma once")
print("namespace crd::hesap::special::detail {")
print(f"inline constexpr double kExpintHi = {HI};")
errs = []

# E1 low poly A over (0,1]
x = cheb_nodes(1e-9, 1.0, 7000)
cA, e = poly_fit(x, special.exp1(x) + np.log(x), np.abs(special.exp1(x)), 0.0, 1.0, 13)
arr("E1lowA", cA)
errs.append(("E1lowA", e))
# E1 rational pieces  (B = x e^x E1, E1 = e^-x/x B)
for tag, a, b, m, n in [("E1B1", 1.0, 8.0, 12, 10), ("E1B2", 8.0, HI, 12, 10)]:
    x = cheb_nodes(a, b, 7000)
    bb = x * np.exp(x) * special.exp1(x)
    p, q, e = rat_fit(x, bb, bb, a, b, m, n)
    arr(tag + "P", p)
    arr(tag + "Q", q)
    errs.append((tag, e))
# Ei low poly C over (0,2], cap weight near Ei zero
x = cheb_nodes(1e-9, 2.0, 7000)
ei = special.expi(x)
cC, e = poly_fit(x, ei - np.log(x), np.abs(ei) + 0.1, 0.0, 2.0, 16)
arr("EilowC", cC)
errs.append(("EilowC", e))
# Ei rational pieces  (D = x e^-x Ei, Ei = e^x/x D)
for tag, a, b, m, n in [("EiD1", 2.0, 8.0, 12, 10), ("EiD2", 8.0, 18.0, 12, 10), ("EiD3", 18.0, HI, 10, 8)]:
    x = cheb_nodes(a, b, 7000)
    dd = x * np.exp(-x) * special.expi(x)
    p, q, e = rat_fit(x, dd, dd, a, b, m, n)
    arr(tag + "P", p)
    arr(tag + "Q", q)
    errs.append((tag, e))
print("} // namespace")
for name, e in errs:
    print(f"// {name}: {e:.2e}", file=sys.stderr)
worst = max(e for _, e in errs)
print(f"// WORST = {worst:.2e}", file=sys.stderr)
sys.exit(0 if worst < 1e-12 else 1)
