// kir_autotune — ADR-0098 §4 · AS-2b: the OFFLINE auto-scheduler CLI. Runs the CKIR GEMM schedule search on the GPU for a set of
// shapes and emits the checked-in tuning DB (`ckir_tuning_db.inc`) that `select_schedule` replays deterministically — "tune
// offline, replay from the DB, never at runtime" (ADR-0098). Usage:
//   kir_autotune [SIZE ...] [out.inc]
// SIZE args are square-GEMM sizes (default 512 1024 2048); a trailing non-numeric arg is the output path (else stdout).
#include <crd/kir/cuda/autotune_cuda.hpp>
#include <crd/memory/allocators/tlsf_allocator.hpp>

#include <cstdio>
#include <cstdlib>

int main(int argc, char** argv)
{
    crd::memory::TlsfAllocator alloc(512U << 20U);
    crd::kir::KirBackendCuda   cu(&alloc);
    if (!cu.valid())
    {
        std::fprintf(stderr, "kir_autotune: no CUDA device/driver — cannot tune.\n");
        return 1;
    }

    struct Shape { int m; int n; int k; };
    Shape       shapes[64];
    int         nshapes = 0;
    const char* outpath = nullptr;
    for (int i = 1; i < argc; ++i)
    {
        // "MxNxK" (rectangular) or a bare "S" (square S×S×S); a non-numeric arg is the output path.
        int         m = 0;
        int         n = 0;
        int         k = 0;
        const char* p = argv[i];
        if (std::sscanf(p, "%dx%dx%d", &m, &n, &k) == 3 && m > 0 && n > 0 && k > 0)
        {
            if (nshapes < 64) { shapes[nshapes++] = {m, n, k}; }
        }
        else if (const int s = std::atoi(p); s > 0)
        {
            if (nshapes < 64) { shapes[nshapes++] = {s, s, s}; }
        }
        else { outpath = p; }
    }
    if (nshapes == 0)
    {
        // a default LADDER: square + rectangular (MLP-shaped) so the DB generalises, not just square.
        const Shape def[] = {{512, 512, 512}, {1024, 1024, 1024}, {2048, 2048, 2048}, {4096, 4096, 4096},
                             {2048, 512, 1024}, {4096, 1024, 256}, {1024, 4096, 512}};
        for (const Shape& d : def) { if (nshapes < 64) { shapes[nshapes++] = d; } }
    }

    crd::kir::AutotuneResult results[64];
    int                      nres = 0;
    for (int i = 0; i < nshapes; ++i)
    {
        const int m = shapes[i].m;
        const int n = shapes[i].n;
        const int k = shapes[i].k;
        std::fprintf(stderr, "[kir_autotune] tuning GEMM %dx%dx%d ...\n", m, n, k);
        const crd::kir::AutotuneResult r = crd::kir::autotune_contract(cu, m, n, k, 16, true, &alloc);
        if (!r.ok) { std::fprintf(stderr, "[kir_autotune]   no valid schedule (skipped)\n"); continue; }
        const double gflops = 2.0 * static_cast<double>(m) * n * k / (r.ms * 1.0e6);
        std::fprintf(stderr,
                     "[kir_autotune]   winner %.3f ms (%.0f GFLOP/s) BM%d BN%d BK%d TM%d TN%d NT%d DB%d; "
                     "naive %.3f ms (%.1fx); %d/%d correct\n",
                     r.ms, gflops, r.sched.bm, r.sched.bn, r.sched.bk, r.sched.tm, r.sched.tn, r.sched.nt,
                     r.sched.double_buffer ? 1 : 0, r.naive_ms, r.naive_ms > 0.0 ? r.naive_ms / r.ms : 0.0, r.correct,
                     r.measured);
        results[nres++] = r;
    }

    std::FILE* f = (outpath != nullptr) ? std::fopen(outpath, "w") : stdout;
    if (f == nullptr) { std::fprintf(stderr, "kir_autotune: cannot open %s\n", outpath); return 2; }
    std::fprintf(f, "// ckir_tuning_db.inc - the CKIR AUTO-TUNED SCHEDULE DATABASE (ADR-0098 sec.4, AS-2). GENERATED by kir_autotune\n");
    std::fprintf(f, "// from on-GPU measurements; DO NOT edit by hand -- re-run kir_autotune. Included inside crd::kir by ckir_tile.hpp.\n");
    std::fprintf(f, "// Row: { op, M, N, K, { kind, BM,BN,BK, WM,WN,WNITER, TM,TN, NT, double_buffer, fma } }.\n");
    for (int i = 0; i < nres; ++i)
    {
        const crd::kir::AutotuneResult& r = results[i];
        std::fprintf(f, "{ KOp::Contract, %d, %d, %d, { Sched::WarpTiled, %d, %d, %d, %d, %d, %d, %d, %d, %d, %s, %s } },\n",
                     r.m, r.n, r.k, r.sched.bm, r.sched.bn, r.sched.bk, r.sched.wm, r.sched.wn, r.sched.wniter, r.sched.tm,
                     r.sched.tn, r.sched.nt, r.sched.double_buffer ? "true" : "false", r.sched.fma ? "true" : "false");
    }
    if (outpath != nullptr) { std::fclose(f); std::fprintf(stderr, "[kir_autotune] wrote %d entries -> %s\n", nres, outpath); }
    return 0;
}
