// test_ckir_subgroup.cpp — B-cmp: the CKIR SUBGROUP (wave) ops on the CPU oracle. `subgroup_ballot` + `subgroup_ballot_excl_count`
// compose into a cheap DETERMINISTIC within-subgroup rank — the building block of the radix-sort crush rank + warp-scan. The
// oracle models a FIXED 32-lane subgroup (bit-exact requires the GPU forced to the same size). This validates the IR + oracle;
// the oracle-vs-Vulkan bit-exactness check lives in the gpu-context suite.

#include <crd/kir/ckir.hpp>
#include <crd/kir/ckir_kernel_eval.hpp>

#include <crd/containers/array.hpp>
#include <crd/memory/allocators/tlsf_allocator.hpp>

#include <catch2/catch_test_macros.hpp>

namespace kir = crd::kir;

TEST_CASE("B-cmp: CKIR subgroup ballot+exclusive-count == within-subgroup odd rank (oracle)", "[kir][kernel][subgroup]")
{
    constexpr int              threads = 64; // two 32-lane subgroups
    crd::memory::TlsfAllocator alloc(4U << 20U);

    // out[t] = # lanes l in [subgroup_base, t) whose in[l] is ODD.
    kir::KGraph g(&alloc);
    const auto  ku      = [&](crd::u32 v) { return g.constant(static_cast<crd::f64>(v), kir::make_shape({1}), kir::DType::U32); };
    const int   in_buf  = g.buffer_decl(kir::DType::U32, 0, 0, false);
    const int   out_buf = g.buffer_decl(kir::DType::U32, 0, 1, true);
    const int   tid     = g.builtin(kir::KBuiltin::LocalInvocationIndex);
    const int   mark    = g.kernel_stmt_mark();
    const int   key     = g.buffer_load(in_buf, tid);
    const int   odd     = g.binary(kir::KOp::BitAnd, key, ku(1)); // predicate: low bit
    const int   mask    = g.subgroup_ballot(odd);
    const int   rank    = g.subgroup_ballot_excl_count(mask);
    g.stmt_buffer_store(out_buf, tid, rank);
    kir::KEntry e;
    e.stage             = kir::KStage::Compute;
    e.local_size[0]     = static_cast<crd::u32>(threads);
    e.kernel_body_begin = mark;
    e.kernel_body_count = g.stmt_count() - mark;

    crd::containers::Array<crd::f64> in(&alloc);
    crd::containers::Array<crd::f64> out(&alloc);
    in.resize(threads);
    out.resize(threads, -1.0);
    for (int i = 0; i < threads; ++i) { in[static_cast<crd::usize>(i)] = static_cast<crd::f64>(static_cast<crd::u32>(i * 2654435761U)); }

    kir::KernelBuffer kb[2] = {{in.data(), threads, 0, 0}, {out.data(), threads, 0, 1}};
    kir::eval_cpu_kernel(g, e, kb, 2, e.local_size[0], &alloc, 1U);

    int bad = 0;
    for (int t = 0; t < threads; ++t)
    {
        const int sgbase = (t / 32) * 32;
        int       ref    = 0;
        for (int l = sgbase; l < t; ++l) { if ((static_cast<crd::u32>(in[static_cast<crd::usize>(l)]) & 1U) != 0U) { ++ref; } }
        if (static_cast<int>(out[static_cast<crd::usize>(t)]) != ref) { ++bad; }
    }
    CHECK(bad == 0);
}

// CUDA-BACKEND sort campaign: emit the ONESWEEP pipeline as native CUDA source (hardware __match_any_sync rank) into
// bench/gpu-compute/ckir_onesweep_gen.cu — the SAME IR that runs bit-exact on the oracle + Vulkan, lowered to CUB's own
// arena. Hidden tool test ([.emit-cuda-sort]); the bench driver + CUB gold live in bench/gpu-compute/ckir_onesweep_bench.cu.
#include <crd/kir/ckir_cuda.hpp>
#include <crd/kir/ckir_sort.hpp>

#include <fstream>

TEST_CASE("emit ONESWEEP sort as CUDA", "[.emit-cuda-sort]")
{
    crd::memory::TlsfAllocator alloc(64U << 20U);
    std::ofstream              f("D:/Dev/cerid/bench/gpu-compute/ckir_onesweep_gen.cu", std::ios::binary);
    REQUIRE(f.is_open());
    f << "// GENERATED by test_ckir_subgroup.cpp [.emit-cuda-sort] -- CKIR onesweep radix sort lowered to CUDA.\n";
    f << "// Configs: A = epb 2048 / 256 threads, B = epb 4096 / 256 threads. Rank = hardware __match_any_sync.\n";

    const auto emit = [&](const char* name, kir::KGraph& g, const kir::KEntry& e) {
        kir::GlslKernel k(&alloc);
        REQUIRE(kir::emit_compute_kernel_cuda(g, e, &alloc, k));
        // rename the fixed `ckir` entry to a unique kernel name
        const char* p   = k.source.c_str();
        const char* hit = nullptr;
        for (const char* q = p; *q != '\0'; ++q)
        {
            if (q[0] == 'c' && q[1] == 'k' && q[2] == 'i' && q[3] == 'r' && q[4] == '(') { hit = q; break; }
        }
        REQUIRE(hit != nullptr);
        f.write(p, hit - p);
        f << name << "(";
        f.write(hit + 5, static_cast<std::streamsize>(k.source.size() - static_cast<crd::usize>(hit - p) - 5U));
        f << "\n";
    };

    constexpr int radix_bits = 8;
    { kir::KGraph g(&alloc); emit("k_clear", g, kir::build_sort_clear(g, 4 * 256 + 4 + 4 * 8192 * 256, 256)); } // worst-case total (epb 2048)
    { kir::KGraph g(&alloc); emit("k_ghist_a", g, kir::build_sort_ghist(g, 2048, 256, radix_bits)); }
    { kir::KGraph g(&alloc); emit("k_ghist_b", g, kir::build_sort_ghist(g, 4096, 256, radix_bits)); }
    { kir::KGraph g(&alloc); emit("k_gbase", g, kir::build_sort_gbase(g, radix_bits)); }
    for (int p = 0; p < 4; ++p)
    {
        kir::KGraph ga(&alloc);
        char        na[16] = {'k', '_', 's', 'a', static_cast<char>('0' + p), '\0'};
        emit(na, ga, kir::build_sort_scatter_onesweep(ga, 2048, 256, radix_bits, p * 8, p, 8192, true));
        kir::KGraph gb(&alloc);
        char        nb[16] = {'k', '_', 's', 'b', static_cast<char>('0' + p), '\0'};
        emit(nb, gb, kir::build_sort_scatter_onesweep(gb, 4096, 256, radix_bits, p * 8, p, 4096, true));
        kir::KGraph gc(&alloc);
        char        nc[16] = {'k', '_', 's', 'c', static_cast<char>('0' + p), '\0'};
        emit(nc, gc, kir::build_sort_scatter_onesweep(gc, 8192, 256, radix_bits, p * 8, p, 2048, true)); // 41KB static shared, 128B runs
    }
    { kir::KGraph g(&alloc); emit("k_ghist_c", g, kir::build_sort_ghist(g, 8192, 256, radix_bits)); }
    f.close();
    CHECK(true);
}
