// crd-hesap-motion v13-n/o/p/q - trajectory generation: SQUAD (attitude) / clothoid (Fresnel) / NURBS (exact conics) /
// min-jerk+min-snap (BCs) / jerk-limited S-curve+trapezoidal profiles / Kochanek-Bartels. Gated on the geometric +
// kinematic invariants (unit-norm, curvature-linearity, exact circle, boundary conditions, limit conformance).

#include <crd/hesap/motion/motion.hpp>
#include <crd/memory/allocators/tlsf_allocator.hpp>

#include <catch2/catch_test_macros.hpp>
#include <cmath>

namespace m = crd::hesap::motion;
using crd::f64;
using crd::containers::ConstSpan;
using Q = crd::math::Quat<f64>;

namespace
{
bool close(f64 g, f64 r, f64 rtol, f64 atol) noexcept
{
    return std::abs(g - r) <= atol + rtol * std::abs(r);
}
Q axis_angle(f64 ax, f64 ay, f64 az, f64 ang) noexcept
{
    const f64 n = std::sqrt(ax * ax + ay * ay + az * az);
    const f64 s = std::sin(ang / 2) / n;
    return Q(ax * s, ay * s, az * s, std::cos(ang / 2));
}
} // namespace

TEST_CASE("v13-n: SQUAD - unit-norm preserved + endpoint interpolation", "[v13-n][motion]")
{
    const Q q0 = axis_angle(1, 0, 0, 0.3);
    const Q q1 = axis_angle(0, 1, 0, 0.9);
    const Q q2 = axis_angle(0.3, 0.6, 0.2, 1.2);
    const Q q3 = axis_angle(1, 1, 0, 0.7);
    const Q s1 = m::squad_control_point<f64>(q0, q1, q2);
    const Q s2 = m::squad_control_point<f64>(q1, q2, q3);
    for (int i = 0; i <= 10; ++i)
    {
        const f64 t = i / 10.0;
        const Q q = m::squad<f64>(q1, q2, s1, s2, t);
        CHECK(close(std::sqrt(crd::math::length_squared(q)), 1.0, 1e-12, 1e-12)); // unit-norm
    }
    // endpoints (t=0 -> q1, t=1 -> q2, up to sign)
    const Q at0 = m::squad<f64>(q1, q2, s1, s2, 0.0);
    const Q at1 = m::squad<f64>(q1, q2, s1, s2, 1.0);
    CHECK(close(std::abs(crd::math::dot(at0, q1)), 1.0, 1e-12, 1e-12));
    CHECK(close(std::abs(crd::math::dot(at1, q2)), 1.0, 1e-12, 1e-12));
}

TEST_CASE("v13-n: quaternion cubic B-spline - unit-norm + C0/C1 continuity", "[v13-n][motion]")
{
    const Q qc[6] = {axis_angle(1, 0, 0, 0.0),       axis_angle(1, 0, 0, 0.6), axis_angle(0, 1, 0, 1.1),
                     axis_angle(0.3, 0.5, 0.2, 0.8), axis_angle(1, 1, 0, 1.3), axis_angle(0, 0, 1, 0.5)};
    for (int i = 0; i <= 10; ++i)
    {
        const Q q = m::quaternion_bspline<f64>(qc[1], qc[2], qc[3], qc[4], i / 10.0);
        CHECK(close(std::sqrt(crd::math::length_squared(q)), 1.0, 1e-12, 1e-12));
    }
    const Q left = m::quaternion_bspline<f64>(qc[1], qc[2], qc[3], qc[4], 1.0);
    const Q right = m::quaternion_bspline<f64>(qc[2], qc[3], qc[4], qc[5], 0.0);
    CHECK(close(std::abs(crd::math::dot(left, right)), 1.0, 1e-9, 1e-9)); // C0 at the knot
    const f64 h = 1e-5;
    const Q lv = m::quaternion_bspline<f64>(qc[1], qc[2], qc[3], qc[4], 1.0 - h);
    const Q rv = m::quaternion_bspline<f64>(qc[2], qc[3], qc[4], qc[5], h);
    const f64 dl[4] = {(left.x - lv.x) / h, (left.y - lv.y) / h, (left.z - lv.z) / h, (left.w - lv.w) / h};
    const f64 dr[4] = {(rv.x - right.x) / h, (rv.y - right.y) / h, (rv.z - right.z) / h, (rv.w - right.w) / h};
    f64 dvel = 0.0;
    for (int k = 0; k < 4; ++k)
    {
        dvel += (dl[k] - dr[k]) * (dl[k] - dr[k]);
    }
    CHECK(std::sqrt(dvel) < 1e-3); // C1 (finite-diff tolerance)
}

TEST_CASE("v13-p: minimum-snap multi-segment QP - waypoints + C3 continuity + BCs", "[v13-p][motion]")
{
    crd::memory::TlsfAllocator alloc(1U << 22);
    const f64 wp[5] = {0.0, 2.0, -1.0, 3.0, 1.0};
    const f64 times[5] = {0.0, 1.0, 2.0, 3.0, 4.0};
    constexpr int deg = 7;
    constexpr int nseg = 4;
    f64 coeffs[nseg * (deg + 1)];
    REQUIRE(m::min_snap_trajectory<f64>(&alloc, wp, times, nseg, deg, 4, 3, coeffs));
    auto seg = [&](int j)
    {
        return &coeffs[j * (deg + 1)];
    };
    for (int j = 0; j < nseg; ++j)
    {
        CHECK(close(m::poly_eval_deriv<f64>(seg(j), deg, 0.0, 0), wp[j], 1e-8, 1e-9));
        CHECK(close(m::poly_eval_deriv<f64>(seg(j), deg, times[j + 1] - times[j], 0), wp[j + 1], 1e-8, 1e-9));
    }
    for (int j = 0; j < nseg - 1; ++j)
    {
        const f64 tj = times[j + 1] - times[j];
        for (int order = 1; order <= 3; ++order)
        {
            CHECK(close(m::poly_eval_deriv<f64>(seg(j), deg, tj, order),
                        m::poly_eval_deriv<f64>(seg(j + 1), deg, 0.0, order), 1e-6, 1e-7));
        }
    }
    CHECK(close(m::poly_eval_deriv<f64>(seg(0), deg, 0.0, 1), 0.0, 1e-8, 1e-8));
    CHECK(close(m::poly_eval_deriv<f64>(seg(nseg - 1), deg, times[nseg] - times[nseg - 1], 1), 0.0, 1e-8, 1e-8));
    CHECK(!m::min_snap_trajectory<f64>(&alloc, wp, times, nseg, 5, 4, 3, coeffs)); // deg < 2*snap-1
}

namespace
{
// generated by build/gen_otg_ref.py — ruckig 0.17.3 reference (arbitrary boundary states)
struct OtgRef
{
    double v0, a0, vf, af, pf, vmax, amax, jmax, dur;
};
constexpr OtgRef kOtgRef[] = {
    {0, 0, 0, 0, 10, 2, 1.5, 3, 6.8333333333},
    {1.5, 0, 0, 0, 10, 2, 1.5, 3, 6.0187287393},
    {-1, 0.5, 0, 0, 10, 2, 1.5, 3, 7.5865162037},
    {0, 0, 1, 0, 10, 2, 1.5, 3, 6.2083333333},
    {0.5, 0.3, -0.8, 0.4, 10, 2, 1.5, 3, 7.3692717593},
    {3, 0, 0, 0, 10, 2, 1.5, 3, 5.7616037607},
    {1.0, -0.8, 0, 0, -5, 2, 1.5, 3, 5.0040814815},
    {-0.115, 2.112, -0.008, 0.467, 12.04, 0.33, 2.12, 1.25, 32.7234943954},
    {2.0, 1.0, -1.0, 0.5, -8, 3, 2, 4, 6.1350640191},
    {0, 0, 0, 0, 0.3, 1, 1, 2, 1.6868653306},
    {0.44, 0.915, 0.097, 0.697, -4.65, 0.61, 1.47, 1.72, 10.9632565572},
    {-0.618, -1.21, -0.663, 0.525, 1.93, 0.97, 2.43, 1.88, 7.4663318647},
};
} // namespace

TEST_CASE("v13-q: arbitrary-state OTG - matches Ruckig min-time + reaches target + limits (faithful port)",
          "[v13-q][motion][otg]")
{
    for (const OtgRef& r : kOtgRef)
    {
        const auto prof = m::plan_otg<f64>(0.0, r.v0, r.a0, r.pf, r.vf, r.af, r.vmax, r.amax, r.jmax);
        REQUIRE(prof.valid);
        CHECK(close(prof.duration, r.dur, 1e-4, 1e-4)); // time-optimal == Ruckig's duration
        f64 p;
        f64 v;
        f64 a;
        prof.eval(prof.duration, p, v, a);
        CHECK(close(p, r.pf, 1e-4, 1e-4)); // reaches target state
        CHECK(close(v, r.vf, 1e-4, 1e-4));
        CHECK(close(a, r.af, 1e-4, 1e-4));
        // accel + jerk stay hard everywhere; velocity limit holds on the back half (Ruckig allows front overshoot)
        const int ns = 1500;
        for (int i = 0; i <= ns; ++i)
        {
            const f64 tt = prof.duration * i / ns;
            prof.eval(tt, p, v, a);
            CHECK(std::abs(a) <= r.amax * 1.0 + 1e-3);
            if (tt > 0.55 * prof.duration)
            {
                CHECK(std::abs(v) <= r.vmax + 1e-3);
            }
        }
    }
}

namespace
{
// generated by build/gen_sync_ref.py — ruckig 0.17.3 multi-DoF sync reference (3 DoF, arbitrary states)
struct SyncRef
{
    double v0[3], a0[3], vf[3], af[3], pf[3], vmax[3], amax[3], jmax[3], tsync;
};
constexpr SyncRef kSyncRef[] = {
    {{0.192264, 1.196834, -0.368105},
     {-0.664228, 0.529017, 0.149285},
     {-0.670393, -0.732656, -0.635644},
     {-0.682672, -0.405050, -0.221933},
     {26.260290, -5.065528, -2.138211},
     {1.623988, 2.122453, 1.469333},
     {1.931000, 1.591302, 1.334659},
     {3.249583, 1.257637, 2.409446},
     18.0115856983},
    {{0.030804, 0.349024, 0.524823},
     {0.157035, -0.376791, -0.311957},
     {-0.981493, -0.455329, 0.208383},
     {0.146196, 0.284226, -0.194803},
     {17.216814, -0.957560, 0.321088},
     {1.803354, 0.943114, 1.068484},
     {1.699246, 1.928440, 1.293248},
     {1.759087, 3.903770, 1.296288},
     12.5994390826},
    {{0.661231, -0.208489, 0.514239},
     {0.377440, -0.097338, -0.578515},
     {0.948895, -0.272922, 0.828519},
     {0.067261, 0.229952, 0.296153},
     {26.984365, -2.291947, -4.820549},
     {2.002763, 0.994684, 1.418056},
     {0.858796, 0.874376, 1.359775},
     {3.914837, 1.326636, 1.594588},
     14.4103566488},
    {{0.223185, -1.413457, 0.704186},
     {0.472457, -0.278351, 0.328876},
     {-0.415127, -0.566160, 0.202352},
     {-0.197202, 0.270498, 0.273374},
     {16.506298, 2.200920, -0.099270},
     {0.812149, 2.698828, 2.751868},
     {1.741646, 1.472617, 1.261101},
     {3.179201, 2.126514, 1.534864},
     21.4123145004},
    {{-0.917540, 0.857623, 1.268316},
     {-0.561609, -0.257373, 0.525768},
     {0.319202, -1.419645, -1.070176},
     {-0.178004, -0.159622, 0.543731},
     {21.611419, -5.420459, 0.629476},
     {1.950012, 2.796646, 2.845335},
     {1.198557, 0.949009, 1.731369},
     {1.271174, 2.349072, 2.973531},
     15.2462795202},
    {{-1.205580, -0.271877, 1.099067},
     {-0.504552, -0.499895, 0.732621},
     {-0.225357, -0.158870, -0.578250},
     {0.471814, 0.465957, -0.003487},
     {26.189498, -2.828753, -3.185947},
     {2.576368, 0.815295, 1.941339},
     {1.854528, 1.315046, 1.584227},
     {2.090410, 2.368751, 2.218163},
     14.3234620544},
    {{0.004586, -0.346297, 0.069079},
     {-0.292275, 0.221234, -0.608513},
     {-0.378953, 0.351230, 0.647452},
     {0.212834, -0.269758, -0.212946},
     {18.114305, 3.651462, -5.015704},
     {1.426649, 1.118769, 1.609123},
     {0.651642, 1.285234, 1.485228},
     {2.906780, 3.959821, 2.973883},
     16.0251284954},
    {{-0.516113, -1.009169, 0.090583},
     {0.017260, -0.181412, 0.045187},
     {-0.292006, -1.076119, -0.423612},
     {0.165758, 0.387806, -0.496082},
     {17.266764, 6.037430, 6.355452},
     {0.889705, 2.320063, 1.367472},
     {1.427250, 1.141429, 1.523978},
     {3.097180, 3.822844, 3.488222},
     21.4732319620},
    {{-0.503203, 1.058147, 0.186784},
     {0.335847, 0.076394, 0.125388},
     {1.325198, -1.303064, -0.268386},
     {0.460274, -0.228850, 0.140061},
     {25.138382, 2.616028, -4.204015},
     {2.780920, 2.212470, 0.811135},
     {1.486342, 0.717796, 0.825131},
     {2.149283, 1.652560, 2.736455},
     11.1670412660},
    {{0.635257, -0.177472, 0.552354},
     {0.259287, 0.369145, -0.282699},
     {0.124257, 0.217708, -1.181136},
     {-0.534753, 0.222072, 0.150072},
     {19.780305, 0.042193, -5.166229},
     {1.515879, 1.383445, 2.069189},
     {1.645088, 0.941586, 1.289525},
     {3.018972, 3.924430, 1.746680},
     13.8256514350},
};
} // namespace

TEST_CASE("v13-q: multi-DoF arbitrary-state SYNC (Ruckig step2) - tsync + all axes reach target",
          "[v13-q][motion][otg]")
{
    for (const SyncRef& r : kSyncRef)
    {
        const f64 zp[3] = {0.0, 0.0, 0.0};
        m::OtgProfile<f64> out[3];
        const f64 ts = m::plan_synchronized_otg<f64>(3, zp, r.v0, r.a0, r.pf, r.vf, r.af, r.vmax, r.amax, r.jmax, out);
        CHECK(close(ts, r.tsync, 1e-4, 1e-4)); // tsync matches Ruckig's multi-DoF duration
        for (int d = 0; d < 3; ++d)
        {
            REQUIRE(out[d].valid);
            CHECK(close(out[d].duration, ts, 1e-9, 1e-9)); // every axis finishes at tsync
            f64 p;
            f64 v;
            f64 a;
            out[d].eval(ts, p, v, a);
            CHECK(close(p, r.pf[d], 1e-3, 1e-4)); // reaches its target state at the synchronized time
            CHECK(close(v, r.vf[d], 1e-3, 1e-4));
            CHECK(close(a, r.af[d], 1e-3, 1e-4));
            f64 maxa = 0;
            const int ns = 800;
            for (int i = 0; i <= ns; ++i)
            {
                out[d].eval(ts * i / ns, p, v, a);
                maxa = std::max(maxa, std::abs(a));
                if (ts * i / ns > 0.55 * ts)
                {
                    CHECK(std::abs(v) <= r.vmax[d] + 1e-3); // velocity limited on the back half (Ruckig's rule)
                }
            }
            CHECK(maxa <= r.amax[d] + 1e-3); // acceleration stays hard
        }
    }
}

TEST_CASE("v13-q: multi-DoF time-synchronized OTG - all axes finish together (Ruckig core)", "[v13-q][motion]")
{
    constexpr int nd = 3;
    const f64 p0[nd] = {0.0, 0.0, 0.0};
    const f64 p_t[nd] = {10.0, 3.0, 6.0};
    const f64 vmax[nd] = {2.0, 2.0, 1.5};
    const f64 amax[nd] = {1.5, 1.5, 1.0};
    const f64 jmax[nd] = {3.0, 3.0, 2.0};
    m::ScurveProfile<f64> prof[nd];
    const f64 tsync = m::plan_synchronized<f64>(nd, p0, p_t, vmax, amax, jmax, prof);
    f64 tmax = 0.0;
    for (int d = 0; d < nd; ++d)
    {
        tmax = std::max(tmax, m::scurve_duration<f64>(p0[d], p_t[d], vmax[d], amax[d], jmax[d]));
    }
    CHECK(close(tsync, tmax, 1e-9, 1e-9)); // tsync = the critical DoF's minimum time
    for (int d = 0; d < nd; ++d)
    {
        CHECK(close(prof[d].total, tsync, 1e-9, 1e-9));
        f64 maxv = 0;
        f64 maxa = 0;
        f64 maxj = 0;
        f64 p;
        f64 v;
        f64 a;
        f64 j;
        const int ns = 2000;
        for (int i = 0; i <= ns; ++i)
        {
            prof[d].eval(tsync * i / ns, p, v, a, j);
            maxv = std::max(maxv, std::abs(v));
            maxa = std::max(maxa, std::abs(a));
            maxj = std::max(maxj, std::abs(j));
        }
        prof[d].eval(tsync, p, v, a, j);
        CHECK(close(p, p_t[d], 1e-3, 1e-4)); // reaches target at the synchronized time
        CHECK(maxv <= vmax[d] * 1.0001);
        CHECK(maxa <= amax[d] * 1.0001);
        CHECK(maxj <= jmax[d] * 1.0001);
    }
}

TEST_CASE("v13-o: clothoid - curvature linear in arc length + circular-arc limit", "[v13-o][motion]")
{
    // curvature kappa(s) = kappa0 + kappa1*s
    const f64 k0 = 0.2;
    const f64 k1 = 0.6;
    for (f64 s : {0.0, 0.5, 1.5, 3.0})
    {
        const auto p = m::clothoid_eval<f64>(0.0, 0.0, 0.0, k0, k1, s);
        CHECK(close(p.kappa, k0 + k1 * s, 1e-14, 1e-14));
    }
    // kappa1 = 0, kappa0 = 0.5 -> circular arc of radius r = 1/kappa0 = 2, centred at (0,2). heading advances kappa0*s.
    const f64 pi = 3.14159265358979323846;
    const auto q90 = m::clothoid_eval<f64>(0.0, 0.0, 0.0, 0.5, 0.0, pi); // s=pi -> swept angle pi/2 (quarter turn)
    CHECK(close(q90.theta, 0.5 * pi, 1e-12, 1e-12));
    CHECK(close(q90.x, 2.0, 1e-9, 1e-9)); // (r sin(pi/2), r(1-cos(pi/2))) = (2, 2)
    CHECK(close(q90.y, 2.0, 1e-9, 1e-9));
    const auto q180 = m::clothoid_eval<f64>(0.0, 0.0, 0.0, 0.5, 0.0, 2.0 * pi); // swept angle pi -> half circle
    CHECK(close(q180.x, 0.0, 1e-9, 1e-9));                                      // diameter = 4 -> back to x=0, y=4
    CHECK(close(q180.y, 4.0, 1e-9, 1e-9));
    // straight line (both zero)
    const auto line = m::clothoid_eval<f64>(1.0, 2.0, 0.0, 0.0, 0.0, 3.0);
    CHECK(close(line.x, 4.0, 1e-14, 1e-14));
    CHECK(close(line.y, 2.0, 1e-14, 1e-14));
}

TEST_CASE("v13-o: NURBS - exact unit circle (rational quadratic)", "[v13-o][motion]")
{
    const f64 r2 = std::sqrt(2.0) / 2.0;
    const f64 cx[9] = {1, 1, 0, -1, -1, -1, 0, 1, 1};
    const f64 cy[9] = {0, 1, 1, 1, 0, -1, -1, -1, 0};
    const f64 w[9] = {1, r2, 1, r2, 1, r2, 1, r2, 1};
    const f64 knots[12] = {0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 4};
    for (int i = 0; i <= 20; ++i)
    {
        const f64 u = 4.0 * i / 20.0;
        f64 x;
        f64 y;
        m::nurbs_eval2<f64>(ConstSpan<f64>{cx, 9}, ConstSpan<f64>{cy, 9}, ConstSpan<f64>{w, 9},
                            ConstSpan<f64>{knots, 12}, 2, u, x, y);
        INFO("u=" << u);
        CHECK(close(x * x + y * y, 1.0, 1e-12, 1e-12)); // on the unit circle
    }
}

TEST_CASE("v13-p: min-jerk quintic + min-snap septic boundary conditions", "[v13-p][motion]")
{
    f64 c[6];
    m::min_jerk_quintic<f64>(0.0, 1.0, 0.5, 3.0, -0.5, 0.2, 2.0, c);
    CHECK(close(m::poly_eval_deriv<f64>(c, 5, 0.0, 0), 0.0, 1e-12, 1e-12));  // p(0)
    CHECK(close(m::poly_eval_deriv<f64>(c, 5, 0.0, 1), 1.0, 1e-12, 1e-12));  // v(0)
    CHECK(close(m::poly_eval_deriv<f64>(c, 5, 0.0, 2), 0.5, 1e-12, 1e-12));  // a(0)
    CHECK(close(m::poly_eval_deriv<f64>(c, 5, 2.0, 0), 3.0, 1e-10, 1e-11));  // p(T)
    CHECK(close(m::poly_eval_deriv<f64>(c, 5, 2.0, 1), -0.5, 1e-10, 1e-11)); // v(T)
    CHECK(close(m::poly_eval_deriv<f64>(c, 5, 2.0, 2), 0.2, 1e-10, 1e-11));  // a(T)
    f64 cs[8];
    m::min_snap_septic<f64>(0.0, 0.0, 0.0, 0.0, 5.0, 0.0, 0.0, 0.0, 1.5, cs);
    CHECK(close(m::poly_eval_deriv<f64>(cs, 7, 1.5, 0), 5.0, 1e-9, 1e-10));  // p(T)
    CHECK(close(m::poly_eval_deriv<f64>(cs, 7, 1.5, 3), 0.0, 1e-8, 1e-8));   // jerk(T)=0
    CHECK(close(m::poly_eval_deriv<f64>(cs, 7, 0.0, 3), 0.0, 1e-12, 1e-12)); // jerk(0)=0
}

TEST_CASE("v13-q: jerk-limited S-curve + trapezoidal profiles - limits + target", "[v13-q][motion]")
{
    for (const auto& tc : {std::make_tuple(10.0, 2.0, 1.5, 3.0), std::make_tuple(0.5, 2.0, 1.5, 3.0),
                           std::make_tuple(100.0, 5.0, 2.0, 1.0)})
    {
        const auto [dist, vmax, amax, jmax] = tc;
        const auto pr = m::plan_scurve<f64>(0.0, dist, vmax, amax, jmax);
        REQUIRE(pr.valid);
        // sample & check limits + endpoints
        f64 maxv = 0;
        f64 maxa = 0;
        f64 maxj = 0;
        const int nsamp = 2000;
        for (int i = 0; i <= nsamp; ++i)
        {
            const f64 t = pr.total * i / nsamp;
            f64 p;
            f64 v;
            f64 a;
            f64 j;
            pr.eval(t, p, v, a, j);
            maxv = std::max(maxv, std::abs(v));
            maxa = std::max(maxa, std::abs(a));
            maxj = std::max(maxj, std::abs(j));
        }
        f64 p;
        f64 v;
        f64 a;
        f64 j;
        pr.eval(pr.total, p, v, a, j);
        CHECK(close(p, dist, 1e-6, 1e-7)); // reaches target
        CHECK(close(v, 0.0, 1e-6, 1e-7));  // rest at end
        CHECK(maxv <= vmax * 1.0001);      // velocity-limited
        CHECK(maxa <= amax * 1.0001);      // accel-limited
        CHECK(maxj <= jmax * 1.0001);      // jerk-limited
    }
    // trapezoidal reaches target with bounded acc
    const auto tr = m::plan_trapezoidal<f64>(0.0, 8.0, 2.0, 1.5);
    REQUIRE(tr.valid);
    f64 p;
    f64 v;
    f64 a;
    f64 j;
    tr.eval(tr.total, p, v, a, j);
    CHECK(close(p, 8.0, 1e-6, 1e-7));
}

TEST_CASE("v13-q: Kochanek-Bartels - Catmull-Rom special case + endpoint interpolation", "[v13-q][motion]")
{
    const f64 pm1 = 0.0;
    const f64 p0 = 1.0;
    const f64 p1 = 3.0;
    const f64 p2 = 2.0;
    // endpoints
    CHECK(close(m::kb_eval<f64>(pm1, p0, p1, p2, 0.0, 0.0, 0.0, 0.0), p0, 1e-14, 1e-14));
    CHECK(close(m::kb_eval<f64>(pm1, p0, p1, p2, 0.0, 0.0, 0.0, 1.0), p1, 1e-14, 1e-14));
    // Catmull-Rom (T=C=B=0): midpoint uses the CR tangents 0.5(p1-pm1), 0.5(p2-p0)
    const f64 m0 = 0.5 * (p1 - pm1);
    const f64 m1 = 0.5 * (p2 - p0);
    const f64 u = 0.5;
    const f64 u2 = u * u;
    const f64 u3 = u2 * u;
    const f64 ref = (2 * u3 - 3 * u2 + 1) * p0 + (u3 - 2 * u2 + u) * m0 + (-2 * u3 + 3 * u2) * p1 + (u3 - u2) * m1;
    CHECK(close(m::kb_eval<f64>(pm1, p0, p1, p2, 0.0, 0.0, 0.0, u), ref, 1e-14, 1e-14));
}
