#!/usr/bin/env python3
"""QMC references for v12-g — Sobol points vs scipy.stats.qmc (same Joe-Kuo direction numbers). Plain double arrays."""
import numpy as np
from scipy.stats import qmc


def emit(name, arr):
    flat = np.asarray(arr, dtype=float).ravel()
    vals = ", ".join(f"{x:.17g}" for x in flat)
    print(f"inline const double ref_{name}[] = {{{vals}}};")


def main():
    print("// GENERATED by gen_qmc_refs.py — QMC KAT references (v12-g).")
    print("#pragma once")
    s = qmc.Sobol(d=4, scramble=False)
    emit("sobol_4d_16", s.random(16))  # 16 points × 4 dims, row-major


if __name__ == "__main__":
    main()
