#!/usr/bin/env python3
"""v12-i discrete-distribution references vs scipy.stats — plain C arrays (no std containers).
Each: k eval points + pmf/logpmf/cdf/sf, p points + ppf (integer), [mean,var,skew,exkurt], entropy.
NaN in a moment/entropy slot ⇒ the test SKIPS that gate."""
import numpy as np
from scipy import stats

NAN = float("nan")


def row(name, dist, ks, ps, skip_var=False, skip_skew=False, skip_kurt=False, skip_entropy=False):
    ks = np.asarray(ks, dtype=np.int64)
    ps = np.asarray(ps, float)
    m, v, s, k = dist.stats(moments="mvsk")
    mvsk = [float(m), NAN if skip_var else float(v), NAN if skip_skew else float(s), NAN if skip_kurt else float(k)]
    ent = NAN if skip_entropy else float(dist.entropy())
    return {
        "name": name,
        "k": ks, "pmf": dist.pmf(ks), "logpmf": dist.logpmf(ks), "cdf": dist.cdf(ks), "sf": dist.sf(ks),
        "p": ps, "ppf": dist.ppf(ps).astype(np.int64), "mvsk": mvsk, "entropy": ent,
    }


def fmtd(a):
    return ", ".join("HUGE_VAL" if np.isinf(x) and x > 0 else ("-HUGE_VAL" if np.isinf(x) else
                     ("NAN" if np.isnan(x) else f"{x:.17g}")) for x in np.atleast_1d(a))


def fmti(a):
    return ", ".join(str(int(x)) for x in np.atleast_1d(a))


P = [0.1, 0.3, 0.5, 0.7, 0.9]
rows = []
rows.append(row("bernoulli", stats.bernoulli(0.3), [0, 1], P))
rows.append(row("binomial", stats.binom(20, 0.35), [2, 5, 7, 10], P))
rows.append(row("poisson", stats.poisson(4.5), [1, 3, 5, 9], P))
rows.append(row("geometric", stats.geom(0.3), [1, 2, 4, 8], P))
rows.append(row("negbinom", stats.nbinom(5, 0.4), [2, 5, 8, 14], P))
rows.append(row("discreteuniform", stats.randint(2, 10), [2, 4, 6, 9], P))
rows.append(row("hypergeom", stats.hypergeom(30, 12, 10), [2, 4, 5, 7], P))
rows.append(row("skellam", stats.skellam(4.0, 2.0), [-2, 0, 2, 5], P))
rows.append(row("zipf", stats.zipf(3.5), [1, 2, 3, 5], P, skip_skew=True, skip_kurt=True, skip_entropy=True))
rows.append(row("yulesimon", stats.yulesimon(3.0), [1, 2, 4, 8], P, skip_skew=True, skip_kurt=True, skip_entropy=True))
rows.append(row("betabinom", stats.betabinom(15, 2.0, 3.0), [2, 5, 8, 12], P, skip_kurt=True))
rows.append(row("logarithmic", stats.logser(0.6), [1, 2, 4, 8], P, skip_skew=True, skip_kurt=True, skip_entropy=True))

print("// GENERATED by gen_discrete_refs.py — scipy.stats references for v12-i (plain C arrays).")
print("#pragma once")
print("#include <cmath>  // HUGE_VAL, NAN")
for r in rows:
    n = r["name"]
    print(f'inline const long long ref_{n}_k[] = {{{fmti(r["k"])}}};')
    print(f'inline const double ref_{n}_pmf[] = {{{fmtd(r["pmf"])}}};')
    print(f'inline const double ref_{n}_logpmf[] = {{{fmtd(r["logpmf"])}}};')
    print(f'inline const double ref_{n}_cdf[] = {{{fmtd(r["cdf"])}}};')
    print(f'inline const double ref_{n}_sf[] = {{{fmtd(r["sf"])}}};')
    print(f'inline const double ref_{n}_p[] = {{{fmtd(r["p"])}}};')
    print(f'inline const long long ref_{n}_ppf[] = {{{fmti(r["ppf"])}}};')
    print(f'inline const double ref_{n}_mvsk[] = {{{fmtd(r["mvsk"])}}};')
    print(f'inline const double ref_{n}_entropy = {fmtd([r["entropy"]])};')
