#pragma once

#include <crd/core/types.hpp>
#include <crd/log/log_level.hpp>

namespace crd::log
{
// A "Channel" is a named filter for one subsystem (Renderer, Audio, Physics...).
// Each channel has its own runtime level. When you call CRD_LOG_INFO(g_log_renderer, ...)
// the macro consults this channel's level to decide whether to format and dispatch.
//
// Channels are POD-ish; they auto-link into a global registry via a static registrar
// emitted by the CRD_DEFINE_LOG_CHANNEL macro. No heap allocation, no init order
// problems, safe to declare in headers.
struct Channel
{
    const char* name;       // stable string literal
    LogLevel runtime_level; // mutable; reads are relaxed (one byte)
    Channel* next;          // intrusive registry pointer (nullptr until registered)
};

namespace detail
{
// Called by the registrar generated by CRD_DEFINE_LOG_CHANNEL.
void register_channel(Channel* ch) noexcept;
} // namespace detail

// Lookup by name. Returns nullptr if no such channel was registered.
Channel* find_channel(const char* name) noexcept;

// Adjust one channel's threshold at runtime.
bool set_channel_level(const char* name, LogLevel level) noexcept;

// Adjust every registered channel.
void set_all_channels_level(LogLevel level) noexcept;

// Iteration: returns the head of the channel registry list. Walk via ch->next.
Channel* first_channel() noexcept;

// Number of registered channels (for diagnostics / dev UI).
usize channel_count() noexcept;
} // namespace crd::log

// --------------- Macros ---------------------------------------------------
// Declare a channel in a header (extern reference).
#define CRD_DECLARE_LOG_CHANNEL(VAR) extern ::crd::log::Channel VAR

// Define a channel in a .cpp.
//   VAR           : C++ identifier (e.g. g_log_renderer)
//   NAME          : string literal name shown in logs (e.g. "Renderer")
//   DEFAULT_LEVEL : initial LogLevel (e.g. ::crd::log::LogLevel::Info)
//
// The trailing static struct registers the channel with the global registry on
// program startup (translation-unit local; safe across DLLs since we use a list head
// with a function-local static).
#define CRD_DEFINE_LOG_CHANNEL(VAR, NAME, DEFAULT_LEVEL)                                                               \
    ::crd::log::Channel VAR{(NAME), (DEFAULT_LEVEL), nullptr};                                                         \
    namespace                                                                                                          \
    {                                                                                                                  \
    struct VAR##_LogChannelRegistrar                                                                                   \
    {                                                                                                                  \
        VAR##_LogChannelRegistrar() noexcept { ::crd::log::detail::register_channel(&VAR); }                           \
    };                                                                                                                 \
    const VAR##_LogChannelRegistrar VAR##_log_channel_registrar_instance;                                              \
    }
