include(CTest)
include(Catch)

add_subdirectory(core)
add_subdirectory(units)
add_subdirectory(time)
add_subdirectory(perf)
add_subdirectory(perf-ui)
add_subdirectory(log)
add_subdirectory(memory)
add_subdirectory(math)
add_subdirectory(geometry-primitives)
add_subdirectory(geometry-bvh)
add_subdirectory(geometry-convex)
add_subdirectory(geometry-mesh)
add_subdirectory(geometry-spatial)
add_subdirectory(geometry-polygon)
add_subdirectory(geometry-mesh-processing)
add_subdirectory(geometry-delaunay)
add_subdirectory(containers)
add_subdirectory(platform)
add_subdirectory(app)
add_subdirectory(config)
add_subdirectory(imgui)
add_subdirectory(renderer)
add_subdirectory(shader)
add_subdirectory(rhi)
add_subdirectory(rhi_vulkan)
add_subdirectory(jobs)
add_subdirectory(stress)
add_subdirectory(resources)
add_subdirectory(meshgen)
add_subdirectory(scene)
add_subdirectory(scene_cooker)
add_subdirectory(cooker)
add_subdirectory(preset)
add_subdirectory(profile)
add_subdirectory(eylem)
add_subdirectory(eylem-rigid3d)
add_subdirectory(draw)
add_subdirectory(eylem-viz)
add_subdirectory(geometry-viz)
add_subdirectory(sandbox)

if(CRD_BUILD_BENCHMARKS)
    add_subdirectory(bench)
endif()
