#!/usr/bin/env python3
"""crd-math transcendental accuracy refs — mpmath ground truth → correctly-rounded f64 → plain-C arrays.
THE family pattern: add a function = add one entry to FUNCS (name, cerid-call, mpmath fn, grid). The C++ test
(test_transcendental.cpp) reads these and asserts <=1 ulp. mpmath = arbitrary precision = the gold gate.
NO std containers in the emitted file (plain `inline const double[]`)."""
import sys
import numpy as np
import mpmath as mp

mp.mp.dps = 50  # 50 decimal digits ground truth


def grid(lo, hi, n, *, log=False, extra=None):
    if log:
        xs = np.exp(np.linspace(np.log(lo), np.log(hi), n))
    else:
        xs = np.linspace(lo, hi, n)
    if extra:
        xs = np.concatenate([xs, np.array(extra, dtype=float)])
    return np.unique(xs.astype(np.float64))


# (name, mpmath fn, grid) — grid is f64 inputs; ref = correctly-rounded f64 of mpmath(input).
FUNCS = [
    ("exp", mp.exp, grid(-700, 700, 400, extra=[0.0, 1.0, -1.0, 1e-8, -1e-8, 709.0, -745.0])),
    ("exp2", lambda v: mp.power(2, v), grid(-1020, 1020, 400, extra=[0.0, 0.5, -0.5, 10.0, 1023.0])),
    ("exp10", lambda v: mp.power(10, v), grid(-300, 300, 400, extra=[0.0, 1.0, 2.0, -1.0, 0.5])),
    ("expm1", mp.expm1, grid(-40.0, 40.0, 600, extra=[1e-10, -1e-10, 1e-6, -1e-6, 1e-3, 0.34, 0.35, 0.5, -0.5, 0.7, -0.7, 2.0, 3.0, 5.0, -5.0, 700.0, -700.0, 0.0])),
    ("log", mp.log, grid(1e-300, 1e300, 400, log=True, extra=[1.0, 2.0, 0.5, 1.0000001, 0.9999999])),
    ("log2", lambda v: mp.log(v, 2), grid(1e-300, 1e300, 400, log=True, extra=[1.0, 2.0, 4.0, 0.5, 8.0])),
    ("log10", lambda v: mp.log10(v), grid(1e-300, 1e300, 400, log=True, extra=[1.0, 10.0, 100.0, 0.1])),
    ("log1p", mp.log1p, grid(-0.9, 1e6, 300, log=False, extra=[1e-12, -1e-12, 1e-8, -1e-8, 1e-3, -0.5, 0.0])),
]

# trig: Cody-Waite 3-part reduction holds to |x| ~ 1e6 (the practical angle range). Dense small-x + sparse large-x.
_trig_extra = list(np.linspace(-6.3, 6.3, 260)) + [0.0, 0.1, 0.5, 1.0, 1.5707963267948966, 3.141592653589793, 6.283185307179586, 100.0, 1000.0, 12345.678, -100.0, -1000.0]
FUNCS += [
    ("sin", mp.sin, grid(-1e6, 1e6, 1500, extra=_trig_extra)),
    ("cos", mp.cos, grid(-1e6, 1e6, 1500, extra=_trig_extra)),
    ("tan", mp.tan, grid(-1e6, 1e6, 1500, extra=_trig_extra)),
]

# hyperbolic: compose expm1/log1p (≤1 ulp anti-cancellation forms).
_he = [0.0, 1e-8, -1e-8, 1e-4, -1e-4, 0.1, 0.5, 1.0, -1.0, 2.0, 5.0, 10.0]
FUNCS += [
    ("sinh", mp.sinh, grid(-709, 709, 600, extra=_he)),
    ("cosh", mp.cosh, grid(-709, 709, 600, extra=_he)),
    ("tanh", mp.tanh, grid(-20, 20, 600, extra=_he)),
    ("asinh", mp.asinh, grid(-1e7, 1e7, 600, extra=_he + [1e-12, -1e-12, 100.0, -100.0])),
    ("acosh", mp.acosh, grid(1.0, 1e7, 600, extra=[1.0, 1.0000001, 1.0001, 1.01, 1.5, 2.0, 10.0, 100.0])),
    ("atanh", mp.atanh, grid(-0.9999, 0.9999, 600, extra=[0.0, 1e-8, -1e-8, 0.1, 0.5, -0.5, 0.9, -0.9, 0.99])),
]

# inverse trig.
FUNCS += [
    ("atan", mp.atan, grid(-1e6, 1e6, 800, extra=[0.0, 0.1, 0.5, 1.0, -1.0, 2.0, 0.41421356, -0.41421356, 1e-8, -1e-8, 100.0])),
    ("asin", mp.asin, grid(-1.0, 1.0, 800, extra=[0.0, 0.5, -0.5, 0.9999, -0.9999, 1e-8, 0.70710678, -0.70710678])),
    ("acos", mp.acos, grid(-1.0, 1.0, 800, extra=[0.0, 0.5, -0.5, 0.9999, -0.9999, 0.70710678, -0.70710678])),
]

# power/root.
FUNCS += [
    ("cbrt", lambda v: mp.cbrt(v) if v >= 0 else -mp.cbrt(-v), grid(-1e6, 1e6, 700, extra=[1.0, 8.0, 27.0, 64.0, 125.0, 0.001, 1e-9, -1e-9, 1e9, -1e9, -8.0, -27.0, 2.0])),
    ("rsqrt", lambda v: 1 / mp.sqrt(v), grid(1e-300, 1e300, 500, log=True, extra=[1.0, 4.0, 0.25, 2.0, 9.0])),
]


def emit(name, fn, xs):
    gx, gy = [], []
    for x in xs:
        if not np.isfinite(x):
            continue
        try:
            y = float(fn(mp.mpf(float(x))))  # float(x): numpy 2.0 repr() is "np.float64(..)" — breaks mp.mpf
        except (ValueError, ZeroDivisionError, OverflowError):
            continue
        if not np.isfinite(y):  # skip overflow/underflow-to-edge — ulp gate is for the finite range
            continue
        gx.append(float(x))
        gy.append(y)
    xf = ", ".join(f"{v:.17e}" for v in gx)
    yf = ", ".join(f"{v:.17e}" for v in gy)
    print(f"inline const double ref_{name}_x[] = {{{xf}}};")
    print(f"inline const double ref_{name}_y[] = {{{yf}}};")
    print(f"inline constexpr int ref_{name}_n = {len(gx)};")


print("// GENERATED by gen_transcendental_refs.py — mpmath(50-dps) correctly-rounded f64 refs for crd::math (tx-a).")
print("#pragma once")
print("namespace crd::math::txref {")
for name, fn, xs in FUNCS:
    emit(name, fn, xs)
print("} // namespace")
sys.exit(0)
