// crd-hesap-dsp v11-b — window gates: vs scipy.signal.windows reference vectors (window_refs.inc,
// generated by gen_window_refs.py) to ~1e-12, plus ENBW sanity. scipy is the free primary; MATLAB R2026a
// is the spec-compliance authority (cross-checked separately for the parametric/special windows).

#include <crd/hesap/dsp/windows.hpp>
#include <crd/memory/allocators/tlsf_allocator.hpp>

#include "window_refs.inc"

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>
#include <cmath>

namespace dsp = crd::hesap::dsp;
namespace cont = crd::containers;
using crd::f64;
using crd::usize;
using Catch::Matchers::WithinAbs;

namespace
{
// the reference is a plain C array (no STL — project rule); N is deduced.
template <crd::usize N> void check_against(const double (&ref)[N], const cont::Array<f64>& w, double tol = 1e-12)
{
    REQUIRE(w.size() == N);
    for (usize i = 0; i < w.size(); ++i)
    {
        INFO("[" << i << "]");
        CHECK_THAT(w[i], WithinAbs(ref[i], tol));
    }
}
} // namespace

TEST_CASE("dsp windows: cosine-sum family matches scipy (~1e-13)", "[v11-b][dsp][window]")
{
    crd::memory::TlsfAllocator alloc(1U << 20);
    check_against(ref_hann, dsp::hann<f64>(&alloc, 16));
    check_against(ref_hamming, dsp::hamming<f64>(&alloc, 16));
    check_against(ref_blackman, dsp::blackman<f64>(&alloc, 16));
    check_against(ref_blackmanharris, dsp::blackmanharris<f64>(&alloc, 16));
    check_against(ref_nuttall, dsp::nuttall<f64>(&alloc, 16));
    check_against(ref_flattop, dsp::flattop<f64>(&alloc, 16));
}

TEST_CASE("dsp windows: simple windows match scipy", "[v11-b][dsp][window]")
{
    crd::memory::TlsfAllocator alloc(1U << 20);
    check_against(ref_boxcar, dsp::boxcar<f64>(&alloc, 16));
    check_against(ref_bartlett, dsp::bartlett<f64>(&alloc, 16));
    check_against(ref_triang, dsp::triang<f64>(&alloc, 16));
    check_against(ref_cosine, dsp::cosine<f64>(&alloc, 16));
    check_against(ref_lanczos, dsp::lanczos<f64>(&alloc, 16));
    check_against(ref_barthann, dsp::barthann<f64>(&alloc, 16));
    check_against(ref_bohman, dsp::bohman<f64>(&alloc, 16));
    check_against(ref_parzen, dsp::parzen<f64>(&alloc, 16));
}

TEST_CASE("dsp windows: periodic (fftbins) variants match scipy", "[v11-b][dsp][window]")
{
    crd::memory::TlsfAllocator alloc(1U << 20);
    check_against(ref_hann_periodic, dsp::hann<f64>(&alloc, 16, false));
    check_against(ref_hamming_periodic, dsp::hamming<f64>(&alloc, 16, false));
}

TEST_CASE("dsp windows: parametric (kaiser/gaussian/tukey/...) match scipy", "[v11-b][dsp][window]")
{
    crd::memory::TlsfAllocator alloc(1U << 20);
    check_against(ref_kaiser_8, dsp::kaiser<f64>(&alloc, 16, 8.0));
    check_against(ref_kaiser_14, dsp::kaiser<f64>(&alloc, 16, 14.0));
    check_against(ref_gaussian_2, dsp::gaussian<f64>(&alloc, 16, 2.0));
    check_against(ref_tukey_05, dsp::tukey<f64>(&alloc, 16, 0.5));
    check_against(ref_general_gaussian, dsp::general_gaussian<f64>(&alloc, 16, 1.5, 2.0));
    check_against(ref_exponential, dsp::exponential<f64>(&alloc, 16));
}

TEST_CASE("dsp windows: ENBW ordering is physically sane", "[v11-b][dsp][window]")
{
    crd::memory::TlsfAllocator alloc(1U << 20);
    // boxcar has the smallest ENBW (1.0); flattop the largest of the common windows.
    const auto bc = dsp::boxcar<f64>(&alloc, 64);
    const auto hn = dsp::hann<f64>(&alloc, 64);
    const auto ft = dsp::flattop<f64>(&alloc, 64);
    const double e_bc = dsp::enbw<f64>(cont::ConstSpan<f64>(bc.data(), bc.size()));
    const double e_hn = dsp::enbw<f64>(cont::ConstSpan<f64>(hn.data(), hn.size()));
    const double e_ft = dsp::enbw<f64>(cont::ConstSpan<f64>(ft.data(), ft.size()));
    CHECK_THAT(e_bc, WithinAbs(1.0, 1e-9));
    CHECK(e_hn > e_bc);
    CHECK(e_ft > e_hn);
    CHECK((e_hn > 1.5 && e_hn < 1.55)); // hann ENBW -> 1.5 asymptotically; ~1.524 at N=64
}

TEST_CASE("dsp windows: DPSS/Slepian (eigenvector) matches scipy", "[v11-b][dsp][window][dpss]")
{
    crd::memory::TlsfAllocator alloc(1U << 22);
    // the 0th Slepian sequence (NW=3) — leading eigenvector of the tridiagonal concentration matrix.
    const auto d = dsp::dpss<f64>(&alloc, 16, 3.0);
    check_against(ref_dpss_nw3, d, 1e-9); // eigenvector ~1e-9 (eig vs scipy LAPACK)
    // scipy 'approximate' norm (Kmax=None default): max == M^2/(M^2+NW) for even M.
    f64 mx = d[0];
    for (usize i = 1; i < d.size(); ++i)
    {
        mx = std::max(mx, d[i]);
    }
    CHECK_THAT(mx, WithinAbs(256.0 / 259.0, 1e-12));
}

TEST_CASE("dsp windows: Dolph-Chebyshev (chebwin, equiripple) matches scipy", "[v11-b][dsp][window][chebwin]")
{
    crd::memory::TlsfAllocator alloc(1U << 22);
    const auto c = dsp::chebwin<f64>(&alloc, 16, 100.0);
    check_against(ref_chebwin_100, c, 1e-10);
    // equiripple property: the window is normalized so max == 1.
    f64 mx = c[0];
    for (usize i = 1; i < c.size(); ++i)
    {
        mx = std::max(mx, c[i]);
    }
    CHECK_THAT(mx, WithinAbs(1.0, 1e-12));
}

TEST_CASE("dsp windows: Taylor (radar) matches scipy", "[v11-b][dsp][window][taylor]")
{
    crd::memory::TlsfAllocator alloc(1U << 20);
    check_against(ref_taylor, dsp::taylor<f64>(&alloc, 16, 4, 30.0, false), 1e-11);
}
