// AUTO-GENERATED by scripts/gen_aos_codelets.py — AoS within-transform FFT codelets (DO NOT EDIT).
// The MKL-crush building block (validated ~45 GFLOPS). See docs/sessions/2026-06-14-fft-*midband*.
#pragma once
#include <immintrin.h>

namespace crd::hesap::fft::detail
{
// AoS radix-8 DIT codelet (fwd). in/out: raw AoS doubles [r0,i0,r1,i1,...], 8 complex.
static inline void aos_codelet_8_fwd(const double* in, double* out) noexcept
{
    __m256d r0 = _mm256_set_pd(in[9], in[8], in[1], in[0]);
    __m256d r1 = _mm256_set_pd(in[13], in[12], in[5], in[4]);
    __m256d r2 = _mm256_set_pd(in[11], in[10], in[3], in[2]);
    __m256d r3 = _mm256_set_pd(in[15], in[14], in[7], in[6]);
    // stage 0 (distance 1, intra-ymm, twiddle 1)
    { const __m256d sw = _mm256_permute2f128_pd(r0, r0, 0x01);
      r0 = _mm256_blend_pd(_mm256_add_pd(r0, sw), _mm256_sub_pd(sw, r0), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r1, r1, 0x01);
      r1 = _mm256_blend_pd(_mm256_add_pd(r1, sw), _mm256_sub_pd(sw, r1), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r2, r2, 0x01);
      r2 = _mm256_blend_pd(_mm256_add_pd(r2, sw), _mm256_sub_pd(sw, r2), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r3, r3, 0x01);
      r3 = _mm256_blend_pd(_mm256_add_pd(r3, sw), _mm256_sub_pd(sw, r3), 0xC); }
    // stage 1 (m=4, ymm-distance 1)
    { const __m256d b = r1; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-1.0, -1.0, 0.0, 0.0), xsw));
      r1 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r3; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-1.0, -1.0, 0.0, 0.0), xsw));
      r3 = _mm256_sub_pd(r2, t); r2 = _mm256_add_pd(r2, t); }
    // stage 2 (m=8, ymm-distance 2)
    { const __m256d b = r2; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 0.0, 0.0), xsw));
      r2 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r3; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(-0.7071067811865476, -0.7071067811865476, -1.0, -1.0), xsw));
      r3 = _mm256_sub_pd(r1, t); r1 = _mm256_add_pd(r1, t); }
    _mm256_storeu_pd(out + 0, r0);
    _mm256_storeu_pd(out + 4, r1);
    _mm256_storeu_pd(out + 8, r2);
    _mm256_storeu_pd(out + 12, r3);
}
// AoS radix-8 DIT codelet (inv). in/out: raw AoS doubles [r0,i0,r1,i1,...], 8 complex.
static inline void aos_codelet_8_inv(const double* in, double* out) noexcept
{
    __m256d r0 = _mm256_set_pd(in[9], in[8], in[1], in[0]);
    __m256d r1 = _mm256_set_pd(in[13], in[12], in[5], in[4]);
    __m256d r2 = _mm256_set_pd(in[11], in[10], in[3], in[2]);
    __m256d r3 = _mm256_set_pd(in[15], in[14], in[7], in[6]);
    // stage 0 (distance 1, intra-ymm, twiddle 1)
    { const __m256d sw = _mm256_permute2f128_pd(r0, r0, 0x01);
      r0 = _mm256_blend_pd(_mm256_add_pd(r0, sw), _mm256_sub_pd(sw, r0), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r1, r1, 0x01);
      r1 = _mm256_blend_pd(_mm256_add_pd(r1, sw), _mm256_sub_pd(sw, r1), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r2, r2, 0x01);
      r2 = _mm256_blend_pd(_mm256_add_pd(r2, sw), _mm256_sub_pd(sw, r2), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r3, r3, 0x01);
      r3 = _mm256_blend_pd(_mm256_add_pd(r3, sw), _mm256_sub_pd(sw, r3), 0xC); }
    // stage 1 (m=4, ymm-distance 1)
    { const __m256d b = r1; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(1.0, 1.0, 0.0, 0.0), xsw));
      r1 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r3; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(1.0, 1.0, 0.0, 0.0), xsw));
      r3 = _mm256_sub_pd(r2, t); r2 = _mm256_add_pd(r2, t); }
    // stage 2 (m=8, ymm-distance 2)
    { const __m256d b = r2; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(0.7071067811865475, 0.7071067811865475, 0.0, 0.0), xsw));
      r2 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r3; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), xsw));
      r3 = _mm256_sub_pd(r1, t); r1 = _mm256_add_pd(r1, t); }
    _mm256_storeu_pd(out + 0, r0);
    _mm256_storeu_pd(out + 4, r1);
    _mm256_storeu_pd(out + 8, r2);
    _mm256_storeu_pd(out + 12, r3);
}

// AoS radix-16 DIT codelet (fwd). in/out: raw AoS doubles [r0,i0,r1,i1,...], 16 complex.
static inline void aos_codelet_16_fwd(const double* in, double* out) noexcept
{
    __m256d r0 = _mm256_set_pd(in[17], in[16], in[1], in[0]);
    __m256d r1 = _mm256_set_pd(in[25], in[24], in[9], in[8]);
    __m256d r2 = _mm256_set_pd(in[21], in[20], in[5], in[4]);
    __m256d r3 = _mm256_set_pd(in[29], in[28], in[13], in[12]);
    __m256d r4 = _mm256_set_pd(in[19], in[18], in[3], in[2]);
    __m256d r5 = _mm256_set_pd(in[27], in[26], in[11], in[10]);
    __m256d r6 = _mm256_set_pd(in[23], in[22], in[7], in[6]);
    __m256d r7 = _mm256_set_pd(in[31], in[30], in[15], in[14]);
    // stage 0 (distance 1, intra-ymm, twiddle 1)
    { const __m256d sw = _mm256_permute2f128_pd(r0, r0, 0x01);
      r0 = _mm256_blend_pd(_mm256_add_pd(r0, sw), _mm256_sub_pd(sw, r0), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r1, r1, 0x01);
      r1 = _mm256_blend_pd(_mm256_add_pd(r1, sw), _mm256_sub_pd(sw, r1), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r2, r2, 0x01);
      r2 = _mm256_blend_pd(_mm256_add_pd(r2, sw), _mm256_sub_pd(sw, r2), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r3, r3, 0x01);
      r3 = _mm256_blend_pd(_mm256_add_pd(r3, sw), _mm256_sub_pd(sw, r3), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r4, r4, 0x01);
      r4 = _mm256_blend_pd(_mm256_add_pd(r4, sw), _mm256_sub_pd(sw, r4), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r5, r5, 0x01);
      r5 = _mm256_blend_pd(_mm256_add_pd(r5, sw), _mm256_sub_pd(sw, r5), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r6, r6, 0x01);
      r6 = _mm256_blend_pd(_mm256_add_pd(r6, sw), _mm256_sub_pd(sw, r6), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r7, r7, 0x01);
      r7 = _mm256_blend_pd(_mm256_add_pd(r7, sw), _mm256_sub_pd(sw, r7), 0xC); }
    // stage 1 (m=4, ymm-distance 1)
    { const __m256d b = r1; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-1.0, -1.0, 0.0, 0.0), xsw));
      r1 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r3; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-1.0, -1.0, 0.0, 0.0), xsw));
      r3 = _mm256_sub_pd(r2, t); r2 = _mm256_add_pd(r2, t); }
    { const __m256d b = r5; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-1.0, -1.0, 0.0, 0.0), xsw));
      r5 = _mm256_sub_pd(r4, t); r4 = _mm256_add_pd(r4, t); }
    { const __m256d b = r7; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-1.0, -1.0, 0.0, 0.0), xsw));
      r7 = _mm256_sub_pd(r6, t); r6 = _mm256_add_pd(r6, t); }
    // stage 2 (m=8, ymm-distance 2)
    { const __m256d b = r2; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 0.0, 0.0), xsw));
      r2 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r3; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(-0.7071067811865476, -0.7071067811865476, -1.0, -1.0), xsw));
      r3 = _mm256_sub_pd(r1, t); r1 = _mm256_add_pd(r1, t); }
    { const __m256d b = r6; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 0.0, 0.0), xsw));
      r6 = _mm256_sub_pd(r4, t); r4 = _mm256_add_pd(r4, t); }
    { const __m256d b = r7; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(-0.7071067811865476, -0.7071067811865476, -1.0, -1.0), xsw));
      r7 = _mm256_sub_pd(r5, t); r5 = _mm256_add_pd(r5, t); }
    // stage 3 (m=16, ymm-distance 4)
    { const __m256d b = r4; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.9238795325112867, 0.9238795325112867, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-0.3826834323650898, -0.3826834323650898, 0.0, 0.0), xsw));
      r4 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r5; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.38268343236508984, 0.38268343236508984, 0.7071067811865476, 0.7071067811865476), b, _mm256_mul_pd(_mm256_set_pd(-0.9238795325112867, -0.9238795325112867, -0.7071067811865475, -0.7071067811865475), xsw));
      r5 = _mm256_sub_pd(r1, t); r1 = _mm256_add_pd(r1, t); }
    { const __m256d b = r6; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.3826834323650897, -0.3826834323650897, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(-0.9238795325112867, -0.9238795325112867, -1.0, -1.0), xsw));
      r6 = _mm256_sub_pd(r2, t); r2 = _mm256_add_pd(r2, t); }
    { const __m256d b = r7; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.9238795325112867, -0.9238795325112867, -0.7071067811865475, -0.7071067811865475), b, _mm256_mul_pd(_mm256_set_pd(-0.3826834323650899, -0.3826834323650899, -0.7071067811865476, -0.7071067811865476), xsw));
      r7 = _mm256_sub_pd(r3, t); r3 = _mm256_add_pd(r3, t); }
    _mm256_storeu_pd(out + 0, r0);
    _mm256_storeu_pd(out + 4, r1);
    _mm256_storeu_pd(out + 8, r2);
    _mm256_storeu_pd(out + 12, r3);
    _mm256_storeu_pd(out + 16, r4);
    _mm256_storeu_pd(out + 20, r5);
    _mm256_storeu_pd(out + 24, r6);
    _mm256_storeu_pd(out + 28, r7);
}
// AoS radix-16 DIT codelet (inv). in/out: raw AoS doubles [r0,i0,r1,i1,...], 16 complex.
static inline void aos_codelet_16_inv(const double* in, double* out) noexcept
{
    __m256d r0 = _mm256_set_pd(in[17], in[16], in[1], in[0]);
    __m256d r1 = _mm256_set_pd(in[25], in[24], in[9], in[8]);
    __m256d r2 = _mm256_set_pd(in[21], in[20], in[5], in[4]);
    __m256d r3 = _mm256_set_pd(in[29], in[28], in[13], in[12]);
    __m256d r4 = _mm256_set_pd(in[19], in[18], in[3], in[2]);
    __m256d r5 = _mm256_set_pd(in[27], in[26], in[11], in[10]);
    __m256d r6 = _mm256_set_pd(in[23], in[22], in[7], in[6]);
    __m256d r7 = _mm256_set_pd(in[31], in[30], in[15], in[14]);
    // stage 0 (distance 1, intra-ymm, twiddle 1)
    { const __m256d sw = _mm256_permute2f128_pd(r0, r0, 0x01);
      r0 = _mm256_blend_pd(_mm256_add_pd(r0, sw), _mm256_sub_pd(sw, r0), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r1, r1, 0x01);
      r1 = _mm256_blend_pd(_mm256_add_pd(r1, sw), _mm256_sub_pd(sw, r1), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r2, r2, 0x01);
      r2 = _mm256_blend_pd(_mm256_add_pd(r2, sw), _mm256_sub_pd(sw, r2), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r3, r3, 0x01);
      r3 = _mm256_blend_pd(_mm256_add_pd(r3, sw), _mm256_sub_pd(sw, r3), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r4, r4, 0x01);
      r4 = _mm256_blend_pd(_mm256_add_pd(r4, sw), _mm256_sub_pd(sw, r4), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r5, r5, 0x01);
      r5 = _mm256_blend_pd(_mm256_add_pd(r5, sw), _mm256_sub_pd(sw, r5), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r6, r6, 0x01);
      r6 = _mm256_blend_pd(_mm256_add_pd(r6, sw), _mm256_sub_pd(sw, r6), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r7, r7, 0x01);
      r7 = _mm256_blend_pd(_mm256_add_pd(r7, sw), _mm256_sub_pd(sw, r7), 0xC); }
    // stage 1 (m=4, ymm-distance 1)
    { const __m256d b = r1; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(1.0, 1.0, 0.0, 0.0), xsw));
      r1 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r3; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(1.0, 1.0, 0.0, 0.0), xsw));
      r3 = _mm256_sub_pd(r2, t); r2 = _mm256_add_pd(r2, t); }
    { const __m256d b = r5; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(1.0, 1.0, 0.0, 0.0), xsw));
      r5 = _mm256_sub_pd(r4, t); r4 = _mm256_add_pd(r4, t); }
    { const __m256d b = r7; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(1.0, 1.0, 0.0, 0.0), xsw));
      r7 = _mm256_sub_pd(r6, t); r6 = _mm256_add_pd(r6, t); }
    // stage 2 (m=8, ymm-distance 2)
    { const __m256d b = r2; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(0.7071067811865475, 0.7071067811865475, 0.0, 0.0), xsw));
      r2 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r3; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), xsw));
      r3 = _mm256_sub_pd(r1, t); r1 = _mm256_add_pd(r1, t); }
    { const __m256d b = r6; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(0.7071067811865475, 0.7071067811865475, 0.0, 0.0), xsw));
      r6 = _mm256_sub_pd(r4, t); r4 = _mm256_add_pd(r4, t); }
    { const __m256d b = r7; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), xsw));
      r7 = _mm256_sub_pd(r5, t); r5 = _mm256_add_pd(r5, t); }
    // stage 3 (m=16, ymm-distance 4)
    { const __m256d b = r4; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.9238795325112867, 0.9238795325112867, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(0.3826834323650898, 0.3826834323650898, 0.0, 0.0), xsw));
      r4 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r5; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.38268343236508984, 0.38268343236508984, 0.7071067811865476, 0.7071067811865476), b, _mm256_mul_pd(_mm256_set_pd(0.9238795325112867, 0.9238795325112867, 0.7071067811865475, 0.7071067811865475), xsw));
      r5 = _mm256_sub_pd(r1, t); r1 = _mm256_add_pd(r1, t); }
    { const __m256d b = r6; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.3826834323650897, -0.3826834323650897, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(0.9238795325112867, 0.9238795325112867, 1.0, 1.0), xsw));
      r6 = _mm256_sub_pd(r2, t); r2 = _mm256_add_pd(r2, t); }
    { const __m256d b = r7; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.9238795325112867, -0.9238795325112867, -0.7071067811865475, -0.7071067811865475), b, _mm256_mul_pd(_mm256_set_pd(0.3826834323650899, 0.3826834323650899, 0.7071067811865476, 0.7071067811865476), xsw));
      r7 = _mm256_sub_pd(r3, t); r3 = _mm256_add_pd(r3, t); }
    _mm256_storeu_pd(out + 0, r0);
    _mm256_storeu_pd(out + 4, r1);
    _mm256_storeu_pd(out + 8, r2);
    _mm256_storeu_pd(out + 12, r3);
    _mm256_storeu_pd(out + 16, r4);
    _mm256_storeu_pd(out + 20, r5);
    _mm256_storeu_pd(out + 24, r6);
    _mm256_storeu_pd(out + 28, r7);
}

// AoS radix-32 DIT codelet (fwd). in/out: raw AoS doubles [r0,i0,r1,i1,...], 32 complex.
static inline void aos_codelet_32_fwd(const double* in, double* out) noexcept
{
    __m256d r0 = _mm256_set_pd(in[33], in[32], in[1], in[0]);
    __m256d r1 = _mm256_set_pd(in[49], in[48], in[17], in[16]);
    __m256d r2 = _mm256_set_pd(in[41], in[40], in[9], in[8]);
    __m256d r3 = _mm256_set_pd(in[57], in[56], in[25], in[24]);
    __m256d r4 = _mm256_set_pd(in[37], in[36], in[5], in[4]);
    __m256d r5 = _mm256_set_pd(in[53], in[52], in[21], in[20]);
    __m256d r6 = _mm256_set_pd(in[45], in[44], in[13], in[12]);
    __m256d r7 = _mm256_set_pd(in[61], in[60], in[29], in[28]);
    __m256d r8 = _mm256_set_pd(in[35], in[34], in[3], in[2]);
    __m256d r9 = _mm256_set_pd(in[51], in[50], in[19], in[18]);
    __m256d r10 = _mm256_set_pd(in[43], in[42], in[11], in[10]);
    __m256d r11 = _mm256_set_pd(in[59], in[58], in[27], in[26]);
    __m256d r12 = _mm256_set_pd(in[39], in[38], in[7], in[6]);
    __m256d r13 = _mm256_set_pd(in[55], in[54], in[23], in[22]);
    __m256d r14 = _mm256_set_pd(in[47], in[46], in[15], in[14]);
    __m256d r15 = _mm256_set_pd(in[63], in[62], in[31], in[30]);
    // stage 0 (distance 1, intra-ymm, twiddle 1)
    { const __m256d sw = _mm256_permute2f128_pd(r0, r0, 0x01);
      r0 = _mm256_blend_pd(_mm256_add_pd(r0, sw), _mm256_sub_pd(sw, r0), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r1, r1, 0x01);
      r1 = _mm256_blend_pd(_mm256_add_pd(r1, sw), _mm256_sub_pd(sw, r1), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r2, r2, 0x01);
      r2 = _mm256_blend_pd(_mm256_add_pd(r2, sw), _mm256_sub_pd(sw, r2), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r3, r3, 0x01);
      r3 = _mm256_blend_pd(_mm256_add_pd(r3, sw), _mm256_sub_pd(sw, r3), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r4, r4, 0x01);
      r4 = _mm256_blend_pd(_mm256_add_pd(r4, sw), _mm256_sub_pd(sw, r4), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r5, r5, 0x01);
      r5 = _mm256_blend_pd(_mm256_add_pd(r5, sw), _mm256_sub_pd(sw, r5), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r6, r6, 0x01);
      r6 = _mm256_blend_pd(_mm256_add_pd(r6, sw), _mm256_sub_pd(sw, r6), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r7, r7, 0x01);
      r7 = _mm256_blend_pd(_mm256_add_pd(r7, sw), _mm256_sub_pd(sw, r7), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r8, r8, 0x01);
      r8 = _mm256_blend_pd(_mm256_add_pd(r8, sw), _mm256_sub_pd(sw, r8), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r9, r9, 0x01);
      r9 = _mm256_blend_pd(_mm256_add_pd(r9, sw), _mm256_sub_pd(sw, r9), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r10, r10, 0x01);
      r10 = _mm256_blend_pd(_mm256_add_pd(r10, sw), _mm256_sub_pd(sw, r10), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r11, r11, 0x01);
      r11 = _mm256_blend_pd(_mm256_add_pd(r11, sw), _mm256_sub_pd(sw, r11), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r12, r12, 0x01);
      r12 = _mm256_blend_pd(_mm256_add_pd(r12, sw), _mm256_sub_pd(sw, r12), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r13, r13, 0x01);
      r13 = _mm256_blend_pd(_mm256_add_pd(r13, sw), _mm256_sub_pd(sw, r13), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r14, r14, 0x01);
      r14 = _mm256_blend_pd(_mm256_add_pd(r14, sw), _mm256_sub_pd(sw, r14), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r15, r15, 0x01);
      r15 = _mm256_blend_pd(_mm256_add_pd(r15, sw), _mm256_sub_pd(sw, r15), 0xC); }
    // stage 1 (m=4, ymm-distance 1)
    { const __m256d b = r1; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-1.0, -1.0, 0.0, 0.0), xsw));
      r1 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r3; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-1.0, -1.0, 0.0, 0.0), xsw));
      r3 = _mm256_sub_pd(r2, t); r2 = _mm256_add_pd(r2, t); }
    { const __m256d b = r5; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-1.0, -1.0, 0.0, 0.0), xsw));
      r5 = _mm256_sub_pd(r4, t); r4 = _mm256_add_pd(r4, t); }
    { const __m256d b = r7; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-1.0, -1.0, 0.0, 0.0), xsw));
      r7 = _mm256_sub_pd(r6, t); r6 = _mm256_add_pd(r6, t); }
    { const __m256d b = r9; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-1.0, -1.0, 0.0, 0.0), xsw));
      r9 = _mm256_sub_pd(r8, t); r8 = _mm256_add_pd(r8, t); }
    { const __m256d b = r11; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-1.0, -1.0, 0.0, 0.0), xsw));
      r11 = _mm256_sub_pd(r10, t); r10 = _mm256_add_pd(r10, t); }
    { const __m256d b = r13; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-1.0, -1.0, 0.0, 0.0), xsw));
      r13 = _mm256_sub_pd(r12, t); r12 = _mm256_add_pd(r12, t); }
    { const __m256d b = r15; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-1.0, -1.0, 0.0, 0.0), xsw));
      r15 = _mm256_sub_pd(r14, t); r14 = _mm256_add_pd(r14, t); }
    // stage 2 (m=8, ymm-distance 2)
    { const __m256d b = r2; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 0.0, 0.0), xsw));
      r2 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r3; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(-0.7071067811865476, -0.7071067811865476, -1.0, -1.0), xsw));
      r3 = _mm256_sub_pd(r1, t); r1 = _mm256_add_pd(r1, t); }
    { const __m256d b = r6; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 0.0, 0.0), xsw));
      r6 = _mm256_sub_pd(r4, t); r4 = _mm256_add_pd(r4, t); }
    { const __m256d b = r7; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(-0.7071067811865476, -0.7071067811865476, -1.0, -1.0), xsw));
      r7 = _mm256_sub_pd(r5, t); r5 = _mm256_add_pd(r5, t); }
    { const __m256d b = r10; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 0.0, 0.0), xsw));
      r10 = _mm256_sub_pd(r8, t); r8 = _mm256_add_pd(r8, t); }
    { const __m256d b = r11; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(-0.7071067811865476, -0.7071067811865476, -1.0, -1.0), xsw));
      r11 = _mm256_sub_pd(r9, t); r9 = _mm256_add_pd(r9, t); }
    { const __m256d b = r14; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 0.0, 0.0), xsw));
      r14 = _mm256_sub_pd(r12, t); r12 = _mm256_add_pd(r12, t); }
    { const __m256d b = r15; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(-0.7071067811865476, -0.7071067811865476, -1.0, -1.0), xsw));
      r15 = _mm256_sub_pd(r13, t); r13 = _mm256_add_pd(r13, t); }
    // stage 3 (m=16, ymm-distance 4)
    { const __m256d b = r4; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.9238795325112867, 0.9238795325112867, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-0.3826834323650898, -0.3826834323650898, 0.0, 0.0), xsw));
      r4 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r5; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.38268343236508984, 0.38268343236508984, 0.7071067811865476, 0.7071067811865476), b, _mm256_mul_pd(_mm256_set_pd(-0.9238795325112867, -0.9238795325112867, -0.7071067811865475, -0.7071067811865475), xsw));
      r5 = _mm256_sub_pd(r1, t); r1 = _mm256_add_pd(r1, t); }
    { const __m256d b = r6; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.3826834323650897, -0.3826834323650897, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(-0.9238795325112867, -0.9238795325112867, -1.0, -1.0), xsw));
      r6 = _mm256_sub_pd(r2, t); r2 = _mm256_add_pd(r2, t); }
    { const __m256d b = r7; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.9238795325112867, -0.9238795325112867, -0.7071067811865475, -0.7071067811865475), b, _mm256_mul_pd(_mm256_set_pd(-0.3826834323650899, -0.3826834323650899, -0.7071067811865476, -0.7071067811865476), xsw));
      r7 = _mm256_sub_pd(r3, t); r3 = _mm256_add_pd(r3, t); }
    { const __m256d b = r12; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.9238795325112867, 0.9238795325112867, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-0.3826834323650898, -0.3826834323650898, 0.0, 0.0), xsw));
      r12 = _mm256_sub_pd(r8, t); r8 = _mm256_add_pd(r8, t); }
    { const __m256d b = r13; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.38268343236508984, 0.38268343236508984, 0.7071067811865476, 0.7071067811865476), b, _mm256_mul_pd(_mm256_set_pd(-0.9238795325112867, -0.9238795325112867, -0.7071067811865475, -0.7071067811865475), xsw));
      r13 = _mm256_sub_pd(r9, t); r9 = _mm256_add_pd(r9, t); }
    { const __m256d b = r14; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.3826834323650897, -0.3826834323650897, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(-0.9238795325112867, -0.9238795325112867, -1.0, -1.0), xsw));
      r14 = _mm256_sub_pd(r10, t); r10 = _mm256_add_pd(r10, t); }
    { const __m256d b = r15; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.9238795325112867, -0.9238795325112867, -0.7071067811865475, -0.7071067811865475), b, _mm256_mul_pd(_mm256_set_pd(-0.3826834323650899, -0.3826834323650899, -0.7071067811865476, -0.7071067811865476), xsw));
      r15 = _mm256_sub_pd(r11, t); r11 = _mm256_add_pd(r11, t); }
    // stage 4 (m=32, ymm-distance 8)
    { const __m256d b = r8; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.9807852804032304, 0.9807852804032304, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(-0.19509032201612825, -0.19509032201612825, 0.0, 0.0), xsw));
      r8 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r9; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.8314696123025452, 0.8314696123025452, 0.9238795325112867, 0.9238795325112867), b, _mm256_mul_pd(_mm256_set_pd(-0.5555702330196022, -0.5555702330196022, -0.3826834323650898, -0.3826834323650898), xsw));
      r9 = _mm256_sub_pd(r1, t); r1 = _mm256_add_pd(r1, t); }
    { const __m256d b = r10; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.5555702330196023, 0.5555702330196023, 0.7071067811865476, 0.7071067811865476), b, _mm256_mul_pd(_mm256_set_pd(-0.8314696123025452, -0.8314696123025452, -0.7071067811865475, -0.7071067811865475), xsw));
      r10 = _mm256_sub_pd(r2, t); r2 = _mm256_add_pd(r2, t); }
    { const __m256d b = r11; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.19509032201612833, 0.19509032201612833, 0.38268343236508984, 0.38268343236508984), b, _mm256_mul_pd(_mm256_set_pd(-0.9807852804032304, -0.9807852804032304, -0.9238795325112867, -0.9238795325112867), xsw));
      r11 = _mm256_sub_pd(r3, t); r3 = _mm256_add_pd(r3, t); }
    { const __m256d b = r12; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.1950903220161282, -0.1950903220161282, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(-0.9807852804032304, -0.9807852804032304, -1.0, -1.0), xsw));
      r12 = _mm256_sub_pd(r4, t); r4 = _mm256_add_pd(r4, t); }
    { const __m256d b = r13; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.555570233019602, -0.555570233019602, -0.3826834323650897, -0.3826834323650897), b, _mm256_mul_pd(_mm256_set_pd(-0.8314696123025455, -0.8314696123025455, -0.9238795325112867, -0.9238795325112867), xsw));
      r13 = _mm256_sub_pd(r5, t); r5 = _mm256_add_pd(r5, t); }
    { const __m256d b = r14; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.8314696123025453, -0.8314696123025453, -0.7071067811865475, -0.7071067811865475), b, _mm256_mul_pd(_mm256_set_pd(-0.5555702330196022, -0.5555702330196022, -0.7071067811865476, -0.7071067811865476), xsw));
      r14 = _mm256_sub_pd(r6, t); r6 = _mm256_add_pd(r6, t); }
    { const __m256d b = r15; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.9807852804032304, -0.9807852804032304, -0.9238795325112867, -0.9238795325112867), b, _mm256_mul_pd(_mm256_set_pd(-0.1950903220161286, -0.1950903220161286, -0.3826834323650899, -0.3826834323650899), xsw));
      r15 = _mm256_sub_pd(r7, t); r7 = _mm256_add_pd(r7, t); }
    _mm256_storeu_pd(out + 0, r0);
    _mm256_storeu_pd(out + 4, r1);
    _mm256_storeu_pd(out + 8, r2);
    _mm256_storeu_pd(out + 12, r3);
    _mm256_storeu_pd(out + 16, r4);
    _mm256_storeu_pd(out + 20, r5);
    _mm256_storeu_pd(out + 24, r6);
    _mm256_storeu_pd(out + 28, r7);
    _mm256_storeu_pd(out + 32, r8);
    _mm256_storeu_pd(out + 36, r9);
    _mm256_storeu_pd(out + 40, r10);
    _mm256_storeu_pd(out + 44, r11);
    _mm256_storeu_pd(out + 48, r12);
    _mm256_storeu_pd(out + 52, r13);
    _mm256_storeu_pd(out + 56, r14);
    _mm256_storeu_pd(out + 60, r15);
}
// AoS radix-32 DIT codelet (inv). in/out: raw AoS doubles [r0,i0,r1,i1,...], 32 complex.
static inline void aos_codelet_32_inv(const double* in, double* out) noexcept
{
    __m256d r0 = _mm256_set_pd(in[33], in[32], in[1], in[0]);
    __m256d r1 = _mm256_set_pd(in[49], in[48], in[17], in[16]);
    __m256d r2 = _mm256_set_pd(in[41], in[40], in[9], in[8]);
    __m256d r3 = _mm256_set_pd(in[57], in[56], in[25], in[24]);
    __m256d r4 = _mm256_set_pd(in[37], in[36], in[5], in[4]);
    __m256d r5 = _mm256_set_pd(in[53], in[52], in[21], in[20]);
    __m256d r6 = _mm256_set_pd(in[45], in[44], in[13], in[12]);
    __m256d r7 = _mm256_set_pd(in[61], in[60], in[29], in[28]);
    __m256d r8 = _mm256_set_pd(in[35], in[34], in[3], in[2]);
    __m256d r9 = _mm256_set_pd(in[51], in[50], in[19], in[18]);
    __m256d r10 = _mm256_set_pd(in[43], in[42], in[11], in[10]);
    __m256d r11 = _mm256_set_pd(in[59], in[58], in[27], in[26]);
    __m256d r12 = _mm256_set_pd(in[39], in[38], in[7], in[6]);
    __m256d r13 = _mm256_set_pd(in[55], in[54], in[23], in[22]);
    __m256d r14 = _mm256_set_pd(in[47], in[46], in[15], in[14]);
    __m256d r15 = _mm256_set_pd(in[63], in[62], in[31], in[30]);
    // stage 0 (distance 1, intra-ymm, twiddle 1)
    { const __m256d sw = _mm256_permute2f128_pd(r0, r0, 0x01);
      r0 = _mm256_blend_pd(_mm256_add_pd(r0, sw), _mm256_sub_pd(sw, r0), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r1, r1, 0x01);
      r1 = _mm256_blend_pd(_mm256_add_pd(r1, sw), _mm256_sub_pd(sw, r1), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r2, r2, 0x01);
      r2 = _mm256_blend_pd(_mm256_add_pd(r2, sw), _mm256_sub_pd(sw, r2), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r3, r3, 0x01);
      r3 = _mm256_blend_pd(_mm256_add_pd(r3, sw), _mm256_sub_pd(sw, r3), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r4, r4, 0x01);
      r4 = _mm256_blend_pd(_mm256_add_pd(r4, sw), _mm256_sub_pd(sw, r4), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r5, r5, 0x01);
      r5 = _mm256_blend_pd(_mm256_add_pd(r5, sw), _mm256_sub_pd(sw, r5), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r6, r6, 0x01);
      r6 = _mm256_blend_pd(_mm256_add_pd(r6, sw), _mm256_sub_pd(sw, r6), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r7, r7, 0x01);
      r7 = _mm256_blend_pd(_mm256_add_pd(r7, sw), _mm256_sub_pd(sw, r7), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r8, r8, 0x01);
      r8 = _mm256_blend_pd(_mm256_add_pd(r8, sw), _mm256_sub_pd(sw, r8), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r9, r9, 0x01);
      r9 = _mm256_blend_pd(_mm256_add_pd(r9, sw), _mm256_sub_pd(sw, r9), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r10, r10, 0x01);
      r10 = _mm256_blend_pd(_mm256_add_pd(r10, sw), _mm256_sub_pd(sw, r10), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r11, r11, 0x01);
      r11 = _mm256_blend_pd(_mm256_add_pd(r11, sw), _mm256_sub_pd(sw, r11), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r12, r12, 0x01);
      r12 = _mm256_blend_pd(_mm256_add_pd(r12, sw), _mm256_sub_pd(sw, r12), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r13, r13, 0x01);
      r13 = _mm256_blend_pd(_mm256_add_pd(r13, sw), _mm256_sub_pd(sw, r13), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r14, r14, 0x01);
      r14 = _mm256_blend_pd(_mm256_add_pd(r14, sw), _mm256_sub_pd(sw, r14), 0xC); }
    { const __m256d sw = _mm256_permute2f128_pd(r15, r15, 0x01);
      r15 = _mm256_blend_pd(_mm256_add_pd(r15, sw), _mm256_sub_pd(sw, r15), 0xC); }
    // stage 1 (m=4, ymm-distance 1)
    { const __m256d b = r1; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(1.0, 1.0, 0.0, 0.0), xsw));
      r1 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r3; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(1.0, 1.0, 0.0, 0.0), xsw));
      r3 = _mm256_sub_pd(r2, t); r2 = _mm256_add_pd(r2, t); }
    { const __m256d b = r5; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(1.0, 1.0, 0.0, 0.0), xsw));
      r5 = _mm256_sub_pd(r4, t); r4 = _mm256_add_pd(r4, t); }
    { const __m256d b = r7; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(1.0, 1.0, 0.0, 0.0), xsw));
      r7 = _mm256_sub_pd(r6, t); r6 = _mm256_add_pd(r6, t); }
    { const __m256d b = r9; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(1.0, 1.0, 0.0, 0.0), xsw));
      r9 = _mm256_sub_pd(r8, t); r8 = _mm256_add_pd(r8, t); }
    { const __m256d b = r11; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(1.0, 1.0, 0.0, 0.0), xsw));
      r11 = _mm256_sub_pd(r10, t); r10 = _mm256_add_pd(r10, t); }
    { const __m256d b = r13; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(1.0, 1.0, 0.0, 0.0), xsw));
      r13 = _mm256_sub_pd(r12, t); r12 = _mm256_add_pd(r12, t); }
    { const __m256d b = r15; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(6.123233995736766e-17, 6.123233995736766e-17, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(1.0, 1.0, 0.0, 0.0), xsw));
      r15 = _mm256_sub_pd(r14, t); r14 = _mm256_add_pd(r14, t); }
    // stage 2 (m=8, ymm-distance 2)
    { const __m256d b = r2; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(0.7071067811865475, 0.7071067811865475, 0.0, 0.0), xsw));
      r2 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r3; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), xsw));
      r3 = _mm256_sub_pd(r1, t); r1 = _mm256_add_pd(r1, t); }
    { const __m256d b = r6; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(0.7071067811865475, 0.7071067811865475, 0.0, 0.0), xsw));
      r6 = _mm256_sub_pd(r4, t); r4 = _mm256_add_pd(r4, t); }
    { const __m256d b = r7; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), xsw));
      r7 = _mm256_sub_pd(r5, t); r5 = _mm256_add_pd(r5, t); }
    { const __m256d b = r10; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(0.7071067811865475, 0.7071067811865475, 0.0, 0.0), xsw));
      r10 = _mm256_sub_pd(r8, t); r8 = _mm256_add_pd(r8, t); }
    { const __m256d b = r11; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), xsw));
      r11 = _mm256_sub_pd(r9, t); r9 = _mm256_add_pd(r9, t); }
    { const __m256d b = r14; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(0.7071067811865475, 0.7071067811865475, 0.0, 0.0), xsw));
      r14 = _mm256_sub_pd(r12, t); r12 = _mm256_add_pd(r12, t); }
    { const __m256d b = r15; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.7071067811865475, -0.7071067811865475, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(0.7071067811865476, 0.7071067811865476, 1.0, 1.0), xsw));
      r15 = _mm256_sub_pd(r13, t); r13 = _mm256_add_pd(r13, t); }
    // stage 3 (m=16, ymm-distance 4)
    { const __m256d b = r4; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.9238795325112867, 0.9238795325112867, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(0.3826834323650898, 0.3826834323650898, 0.0, 0.0), xsw));
      r4 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r5; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.38268343236508984, 0.38268343236508984, 0.7071067811865476, 0.7071067811865476), b, _mm256_mul_pd(_mm256_set_pd(0.9238795325112867, 0.9238795325112867, 0.7071067811865475, 0.7071067811865475), xsw));
      r5 = _mm256_sub_pd(r1, t); r1 = _mm256_add_pd(r1, t); }
    { const __m256d b = r6; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.3826834323650897, -0.3826834323650897, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(0.9238795325112867, 0.9238795325112867, 1.0, 1.0), xsw));
      r6 = _mm256_sub_pd(r2, t); r2 = _mm256_add_pd(r2, t); }
    { const __m256d b = r7; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.9238795325112867, -0.9238795325112867, -0.7071067811865475, -0.7071067811865475), b, _mm256_mul_pd(_mm256_set_pd(0.3826834323650899, 0.3826834323650899, 0.7071067811865476, 0.7071067811865476), xsw));
      r7 = _mm256_sub_pd(r3, t); r3 = _mm256_add_pd(r3, t); }
    { const __m256d b = r12; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.9238795325112867, 0.9238795325112867, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(0.3826834323650898, 0.3826834323650898, 0.0, 0.0), xsw));
      r12 = _mm256_sub_pd(r8, t); r8 = _mm256_add_pd(r8, t); }
    { const __m256d b = r13; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.38268343236508984, 0.38268343236508984, 0.7071067811865476, 0.7071067811865476), b, _mm256_mul_pd(_mm256_set_pd(0.9238795325112867, 0.9238795325112867, 0.7071067811865475, 0.7071067811865475), xsw));
      r13 = _mm256_sub_pd(r9, t); r9 = _mm256_add_pd(r9, t); }
    { const __m256d b = r14; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.3826834323650897, -0.3826834323650897, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(0.9238795325112867, 0.9238795325112867, 1.0, 1.0), xsw));
      r14 = _mm256_sub_pd(r10, t); r10 = _mm256_add_pd(r10, t); }
    { const __m256d b = r15; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.9238795325112867, -0.9238795325112867, -0.7071067811865475, -0.7071067811865475), b, _mm256_mul_pd(_mm256_set_pd(0.3826834323650899, 0.3826834323650899, 0.7071067811865476, 0.7071067811865476), xsw));
      r15 = _mm256_sub_pd(r11, t); r11 = _mm256_add_pd(r11, t); }
    // stage 4 (m=32, ymm-distance 8)
    { const __m256d b = r8; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.9807852804032304, 0.9807852804032304, 1.0, 1.0), b, _mm256_mul_pd(_mm256_set_pd(0.19509032201612825, 0.19509032201612825, 0.0, 0.0), xsw));
      r8 = _mm256_sub_pd(r0, t); r0 = _mm256_add_pd(r0, t); }
    { const __m256d b = r9; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.8314696123025452, 0.8314696123025452, 0.9238795325112867, 0.9238795325112867), b, _mm256_mul_pd(_mm256_set_pd(0.5555702330196022, 0.5555702330196022, 0.3826834323650898, 0.3826834323650898), xsw));
      r9 = _mm256_sub_pd(r1, t); r1 = _mm256_add_pd(r1, t); }
    { const __m256d b = r10; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.5555702330196023, 0.5555702330196023, 0.7071067811865476, 0.7071067811865476), b, _mm256_mul_pd(_mm256_set_pd(0.8314696123025452, 0.8314696123025452, 0.7071067811865475, 0.7071067811865475), xsw));
      r10 = _mm256_sub_pd(r2, t); r2 = _mm256_add_pd(r2, t); }
    { const __m256d b = r11; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(0.19509032201612833, 0.19509032201612833, 0.38268343236508984, 0.38268343236508984), b, _mm256_mul_pd(_mm256_set_pd(0.9807852804032304, 0.9807852804032304, 0.9238795325112867, 0.9238795325112867), xsw));
      r11 = _mm256_sub_pd(r3, t); r3 = _mm256_add_pd(r3, t); }
    { const __m256d b = r12; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.1950903220161282, -0.1950903220161282, 6.123233995736766e-17, 6.123233995736766e-17), b, _mm256_mul_pd(_mm256_set_pd(0.9807852804032304, 0.9807852804032304, 1.0, 1.0), xsw));
      r12 = _mm256_sub_pd(r4, t); r4 = _mm256_add_pd(r4, t); }
    { const __m256d b = r13; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.555570233019602, -0.555570233019602, -0.3826834323650897, -0.3826834323650897), b, _mm256_mul_pd(_mm256_set_pd(0.8314696123025455, 0.8314696123025455, 0.9238795325112867, 0.9238795325112867), xsw));
      r13 = _mm256_sub_pd(r5, t); r5 = _mm256_add_pd(r5, t); }
    { const __m256d b = r14; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.8314696123025453, -0.8314696123025453, -0.7071067811865475, -0.7071067811865475), b, _mm256_mul_pd(_mm256_set_pd(0.5555702330196022, 0.5555702330196022, 0.7071067811865476, 0.7071067811865476), xsw));
      r14 = _mm256_sub_pd(r6, t); r6 = _mm256_add_pd(r6, t); }
    { const __m256d b = r15; const __m256d xsw = _mm256_permute_pd(b, 0x5);
      const __m256d t = _mm256_fmaddsub_pd(_mm256_set_pd(-0.9807852804032304, -0.9807852804032304, -0.9238795325112867, -0.9238795325112867), b, _mm256_mul_pd(_mm256_set_pd(0.1950903220161286, 0.1950903220161286, 0.3826834323650899, 0.3826834323650899), xsw));
      r15 = _mm256_sub_pd(r7, t); r7 = _mm256_add_pd(r7, t); }
    _mm256_storeu_pd(out + 0, r0);
    _mm256_storeu_pd(out + 4, r1);
    _mm256_storeu_pd(out + 8, r2);
    _mm256_storeu_pd(out + 12, r3);
    _mm256_storeu_pd(out + 16, r4);
    _mm256_storeu_pd(out + 20, r5);
    _mm256_storeu_pd(out + 24, r6);
    _mm256_storeu_pd(out + 28, r7);
    _mm256_storeu_pd(out + 32, r8);
    _mm256_storeu_pd(out + 36, r9);
    _mm256_storeu_pd(out + 40, r10);
    _mm256_storeu_pd(out + 44, r11);
    _mm256_storeu_pd(out + 48, r12);
    _mm256_storeu_pd(out + 52, r13);
    _mm256_storeu_pd(out + 56, r14);
    _mm256_storeu_pd(out + 60, r15);
}

} // namespace crd::hesap::fft::detail
