// v14-a substrate gates: the NumPy view/stride-semantics corpus (ADR-0096 §3).
// Reference values generated by scripts/v14a_view_corpus.py from
// arange(24, f64).reshape(2,3,4) — reconstruct-verify-first: every expected
// shape / ELEMENT stride / contiguity flag / row-major element readout below
// is NumPy's own output, baked as plain C arrays (no std containers in refs).

#include <crd/hesap/tensor/tensor.hpp>
#include <crd/memory/allocators/tlsf_allocator.hpp>

#include <catch2/catch_test_macros.hpp>

using crd::hesap::tensor::kMaxRank;
using crd::hesap::tensor::Tensor;
using crd::hesap::tensor::TensorStatus;
using crd::hesap::tensor::TensorView;

namespace
{

// Fill with arange(24) and return the base 2x3x4 tensor.
Tensor<crd::f64> make_base(crd::memory::IAllocator* alloc)
{
    const crd::u64 shape[] = {2U, 3U, 4U};
    Tensor<crd::f64> t(alloc, shape);
    for (crd::u64 i = 0; i < 24U; ++i)
    {
        t.data()[i] = static_cast<crd::f64>(i);
    }
    return t;
}

// Gate a view against NumPy's shape / element strides / contiguity / row-major readout.
template <crd::usize NS, crd::usize NE>
void check_against_numpy(const TensorView<crd::f64>& v, const crd::u64 (&shape)[NS], const crd::i64 (&strides)[NS],
                         bool contiguous, const crd::f64 (&flat)[NE])
{
    REQUIRE(v.rank() == static_cast<crd::u32>(NS));
    for (crd::u32 d = 0; d < static_cast<crd::u32>(NS); ++d)
    {
        CHECK(v.shape(d) == shape[d]);
        CHECK(v.stride(d) == strides[d]);
    }
    CHECK(v.is_contiguous() == contiguous);
    REQUIRE(v.size() == static_cast<crd::u64>(NE));
    crd::u64 k = 0;
    v.for_each([&](const crd::u64* /*idx*/, crd::f64& value) { CHECK(value == flat[k++]); });
    CHECK(k == static_cast<crd::u64>(NE));
}

} // namespace

TEST_CASE("v14-a TensorView: base contiguous layout matches NumPy", "[hesap][tensor][v14]")
{
    crd::memory::TlsfAllocator alloc(1U << 20);
    Tensor<crd::f64> t = make_base(&alloc);

    const crd::u64 shape[] = {2U, 3U, 4U};
    const crd::i64 strides[] = {12, 4, 1};
    const crd::f64 flat[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
    check_against_numpy(t.view(), shape, strides, true, flat);

    // Element access agrees with the stride math.
    TensorView<crd::f64> v = t.view();
    CHECK(v(1U, 2U, 3U) == 23.0);
    const crd::u64 idx[] = {0U, 2U, 1U};
    CHECK(v.at(idx) == 9.0);
}

TEST_CASE("v14-a TensorView: permute(2,0,1) matches NumPy transpose", "[hesap][tensor][v14]")
{
    crd::memory::TlsfAllocator alloc(1U << 20);
    Tensor<crd::f64> t = make_base(&alloc);

    const crd::u32 order[] = {2U, 0U, 1U};
    TensorView<crd::f64> v = t.view().permute(order);

    const crd::u64 shape[] = {4U, 2U, 3U};
    const crd::i64 strides[] = {1, 12, 4};
    const crd::f64 flat[] = {0, 4, 8, 12, 16, 20, 1, 5, 9, 13, 17, 21, 2, 6, 10, 14, 18, 22, 3, 7, 11, 15, 19, 23};
    check_against_numpy(v, shape, strides, false, flat);
}

TEST_CASE("v14-a TensorView: slice[:,1:3,::2] matches NumPy basic slicing", "[hesap][tensor][v14]")
{
    crd::memory::TlsfAllocator alloc(1U << 20);
    Tensor<crd::f64> t = make_base(&alloc);

    TensorView<crd::f64> v = t.view().slice(1U, 1U, 3U).slice(2U, 0U, 4U, 2U);

    const crd::u64 shape[] = {2U, 2U, 2U};
    const crd::i64 strides[] = {12, 4, 2};
    const crd::f64 flat[] = {4, 6, 8, 10, 16, 18, 20, 22};
    check_against_numpy(v, shape, strides, false, flat);
}

TEST_CASE("v14-a TensorView: flip(dim 2) = NumPy [::-1] negative stride", "[hesap][tensor][v14]")
{
    crd::memory::TlsfAllocator alloc(1U << 20);
    Tensor<crd::f64> t = make_base(&alloc);

    TensorView<crd::f64> v = t.view().flip(2U);

    const crd::u64 shape[] = {2U, 3U, 4U};
    const crd::i64 strides[] = {12, 4, -1};
    const crd::f64 flat[] = {3, 2, 1, 0, 7, 6, 5, 4, 11, 10, 9, 8, 15, 14, 13, 12, 19, 18, 17, 16, 23, 22, 21, 20};
    check_against_numpy(v, shape, strides, false, flat);
}

TEST_CASE("v14-a TensorView: select drops rank like NumPy integer indexing", "[hesap][tensor][v14]")
{
    crd::memory::TlsfAllocator alloc(1U << 20);
    Tensor<crd::f64> t = make_base(&alloc);

    // a[1,:,:] — NumPy reports this view C-contiguous.
    {
        TensorView<crd::f64> v = t.view().select(0U, 1U);
        const crd::u64 shape[] = {3U, 4U};
        const crd::i64 strides[] = {4, 1};
        const crd::f64 flat[] = {12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
        check_against_numpy(v, shape, strides, true, flat);
    }
    // a[:,2,:] — mid-dim drop is NOT contiguous.
    {
        TensorView<crd::f64> v = t.view().select(1U, 2U);
        const crd::u64 shape[] = {2U, 4U};
        const crd::i64 strides[] = {12, 1};
        const crd::f64 flat[] = {8, 9, 10, 11, 20, 21, 22, 23};
        check_against_numpy(v, shape, strides, false, flat);
    }
}

TEST_CASE("v14-a TensorView: broadcast_to matches NumPy stride-0 semantics", "[hesap][tensor][v14]")
{
    crd::memory::TlsfAllocator alloc(1U << 20);
    // b = arange(3).reshape(3,1) broadcast to (2,3,4).
    const crd::u64 bshape[] = {3U, 1U};
    Tensor<crd::f64> b(&alloc, bshape);
    for (crd::u64 i = 0; i < 3U; ++i)
    {
        b.data()[i] = static_cast<crd::f64>(i);
    }

    const crd::u64 target[] = {2U, 3U, 4U};
    TensorView<crd::f64> v;
    REQUIRE(b.view().broadcast_to(target, v) == TensorStatus::Ok);

    const crd::u64 shape[] = {2U, 3U, 4U};
    const crd::i64 strides[] = {0, 1, 0};
    const crd::f64 flat[] = {0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2};
    check_against_numpy(v, shape, strides, false, flat);

    // Mismatched non-1 dim is rejected with a status, never UB.
    const crd::u64 bad[] = {2U, 4U, 4U};
    TensorView<crd::f64> w;
    CHECK(b.view().broadcast_to(bad, w) == TensorStatus::ShapeMismatch);
}

TEST_CASE("v14-a TensorView: reshape (contiguous view-level) matches NumPy", "[hesap][tensor][v14]")
{
    crd::memory::TlsfAllocator alloc(1U << 20);
    Tensor<crd::f64> t = make_base(&alloc);

    const crd::u64 new_shape[] = {6U, 4U};
    TensorView<crd::f64> v;
    REQUIRE(t.view().reshape(new_shape, v) == TensorStatus::Ok);

    const crd::u64 shape[] = {6U, 4U};
    const crd::i64 strides[] = {4, 1};
    const crd::f64 flat[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
    check_against_numpy(v, shape, strides, true, flat);

    // Non-contiguous source → status (a copy is a Tensor-level op).
    TensorView<crd::f64> w;
    CHECK(t.view().flip(2U).reshape(new_shape, w) == TensorStatus::NotContiguous);
    // Element-count mismatch → status.
    const crd::u64 bad[] = {5U, 5U};
    CHECK(t.view().reshape(bad, w) == TensorStatus::ShapeMismatch);
}

TEST_CASE("v14-a TensorView: composed permute-then-slice matches NumPy", "[hesap][tensor][v14]")
{
    crd::memory::TlsfAllocator alloc(1U << 20);
    Tensor<crd::f64> t = make_base(&alloc);

    // np.transpose(a,(2,0,1))[1:4:2, :, 1:]
    const crd::u32 order[] = {2U, 0U, 1U};
    TensorView<crd::f64> v = t.view().permute(order).slice(0U, 1U, 4U, 2U).slice(2U, 1U, 3U);

    const crd::u64 shape[] = {2U, 2U, 2U};
    const crd::i64 strides[] = {2, 12, 4};
    const crd::f64 flat[] = {5, 9, 17, 21, 7, 11, 19, 23};
    check_against_numpy(v, shape, strides, false, flat);
}

TEST_CASE("v14-a Tensor: status contract - rank overflow, count overflow, zero-size", "[hesap][tensor][v14]")
{
    crd::memory::TlsfAllocator alloc(1U << 20);

    // Rank > kMaxRank is a status, never a crash (data-driven paths contract).
    {
        crd::u64 shape[kMaxRank + 1U];
        for (crd::u64& s : shape)
        {
            s = 1U;
        }
        Tensor<crd::f64> t(&alloc);
        CHECK(t.resize(shape) == TensorStatus::RankOverflow);
    }
    // Element-count overflow is BadInput (defensive validation), never a wrapped alloc.
    {
        const crd::u64 shape[] = {~crd::u64{0} / 2U, 4U};
        Tensor<crd::f64> t(&alloc);
        CHECK(t.resize(shape) == TensorStatus::BadInput);
    }
    // Zero-size dims are valid (empty tensor).
    {
        const crd::u64 shape[] = {2U, 0U, 4U};
        Tensor<crd::f64> t(&alloc);
        REQUIRE(t.resize(shape) == TensorStatus::Ok);
        CHECK(t.size() == 0U);
        CHECK(t.view().is_contiguous());
    }
    // Rank-0 scalar view.
    {
        Tensor<crd::f64> t(&alloc, {});
        REQUIRE(t.size() == 1U);
        t.data()[0] = 42.0;
        TensorView<crd::f64> v = t.view();
        CHECK(v.rank() == 0U);
        CHECK(v() == 42.0);
    }
}
