#pragma once

// crd-ceir — the deterministic textual PARSER (CEIR-1e, §10/§166). Text -> IR: the exact inverse of print.hpp. It
// consumes the canonical MLIR-flavored form the printer emits and rebuilds the SEMANTIC graph (ops / values /
// regions / symbols), so that the round-trip is BYTE-EXACT: print(parse(print(x))) == print(x). Graph LAYOUT
// (coords/edges) is regenerated by the printer and is never parsed — the text is semantics only (§10).
//
// Shape: a recursive-descent parser over a whitespace-skipping cursor; the grammar mirrors the printer one-for-one.
// Errors are REPORTED, never thrown: malformed input yields {ok=false, module=nullptr, error_offset=<byte>} — the
// same signal CEIR-1h's malformed-input corpus consumes. A failed parse mutates nothing the caller can observe (the
// half-built module is arena garbage reclaimed with the Context).

#include <crd/ceir/context.hpp>
#include <crd/ceir/ir.hpp>
#include <crd/containers/string_view.hpp>
#include <crd/core/types.hpp>

namespace crd::ceir
{
// The outcome of a parse: the module on success, or a byte-offset + static reason on failure.
struct ParseResult
{
    Module*     module       = nullptr; // the parsed module, or nullptr on error
    bool        ok           = false;
    usize       error_offset = 0;  // byte offset into `text` where parsing failed (valid only when !ok)
    const char* error        = "";  // a static diagnostic string (valid only when !ok)

    [[nodiscard]] explicit operator bool() const noexcept { return ok; }
};

// Parse `text` (the printer's canonical form) into a fresh Module owned by `ctx`. Never throws. On any malformed
// input returns {ok=false, module=nullptr, error_offset}. Symbol-defining ops (those carrying a `sym_name` string
// attribute, e.g. `func.func`) are re-registered into the module's SymbolTable, so the parsed module resolves the
// same as the original (a duplicate symbol name is a parse error).
[[nodiscard]] ParseResult parse(Context& ctx, containers::StringView text);
} // namespace crd::ceir
