#pragma once

// crd-ceir — the deterministic textual PARSER (CEIR-1e, §10/§166). Text -> IR: the exact inverse of print.hpp. It
// consumes the canonical MLIR-flavored form the printer emits and rebuilds the SEMANTIC graph (ops / values /
// regions / symbols), so that the round-trip is BYTE-EXACT: print(parse(print(x))) == print(x). Graph LAYOUT
// (coords/edges) is regenerated by the printer and is never parsed — the text is semantics only (§10).
//
// Shape: a recursive-descent parser over a whitespace-skipping cursor; the grammar mirrors the printer one-for-one.
// Errors are REPORTED, never thrown: malformed input yields {ok=false, module=nullptr, error_offset=<byte>} — the
// same signal CEIR-1h's malformed-input corpus consumes. A failed parse mutates nothing the caller can observe (the
// half-built module is arena garbage reclaimed with the Context).

#include <crd/ceir/context.hpp>
#include <crd/ceir/ir.hpp>
#include <crd/containers/string_view.hpp>
#include <crd/core/types.hpp>

namespace crd::ceir
{
// The outcome of a parse: the module on success, or a byte-offset + static reason on failure.
struct ParseResult
{
    Module*     module       = nullptr; // the parsed module, or nullptr on error
    bool        ok           = false;
    usize       error_offset = 0;  // byte offset into `text` where parsing failed (valid only when !ok)
    const char* error        = "";  // a static diagnostic string (valid only when !ok)
    // DIAG.8a: the failing text position as a 1-based line:col (0 when ok, and always 0 for a binary deserialize, which
    // reports only `error_offset`), plus the file id the caller passed to `parse` (0 = none).
    u32 error_line    = 0;
    u32 error_col     = 0;
    u32 error_file_id = 0;

    [[nodiscard]] explicit operator bool() const noexcept { return ok; }
};

// Parse `text` (the printer's canonical form) into a fresh Module owned by `ctx`. Never throws. On any malformed
// input returns {ok=false, module=nullptr, error_offset}. Symbol-defining ops (those carrying a `sym_name` string
// attribute, e.g. `func.func`) are re-registered into the module's SymbolTable, so the parsed module resolves the
// same as the original (a duplicate symbol name is a parse error).
[[nodiscard]] ParseResult parse(Context& ctx, containers::StringView text);

// DIAG.8a: parse `text` as the contents of source file `file_id` (a `Context::register_file` id; 0 = unnamed). Every op
// records its authored position as a CarrierOp origin in the Context's provenance side table (provenance.hpp) — debug
// metadata outside the content hash, so reformatting the text changes no hash. A failure reports its position in
// `error_line:error_col`. `parse(ctx, text)` is this with file id 0.
[[nodiscard]] ParseResult parse(Context& ctx, containers::StringView text, u32 file_id);
} // namespace crd::ceir
