#!/usr/bin/env python3
"""v12-j heavy-tail/extreme/noncentral references vs scipy.stats — plain C arrays. NaN slot ⇒ test skips that gate."""
import numpy as np
from scipy import stats

NAN = float("nan")


def row(name, dist, xs, ps, skip_var=False, skip_skew=False, skip_kurt=False, skip_entropy=False):
    xs = np.asarray(xs, float)
    ps = np.asarray(ps, float)
    m, v, s, k = dist.stats(moments="mvsk")
    mvsk = [float(m), NAN if skip_var else float(v), NAN if skip_skew else float(s), NAN if skip_kurt else float(k)]
    ent = NAN if skip_entropy else float(dist.entropy())
    return {"name": name, "x": xs, "pdf": dist.pdf(xs), "logpdf": dist.logpdf(xs), "cdf": dist.cdf(xs),
            "sf": dist.sf(xs), "p": ps, "ppf": dist.ppf(ps), "mvsk": mvsk, "entropy": ent}


def fmt(a):
    return ", ".join("HUGE_VAL" if np.isinf(x) and x > 0 else ("-HUGE_VAL" if np.isinf(x) else
                     ("NAN" if np.isnan(x) else f"{x:.17g}")) for x in np.atleast_1d(a))


P = [0.1, 0.3, 0.5, 0.7, 0.9]
rows = []
# GEV(xi=0.2,mu=1,sigma=2) == scipy.genextreme(c=-xi)
rows.append(row("gev", stats.genextreme(-0.2, loc=1.0, scale=2.0), [0.0, 2.0, 5.0, 10.0], P))
# GPD(xi=0.3,mu=0,sigma=1.5) == scipy.genpareto(c=xi)
rows.append(row("gpd", stats.genpareto(0.3, loc=0.0, scale=1.5), [0.5, 2.0, 5.0, 10.0], P))
rows.append(row("levy", stats.levy(loc=0.0, scale=1.5), [0.5, 1.5, 4.0, 10.0], P, skip_skew=True, skip_kurt=True))
rows.append(row("betaprime", stats.betaprime(2.5, 5.0), [0.3, 1.0, 2.5, 6.0], P, skip_kurt=True))
rows.append(row("ncx2", stats.ncx2(4.0, 3.0), [1.0, 4.0, 8.0, 15.0], P, skip_entropy=True))
rows.append(row("skewnorm", stats.skewnorm(4.0, loc=1.0, scale=2.0), [0.0, 2.0, 3.0, 5.0], P, skip_entropy=True))
rows.append(row("nct", stats.nct(6.0, 2.0), [-1.0, 1.0, 2.3, 5.0], P, skip_skew=True, skip_kurt=True, skip_entropy=True))
rows.append(row("ncf", stats.ncf(5.0, 10.0, 3.0), [0.5, 1.5, 3.0, 6.0], P, skip_skew=True, skip_kurt=True, skip_entropy=True))

print("// GENERATED by gen_heavy_refs.py — scipy.stats references for v12-j (plain C arrays).")
print("#pragma once")
print("#include <cmath>")
for r in rows:
    n = r["name"]
    print(f'inline const double ref_{n}_x[] = {{{fmt(r["x"])}}};')
    print(f'inline const double ref_{n}_pdf[] = {{{fmt(r["pdf"])}}};')
    print(f'inline const double ref_{n}_logpdf[] = {{{fmt(r["logpdf"])}}};')
    print(f'inline const double ref_{n}_cdf[] = {{{fmt(r["cdf"])}}};')
    print(f'inline const double ref_{n}_sf[] = {{{fmt(r["sf"])}}};')
    print(f'inline const double ref_{n}_p[] = {{{fmt(r["p"])}}};')
    print(f'inline const double ref_{n}_ppf[] = {{{fmt(r["ppf"])}}};')
    print(f'inline const double ref_{n}_mvsk[] = {{{fmt(r["mvsk"])}}};')
    print(f'inline const double ref_{n}_entropy = {fmt([r["entropy"]])};')
