#!/usr/bin/env python3
"""v12-k multivariate reference values from scipy.stats (+ the analytic LKJ p=2 marginal — no scipy LKJ).
Emits plain-C arrays (NO std containers) into multivariate_refs.inc. Params are emitted too so the test builds the
exact same distributions and gates pdf/logpdf <1e-9 + moments."""
import sys
import numpy as np
from scipy import stats, special


def arr(name, vals):
    flat = np.asarray(vals, dtype=float).ravel()
    print(f"inline const double {name}[] = {{{', '.join(repr(float(v)) for v in flat)}}};")


def scal(name, v):
    print(f"inline constexpr double {name} = {repr(float(v))};")


print("// GENERATED by gen_multivariate_refs.py — v12-k multivariate refs (scipy.stats + analytic LKJ p=2).")
print("#pragma once")

# ---- MultivariateNormal, k=3, non-diagonal cov (diagonal would hide whitening bugs) ----
mean3 = [1.0, -2.0, 0.5]
cov3 = [[2.0, 0.5, 0.3], [0.5, 1.5, -0.2], [0.3, -0.2, 1.0]]
mvn = stats.multivariate_normal(mean3, cov3)
xs_mvn = [[1.0, -1.0, 0.0], [0.5, -2.0, 1.0], [2.0, -3.0, -0.5], [1.0, -2.0, 0.5]]
arr("mvn_mean", mean3)
arr("mvn_cov", cov3)
arr("mvn_x", xs_mvn)
arr("mvn_logpdf", [mvn.logpdf(x) for x in xs_mvn])
arr("mvn_pdf", [mvn.pdf(x) for x in xs_mvn])
scal("mvn_entropy", mvn.entropy())

# ---- MultivariateT, k=2, scipy takes `shape` (NOT covariance) ----
loc2 = [0.5, -0.5]
shape2 = [[2.0, 0.4], [0.4, 1.0]]
dfm = 5.0
mvt = stats.multivariate_t(loc2, shape2, df=dfm)
xs_mvt = [[0.0, 0.0], [1.0, -1.0], [2.0, 1.0], [0.5, -0.5]]
arr("mvt_loc", loc2)
arr("mvt_shape", shape2)
scal("mvt_df", dfm)
arr("mvt_x", xs_mvt)
arr("mvt_logpdf", [mvt.logpdf(x) for x in xs_mvt])
arr("mvt_pdf", [mvt.pdf(x) for x in xs_mvt])

# ---- Dirichlet, k=3 ----
alpha = [2.0, 3.0, 4.0]
dd = stats.dirichlet(alpha)
xs_dir = [[0.2, 0.3, 0.5], [0.1, 0.6, 0.3], [1.0 / 3, 1.0 / 3, 1.0 / 3]]
arr("dir_alpha", alpha)
arr("dir_x", xs_dir)
arr("dir_logpdf", [dd.logpdf(np.array(x)) for x in xs_dir])
arr("dir_mean", dd.mean())

# ---- Wishart, k=2 ----
dfw = 6.0
Vw = [[2.0, 0.3], [0.3, 1.0]]
wis = stats.wishart(df=dfw, scale=Vw)
Xs = [[[3.0, 0.5], [0.5, 2.0]], [[2.0, 0.0], [0.0, 2.0]], [[1.5, -0.3], [-0.3, 1.2]]]
scal("wis_df", dfw)
arr("wis_scale", Vw)
arr("wis_X", Xs)
arr("wis_logpdf", [wis.logpdf(np.array(X)) for X in Xs])

# ---- InverseWishart, k=2 (the df/scale convention trap — verified numerically vs scipy) ----
iw = stats.invwishart(df=dfw, scale=Vw)
arr("iw_logpdf", [iw.logpdf(np.array(X)) for X in Xs])

# ---- LKJ, k=2: analytic marginal r ~ ((1−r²)^(η−1)) / Z, Z = √π Γ(η)/Γ(η+½) ----
eta = 2.5
logZ = 0.5 * np.log(np.pi) + special.gammaln(eta) - special.gammaln(eta + 0.5)
rs = [0.0, 0.3, -0.5, 0.8]
scal("lkj_eta", eta)
scal("lkj_logc", logZ)  # the LKJ normalising constant log Z for k=2 (== my m_log_c)
arr("lkj_r", rs)
arr("lkj_logpdf", [(eta - 1) * np.log(1 - r * r) - logZ for r in rs])

# ---- Multinomial, k=3 ----
nm = 20
pm = [0.2, 0.3, 0.5]
mn = stats.multinomial(nm, pm)
cnts = [[4, 6, 10], [10, 5, 5], [0, 0, 20], [7, 7, 6]]
scal("mn_n", float(nm))
arr("mn_p", pm)
arr("mn_x", cnts)
arr("mn_logpmf", [mn.logpmf(np.array(c)) for c in cnts])

sys.exit(0)
