#!/usr/bin/env python3
"""v12-h continuous-distribution references vs scipy.stats — emits plain C arrays (no std containers).
Each distribution: x eval points + pdf/logpdf/cdf/sf, p points + ppf, [mean,var,skew,exkurt], entropy.
NaN in a moment/entropy slot ⇒ the test SKIPS that gate (undefined moment, or no simple closed form here)."""
import numpy as np
from scipy import stats

NAN = float("nan")


def row(name, dist, xs, ps, skip_var=False, skip_skew=False, skip_kurt=False, skip_entropy=False):
    xs = np.asarray(xs, float)
    ps = np.asarray(ps, float)
    m, v, s, k = dist.stats(moments="mvsk")
    mvsk = [float(m), NAN if skip_var else float(v), NAN if skip_skew else float(s), NAN if skip_kurt else float(k)]
    ent = NAN if skip_entropy else float(dist.entropy())
    return {
        "name": name,
        "x": xs, "pdf": dist.pdf(xs), "logpdf": dist.logpdf(xs), "cdf": dist.cdf(xs), "sf": dist.sf(xs),
        "p": ps, "ppf": dist.ppf(ps), "mvsk": mvsk, "entropy": ent,
    }


def fmt(a):
    return ", ".join("HUGE_VAL" if np.isinf(x) and x > 0 else ("-HUGE_VAL" if np.isinf(x) else
                     ("NAN" if np.isnan(x) else f"{x:.17g}")) for x in np.atleast_1d(a))


P = [0.05, 0.25, 0.5, 0.75, 0.95]
rows = []
rows.append(row("normal", stats.norm(0.5, 2.0), [-1.0, 0.5, 1.5, 3.0], P))
rows.append(row("lognormal", stats.lognorm(s=0.7, scale=np.exp(0.2)), [0.3, 0.8, 1.5, 3.0], P))
rows.append(row("exponential", stats.expon(scale=2.0), [0.2, 1.0, 2.0, 4.0], P))
rows.append(row("gamma", stats.gamma(2.5, scale=1.5), [0.5, 2.0, 4.0, 7.0], P))
rows.append(row("beta", stats.beta(2.0, 5.0), [0.1, 0.3, 0.5, 0.7], P))
rows.append(row("chisquared", stats.chi2(4.0), [1.0, 3.0, 5.0, 8.0], P))
rows.append(row("studentt", stats.t(5.0), [-2.0, -0.5, 0.5, 2.0], P))
rows.append(row("fisherf", stats.f(5.0, 10.0), [0.3, 1.0, 2.0, 4.0], P))
rows.append(row("cauchy", stats.cauchy(0.0, 1.0), [-2.0, -0.5, 0.5, 2.0], P))
rows.append(row("laplace", stats.laplace(0.0, 1.5), [-2.0, -0.5, 0.5, 2.0], P))
rows.append(row("logistic", stats.logistic(0.0, 1.2), [-2.0, -0.5, 0.5, 2.0], P))
rows.append(row("weibull", stats.weibull_min(1.8, scale=2.0), [0.5, 1.5, 3.0, 5.0], P))
rows.append(row("gumbel", stats.gumbel_r(0.5, 1.3), [-1.0, 0.5, 2.0, 4.0], P))
rows.append(row("pareto", stats.pareto(5.0, scale=1.5), [1.6, 2.5, 4.0, 7.0], P))
rows.append(row("rayleigh", stats.rayleigh(scale=1.4), [0.5, 1.4, 2.5, 4.0], P))
rows.append(row("maxwell", stats.maxwell(scale=1.2), [0.5, 1.5, 2.5, 4.0], P))
rows.append(row("uniform", stats.uniform(-1.0, 4.0), [-0.5, 0.5, 1.5, 2.5], P))
rows.append(row("halfnormal", stats.halfnorm(scale=1.5), [0.2, 1.0, 2.0, 3.5], P))
rows.append(row("halfcauchy", stats.halfcauchy(scale=1.3), [0.3, 1.0, 2.5, 5.0], P))
rows.append(row("triangular", stats.triang(0.35, loc=0.0, scale=2.0), [0.3, 0.7, 1.2, 1.8], P))
rows.append(row("invgamma", stats.invgamma(5.0, scale=2.0), [0.3, 0.7, 1.5, 3.0], P))
rows.append(row("nakagami", stats.nakagami(1.5, scale=1.2), [0.4, 1.0, 1.8, 3.0], P))
# Wald(mu=1,lam=2) = invgauss(0.5, scale=2); entropy has no simple closed form here ⇒ skip.
rows.append(row("wald", stats.invgauss(0.5, scale=2.0), [0.3, 0.8, 1.5, 3.0], P, skip_entropy=True))
# von Mises is CIRCULAR: var/skew/kurt use the circular convention (mine) vs scipy's linear-over-period ⇒ skip those.
rows.append(row("vonmises", stats.vonmises(2.0, loc=0.3), [-1.0, 0.3, 1.0, 2.5], P,
               skip_var=True, skip_skew=True, skip_kurt=True))
rows.append(row("rice", stats.rice(1.0, scale=1.0), [0.3, 1.0, 2.0, 3.5], P,
               skip_skew=True, skip_kurt=True, skip_entropy=True))

print("// GENERATED by gen_continuous_refs.py — scipy.stats references for v12-h (plain C arrays).")
print("#pragma once")
print("#include <cmath>  // HUGE_VAL, NAN")
for r in rows:
    n = r["name"]
    print(f'inline const double ref_{n}_x[] = {{{fmt(r["x"])}}};')
    print(f'inline const double ref_{n}_pdf[] = {{{fmt(r["pdf"])}}};')
    print(f'inline const double ref_{n}_logpdf[] = {{{fmt(r["logpdf"])}}};')
    print(f'inline const double ref_{n}_cdf[] = {{{fmt(r["cdf"])}}};')
    print(f'inline const double ref_{n}_sf[] = {{{fmt(r["sf"])}}};')
    print(f'inline const double ref_{n}_p[] = {{{fmt(r["p"])}}};')
    print(f'inline const double ref_{n}_ppf[] = {{{fmt(r["ppf"])}}};')
    print(f'inline const double ref_{n}_mvsk[] = {{{fmt(r["mvsk"])}}};')
    print(f'inline const double ref_{n}_entropy = {fmt([r["entropy"]])};')
