#!/usr/bin/env python3
"""RNG KAT references for v12-e (plain u64 literals, no STL).

PCG64-DXSM + SFC64 gated vs NumPy random_raw at a set internal state (NumPy = the independent reference);
xoshiro256**/++ vs a faithful Python transcription; SplitMix64/Threefry/MT19937 anchored to published KATs in the
test directly. Run: python3 tests/hesap-stats/gen_rng_refs.py > tests/hesap-stats/rng_refs.inc
"""
import numpy as np

M64 = (1 << 64) - 1


def emit(name, arr):
    vals = ", ".join(f"{int(x) & M64}ULL" for x in arr)
    print(f"inline const crd::u64 ref_{name}[] = {{{vals}}};")


def emit1(name, v):
    print(f"inline const crd::u64 ref_{name} = {int(v) & M64}ULL;")


# Faithful SplitMix64 / xoshiro256** / xoshiro256++ (transcription of Vigna's reference).
def splitmix(seed):
    s = seed & M64
    while True:
        s = (s + 0x9E3779B97F4A7C15) & M64
        z = s
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & M64
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & M64
        yield z ^ (z >> 31)


def rotl(x, k):
    return ((x << k) | (x >> (64 - k))) & M64


def xoshiro(seed, plus_plus):
    sm = splitmix(seed)
    s = [next(sm) for _ in range(4)]
    while True:
        if plus_plus:
            res = (rotl((s[0] + s[3]) & M64, 23) + s[0]) & M64
        else:
            res = (rotl((s[1] * 5) & M64, 7) * 9) & M64
        t = (s[1] << 17) & M64
        s[2] ^= s[0]; s[3] ^= s[1]; s[1] ^= s[2]; s[0] ^= s[3]; s[2] ^= t; s[3] = rotl(s[3], 45)
        yield res


def main():
    print("// GENERATED by gen_rng_refs.py — RNG KAT references (v12-e). u64 literals.")
    print("#pragma once")
    print("#include <crd/core/types.hpp>")

    # --- PCG64-DXSM vs NumPy random_raw at a known state ---
    shi, slo = 0x0123456789ABCDEF, 0xFEDCBA9876543210
    ihi, ilo = 0x1357924680ABCDEF, 0x1122334455667781  # inc odd
    bg = np.random.PCG64DXSM()
    st = bg.state
    st["state"]["state"] = (shi << 64) | slo
    st["state"]["inc"] = (ihi << 64) | ilo
    bg.state = st
    emit1("pcg_shi", shi); emit1("pcg_slo", slo); emit1("pcg_ihi", ihi); emit1("pcg_ilo", ilo)
    emit("pcg_out", bg.random_raw(8))

    # --- SFC64 vs NumPy random_raw at a known state {a,b,c,counter} ---
    a, b, c, w = 0x1111111111111111, 0x2222222222222222, 0x3333333333333333, 0x44
    bg2 = np.random.SFC64()
    st2 = bg2.state
    st2["state"]["state"] = np.array([a, b, c, w], dtype=np.uint64)
    bg2.state = st2
    emit1("sfc_a", a); emit1("sfc_b", b); emit1("sfc_c", c); emit1("sfc_w", w)
    emit("sfc_out", bg2.random_raw(8))

    # --- xoshiro256** / ++ vs the faithful reference ---
    seed = 0xDEADBEEFCAFEBABE
    emit1("xo_seed", seed)
    g = xoshiro(seed, False)
    emit("xoss_out", [next(g) for _ in range(8)])
    g2 = xoshiro(seed, True)
    emit("xopp_out", [next(g2) for _ in range(8)])

    # --- MT19937 via NumPy legacy RandomState (array seed ⇒ the canonical init_by_array) ---
    rs = np.random.RandomState([0x123, 0x234, 0x345, 0x456])
    raw = np.asarray(rs._bit_generator.random_raw(10)).astype(np.uint64)
    emit("mt_out", raw)


if __name__ == "__main__":
    main()
