import numpy as np
from scipy.special import roots_jacobi, eval_legendre
from scipy.integrate import simpson, trapezoid, newton_cotes
def lobatto(n):
    xi,_=roots_jacobi(n-2,1,1); x=np.concatenate(([-1.0],xi,[1.0]))
    return x, 2.0/(n*(n-1)*eval_legendre(n-1,x)**2)
def radau(n):
    xi,_=roots_jacobi(n-1,0,1); x=np.concatenate(([-1.0],xi))
    w=np.empty(n); w[0]=2.0/n**2; w[1:]=(1.0-xi)/(n**2*eval_legendre(n-1,xi)**2)
    return x,w
def carr(name,a):
    print("constexpr double %s[] = {%s};"%(name,", ".join("%.17g"%v for v in np.asarray(a).ravel())))
print("// generated by gen_integrate_refs.py — scipy reference values")
xl,wl=lobatto(5); xr,wr=radau(5)
carr("ref_lob5_x",xl); carr("ref_lob5_w",wl); carr("ref_rad5_x",xr); carr("ref_rad5_w",wr)
for n in (2,3,4,6,8):
    w,_=newton_cotes(n,1); carr("ref_nc%d"%n,w)
# composite-rule samples: f(x)=exp(x)*sin(2x) on uniform grids
f=lambda x: np.exp(x)*np.sin(2*x)
xo=np.linspace(0,2,9); yo=f(xo)            # 9 pts (odd N, even intervals)
xe=np.linspace(0,2,8); ye=f(xe)            # 8 pts (even N, odd intervals)
carr("ref_samp_odd",yo); carr("ref_samp_even",ye)
print("constexpr double ref_dx_odd = %.17g;"%(xo[1]-xo[0]))
print("constexpr double ref_dx_even = %.17g;"%(xe[1]-xe[0]))
print("constexpr double ref_simpson_odd = %.17g;"%simpson(yo,dx=xo[1]-xo[0]))
print("constexpr double ref_simpson_even = %.17g;"%simpson(ye,dx=xe[1]-xe[0]))
print("constexpr double ref_trap_odd = %.17g;"%trapezoid(yo,dx=xo[1]-xo[0]))
# non-uniform trapezoid
xn=np.array([0.0,0.3,0.5,1.1,1.4,2.0]); yn=f(xn)
carr("ref_nu_x",xn); carr("ref_nu_y",yn)
print("constexpr double ref_trap_nu = %.17g;"%trapezoid(yn,xn))
