#!/usr/bin/env python3
"""scipy Gauss-quadrature node/weight references for v12-c Golub-Welsch (plain C arrays, no STL). n = 8.

Run: python3 tests/hesap-quadrature/gen_gauss_refs.py > tests/hesap-quadrature/gauss_refs.inc
"""
import numpy as np
from scipy import special as sp

N = 8


def emit(name, arr):
    vals = ", ".join(f"{float(x):.17g}" for x in np.asarray(arr, dtype=float).ravel())
    print(f"inline const double ref_{name}[] = {{{vals}}};")


def main():
    print("// GENERATED by gen_gauss_refs.py — scipy Gauss quadrature nodes/weights (v12-c, n=8). Plain C arrays.")
    print("#pragma once")
    for tag, (x, w) in {
        "gl": sp.roots_legendre(N),
        "gh": sp.roots_hermite(N),
        "gla": sp.roots_laguerre(N),
        "ggla": sp.roots_genlaguerre(N, 1.5),
        "gj": sp.roots_jacobi(N, 1.5, 0.5),
        "ggeg": sp.roots_gegenbauer(N, 0.75),
        "gct": sp.roots_chebyt(N),
    }.items():
        emit(tag + "_x", x)
        emit(tag + "_w", w)


if __name__ == "__main__":
    main()
