#!/usr/bin/env python3
"""scipy.special reference vectors for v12-c orthogonal polynomials (plain C arrays, no STL).

Run: python3 tests/hesap-special/gen_orthopoly_refs.py > tests/hesap-special/orthopoly_refs.inc
"""
import numpy as np
from scipy import special as sp


def emit(name, arr):
    vals = ", ".join(f"{float(x):.17g}" for x in np.asarray(arr, dtype=float).ravel())
    print(f"inline const double ref_{name}[] = {{{vals}}};")


def grid(ns, xs):
    N, X = [], []
    for n in ns:
        for x in xs:
            N.append(n)
            X.append(x)
    return N, X


def main():
    print("// GENERATED by gen_orthopoly_refs.py — scipy.special orthogonal-polynomial refs (v12-c). Plain C arrays.")
    print("#pragma once")
    ns = [0, 1, 2, 3, 5, 8]
    xs = [-0.8, -0.3, 0.0, 0.4, 0.7, 0.95]
    N, X = grid(ns, xs)
    emit("op_n", N); emit("op_x", X)
    emit("leg_y", [sp.eval_legendre(n, x) for n, x in zip(N, X)])
    emit("cht_y", [sp.eval_chebyt(n, x) for n, x in zip(N, X)])
    emit("chu_y", [sp.eval_chebyu(n, x) for n, x in zip(N, X)])
    th = np.arccos(np.asarray(X))
    emit("chv_y", [np.cos((n + 0.5) * t) / np.cos(t / 2) for n, t in zip(N, th)])
    emit("chw_y", [np.sin((n + 0.5) * t) / np.sin(t / 2) for n, t in zip(N, th)])
    emit("geg_y", [sp.eval_gegenbauer(n, 0.75, x) for n, x in zip(N, X)])  # alpha = 0.75
    emit("jac_y", [sp.eval_jacobi(n, 1.5, 0.5, x) for n, x in zip(N, X)])  # alpha=1.5, beta=0.5

    xh = [-2.0, -0.5, 0.0, 1.0, 2.5]
    Nh, Xh = grid(ns, xh)
    emit("her_n", Nh); emit("her_x", Xh)
    emit("her_y", [sp.eval_hermite(n, x) for n, x in zip(Nh, Xh)])
    emit("hee_y", [sp.eval_hermitenorm(n, x) for n, x in zip(Nh, Xh)])

    xl = [0.1, 0.5, 1.0, 3.0, 7.0]
    Nl, Xl = grid(ns, xl)
    emit("lag_n", Nl); emit("lag_x", Xl)
    emit("lag_y", [sp.eval_laguerre(n, x) for n, x in zip(Nl, Xl)])
    emit("glag_y", [sp.eval_genlaguerre(n, 1.5, x) for n, x in zip(Nl, Xl)])  # alpha = 1.5

    amn = [(0, 2), (1, 2), (2, 3), (1, 4), (3, 5)]
    ax = [-0.5, 0.3, 0.8]
    Am, An, Ax = [], [], []
    for (m, nn) in amn:
        for x in ax:
            Am.append(m); An.append(nn); Ax.append(x)
    emit("alp_m", Am); emit("alp_n", An); emit("alp_x", Ax)
    emit("alp_y", [sp.lpmv(m, n, x) for m, n, x in zip(Am, An, Ax)])


if __name__ == "__main__":
    main()
