#!/usr/bin/env python3
"""scipy.special reference vectors for the v12-a special-function gates (batch-once harness; plain C arrays, no STL).

Run: python3 tests/hesap-special/gen_special_refs.py > tests/hesap-special/special_refs.inc
"""
import numpy as np
from scipy import special as sp


def emit(name, arr):
    vals = ", ".join(f"{float(x):.17g}" for x in np.asarray(arr, dtype=float).ravel())
    print(f"inline const double ref_{name}[] = {{{vals}}};")


def main():
    print("// GENERATED by gen_special_refs.py — scipy.special reference vectors (v12-a). Plain C arrays (no STL).")
    print("#pragma once")

    # ---- gamma family ----
    gx = [0.1, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 5.0, 10.0, 20.0, 50.0, 0.01, -0.5, -1.5, -2.5, -10.3, 100.0, 170.0]
    emit("gamma_x", gx); emit("lgamma_y", sp.gammaln(gx)); emit("tgamma_y", sp.gamma(gx))
    dx = [0.1, 0.5, 1.0, 1.5, 2.0, 5.0, 10.0, 50.0, -0.5, -1.5, -10.3, 0.01, 100.0]
    emit("digamma_x", dx); emit("digamma_y", sp.digamma(dx))
    tx = [0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 50.0, -0.5, -2.5, 0.01]
    emit("trigamma_x", tx); emit("trigamma_y", sp.polygamma(1, tx))
    px = [2.0, 3.0, 5.0]  # polygamma orders
    pgx = [1.5, 3.0, 7.5]
    emit("polygamma_n", [2, 2, 3, 3, 4])
    emit("polygamma_x", [1.5, 5.0, 2.0, 8.0, 3.0])
    emit("polygamma_y", [sp.polygamma(2, 1.5), sp.polygamma(2, 5.0), sp.polygamma(3, 2.0),
                         sp.polygamma(3, 8.0), sp.polygamma(4, 3.0)])
    ba = [1.0, 2.0, 0.5, 5.0, 10.0, 0.1, 50.0]
    bb = [1.0, 3.0, 0.5, 7.0, 20.0, 0.2, 3.0]
    emit("beta_a", ba); emit("beta_b", bb)
    emit("beta_y", [sp.beta(a, b) for a, b in zip(ba, bb)])
    emit("lbeta_y", [sp.betaln(a, b) for a, b in zip(ba, bb)])

    # ---- incomplete gamma P/Q + inverse ----
    ga = [0.5, 0.5, 2.0, 2.0, 5.0, 5.0, 10.0, 10.0, 1.0, 1.0, 100.0, 100.0]
    gxx = [0.1, 1.0, 1.0, 5.0, 3.0, 10.0, 8.0, 20.0, 0.5, 3.0, 90.0, 120.0]
    emit("gammainc_a", ga); emit("gammainc_x", gxx)
    emit("gammainc_p", [sp.gammainc(a, x) for a, x in zip(ga, gxx)])
    emit("gammainc_q", [sp.gammaincc(a, x) for a, x in zip(ga, gxx)])
    ia = [0.5, 1.0, 2.0, 5.0, 10.0, 100.0]
    ip = [0.01, 0.1, 0.5, 0.9, 0.99]
    aa, pp, yy = [], [], []
    for a in ia:
        for p in ip:
            aa.append(a); pp.append(p); yy.append(sp.gammaincinv(a, p))
    emit("gammaincinv_a", aa); emit("gammaincinv_p", pp); emit("gammaincinv_y", yy)

    # ---- incomplete beta + inverse ----
    Ba = [0.5, 2.0, 2.0, 5.0, 10.0, 1.0, 3.0, 0.5]
    Bb = [0.5, 3.0, 2.0, 2.0, 5.0, 1.0, 7.0, 2.0]
    Bx = [0.3, 0.5, 0.5, 0.7, 0.4, 0.5, 0.2, 0.9]
    emit("betainc_a", Ba); emit("betainc_b", Bb); emit("betainc_x", Bx)
    emit("betainc_y", [sp.betainc(a, b, x) for a, b, x in zip(Ba, Bb, Bx)])
    iba, ibb, ibp, iby = [], [], [], []
    for (a, b) in [(0.5, 0.5), (2.0, 3.0), (5.0, 2.0), (10.0, 10.0), (1.0, 3.0), (0.5, 2.0)]:
        for p in [0.05, 0.25, 0.5, 0.75, 0.95]:
            iba.append(a); ibb.append(b); ibp.append(p); iby.append(sp.betaincinv(a, b, p))
    emit("betaincinv_a", iba); emit("betaincinv_b", ibb); emit("betaincinv_p", ibp); emit("betaincinv_y", iby)

    # ---- erf family ----
    ex = [-3.0, -2.3, -1.0, -0.5, 0.0, 0.1, 0.5, 1.0, 2.0, 3.0, 5.0]
    emit("erf_x", ex); emit("erf_y", sp.erf(ex)); emit("erfc_y", sp.erfc(ex))
    cx = [0.0, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 50.0, -1.0, 100.0]
    emit("erfcx_x", cx); emit("erfcx_y", sp.erfcx(cx))
    iy = [-0.99, -0.9, -0.5, -0.1, 0.0, 0.1, 0.5, 0.9, 0.99, 0.999]
    emit("erfinv_y", iy); emit("erfinv_x", sp.erfinv(iy))
    icy = [0.001, 0.01, 0.1, 0.5, 1.0, 1.5, 1.9, 1.99]
    emit("erfcinv_y", icy); emit("erfcinv_x", sp.erfcinv(icy))
    wx = [-3.0, -1.0, -0.21, -0.19, 0.1, 0.19, 0.21, 0.5, 1.0, 2.0, 3.0, 5.0]
    emit("dawson_x", wx); emit("dawson_y", sp.dawsn(wx))


if __name__ == "__main__":
    main()
