#!/usr/bin/env python3
"""Iteration-free Lambert W0(x) over [0.3,20] via a 3-piece minimax rational (generate-don't-transcribe).
Covers the common/bench range with no Halley/Fritsch iteration; outside [0.3,20] the existing iteration handles the
branch point and the large-x tail. Gate = 1e-12 rel + 1e-13 abs vs scipy.special.lambertw(x,0)."""
import sys
import numpy as np
from numpy.polynomial import chebyshev as Ch
from scipy import special


def cheb_nodes(a, b, n):
    k = np.arange(n)
    return 0.5 * (a + b) + 0.5 * (b - a) * np.cos((2 * k + 1) * np.pi / (2 * n))


def rat_fit(x, f, scale, a, b, m, n, npass=60):
    t = (2 * x - (a + b)) / (b - a)
    ac = np.arccos(np.clip(t, -1, 1))
    TP = np.cos(np.outer(ac, np.arange(m + 1)))
    TQ = np.cos(np.outer(ac, np.arange(1, n + 1)))
    w = 1.0 / scale
    best = None
    for _ in range(npass):
        A = np.hstack([TP * w[:, None], -(f * w)[:, None] * TQ])
        sol, *_ = np.linalg.lstsq(A, f * w, rcond=None)
        p, qj = sol[:m + 1], sol[m + 1:]
        Qv = 1.0 + TQ @ qj
        r = np.abs((TP @ p) / Qv - f) / scale
        if best is None or r.max() < best[1]:
            best = ((p, np.concatenate([[1.0], qj])), r.max())
        w = (1.0 / scale) / np.abs(Qv) * np.clip((r / max(r.max(), 1e-300)) ** 0.5, 0.25, 1.0)
    (p, q), e = best
    return Ch.cheb2poly(p), Ch.cheb2poly(q), e


def arr(name, c):
    print(f"inline constexpr double k{name}[] = {{{', '.join(f'{v:.17e}' for v in c)}}};")


def W0(x):
    return special.lambertw(x, 0).real


print("// GENERATED by gen_lambertw_poly.py — iteration-free Lambert W0 minimax rationals (v12-d perf).")
print("#pragma once")
print("namespace crd::hesap::special::detail {")
errs = []
for tag, a, b, m, n in [("W0R1", 0.3, 1.5, 7, 6), ("W0R2", 1.5, 5.0, 6, 5), ("W0R3", 5.0, 20.0, 7, 6)]:
    x = cheb_nodes(a, b, 6000)
    f = W0(x)
    p, q, e = rat_fit(x, f, np.abs(f), a, b, m, n)
    arr(tag + "P", p)
    arr(tag + "Q", q)
    errs.append((tag, e))
print("} // namespace")
for name, e in errs:
    print(f"// {name}: {e:.2e}", file=sys.stderr)
sys.exit(0 if max(e for _, e in errs) < 1e-12 else 1)
