#!/usr/bin/env python3
"""Iteration-free Riemann zeta(s) for s in [1.8, 22] via minimax rationals (generate-don't-transcribe).
Replaces 8+ std::pow calls (Euler-Maclaurin) with two Horner-rationals. Gate = 1e-13 rel + 1e-14 abs vs scipy.
Outside [1.8,22] (and hurwitz_zeta general a) keep the Euler-Maclaurin path."""
import sys
import numpy as np
from numpy.polynomial import chebyshev as Ch
from scipy import special


def cheb_nodes(a, b, n):
    k = np.arange(n)
    return 0.5 * (a + b) + 0.5 * (b - a) * np.cos((2 * k + 1) * np.pi / (2 * n))


def rat_fit(x, f, scale, a, b, m, n, npass=60):
    t = (2 * x - (a + b)) / (b - a)
    ac = np.arccos(np.clip(t, -1, 1))
    TP = np.cos(np.outer(ac, np.arange(m + 1)))
    TQ = np.cos(np.outer(ac, np.arange(1, n + 1)))
    w = 1.0 / scale
    best = None
    for _ in range(npass):
        A = np.hstack([TP * w[:, None], -(f * w)[:, None] * TQ])
        sol, *_ = np.linalg.lstsq(A, f * w, rcond=None)
        p, qj = sol[:m + 1], sol[m + 1:]
        Qv = 1.0 + TQ @ qj
        r = np.abs((TP @ p) / Qv - f) / scale
        if best is None or r.max() < best[1]:
            best = ((p, np.concatenate([[1.0], qj])), r.max())
        w = (1.0 / scale) / np.abs(Qv) * np.clip((r / max(r.max(), 1e-300)) ** 0.5, 0.25, 1.0)
    (p, q), e = best
    return Ch.cheb2poly(p), Ch.cheb2poly(q), e


def arr(name, c):
    print(f"inline constexpr double k{name}[] = {{{', '.join(f'{v:.17e}' for v in c)}}};")


print("// GENERATED by gen_zeta_poly.py — iteration-free Riemann zeta minimax rationals (v12-d perf).")
print("#pragma once")
print("namespace crd::hesap::special::detail {")
errs = []
for tag, a, b, m, n in [("ZetaR1", 1.8, 8.0, 10, 10), ("ZetaR2", 8.0, 16.0, 10, 8)]:
    x = cheb_nodes(a, b, 6000)
    z = special.zeta(x)
    p, q, e = rat_fit(x, z, np.abs(z), a, b, m, n)
    arr(tag + "P", p)
    arr(tag + "Q", q)
    errs.append((tag, e))
print("} // namespace")
for name, e in errs:
    print(f"// {name}: {e:.2e}", file=sys.stderr)
worst = max(e for _, e in errs)
sys.exit(0 if worst < 1e-13 else 1)
