#!/usr/bin/env python3
"""Iteration-free K(m), E(m) via minimax rationals (generate-don't-transcribe); replaces the ~6-sqrt AGM chain.
Gate = 1e-12 rel + 1e-13 abs vs scipy. K direct-rational over [0,0.9] (the m=1 log-branch caps a wider range);
its tail [0.9,1) uses the Cody form A(m1)+L·B(m1) (L=-ln m1 removes the branch). E is finite at m=1 ⇒ [0,0.94] rational."""
import sys
import numpy as np
from numpy.polynomial import chebyshev as Ch
from scipy import special


def cheb_nodes(a, b, n):
    k = np.arange(n)
    return 0.5 * (a + b) + 0.5 * (b - a) * np.cos((2 * k + 1) * np.pi / (2 * n))


def rat_fit(x, f, scale, a, b, m, n, npass=60):
    t = (2 * x - (a + b)) / (b - a)
    ac = np.arccos(np.clip(t, -1, 1))
    TP = np.cos(np.outer(ac, np.arange(m + 1)))
    TQ = np.cos(np.outer(ac, np.arange(1, n + 1)))
    w = 1.0 / scale
    best = None
    for _ in range(npass):
        A = np.hstack([TP * w[:, None], -(f * w)[:, None] * TQ])
        sol, *_ = np.linalg.lstsq(A, f * w, rcond=None)
        p, qj = sol[:m + 1], sol[m + 1:]
        Qv = 1.0 + TQ @ qj
        r = np.abs((TP @ p) / Qv - f) / scale
        if best is None or r.max() < best[1]:
            best = ((p, np.concatenate([[1.0], qj])), r.max())
        w = (1.0 / scale) / np.abs(Qv) * np.clip((r / max(r.max(), 1e-300)) ** 0.5, 0.25, 1.0)
    (p, q), e = best
    return Ch.cheb2poly(p), Ch.cheb2poly(q), e


def cody_fit(func, a1, b1, deg):
    # F(m) = A(m1) + (-ln m1) B(m1), m1=1-m in [a1,b1]; linear LSQ, relative-weighted. monomial-in-m1.
    u = (np.arange(8000) + 0.5) / 8000.0
    m1 = a1 + (b1 - a1) * u  # uniform grid (Chebyshev clustering near m1→0 wrecks the conditioning)
    f = func(1.0 - m1)
    L = -np.log(m1)
    cols = [m1 ** j for j in range(deg + 1)] + [L * m1 ** j for j in range(deg + 1)]
    M = np.vstack(cols).T
    w = 1.0 / np.abs(f)
    coef, *_ = np.linalg.lstsq(M * w[:, None], f * w, rcond=None)
    A, B = coef[:deg + 1], coef[deg + 1:]
    approx = np.polyval(A[::-1], m1) + L * np.polyval(B[::-1], m1)
    return A, B, (np.abs(approx - f) / np.abs(f)).max()


def arr(name, c):
    print(f"inline constexpr double k{name}[] = {{{', '.join(f'{v:.17e}' for v in c)}}};")


print("// GENERATED by gen_elliptic_poly.py — iteration-free K(m)/E(m) minimax (v12-d perf).")
print("#pragma once")
print("namespace crd::hesap::special::detail {")
errs = []
# K full-range Cody form A(m1)+L·B(m1) over m1 in (1e-9, 1]  (the −ln m1 removes the m=1 branch ⇒ one fast path).
A, B, e = cody_fit(special.ellipk, 1e-9, 1.0, 10)
arr("EllKcodyA", A)
arr("EllKcodyB", B)
errs.append(("K-cody[0,1)", e))
# E full-range Cody form likewise (E finite at m=1 ⇒ B(1)→0, the fit finds it).
A, B, e = cody_fit(special.ellipe, 1e-9, 1.0, 10)
arr("EllEcodyA", A)
arr("EllEcodyB", B)
errs.append(("E-cody[0,1)", e))
print("} // namespace")
for name, e in errs:
    print(f"// {name}: {e:.2e}", file=sys.stderr)
sys.exit(0 if max(e for _, e in errs) < 1e-12 else 1)
