#!/usr/bin/env python3
"""scipy.special reference vectors for the v12-b Bessel/Airy/Kelvin gates (plain C arrays, no STL).

Run: python3 tests/hesap-special/gen_bessel_refs.py > tests/hesap-special/bessel_refs.inc
"""
import numpy as np
from scipy import special as sp


def emit(name, arr):
    vals = ", ".join(f"{float(x):.17g}" for x in np.asarray(arr, dtype=float).ravel())
    print(f"inline const double ref_{name}[] = {{{vals}}};")


def grid(nus, xs):
    NU, X = [], []
    for nu in nus:
        for x in xs:
            NU.append(nu)
            X.append(x)
    return NU, X


def main():
    print("// GENERATED by gen_bessel_refs.py — scipy.special Bessel/Airy/Kelvin refs (v12-b). Plain C arrays (no STL).")
    print("#pragma once")

    nus = [0.0, 1.0, 2.0, 5.0, 0.5, 1.5, 2.5, 1.0 / 3, 2.0 / 3]
    NU, X = grid(nus, [0.5, 1.0, 2.0, 5.0, 10.0, 20.0])
    emit("besj_nu", NU); emit("besj_x", X)
    emit("besj_y", [sp.jv(n, x) for n, x in zip(NU, X)])
    emit("besy_y", [sp.yv(n, x) for n, x in zip(NU, X)])
    emit("besjp_y", [sp.jvp(n, x) for n, x in zip(NU, X)])
    emit("besyp_y", [sp.yvp(n, x) for n, x in zip(NU, X)])

    NUik, Xik = grid(nus, [0.5, 1.0, 2.0, 5.0, 10.0])
    emit("besi_nu", NUik); emit("besi_x", Xik)
    emit("besi_y", [sp.iv(n, x) for n, x in zip(NUik, Xik)])
    emit("besk_y", [sp.kv(n, x) for n, x in zip(NUik, Xik)])
    emit("besip_y", [sp.ivp(n, x) for n, x in zip(NUik, Xik)])
    emit("beskp_y", [sp.kvp(n, x) for n, x in zip(NUik, Xik)])

    nneg = [-0.5, -1.5, -2.5, -1.0 / 3]
    NUn, Xn = grid(nneg, [0.5, 1.0, 2.0, 5.0, 10.0])
    emit("besjn_nu", NUn); emit("besjn_x", Xn)
    emit("besjn_y", [sp.jv(n, x) for n, x in zip(NUn, Xn)])
    emit("besyn_y", [sp.yv(n, x) for n, x in zip(NUn, Xn)])
    emit("besin_y", [sp.iv(n, x) for n, x in zip(NUn, Xn)])

    SN, SX = [], []
    for n in [0, 1, 2, 3, 5]:
        for x in [0.5, 1.0, 2.0, 5.0, 10.0]:
            SN.append(n); SX.append(x)
    emit("sphn", SN); emit("sphx", SX)
    emit("sphj_y", [sp.spherical_jn(n, x) for n, x in zip(SN, SX)])
    emit("sphy_y", [sp.spherical_yn(n, x) for n, x in zip(SN, SX)])

    ax = [-10.0, -5.0, -2.0, -1.0, 0.0, 1.0, 2.0, 5.0, 10.0]
    Ai, Aip, Bi, Bip = sp.airy(ax)
    emit("airy_x", ax); emit("airy_ai", Ai); emit("airy_aip", Aip); emit("airy_bi", Bi); emit("airy_bip", Bip)

    # complex argument
    cnus = [0.0, 1.0, 2.0, 0.5, 1.5, 2.5]
    zpts = [(1.0, 1.0), (3.0, -2.0), (5.0, 4.0), (2.0, 8.0), (0.5, 0.5), (10.0, 3.0), (20.0, -5.0)]
    CNU, ZR, ZI = [], [], []
    for nu in cnus:
        for (a, b) in zpts:
            CNU.append(nu); ZR.append(a); ZI.append(b)
    emit("cbes_nu", CNU); emit("cbes_zr", ZR); emit("cbes_zi", ZI)
    cz = [complex(a, b) for a, b in zip(ZR, ZI)]

    def cemit(name, vals):
        emit(name + "_re", [v.real for v in vals]); emit(name + "_im", [v.imag for v in vals])

    cemit("cbesj", [sp.jv(n, z) for n, z in zip(CNU, cz)])
    cemit("cbesy", [sp.yv(n, z) for n, z in zip(CNU, cz)])
    cemit("cbesi", [sp.iv(n, z) for n, z in zip(CNU, cz)])
    cemit("cbesk", [sp.kv(n, z) for n, z in zip(CNU, cz)])

    kx = [0.5, 1.0, 2.0, 3.0, 5.0, 8.0, 20.0, 30.0]
    emit("kelvin_x", kx)
    emit("kelvin_ber", [sp.ber(x) for x in kx]); emit("kelvin_bei", [sp.bei(x) for x in kx])
    emit("kelvin_ker", [sp.ker(x) for x in kx]); emit("kelvin_kei", [sp.kei(x) for x in kx])


if __name__ == "__main__":
    main()
