#!/usr/bin/env python3
"""scipy.special references for v12-d exponential/trigonometric integrals (plain C arrays, no STL).

Run: python3 tests/hesap-special/gen_expint_refs.py > tests/hesap-special/expint_refs.inc
"""
import numpy as np
from scipy import special as sp
from scipy.stats import ncx2


def emit(name, arr):
    vals = ", ".join(f"{float(x):.17g}" for x in np.asarray(arr, dtype=float).ravel())
    print(f"inline const double ref_{name}[] = {{{vals}}};")


def main():
    print("// GENERATED by gen_expint_refs.py — scipy.special exp/trig-integral refs (v12-d). Plain C arrays.")
    print("#pragma once")

    e1x = [0.01, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 20.0]
    emit("e1_x", e1x); emit("e1_y", sp.exp1(e1x))

    eix = [0.01, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 20.0, -0.5, -1.0, -2.0, -5.0]
    emit("ei_x", eix); emit("ei_y", sp.expi(eix))

    enn = [2, 3, 5]
    enx = [0.5, 1.0, 2.0, 5.0]
    EN, EX = [], []
    for n in enn:
        for x in enx:
            EN.append(n); EX.append(x)
    emit("en_n", EN); emit("en_x", EX)
    emit("en_y", [sp.expn(n, x) for n, x in zip(EN, EX)])

    six = [0.01, 0.1, 0.5, 1.0, 2.0, 3.0, 5.0, 10.0, 20.0, -1.0, -5.0]
    si, _ = sp.sici(six)
    emit("si_x", six); emit("si_y", si)
    cix = [0.01, 0.1, 0.5, 1.0, 2.0, 3.0, 5.0, 10.0, 20.0]
    _, ci = sp.sici(cix)
    emit("ci_x", cix); emit("ci_y", ci)

    # ---- Carlson symmetric integrals ----
    rf = [(1.0, 2.0, 3.0), (0.5, 1.0, 2.0), (2.0, 3.0, 4.0), (0.0, 1.0, 1.0), (1.0, 1.0, 1.0)]
    emit("rf_x", [t[0] for t in rf]); emit("rf_y", [t[1] for t in rf]); emit("rf_z", [t[2] for t in rf])
    emit("rf_v", [sp.elliprf(a, b, c) for a, b, c in rf])
    emit("rd_v", [sp.elliprd(a, b, c) for a, b, c in rf])
    rc = [(1.0, 2.0), (0.5, 1.0), (2.0, 0.5), (1.0, 1.0)]
    emit("rc_x", [t[0] for t in rc]); emit("rc_y", [t[1] for t in rc])
    emit("rc_v", [sp.elliprc(a, b) for a, b in rc])
    rj = [(1.0, 2.0, 3.0, 4.0), (0.5, 1.0, 2.0, 1.5), (2.0, 3.0, 4.0, 5.0)]
    emit("rj_x", [t[0] for t in rj]); emit("rj_y", [t[1] for t in rj])
    emit("rj_z", [t[2] for t in rj]); emit("rj_p", [t[3] for t in rj])
    emit("rj_v", [sp.elliprj(a, b, c, d) for a, b, c, d in rj])

    # ---- complete + incomplete K/E (parameter m=k²) ----
    em = [0.0, 0.1, 0.3, 0.5, 0.7, 0.9, -0.5, -2.0]
    emit("em_m", em); emit("ek_v", sp.ellipk(em)); emit("ee_v", sp.ellipe(em))
    fphi = [(0.3, 0.5), (1.0, 0.3), (1.2, 0.9), (0.7, 0.0), (1.5, 0.6), (0.5, -0.5)]
    emit("fi_phi", [t[0] for t in fphi]); emit("fi_m", [t[1] for t in fphi])
    emit("fi_v", [sp.ellipkinc(p, m) for p, m in fphi])
    emit("ei_v", [sp.ellipeinc(p, m) for p, m in fphi])

    # ---- Jacobi elliptic functions sn/cn/dn ----
    ej = [(0.5, 0.3), (1.0, 0.5), (2.0, 0.8), (1.5, 0.1), (0.7, 0.9), (3.0, 0.5), (1.0, 0.0)]
    eu = [t[0] for t in ej]
    em_ = [t[1] for t in ej]
    sn_, cn_, dn_, _ = sp.ellipj(eu, em_)
    emit("ej_u", eu); emit("ej_m", em_); emit("ej_sn", sn_); emit("ej_cn", cn_); emit("ej_dn", dn_)

    # ---- Fresnel S, C ----
    fx = [0.1, 0.5, 1.0, 1.5, 2.0, 3.0, 5.0, -1.5, -0.5]
    s_, c_ = sp.fresnel(fx)
    emit("fr_x", fx); emit("frs_v", s_); emit("frc_v", c_)

    # ---- Lambert W (real branches) ----
    w0 = [-0.3, -0.1, 0.0, 0.25, 0.5, 1.0, 2.718281828459045, 10.0, 100.0, 1000.0]
    emit("lw0_x", w0); emit("lw0_v", [complex(sp.lambertw(v, 0)).real for v in w0])
    wm1 = [-0.36, -0.3, -0.2, -0.1, -0.01, -0.001]
    emit("lwm1_x", wm1); emit("lwm1_v", [complex(sp.lambertw(v, -1)).real for v in wm1])

    # ---- Hurwitz / Riemann zeta (s>1, a>0) ----
    zz = [(2.0, 1.0), (3.0, 1.0), (1.5, 1.0), (2.0, 2.0), (3.5, 0.5), (4.0, 1.0), (10.0, 1.0)]
    emit("zeta_s", [t[0] for t in zz]); emit("zeta_a", [t[1] for t in zz])
    emit("zeta_v", [sp.zeta(s, a) for s, a in zz])

    # ---- Struve H / modified Struve L ----
    sv = [(0.0, 1.0), (1.0, 2.0), (0.5, 3.0), (2.0, 5.0), (1.0, 8.0), (0.0, 20.0), (1.5, 12.0)]
    emit("st_nu", [t[0] for t in sv]); emit("st_x", [t[1] for t in sv])
    emit("sth_v", [sp.struve(nu, x) for nu, x in sv])
    svl = [(0.0, 1.0), (1.0, 2.0), (0.5, 3.0), (2.0, 5.0), (1.0, 8.0)]
    emit("stl_nu", [t[0] for t in svl]); emit("stl_x", [t[1] for t in svl])
    emit("stl_v", [sp.modstruve(nu, x) for nu, x in svl])

    # ---- hypergeometric ----
    h0 = [(1.5, 0.5), (2.0, -1.0), (0.5, 2.0), (3.0, 1.0), (1.0, -3.0)]
    emit("h0_b", [t[0] for t in h0]); emit("h0_z", [t[1] for t in h0])
    emit("h0_v", [sp.hyp0f1(b, z) for b, z in h0])
    h1 = [(1.0, 2.0, 0.5), (0.5, 1.5, -1.0), (2.0, 3.0, 1.0), (1.5, 2.5, -2.0), (1.0, 2.0, 3.0), (0.5, 1.0, -5.0)]
    emit("h1_a", [t[0] for t in h1]); emit("h1_b", [t[1] for t in h1]); emit("h1_z", [t[2] for t in h1])
    emit("h1_v", [sp.hyp1f1(a, b, z) for a, b, z in h1])
    h2 = [(0.5, 1.0, 1.5, 0.3), (1.0, 2.0, 3.0, -0.5), (0.5, 0.5, 1.0, 0.25), (2.0, 1.0, 4.0, -2.0),
          (1.5, 2.0, 3.5, 0.4), (1.0, 1.0, 2.0, -0.8),
          (0.5, 1.0, 2.5, 0.8), (1.0, 1.5, 3.0, 0.95), (0.5, 1.0, 1.5, -3.0),  # connection (z→1) + 1/z
          (1.0, 2.0, 4.5, -5.0), (0.5, 0.75, 2.25, 0.9)]
    emit("h2_a", [t[0] for t in h2]); emit("h2_b", [t[1] for t in h2])
    emit("h2_c", [t[2] for t in h2]); emit("h2_z", [t[3] for t in h2])
    emit("h2_v", [sp.hyp2f1(a, b, c, z) for a, b, c, z in h2])

    # ---- Marcum Q (= ncx2.sf(b², 2M, a²)) ----
    mq = [(1.0, 1.0, 1.0), (2.0, 2.0, 3.0), (1.0, 0.5, 1.5), (3.0, 2.0, 2.0), (1.0, 2.0, 1.0), (2.0, 0.0, 2.0)]
    emit("mq_m", [t[0] for t in mq]); emit("mq_a", [t[1] for t in mq]); emit("mq_b", [t[2] for t in mq])
    emit("mq_v", [ncx2.sf(b * b, 2.0 * m, a * a) for m, a, b in mq])


if __name__ == "__main__":
    main()
