#pragma once

#include <crd/containers/span.hpp>
#include <crd/core/assert.hpp>
#include <crd/core/types.hpp>
#include <crd/memory/allocator.hpp>

#include <complex>
#include <cstring>
#include <type_traits>

// ---------------------------------------------------------------------------
// crd-hesap-tensor — the N-D tensor substrate (Phase 3.1.6 v14-a; ADR-0096).
//
// NumPy stride-view semantics on a bounded-rank header: shape/strides are
// fixed arrays of rank <= kMaxRank (allocation-free view metadata, WCET-
// analyzable). Strides are in ELEMENTS (typed T* arithmetic), signed
// (negative = flips), stride 0 = broadcast; contiguity is tracked NumPy-style
// (size-1 dims never break C-contiguity). Tensor<T> owns storage via
// IAllocator*; TensorView<T> is non-owning with caller-guaranteed lifetime
// (the engine-wide Span discipline — no refcounted aliasing).
//
// Compute dtypes are template parameters (T in {f32, f64, c32, c64} + i64
// index / u8 mask — ADR-0096 §2); the low-precision storage set (f16/bf16/
// FP8/int8/int4-block) lands as explicit convert buffers in dtypes.hpp.
//
// Error contract (the v13 pillars, ADR-0095 §2): fallible shape operations
// return TensorStatus, never throw (`-fno-exceptions`-clean); programmer
// errors (out-of-range index, rank mismatch) are CRD_ASSERT in debug.
// Gate: the NumPy view/stride-semantics corpus (generated by
// scripts/v14a_view_corpus.py) bit-exact — see tests/hesap-tensor.
// ---------------------------------------------------------------------------

namespace crd::hesap::tensor
{

inline constexpr crd::u32 kMaxRank = 8U;

// The compute dtype set (ADR-0096 §2): f32/f64 arithmetic, c32/c64 complex
// (std::complex — the crd::math complex layer computes on it via the
// deterministic real cores), i64 index tensors, u8 masks. The substrate is
// dtype-generic; the elementwise/reduce SIMD kernels specialize f32/f64.
using c32 = std::complex<crd::f32>;
using c64 = std::complex<crd::f64>;

enum class TensorStatus : crd::u8
{
    Ok,
    BadInput,      // bad dim / bad range / bad permutation / element-count overflow
    RankOverflow,  // requested rank exceeds kMaxRank (data-driven paths: einsum
                   // intermediates, reshape, broadcast, npy/safetensors/DLPack import)
    ShapeMismatch, // element counts / broadcast rules do not match
    NotContiguous, // operation requires a C-contiguous view (e.g. reshape)
    AllocFailed,   // IAllocator returned null (status, never bad_alloc — -fno-exceptions)
    Unsupported,
};

// -----------------------------------------------------------------------
// TensorView<T> — non-owning N-D view: data pointer + shape/strides by value.
//
// The data pointer addresses the view's logical [0,...,0] element (NumPy
// convention — a flipped view points at what is physically the last element
// of the underlying row). rank 0 is a valid scalar view (size() == 1).
// -----------------------------------------------------------------------
template <typename T> class TensorView
{
    static_assert(std::is_trivially_copyable_v<T>, "TensorView<T>: T must be trivially copyable");

public:
    TensorView() = default;

    // Implicit TensorView<U> -> TensorView<const U> (mirrors Span semantics).
    template <typename U>
        requires(std::is_same_v<T, const U>)
    TensorView(const TensorView<U>& other) noexcept // NOLINT(google-explicit-constructor)
        : m_data(other.data()), m_rank(other.rank())
    {
        for (crd::u32 d = 0; d < m_rank; ++d)
        {
            m_shape[d] = other.shape(d);
            m_stride[d] = other.stride(d);
        }
    }

    // Wrap raw storage with explicit shape + element strides (sizes must match).
    TensorView(T* data, crd::containers::ConstSpan<crd::u64> shape,
               crd::containers::ConstSpan<crd::i64> strides) noexcept
        : m_data(data), m_rank(static_cast<crd::u32>(shape.size()))
    {
        CRD_ASSERT_MSG(shape.size() == strides.size(), "TensorView: shape/stride rank mismatch");
        CRD_ASSERT_MSG(shape.size() <= kMaxRank, "TensorView: rank exceeds kMaxRank");
        for (crd::u32 d = 0; d < m_rank; ++d)
        {
            m_shape[d] = shape[d];
            m_stride[d] = strides[d];
        }
    }

    // Wrap contiguous row-major storage (strides computed).
    [[nodiscard]] static TensorView contiguous(T* data, crd::containers::ConstSpan<crd::u64> shape) noexcept
    {
        CRD_ASSERT_MSG(shape.size() <= kMaxRank, "TensorView::contiguous: rank exceeds kMaxRank");
        TensorView v;
        v.m_data = data;
        v.m_rank = static_cast<crd::u32>(shape.size());
        crd::i64 s = 1;
        for (crd::u32 d = v.m_rank; d-- > 0U;)
        {
            v.m_shape[d] = shape[d];
            v.m_stride[d] = s;
            s *= static_cast<crd::i64>(shape[d]);
        }
        return v;
    }

    [[nodiscard]] T* data() const noexcept { return m_data; }
    [[nodiscard]] crd::u32 rank() const noexcept { return m_rank; }
    [[nodiscard]] crd::u64 shape(crd::u32 dim) const noexcept
    {
        CRD_ASSERT_MSG(dim < m_rank, "TensorView::shape: dim out of range");
        return m_shape[dim];
    }
    [[nodiscard]] crd::i64 stride(crd::u32 dim) const noexcept
    {
        CRD_ASSERT_MSG(dim < m_rank, "TensorView::stride: dim out of range");
        return m_stride[dim];
    }
    [[nodiscard]] crd::containers::ConstSpan<crd::u64> shape() const noexcept { return {m_shape, m_rank}; }
    [[nodiscard]] crd::containers::ConstSpan<crd::i64> strides() const noexcept { return {m_stride, m_rank}; }

    // Logical element count (product of the shape; 1 for rank 0).
    [[nodiscard]] crd::u64 size() const noexcept
    {
        crd::u64 n = 1;
        for (crd::u32 d = 0; d < m_rank; ++d)
        {
            n *= m_shape[d];
        }
        return n;
    }

    // NumPy C-contiguity: strides are exactly row-major, but dims of size <= 1
    // never break the property (their stride is unobservable), and a zero-size
    // view is trivially contiguous (NumPy flags every empty array contiguous).
    [[nodiscard]] bool is_contiguous() const noexcept
    {
        if (size() == 0U)
        {
            return true; // empty — no element layout to violate
        }
        crd::i64 expected = 1;
        for (crd::u32 d = m_rank; d-- > 0U;)
        {
            if (m_shape[d] > 1U)
            {
                if (m_stride[d] != expected)
                {
                    return false;
                }
                expected *= static_cast<crd::i64>(m_shape[d]);
            }
        }
        return true;
    }

    // ---- element access ------------------------------------------------

    // Runtime-index access; idx.size() must equal rank().
    [[nodiscard]] T& at(crd::containers::ConstSpan<crd::u64> idx) const noexcept
    {
        CRD_ASSERT_MSG(idx.size() == m_rank, "TensorView::at: index rank mismatch");
        crd::i64 off = 0;
        for (crd::u32 d = 0; d < m_rank; ++d)
        {
            CRD_ASSERT_MSG(idx[d] < m_shape[d], "TensorView::at: index out of range");
            off += static_cast<crd::i64>(idx[d]) * m_stride[d];
        }
        return m_data[off];
    }

    // Variadic access: v(i, j, k) — argument count must equal rank().
    template <typename... Ix>
        requires(std::conjunction_v<std::is_convertible<Ix, crd::u64>...>)
    [[nodiscard]] T& operator()(Ix... ix) const noexcept
    {
        static_assert(sizeof...(Ix) <= kMaxRank, "TensorView::operator(): more indices than kMaxRank");
        CRD_ASSERT_MSG(sizeof...(Ix) == m_rank, "TensorView::operator(): index rank mismatch");
        const crd::u64 idx[sizeof...(Ix) > 0 ? sizeof...(Ix) : 1] = {static_cast<crd::u64>(ix)...};
        crd::i64 off = 0;
        for (crd::u32 d = 0; d < static_cast<crd::u32>(sizeof...(Ix)); ++d)
        {
            CRD_ASSERT_MSG(idx[d] < m_shape[d], "TensorView::operator(): index out of range");
            off += static_cast<crd::i64>(idx[d]) * m_stride[d];
        }
        return m_data[off];
    }

    // ---- view transforms (all zero-copy) --------------------------------

    // Half-open range [start, stop) with step >= 1 along `dim` (NumPy basic
    // slice with a positive step; compose with flip() for negative steps).
    [[nodiscard]] TensorView slice(crd::u32 dim, crd::u64 start, crd::u64 stop, crd::u64 step = 1U) const noexcept
    {
        CRD_ASSERT_MSG(dim < m_rank, "TensorView::slice: dim out of range");
        CRD_ASSERT_MSG(step >= 1U, "TensorView::slice: step must be >= 1");
        CRD_ASSERT_MSG(start <= stop && stop <= m_shape[dim], "TensorView::slice: bad range");
        TensorView v(*this);
        v.m_data += static_cast<crd::i64>(start) * m_stride[dim];
        v.m_shape[dim] = (stop - start + step - 1U) / step;
        v.m_stride[dim] = m_stride[dim] * static_cast<crd::i64>(step);
        return v;
    }

    // Fix `dim` at `index` and drop it (NumPy integer indexing — rank drops by 1).
    [[nodiscard]] TensorView select(crd::u32 dim, crd::u64 index) const noexcept
    {
        CRD_ASSERT_MSG(dim < m_rank, "TensorView::select: dim out of range");
        CRD_ASSERT_MSG(index < m_shape[dim], "TensorView::select: index out of range");
        TensorView v;
        v.m_data = m_data + static_cast<crd::i64>(index) * m_stride[dim];
        v.m_rank = m_rank - 1U;
        crd::u32 o = 0;
        for (crd::u32 d = 0; d < m_rank; ++d)
        {
            if (d != dim)
            {
                v.m_shape[o] = m_shape[d];
                v.m_stride[o] = m_stride[d];
                ++o;
            }
        }
        return v;
    }

    // Reverse the logical order along `dim` (NumPy [::-1] — negative stride).
    [[nodiscard]] TensorView flip(crd::u32 dim) const noexcept
    {
        CRD_ASSERT_MSG(dim < m_rank, "TensorView::flip: dim out of range");
        TensorView v(*this);
        if (m_shape[dim] > 0U)
        {
            v.m_data += static_cast<crd::i64>(m_shape[dim] - 1U) * m_stride[dim];
        }
        v.m_stride[dim] = -m_stride[dim];
        return v;
    }

    // Reorder dimensions: out dim d = in dim order[d] (NumPy transpose).
    [[nodiscard]] TensorView permute(crd::containers::ConstSpan<crd::u32> order) const noexcept
    {
        CRD_ASSERT_MSG(order.size() == m_rank, "TensorView::permute: order rank mismatch");
        TensorView v;
        v.m_data = m_data;
        v.m_rank = m_rank;
#if CRD_ENABLE_ASSERTS
        crd::u32 seen = 0; // bitmask — each source dim used exactly once
#endif
        for (crd::u32 d = 0; d < m_rank; ++d)
        {
            const crd::u32 src = order[d];
            CRD_ASSERT_MSG(src < m_rank, "TensorView::permute: order entry out of range");
#if CRD_ENABLE_ASSERTS
            CRD_ASSERT_MSG((seen & (1U << src)) == 0U, "TensorView::permute: duplicate order entry");
            seen |= 1U << src;
#endif
            v.m_shape[d] = m_shape[src];
            v.m_stride[d] = m_stride[src];
        }
        return v;
    }

    // NumPy broadcast_to: right-aligned; a source dim must equal the target
    // or be 1 (stride becomes 0); missing leading dims broadcast with stride 0.
    [[nodiscard]] TensorStatus broadcast_to(crd::containers::ConstSpan<crd::u64> target, TensorView& out) const noexcept
    {
        if (target.size() > kMaxRank)
        {
            return TensorStatus::RankOverflow;
        }
        if (target.size() < m_rank)
        {
            return TensorStatus::ShapeMismatch;
        }
        const crd::u32 out_rank = static_cast<crd::u32>(target.size());
        const crd::u32 lead = out_rank - m_rank;
        TensorView v;
        v.m_data = m_data;
        v.m_rank = out_rank;
        for (crd::u32 d = 0; d < out_rank; ++d)
        {
            if (d < lead)
            {
                v.m_shape[d] = target[d];
                v.m_stride[d] = 0;
                continue;
            }
            const crd::u64 src = m_shape[d - lead];
            if (src == target[d])
            {
                v.m_shape[d] = src;
                v.m_stride[d] = m_stride[d - lead];
            }
            else if (src == 1U)
            {
                v.m_shape[d] = target[d];
                v.m_stride[d] = 0;
            }
            else
            {
                return TensorStatus::ShapeMismatch;
            }
        }
        out = v;
        return TensorStatus::Ok;
    }

    // View-level reshape: same element count, C-contiguous source only
    // (a non-contiguous reshape requires a copy — that is a Tensor-level op).
    [[nodiscard]] TensorStatus reshape(crd::containers::ConstSpan<crd::u64> new_shape, TensorView& out) const noexcept
    {
        if (new_shape.size() > kMaxRank)
        {
            return TensorStatus::RankOverflow;
        }
        crd::u64 n = 1;
        for (crd::u64 s : new_shape)
        {
            n *= s;
        }
        if (n != size())
        {
            return TensorStatus::ShapeMismatch;
        }
        if (!is_contiguous())
        {
            return TensorStatus::NotContiguous;
        }
        out = contiguous(m_data, new_shape);
        return TensorStatus::Ok;
    }

    // Visit every logical element in row-major order: fn(const u64* idx, T& value).
    // The workhorse for tests + non-fused fallbacks; hot paths use the fused
    // kernels (v14-b+), never this.
    template <typename Fn> void for_each(Fn&& fn) const
    {
        crd::u64 idx[kMaxRank] = {};
        const crd::u64 n = size();
        for (crd::u64 k = 0; k < n; ++k)
        {
            fn(static_cast<const crd::u64*>(idx), at({idx, m_rank}));
            for (crd::u32 d = m_rank; d-- > 0U;)
            {
                if (++idx[d] < m_shape[d])
                {
                    break;
                }
                idx[d] = 0;
            }
        }
    }

private:
    T* m_data = nullptr;
    crd::u32 m_rank = 0;
    crd::u64 m_shape[kMaxRank] = {};
    crd::i64 m_stride[kMaxRank] = {};
};

// -----------------------------------------------------------------------
// Tensor<T> — owning, C-contiguous row-major canonical storage over
// IAllocator. Move-only (relocating live storage under views is caller-
// visible; views hand out non-owning TensorView with the Span lifetime
// discipline).
// -----------------------------------------------------------------------
template <typename T> class Tensor
{
    static_assert(std::is_trivially_copyable_v<T>, "Tensor<T>: T must be trivially copyable");

public:
    // Detached tensor (no allocator): resize returns AllocFailed until it is
    // move-assigned from an allocator-backed one. Enables fixed-size arrays
    // of intermediates (the einsum executor's SSA slots).
    Tensor() noexcept = default;

    explicit Tensor(crd::memory::IAllocator* alloc) noexcept : m_alloc(alloc)
    {
        CRD_ASSERT_MSG(alloc != nullptr, "Tensor: null allocator");
    }

    Tensor(crd::memory::IAllocator* alloc, crd::containers::ConstSpan<crd::u64> shape) : Tensor(alloc)
    {
        [[maybe_unused]] const TensorStatus st = resize(shape);
        CRD_ASSERT_MSG(st == TensorStatus::Ok, "Tensor: bad construction shape");
    }

    Tensor(const Tensor&) = delete;
    Tensor& operator=(const Tensor&) = delete;

    Tensor(Tensor&& other) noexcept
        : m_alloc(other.m_alloc), m_data(other.m_data), m_rank(other.m_rank), m_size(other.m_size)
    {
        for (crd::u32 d = 0; d < kMaxRank; ++d)
        {
            m_shape[d] = other.m_shape[d];
        }
        other.m_data = nullptr;
        other.m_rank = 0;
        other.m_size = 0;
    }

    Tensor& operator=(Tensor&& other) noexcept
    {
        if (this != &other)
        {
            release();
            m_alloc = other.m_alloc;
            m_data = other.m_data;
            m_rank = other.m_rank;
            m_size = other.m_size;
            for (crd::u32 d = 0; d < kMaxRank; ++d)
            {
                m_shape[d] = other.m_shape[d];
            }
            other.m_data = nullptr;
            other.m_rank = 0;
            other.m_size = 0;
        }
        return *this;
    }

    ~Tensor() { release(); }

    // (Re)allocate for `shape`; contents uninitialized (call fill/zero after).
    // Defensive validation per the status contract: 8 u64 dims can overflow the
    // element count / byte count — that is BadInput, never a wrapped allocation.
    [[nodiscard]] TensorStatus resize(crd::containers::ConstSpan<crd::u64> shape)
    {
        if (shape.size() > kMaxRank)
        {
            return TensorStatus::RankOverflow;
        }
        crd::u64 n = 1;
        for (crd::u64 s : shape)
        {
            if (s != 0U && n > (~crd::u64{0} / sizeof(T)) / s)
            {
                return TensorStatus::BadInput; // element/byte-count overflow
            }
            n *= s;
        }
        release();
        m_rank = static_cast<crd::u32>(shape.size());
        m_size = n;
        for (crd::u32 d = 0; d < m_rank; ++d)
        {
            m_shape[d] = shape[d];
        }
        if (n > 0U)
        {
            if (m_alloc == nullptr) // detached (default-constructed): status, never a null deref
            {
                m_rank = 0;
                m_size = 0;
                return TensorStatus::AllocFailed;
            }
            // 64-byte alignment for ALL tensor storage: cache-line isolation, aligned
            // SIMD loads, and the legality of streaming (non-temporal) stores in the
            // permute/reduce kernels.
            m_data = static_cast<T*>(m_alloc->allocate(n * sizeof(T), 64U));
            if (m_data == nullptr)
            {
                m_rank = 0;
                m_size = 0;
                return TensorStatus::AllocFailed;
            }
        }
        return TensorStatus::Ok;
    }

    void zero() noexcept
    {
        if (m_data != nullptr && m_size > 0U)
        {
            std::memset(m_data, 0, m_size * sizeof(T));
        }
    }

    [[nodiscard]] static Tensor zeros(crd::memory::IAllocator* alloc, crd::containers::ConstSpan<crd::u64> shape)
    {
        Tensor t(alloc, shape);
        t.zero();
        return t;
    }

    [[nodiscard]] T* data() noexcept { return m_data; }
    [[nodiscard]] const T* data() const noexcept { return m_data; }
    [[nodiscard]] crd::u32 rank() const noexcept { return m_rank; }
    [[nodiscard]] crd::u64 size() const noexcept { return m_size; }
    [[nodiscard]] crd::containers::ConstSpan<crd::u64> shape() const noexcept { return {m_shape, m_rank}; }
    [[nodiscard]] crd::u64 shape(crd::u32 dim) const noexcept
    {
        CRD_ASSERT_MSG(dim < m_rank, "Tensor::shape: dim out of range");
        return m_shape[dim];
    }

    [[nodiscard]] TensorView<T> view() noexcept { return TensorView<T>::contiguous(m_data, shape()); }
    [[nodiscard]] TensorView<const T> view() const noexcept { return TensorView<const T>::contiguous(m_data, shape()); }

private:
    void release() noexcept
    {
        if (m_data != nullptr)
        {
            m_alloc->deallocate(m_data);
            m_data = nullptr;
        }
    }

    crd::memory::IAllocator* m_alloc = nullptr;
    T* m_data = nullptr;
    crd::u32 m_rank = 0;
    crd::u64 m_size = 0;
    crd::u64 m_shape[kMaxRank] = {};
};

// Human-readable status name (diagnostics/tests; implemented in tensor.cpp).
[[nodiscard]] const char* to_string(TensorStatus status) noexcept;

} // namespace crd::hesap::tensor
