#pragma once
// ---------------------------------------------------------------------------
// crd-hesap-tensor — v14-k: Decompositions II — TENSOR TRAINS.
//
// TtTensor<T> (owned cores — never borrowed lifetimes, the v14-g scar) +
//   tt_svd       dense tensor -> TT at tolerance/rank cap (Oseledets 2011,
//                Alg. 1: sequential unfolding SVD, delta = tol*||A||_F/sqrt(d-1)
//                tail-energy chop) — reuses hesap-dense svd() (SANITY #8);
//   tt_round     rank re-compression (Oseledets 2011, Alg. 2: right-to-left QR
//                orthogonalization, left-to-right SVD truncation) — reuses
//                hesap-dense factor_qr/apply_q + svd();
//   tt_add / tt_hadamard / tt_dot / tt_norm / tt_contract   TT algebra
//                (block concat / slice-wise Kronecker / two-gemm-per-core
//                bilinear contraction / materialization via hesap-dense gemm);
//   tt_eval / tt_eval_many / tt_eval_lerp   ALLOCATION-FREE evaluation of a
//                single element / index batch / multilinear-interpolated point
//                (caller workspace, size = tt_eval_workspace(tt) = 2*max_rank,
//                checked). tt_eval_lerp(TT of a grid LUT) equals multilinear
//                interpolation of the DENSE grid (a tensor-product linear
//                functional factors through the cores) — the v13-interp LUT
//                compression story;
//   maxvol       the Goreinov-Oseledets-Savostyanov-Tyrtyshnikov-Zamarashkin
//                quasi-max-volume submatrix ("How to Find a Good Submatrix",
//                2010). Source of truth: transliterated from tntorch/maxvol.py
//                `py_maxvol` (verbatim in tntorch from A. Mikhalev's maxvolpy),
//                reconstructed + verified in numpy first
//                (scripts/v14k_tt_oracle.py). LU-pivot init, C = A*Ahat^-1 via
//                two row-wise triangular solves, argmax + rank-1 update loop —
//                BOUNDED by max_iters, tol-terminated;
//   tt_cross     TT from FUNCTION EVALUATIONS without materializing the tensor
//                (Oseledets-Tyrtyshnikov 2010 TT-cross; the fixed-rank ALS
//                QR+maxvol sweep scheme of tntorch/cross.py, verified in numpy
//                first). Deterministic: pivot starts + validation points from
//                PhiloxRng(seed) — same seed => bit-identical result. Sweeps
//                BOUNDED by max_sweeps; convergence = validation error < tol.
//
// Error contract: fallible ops return TensorStatus (never throw). TensorStatus
// is frozen (tensor.hpp is not edited this slice), so NotConverged rides the
// info structs (TtCrossInfo::converged / MaxvolInfo::converged) — the
// batched_svd_small info-lane precedent. Programmer errors are CRD_ASSERT.
//
// Determinism: every routine here is SERIAL in v1 (deliberate — the per-op
// working sets are rank-bounded and small; batch parallelism belongs to the
// CALLER over independent TTs, as batched.hpp does over matrices). Run-twice
// bit-identity is gated in tests/hesap-tensor/test_tt.cpp.
//
// Gates: tests/hesap-tensor/ref_tt.inc (generated by scripts/v14k_tt_oracle.py
// against tntorch 1.1.2 + numpy mirrors; ttpy is N/A-with-check — its setup.py
// imports numpy.distutils, removed from numpy on py>=3.12).
// ---------------------------------------------------------------------------
#include "tensor.hpp"

#include <crd/containers/array.hpp>
#include <crd/hesap/dense/blas3.hpp>
#include <crd/hesap/dense/lu.hpp>
#include <crd/hesap/dense/qr.hpp>
#include <crd/hesap/dense/svd.hpp>
#include <crd/hesap/stats/philox.hpp>

#include <cmath>

namespace crd::hesap::tensor
{

// -----------------------------------------------------------------------
// TtTensor<T> — a tensor in tensor-train format: d cores, core k of shape
// (r_{k-1}, n_k, r_k) stored row-major, r_0 = r_d = 1; A(i_1..i_d) =
// G_1[i_1] * G_2[i_2] * ... * G_d[i_d] (a product of rank-slices).
//
// OWNS its cores in one contiguous Array<T> (per-core offsets) — returned
// objects never hold borrowed lifetimes (the v14-g HyperTree scar). Move-only;
// allocator-bound at construction (IAllocator propagation, no defaults).
// -----------------------------------------------------------------------
template <typename T> class TtTensor
{
    static_assert(std::is_floating_point_v<T>, "TtTensor<T>: real f32/f64 in v1");

public:
    explicit TtTensor(crd::memory::IAllocator* alloc) noexcept : m_data(alloc)
    {
        CRD_ASSERT_MSG(alloc != nullptr, "TtTensor: null allocator");
    }

    TtTensor(const TtTensor&) = delete;
    TtTensor& operator=(const TtTensor&) = delete;
    TtTensor(TtTensor&&) noexcept = default;
    TtTensor& operator=(TtTensor&&) noexcept = default;

    // (Re)allocate cores for `shape` (d dims) and `ranks` (d+1 entries,
    // ranks[0] == ranks[d] == 1). Core contents uninitialized.
    [[nodiscard]] TensorStatus init(crd::containers::ConstSpan<crd::u64> shape,
                                    crd::containers::ConstSpan<crd::u64> ranks)
    {
        if (shape.size() == 0U || shape.size() > kMaxRank || ranks.size() != shape.size() + 1U)
        {
            return TensorStatus::BadInput;
        }
        if (ranks[0] != 1U || ranks[shape.size()] != 1U)
        {
            return TensorStatus::BadInput;
        }
        const crd::u32 d = static_cast<crd::u32>(shape.size());
        crd::u64 total = 0;
        crd::u64 off[kMaxRank + 1U];
        for (crd::u32 k = 0; k < d; ++k)
        {
            if (shape[k] == 0U || ranks[k] == 0U || ranks[k + 1U] == 0U)
            {
                return TensorStatus::BadInput;
            }
            const crd::u64 cs = ranks[k] * shape[k] * ranks[k + 1U];
            if (cs / ranks[k] / shape[k] != ranks[k + 1U] || total > ~crd::u64{0} - cs)
            {
                return TensorStatus::BadInput; // element-count overflow
            }
            off[k] = total;
            total += cs;
        }
        off[d] = total;
        if (!m_data.try_reserve(total))
        {
            return TensorStatus::AllocFailed;
        }
        m_data.resize(total);
        m_dims = d;
        for (crd::u32 k = 0; k < d; ++k)
        {
            m_shape[k] = shape[k];
            m_ranks[k] = ranks[k];
            m_offset[k] = off[k];
        }
        m_ranks[d] = 1U;
        m_offset[d] = total;
        return TensorStatus::Ok;
    }

    [[nodiscard]] crd::u32 dims() const noexcept { return m_dims; }
    [[nodiscard]] crd::u64 shape(crd::u32 k) const noexcept
    {
        CRD_ASSERT_MSG(k < m_dims, "TtTensor::shape: dim out of range");
        return m_shape[k];
    }
    // rank(k) for k in [0, dims()] — rank(0) == rank(dims()) == 1.
    [[nodiscard]] crd::u64 rank(crd::u32 k) const noexcept
    {
        CRD_ASSERT_MSG(k <= m_dims, "TtTensor::rank: edge out of range");
        return m_ranks[k];
    }
    [[nodiscard]] crd::containers::ConstSpan<crd::u64> shape() const noexcept { return {m_shape, m_dims}; }
    [[nodiscard]] crd::containers::ConstSpan<crd::u64> ranks() const noexcept
    {
        return {m_ranks, static_cast<crd::usize>(m_dims) + 1U};
    }
    [[nodiscard]] T* core(crd::u32 k) noexcept
    {
        CRD_ASSERT_MSG(k < m_dims, "TtTensor::core: dim out of range");
        return m_data.data() + m_offset[k];
    }
    [[nodiscard]] const T* core(crd::u32 k) const noexcept
    {
        CRD_ASSERT_MSG(k < m_dims, "TtTensor::core: dim out of range");
        return m_data.data() + m_offset[k];
    }
    [[nodiscard]] crd::u64 core_size(crd::u32 k) const noexcept
    {
        CRD_ASSERT_MSG(k < m_dims, "TtTensor::core_size: dim out of range");
        return m_offset[k + 1U] - m_offset[k];
    }
    // Total TT parameter count (the compression numerator: dense elems / this).
    [[nodiscard]] crd::u64 param_count() const noexcept { return m_dims > 0U ? m_offset[m_dims] : 0U; }
    [[nodiscard]] crd::u64 max_rank() const noexcept
    {
        crd::u64 r = 1;
        for (crd::u32 k = 0; k <= m_dims; ++k)
        {
            if (m_ranks[k] > r)
            {
                r = m_ranks[k];
            }
        }
        return r;
    }
    [[nodiscard]] crd::u64 element_count() const noexcept
    {
        crd::u64 n = 1;
        for (crd::u32 k = 0; k < m_dims; ++k)
        {
            n *= m_shape[k];
        }
        return n;
    }
    [[nodiscard]] crd::memory::IAllocator* allocator() const noexcept { return m_data.allocator(); }

private:
    crd::containers::Array<T> m_data; // all cores, contiguous (owned)
    crd::u32 m_dims = 0;
    crd::u64 m_shape[kMaxRank] = {};
    crd::u64 m_ranks[kMaxRank + 1U] = {};
    crd::u64 m_offset[kMaxRank + 1U] = {};
};

// info structs (NotConverged rides here — TensorStatus is frozen this slice)
struct MaxvolInfo
{
    crd::u32 iters = 0;
    bool converged = false; // max |A*Ahat^-1| <= tol reached within max_iters
    bool singular = false;  // a zero pivot was substituted during LU init
};

template <typename T> struct TtCrossInfo
{
    T val_error = T(0);      // final validation relative error
    crd::u64 evals = 0;      // fiber function evaluations (validation counted separately)
    crd::u64 val_evals = 0;  // validation-set function evaluations (one-time)
    crd::u32 sweeps = 0;     // sweep pairs executed
    bool converged = false;  // val_error < tol within max_sweeps
};

template <typename T> struct TtCrossParams
{
    crd::u64 max_rank = 8;   // TT rank cap per edge (clamped to unfolding sizes)
    crd::u32 max_sweeps = 8; // bounded iteration: L2R+R2L sweep pairs
    T tol = T(1e-10);        // validation relative-error convergence target
    crd::u64 val_size = 200; // validation points (deterministic from `seed`)
    crd::u64 seed = 0x7714CCULL; // PhiloxRng seed (pivot starts + validation)
};

namespace ttdetail
{

// row-major MatrixView helpers over raw buffers (the batched.hpp pattern)
template <typename T>
[[nodiscard]] inline crd::hesap::dense::MatrixView<const T, crd::hesap::dense::Layout::RowMajor>
mview(const T* p, crd::u64 rows, crd::u64 cols) noexcept
{
    return {p, static_cast<crd::usize>(rows), static_cast<crd::usize>(cols), static_cast<crd::usize>(cols)};
}

template <typename T>
[[nodiscard]] inline crd::hesap::dense::MatrixView<T, crd::hesap::dense::Layout::RowMajor>
mview_mut(T* p, crd::u64 rows, crd::u64 cols) noexcept
{
    return {p, static_cast<crd::usize>(rows), static_cast<crd::usize>(cols), static_cast<crd::usize>(cols)};
}

// C = A(rows_a x k) @ B(k x cols_b), row-major tight, via hesap-dense gemm.
template <typename T>
inline void gemm_rm(const T* a, const T* b, T* c, crd::u64 rows, crd::u64 k, crd::u64 cols,
                    crd::memory::IAllocator* scratch) noexcept
{
    crd::hesap::dense::MatrixView<T, crd::hesap::dense::Layout::RowMajor> cv = mview_mut(c, rows, cols);
    crd::hesap::dense::gemm<T, crd::hesap::dense::Layout::RowMajor>(
        T(1), mview(a, rows, k), mview(b, k, cols), T(0), cv, crd::hesap::dense::Trans::None,
        crd::hesap::dense::Trans::None, scratch);
}

// Frobenius norm of a raw buffer (sequential order — deterministic).
template <typename T> [[nodiscard]] inline T fro_norm(const T* p, crd::u64 n) noexcept
{
    T s = T(0);
    for (crd::u64 i = 0; i < n; ++i)
    {
        s = std::fma(p[i], p[i], s);
    }
    return std::sqrt(s);
}

// Truncation rank: smallest r >= 1 with sum_{i>=r} s_i^2 <= delta^2, capped.
// EXACT mirror of the oracle's rank_chop (scripts/v14k_tt_oracle.py).
template <typename T>
[[nodiscard]] inline crd::u64 rank_chop(const T* s, crd::u64 count, T delta, crd::u64 rmax) noexcept
{
    crd::u64 r = count;
    T tail = T(0);
    for (crd::u64 i = count; i-- > 1U;)
    {
        tail = std::fma(s[i], s[i], tail);
        if (tail > delta * delta)
        {
            break;
        }
        r = i;
    }
    if (r < 1U)
    {
        r = 1U;
    }
    if (rmax != 0U && r > rmax)
    {
        r = rmax;
    }
    if (r > count)
    {
        r = count;
    }
    return r;
}

// Thin Q formation from a factored Householder QR: Q(:, c) = Q * e_c.
// HOME-> hesap-dense: an orgqr-style explicit thin-Q builder belongs in
// qr.hpp; until it ships we form Q by applying the reflectors to identity
// columns (O(m*k^2), same complexity as the factorization itself).
template <typename T>
inline void form_thin_q(const crd::hesap::dense::QR<T, crd::hesap::dense::Layout::RowMajor>& qr, T* q,
                        crd::u64 m, crd::u64 kk, T* colbuf) noexcept
{
    for (crd::u64 c = 0; c < kk; ++c)
    {
        for (crd::u64 i = 0; i < m; ++i)
        {
            colbuf[i] = i == c ? T(1) : T(0);
        }
        crd::hesap::dense::apply_q(qr, crd::containers::Span<T>{colbuf, static_cast<crd::usize>(m)});
        for (crd::u64 i = 0; i < m; ++i)
        {
            q[i * kk + c] = colbuf[i];
        }
    }
}

} // namespace ttdetail

// -----------------------------------------------------------------------
// maxvol — quasi-maximum-volume row subset of a tall matrix.
//
// Given A (n_rows x r, row-major, n_rows >= r), selects r rows such that the
// spanned submatrix Ahat has quasi-maximal volume: on exit every entry of
// C = A * Ahat^-1 satisfies |C_ij| <= tol (when converged). rows_out receives
// the r selected 0-based row indices; coeff (optional, may be null) receives
// C (n_rows x r, row-major; C[rows_out] == I).
//
// Faithful port of tntorch/maxvol.py `py_maxvol` (maxvolpy; the
// Goreinov-Oseledets algorithm), reconstructed + verified in numpy first —
// see scripts/v14k_tt_oracle.py. Deterministic: LU pivots and the argmax use
// first-max-wins tie rules (fixed scan order). BOUNDED: at most max_iters
// swap iterations; info->converged reports the tol termination.
//
// HOME-> hesap-dense: the tall-matrix partial-pivot LU init (rectangular
// getrf) is inlined here; hesap-dense's LU is square-only today.
// -----------------------------------------------------------------------
template <typename T>
[[nodiscard]] TensorStatus maxvol(crd::memory::IAllocator* alloc, const T* a, crd::u64 n_rows, crd::u64 r,
                                  T tol, crd::u32 max_iters, crd::containers::Span<crd::u64> rows_out,
                                  T* coeff, MaxvolInfo* info) noexcept
{
    if (a == nullptr || alloc == nullptr || r == 0U || n_rows < r || rows_out.size() != r ||
        max_iters == 0U)
    {
        return TensorStatus::BadInput;
    }
    if (tol < T(1))
    {
        tol = T(1);
    }
    MaxvolInfo local;
    if (n_rows == r) // square: the only volume-r submatrix is A itself
    {
        for (crd::u64 i = 0; i < r; ++i)
        {
            rows_out[i] = i;
            if (coeff != nullptr)
            {
                for (crd::u64 j = 0; j < r; ++j)
                {
                    coeff[i * r + j] = i == j ? T(1) : T(0);
                }
            }
        }
        local.converged = true;
        if (info != nullptr)
        {
            *info = local;
        }
        return TensorStatus::Ok;
    }
    // ---- LU with partial pivoting on a copy of the TALL matrix ----------
    crd::containers::Array<T> work(alloc);
    const crd::u64 c_size = n_rows * r;
    if (!work.try_reserve(c_size /*lu*/ + c_size /*C*/ + r /*y*/ + r /*z*/))
    {
        return TensorStatus::AllocFailed;
    }
    work.resize(c_size * 2U + r * 2U);
    T* lu = work.data();
    T* c = work.data() + c_size;
    T* ybuf = work.data() + c_size * 2U;
    T* zbuf = ybuf + r;
    crd::containers::Array<crd::u64> idxbuf(alloc);
    if (!idxbuf.try_reserve(n_rows + r))
    {
        return TensorStatus::AllocFailed;
    }
    idxbuf.resize(n_rows + r);
    crd::u64* index = idxbuf.data();
    crd::u64* ipiv = idxbuf.data() + n_rows;
    for (crd::u64 i = 0; i < c_size; ++i)
    {
        lu[i] = a[i];
    }
    for (crd::u64 j = 0; j < r; ++j)
    {
        crd::u64 p = j;
        T best = lu[j * r + j] < T(0) ? -lu[j * r + j] : lu[j * r + j];
        for (crd::u64 i = j + 1U; i < n_rows; ++i)
        {
            const T v = lu[i * r + j] < T(0) ? -lu[i * r + j] : lu[i * r + j];
            if (v > best) // strictly greater: lowest row wins ties (deterministic)
            {
                best = v;
                p = i;
            }
        }
        ipiv[j] = p;
        if (p != j)
        {
            for (crd::u64 t = 0; t < r; ++t)
            {
                const T tmp = lu[j * r + t];
                lu[j * r + t] = lu[p * r + t];
                lu[p * r + t] = tmp;
            }
        }
        T piv = lu[j * r + j];
        if (piv == T(0))
        {
            local.singular = true; // rank-deficient input; keep bounded on 1.0
            piv = T(1);
        }
        const T inv = T(1) / piv;
        for (crd::u64 i = j + 1U; i < n_rows; ++i)
        {
            const T l = lu[i * r + j] * inv;
            lu[i * r + j] = l;
            for (crd::u64 t = j + 1U; t < r; ++t)
            {
                lu[i * r + t] = std::fma(-l, lu[j * r + t], lu[i * r + t]);
            }
        }
    }
    for (crd::u64 i = 0; i < n_rows; ++i)
    {
        index[i] = i;
    }
    for (crd::u64 i = 0; i < r; ++i) // LAPACK ipiv replay -> selected row ids
    {
        const crd::u64 tmp = index[i];
        index[i] = index[ipiv[i]];
        index[ipiv[i]] = tmp;
    }
    // ---- C = A * U^-1 * L1^-1 (Ahat = A[index[:r]] = L1*U) ---------------
    for (crd::u64 row = 0; row < n_rows; ++row)
    {
        for (crd::u64 j = 0; j < r; ++j) // y * U = a_row  (forward over columns)
        {
            T s = a[row * r + j];
            for (crd::u64 p = 0; p < j; ++p)
            {
                s = std::fma(-ybuf[p], lu[p * r + j], s);
            }
            ybuf[j] = s / lu[j * r + j];
        }
        for (crd::u64 jj = r; jj-- > 0U;) // z * L1 = y  (unit lower, backward)
        {
            T s = ybuf[jj];
            for (crd::u64 p = jj + 1U; p < r; ++p)
            {
                s = std::fma(-zbuf[p], lu[p * r + jj], s);
            }
            zbuf[jj] = s;
        }
        for (crd::u64 j = 0; j < r; ++j)
        {
            c[row * r + j] = zbuf[j];
        }
    }
    // ---- swap loop: argmax |C|, swap the row in, rank-1 update -----------
    for (crd::u32 it = 0; it < max_iters; ++it)
    {
        crd::u64 brow = 0;
        crd::u64 bslot = 0;
        T bval = T(0);
        for (crd::u64 i = 0; i < c_size; ++i) // row-major first-max tie rule
        {
            const T v = c[i] < T(0) ? -c[i] : c[i];
            if (v > bval)
            {
                bval = v;
                brow = i / r;
                bslot = i % r;
            }
        }
        if (!(bval > tol))
        {
            local.converged = true;
            break;
        }
        index[bslot] = brow;
        const T pivot = c[brow * r + bslot];
        const T inv = T(1) / pivot;
        for (crd::u64 j = 0; j < r; ++j) // row of the swap (minus e_slot)
        {
            zbuf[j] = c[brow * r + j];
        }
        zbuf[bslot] -= T(1);
        for (crd::u64 i = 0; i < n_rows; ++i) // C -= C[:,slot] outer zbuf / pivot
        {
            const T ci = c[i * r + bslot] * inv;
            for (crd::u64 j = 0; j < r; ++j)
            {
                c[i * r + j] = std::fma(-ci, zbuf[j], c[i * r + j]);
            }
        }
        local.iters = it + 1U;
    }
    for (crd::u64 i = 0; i < r; ++i)
    {
        rows_out[i] = index[i];
    }
    if (coeff != nullptr)
    {
        for (crd::u64 i = 0; i < c_size; ++i)
        {
            coeff[i] = c[i];
        }
    }
    if (info != nullptr)
    {
        *info = local;
    }
    return TensorStatus::Ok;
}

// -----------------------------------------------------------------------
// tt_svd — dense (contiguous) tensor -> TT at relative tolerance `tol` with
// optional rank cap (max_rank == 0: uncapped). Error contract (gated):
// ||A - TT||_F <= tol * ||A||_F. Exactly the oracle's np_tt_svd.
// -----------------------------------------------------------------------
template <typename T>
[[nodiscard]] TensorStatus tt_svd(crd::memory::IAllocator* alloc, TensorView<const T> a, T tol,
                                  crd::u64 max_rank, TtTensor<T>& out) noexcept
{
    namespace dn = crd::hesap::dense;
    if (alloc == nullptr || a.rank() == 0U || tol < T(0))
    {
        return TensorStatus::BadInput;
    }
    if (!a.is_contiguous())
    {
        return TensorStatus::NotContiguous;
    }
    const crd::u32 d = a.rank();
    const crd::u64 total = a.size();
    if (total == 0U)
    {
        return TensorStatus::BadInput;
    }
    if (d == 1U) // a vector IS its own single core (1, n, 1)
    {
        const crd::u64 shp[1] = {a.shape(0)};
        const crd::u64 rks[2] = {1U, 1U};
        const TensorStatus st = out.init({shp, 1}, {rks, 2});
        if (st != TensorStatus::Ok)
        {
            return st;
        }
        for (crd::u64 i = 0; i < shp[0]; ++i)
        {
            out.core(0)[i] = a.data()[i];
        }
        return TensorStatus::Ok;
    }
    const T nrm = ttdetail::fro_norm(a.data(), total);
    const T delta = tol * nrm / std::sqrt(static_cast<T>(d - 1U));
    // carry buffer C (sizes never grow across steps: r <= r_prev * n_k)
    crd::containers::Array<T> carry(alloc);
    if (!carry.try_reserve(total))
    {
        return TensorStatus::AllocFailed;
    }
    carry.resize(total);
    for (crd::u64 i = 0; i < total; ++i)
    {
        carry.data()[i] = a.data()[i];
    }
    crd::containers::Array<T> corebuf(alloc); // appended cores (offsets tracked)
    crd::u64 core_off[kMaxRank + 1U] = {};
    crd::u64 ranks[kMaxRank + 1U] = {};
    ranks[0] = 1U;
    crd::u64 rest = total / a.shape(0);
    crd::u64 r_prev = 1U;
    for (crd::u32 k = 0; k < d - 1U; ++k)
    {
        const crd::u64 m = r_prev * a.shape(k);
        crd::u64 r = 0;
        const crd::u64 old = static_cast<crd::u64>(corebuf.size());
        if (rest >= 2U * m)
        {
            // WIDE unfolding fast path (the tt_svd hot case: the first unfolds
            // are m x m*rest_ratio with rest_ratio up to n^{d-1}): QR-first, the
            // dgesdd trick. C = R^T Q^T from QR(C^T); SVD(R^T) = U S W^T gives
            // C's left vectors U and singular values DIRECTLY; the carry needs
            // no Q: U_r^T C = S_r V_r^T exactly. Cost: one tall QR (2*rest*m^2,
            // SIMD panel) + an m x m SVD + one (r x m)@(m x rest) gemm — vs the
            // full tall bidiagonalization + rotation accumulation into a
            // rest x m U (measured 0.53x vs torch/MKL at 32^4 BEFORE this path;
            // the fix flipped every tt_svd row — see the v14-k bench doc).
            dn::QR<T> qr(alloc, static_cast<crd::usize>(rest), static_cast<crd::usize>(m));
            {
                dn::Matrix<T>& p = qr.packed();
                const T* src = carry.data();
                for (crd::u64 i = 0; i < m; ++i)
                {
                    for (crd::u64 j = 0; j < rest; ++j)
                    {
                        p.at(static_cast<crd::usize>(j), static_cast<crd::usize>(i)) = src[i * rest + j];
                    }
                }
            }
            dn::factor_qr(qr);
            dn::Matrix<T> rt(alloc, static_cast<crd::usize>(m), static_cast<crd::usize>(m)); // R^T (lower)
            for (crd::u64 i = 0; i < m; ++i)
            {
                for (crd::u64 j = 0; j <= i; ++j)
                {
                    rt.at(static_cast<crd::usize>(i), static_cast<crd::usize>(j)) =
                        qr.packed().at(static_cast<crd::usize>(j), static_cast<crd::usize>(i));
                }
            }
            dn::SVD<T> f = dn::svd<T>(alloc, rt);
            r = ttdetail::rank_chop(f.s.data(), static_cast<crd::u64>(f.s.size()), delta, max_rank);
            if (!corebuf.try_reserve(old + m * r))
            {
                return TensorStatus::AllocFailed;
            }
            corebuf.resize(old + m * r);
            for (crd::u64 i = 0; i < m; ++i)
            {
                for (crd::u64 j = 0; j < r; ++j)
                {
                    corebuf.data()[old + i * r + j] =
                        f.u.at(static_cast<crd::usize>(i), static_cast<crd::usize>(j));
                }
            }
            // carry := U_r^T @ C  (r x rest; = S_r V_r^T) — gemm into a temp,
            // then copy back (C is the gemm source; no in-place aliasing)
            crd::containers::Array<T> tmp(alloc);
            if (!tmp.try_reserve(r * rest))
            {
                return TensorStatus::AllocFailed;
            }
            tmp.resize(r * rest);
            {
                const crd::hesap::dense::MatrixView<const T, dn::Layout::RowMajor> uv{
                    f.u.data(), static_cast<crd::usize>(m), static_cast<crd::usize>(r),
                    static_cast<crd::usize>(f.u.cols())};
                const crd::hesap::dense::MatrixView<const T, dn::Layout::RowMajor> cv{
                    carry.data(), static_cast<crd::usize>(m), static_cast<crd::usize>(rest),
                    static_cast<crd::usize>(rest)};
                crd::hesap::dense::MatrixView<T, dn::Layout::RowMajor> ov =
                    ttdetail::mview_mut(tmp.data(), r, rest);
                dn::gemm<T, dn::Layout::RowMajor>(T(1), uv, cv, T(0), ov, dn::Trans::Transpose,
                                                  dn::Trans::None, alloc);
            }
            for (crd::u64 i = 0; i < r * rest; ++i)
            {
                carry.data()[i] = tmp.data()[i];
            }
        }
        else
        {
            dn::Matrix<T> mat(alloc, static_cast<crd::usize>(m), static_cast<crd::usize>(rest));
            const T* src = carry.data();
            for (crd::u64 i = 0; i < m; ++i)
            {
                for (crd::u64 j = 0; j < rest; ++j)
                {
                    mat.at(static_cast<crd::usize>(i), static_cast<crd::usize>(j)) = src[i * rest + j];
                }
            }
            dn::SVD<T> f = dn::svd<T>(alloc, mat);
            const crd::u64 minmn = static_cast<crd::u64>(f.s.size());
            r = ttdetail::rank_chop(f.s.data(), minmn, delta, max_rank);
            // core k = U(:, :r) reshaped (r_prev, n_k, r)
            if (!corebuf.try_reserve(old + m * r))
            {
                return TensorStatus::AllocFailed;
            }
            corebuf.resize(old + m * r);
            for (crd::u64 i = 0; i < m; ++i)
            {
                for (crd::u64 j = 0; j < r; ++j)
                {
                    corebuf.data()[old + i * r + j] =
                        f.u.at(static_cast<crd::usize>(i), static_cast<crd::usize>(j));
                }
            }
            // C := diag(s_r) * V(:, :r)^T  (r x rest)
            T* dst = carry.data();
            for (crd::u64 i = 0; i < r; ++i)
            {
                const T si = f.s.data()[i];
                for (crd::u64 j = 0; j < rest; ++j)
                {
                    dst[i * rest + j] = si * f.v.at(static_cast<crd::usize>(j), static_cast<crd::usize>(i));
                }
            }
        }
        core_off[k + 1U] = old + m * r;
        ranks[k + 1U] = r;
        r_prev = r;
        if (k + 2U <= d - 1U)
        {
            rest /= a.shape(k + 1U);
        }
    }
    // last core = C reshaped (r_prev, n_{d-1}, 1); rest == n_{d-1} here
    {
        const crd::u64 old = static_cast<crd::u64>(corebuf.size());
        const crd::u64 cs = r_prev * rest;
        if (!corebuf.try_reserve(old + cs))
        {
            return TensorStatus::AllocFailed;
        }
        corebuf.resize(old + cs);
        for (crd::u64 i = 0; i < cs; ++i)
        {
            corebuf.data()[old + i] = carry.data()[i];
        }
        core_off[d] = old + cs;
        ranks[d] = 1U;
    }
    const TensorStatus st = out.init(a.shape(), {ranks, static_cast<crd::usize>(d) + 1U});
    if (st != TensorStatus::Ok)
    {
        return st;
    }
    for (crd::u32 k = 0; k < d; ++k)
    {
        const T* src = corebuf.data() + core_off[k];
        T* dst = out.core(k);
        const crd::u64 cs = out.core_size(k);
        for (crd::u64 i = 0; i < cs; ++i)
        {
            dst[i] = src[i];
        }
    }
    return TensorStatus::Ok;
}

// -----------------------------------------------------------------------
// tt_round — re-compress a TT to relative tolerance `tol` (+ optional rank
// cap). Right-to-left QR orthogonalization, then left-to-right SVD
// truncation with delta = tol*||A||_F/sqrt(d-1) (Oseledets 2011 Alg. 2 —
// the oracle's np_tt_round). Error contract (gated):
// ||A - round(A)||_F <= tol * ||A||_F. In place on `tt`.
// -----------------------------------------------------------------------
template <typename T>
[[nodiscard]] TensorStatus tt_round(crd::memory::IAllocator* alloc, TtTensor<T>& tt, T tol,
                                    crd::u64 max_rank = 0) noexcept
{
    namespace dn = crd::hesap::dense;
    if (alloc == nullptr || tt.dims() == 0U || tol < T(0))
    {
        return TensorStatus::BadInput;
    }
    const crd::u32 d = tt.dims();
    if (d == 1U)
    {
        return TensorStatus::Ok; // single core: nothing to compress
    }
    // work copy (both sweeps only ever SHRINK core sizes => fixed offsets)
    crd::u64 off[kMaxRank + 1U];
    crd::u64 rk[kMaxRank + 1U];
    crd::u64 total = 0;
    for (crd::u32 k = 0; k <= d; ++k)
    {
        rk[k] = tt.rank(k);
    }
    for (crd::u32 k = 0; k < d; ++k)
    {
        off[k] = total;
        total += tt.core_size(k);
    }
    off[d] = total;
    crd::containers::Array<T> work(alloc);
    if (!work.try_reserve(total))
    {
        return TensorStatus::AllocFailed;
    }
    work.resize(total);
    for (crd::u32 k = 0; k < d; ++k)
    {
        const T* src = tt.core(k);
        T* dst = work.data() + off[k];
        for (crd::u64 i = 0; i < tt.core_size(k); ++i)
        {
            dst[i] = src[i];
        }
    }
    // scratch: transposed core / thin Q / R^T / gemm result / apply_q column
    crd::containers::Array<T> scratch(alloc);
    // ---- right-to-left QR orthogonalization ------------------------------
    for (crd::u32 k = d - 1U; k >= 1U; --k)
    {
        const crd::u64 rl = rk[k];
        const crd::u64 ncols = tt.shape(k) * rk[k + 1U];
        const crd::u64 kk = rl < ncols ? rl : ncols;
        dn::QR<T> qr(alloc, static_cast<crd::usize>(ncols), static_cast<crd::usize>(rl));
        {
            const T* m = work.data() + off[k]; // (rl x ncols) row-major
            dn::Matrix<T>& p = qr.packed();
            for (crd::u64 i = 0; i < ncols; ++i)
            {
                for (crd::u64 j = 0; j < rl; ++j)
                {
                    p.at(static_cast<crd::usize>(i), static_cast<crd::usize>(j)) = m[j * ncols + i];
                }
            }
        }
        dn::factor_qr(qr);
        const crd::u64 need = ncols * kk /*Q*/ + rl * kk /*R^T*/ + ncols /*col*/;
        if (!scratch.try_reserve(need))
        {
            return TensorStatus::AllocFailed;
        }
        scratch.resize(need);
        T* q = scratch.data();
        T* rt = q + ncols * kk;
        T* colbuf = rt + rl * kk;
        ttdetail::form_thin_q(qr, q, ncols, kk, colbuf);
        for (crd::u64 i = 0; i < rl; ++i) // R^T (rl x kk) from the packed upper
        {
            for (crd::u64 j = 0; j < kk; ++j)
            {
                rt[i * kk + j] =
                    j <= i ? qr.packed().at(static_cast<crd::usize>(j), static_cast<crd::usize>(i)) : T(0);
            }
        }
        // core k := Q^T (kk x ncols); core k-1 := (prev unfold) @ R^T
        {
            T* m = work.data() + off[k];
            for (crd::u64 i = 0; i < kk; ++i)
            {
                for (crd::u64 j = 0; j < ncols; ++j)
                {
                    m[i * ncols + j] = q[j * kk + i];
                }
            }
        }
        {
            const crd::u64 prows = rk[k - 1U] * tt.shape(k - 1U);
            crd::containers::Array<T> tmp(alloc);
            if (!tmp.try_reserve(prows * kk))
            {
                return TensorStatus::AllocFailed;
            }
            tmp.resize(prows * kk);
            ttdetail::gemm_rm(static_cast<const T*>(work.data() + off[k - 1U]),
                              static_cast<const T*>(rt), tmp.data(), prows, rl, kk, alloc);
            T* dst = work.data() + off[k - 1U];
            for (crd::u64 i = 0; i < prows * kk; ++i)
            {
                dst[i] = tmp.data()[i];
            }
        }
        rk[k] = kk;
    }
    // ---- delta from the orthogonalized norm (= ||first core||_F) ---------
    const T nrm = ttdetail::fro_norm(work.data() + off[0], rk[0] * tt.shape(0) * rk[1]);
    const T delta = tol * nrm / std::sqrt(static_cast<T>(d - 1U));
    // ---- left-to-right SVD truncation ------------------------------------
    for (crd::u32 k = 0; k < d - 1U; ++k)
    {
        const crd::u64 m = rk[k] * tt.shape(k);
        const crd::u64 rr = rk[k + 1U];
        dn::Matrix<T> mat(alloc, static_cast<crd::usize>(m), static_cast<crd::usize>(rr));
        {
            const T* src = work.data() + off[k];
            for (crd::u64 i = 0; i < m; ++i)
            {
                for (crd::u64 j = 0; j < rr; ++j)
                {
                    mat.at(static_cast<crd::usize>(i), static_cast<crd::usize>(j)) = src[i * rr + j];
                }
            }
        }
        dn::SVD<T> f = dn::svd<T>(alloc, mat);
        const crd::u64 minmn = static_cast<crd::u64>(f.s.size());
        const crd::u64 r = ttdetail::rank_chop(f.s.data(), minmn, delta, max_rank);
        {
            T* dst = work.data() + off[k]; // core k := U(:, :r)
            for (crd::u64 i = 0; i < m; ++i)
            {
                for (crd::u64 j = 0; j < r; ++j)
                {
                    dst[i * r + j] = f.u.at(static_cast<crd::usize>(i), static_cast<crd::usize>(j));
                }
            }
        }
        {
            // carry = diag(s_r) V_r^T (r x rr); core k+1 := carry @ (unfold rr x n*r2)
            const crd::u64 ncols2 = tt.shape(k + 1U) * rk[k + 2U]; // k <= d-2 => k+2 <= d
            crd::containers::Array<T> cbuf(alloc);
            if (!cbuf.try_reserve(r * rr + r * ncols2))
            {
                return TensorStatus::AllocFailed;
            }
            cbuf.resize(r * rr + r * ncols2);
            T* carry = cbuf.data();
            T* prod = cbuf.data() + r * rr;
            for (crd::u64 i = 0; i < r; ++i)
            {
                const T si = f.s.data()[i];
                for (crd::u64 j = 0; j < rr; ++j)
                {
                    carry[i * rr + j] = si * f.v.at(static_cast<crd::usize>(j), static_cast<crd::usize>(i));
                }
            }
            ttdetail::gemm_rm(static_cast<const T*>(carry),
                              static_cast<const T*>(work.data() + off[k + 1U]), prod, r, rr, ncols2, alloc);
            T* dst = work.data() + off[k + 1U];
            for (crd::u64 i = 0; i < r * ncols2; ++i)
            {
                dst[i] = prod[i];
            }
        }
        rk[k + 1U] = r;
    }
    // ---- copy out ---------------------------------------------------------
    TtTensor<T> outp(alloc);
    const TensorStatus st = outp.init(tt.shape(), {rk, static_cast<crd::usize>(d) + 1U});
    if (st != TensorStatus::Ok)
    {
        return st;
    }
    for (crd::u32 k = 0; k < d; ++k)
    {
        const T* src = work.data() + off[k];
        T* dst = outp.core(k);
        for (crd::u64 i = 0; i < outp.core_size(k); ++i)
        {
            dst[i] = src[i];
        }
    }
    tt = static_cast<TtTensor<T>&&>(outp);
    return TensorStatus::Ok;
}

// -----------------------------------------------------------------------
// tt_add — C = A + B in TT format (block concatenation; structural ranks
// rC = rA + rB on interior edges). Round afterwards to re-compress.
// -----------------------------------------------------------------------
template <typename T>
[[nodiscard]] TensorStatus tt_add(crd::memory::IAllocator* alloc, const TtTensor<T>& a, const TtTensor<T>& b,
                                  TtTensor<T>& out) noexcept
{
    if (alloc == nullptr || a.dims() == 0U || a.dims() != b.dims())
    {
        return TensorStatus::BadInput;
    }
    const crd::u32 d = a.dims();
    for (crd::u32 k = 0; k < d; ++k)
    {
        if (a.shape(k) != b.shape(k))
        {
            return TensorStatus::ShapeMismatch;
        }
    }
    crd::u64 rk[kMaxRank + 1U];
    rk[0] = 1U;
    rk[d] = 1U;
    for (crd::u32 k = 1; k < d; ++k)
    {
        rk[k] = a.rank(k) + b.rank(k);
    }
    const TensorStatus st = out.init(a.shape(), {rk, static_cast<crd::usize>(d) + 1U});
    if (st != TensorStatus::Ok)
    {
        return st;
    }
    if (d == 1U)
    {
        for (crd::u64 i = 0; i < a.shape(0); ++i)
        {
            out.core(0)[i] = a.core(0)[i] + b.core(0)[i];
        }
        return TensorStatus::Ok;
    }
    for (crd::u32 k = 0; k < d; ++k)
    {
        const crd::u64 al = a.rank(k);
        const crd::u64 ar = a.rank(k + 1U);
        const crd::u64 bl = b.rank(k);
        const crd::u64 br = b.rank(k + 1U);
        const crd::u64 cl = k == 0U ? 1U : al + bl;
        const crd::u64 cr = k == d - 1U ? 1U : ar + br;
        const crd::u64 n = a.shape(k);
        T* dst = out.core(k);
        for (crd::u64 i = 0; i < cl * n * cr; ++i)
        {
            dst[i] = T(0);
        }
        const T* pa = a.core(k);
        const T* pb = b.core(k);
        for (crd::u64 x = 0; x < al; ++x) // A block at [0:al, :, 0:ar]
        {
            for (crd::u64 i = 0; i < n; ++i)
            {
                for (crd::u64 y = 0; y < ar; ++y)
                {
                    dst[(x * n + i) * cr + y] = pa[(x * n + i) * ar + y];
                }
            }
        }
        const crd::u64 xo = k == 0U ? 0U : al; // B block at [al:, :, ar:] (boundary-collapsed)
        const crd::u64 yo = k == d - 1U ? 0U : ar;
        for (crd::u64 x = 0; x < bl; ++x)
        {
            for (crd::u64 i = 0; i < n; ++i)
            {
                for (crd::u64 y = 0; y < br; ++y)
                {
                    dst[((xo + x) * n + i) * cr + (yo + y)] = pb[(x * n + i) * br + y];
                }
            }
        }
    }
    return TensorStatus::Ok;
}

// -----------------------------------------------------------------------
// tt_hadamard — C = A .* B in TT format (slice-wise Kronecker product;
// structural ranks rC = rA * rB). Round afterwards to re-compress.
// -----------------------------------------------------------------------
template <typename T>
[[nodiscard]] TensorStatus tt_hadamard(crd::memory::IAllocator* alloc, const TtTensor<T>& a,
                                       const TtTensor<T>& b, TtTensor<T>& out) noexcept
{
    if (alloc == nullptr || a.dims() == 0U || a.dims() != b.dims())
    {
        return TensorStatus::BadInput;
    }
    const crd::u32 d = a.dims();
    for (crd::u32 k = 0; k < d; ++k)
    {
        if (a.shape(k) != b.shape(k))
        {
            return TensorStatus::ShapeMismatch;
        }
    }
    crd::u64 rk[kMaxRank + 1U];
    for (crd::u32 k = 0; k <= d; ++k)
    {
        rk[k] = a.rank(k) * b.rank(k);
    }
    const TensorStatus st = out.init(a.shape(), {rk, static_cast<crd::usize>(d) + 1U});
    if (st != TensorStatus::Ok)
    {
        return st;
    }
    for (crd::u32 k = 0; k < d; ++k)
    {
        const crd::u64 al = a.rank(k);
        const crd::u64 ar = a.rank(k + 1U);
        const crd::u64 bl = b.rank(k);
        const crd::u64 br = b.rank(k + 1U);
        const crd::u64 n = a.shape(k);
        const T* pa = a.core(k);
        const T* pb = b.core(k);
        T* dst = out.core(k);
        for (crd::u64 i = 0; i < n; ++i) // per-slice Kronecker
        {
            for (crd::u64 x1 = 0; x1 < al; ++x1)
            {
                for (crd::u64 x2 = 0; x2 < bl; ++x2)
                {
                    const crd::u64 row = x1 * bl + x2;
                    for (crd::u64 y1 = 0; y1 < ar; ++y1)
                    {
                        const T av = pa[(x1 * n + i) * ar + y1];
                        for (crd::u64 y2 = 0; y2 < br; ++y2)
                        {
                            dst[(row * n + i) * (ar * br) + y1 * br + y2] =
                                av * pb[(x2 * n + i) * br + y2];
                        }
                    }
                }
            }
        }
    }
    return TensorStatus::Ok;
}

// -----------------------------------------------------------------------
// tt_dot — inner product <A, B> = sum over all indices of A .* B.
// Two gemms per core: O(d * n * r^3). tt_norm = sqrt(<A, A>).
// -----------------------------------------------------------------------
template <typename T>
[[nodiscard]] TensorStatus tt_dot(crd::memory::IAllocator* alloc, const TtTensor<T>& a, const TtTensor<T>& b,
                                  T& out) noexcept
{
    if (alloc == nullptr || a.dims() == 0U || a.dims() != b.dims())
    {
        return TensorStatus::BadInput;
    }
    const crd::u32 d = a.dims();
    crd::u64 mra = 1;
    crd::u64 mrb = 1;
    for (crd::u32 k = 0; k < d; ++k)
    {
        if (a.shape(k) != b.shape(k))
        {
            return TensorStatus::ShapeMismatch;
        }
        if (a.rank(k) > mra)
        {
            mra = a.rank(k);
        }
        if (b.rank(k) > mrb)
        {
            mrb = b.rank(k);
        }
    }
    crd::u64 maxn = 0;
    for (crd::u32 k = 0; k < d; ++k)
    {
        if (a.shape(k) > maxn)
        {
            maxn = a.shape(k);
        }
    }
    crd::containers::Array<T> buf(alloc);
    const crd::u64 vcap = mra * mrb;
    const crd::u64 t1cap = mrb * maxn * mra;
    if (!buf.try_reserve(vcap * 2U + t1cap))
    {
        return TensorStatus::AllocFailed;
    }
    buf.resize(vcap * 2U + t1cap);
    T* v = buf.data();          // (ra_l x rb_l)
    T* vn = buf.data() + vcap;  // (ra_r x rb_r)
    T* t1 = buf.data() + vcap * 2U;
    v[0] = T(1);
    for (crd::u32 k = 0; k < d; ++k)
    {
        const crd::u64 ral = a.rank(k);
        const crd::u64 rar = a.rank(k + 1U);
        const crd::u64 rbl = b.rank(k);
        const crd::u64 rbr = b.rank(k + 1U);
        const crd::u64 n = a.shape(k);
        // t1 = v^T (rbl x ral) @ A_k unfold (ral x n*rar)  -> (rbl x n*rar)
        {
            crd::hesap::dense::MatrixView<T, crd::hesap::dense::Layout::RowMajor> cv =
                ttdetail::mview_mut(t1, rbl, n * rar);
            crd::hesap::dense::gemm<T, crd::hesap::dense::Layout::RowMajor>(
                T(1), ttdetail::mview(v, ral, rbl), ttdetail::mview(a.core(k), ral, n * rar), T(0), cv,
                crd::hesap::dense::Trans::Transpose, crd::hesap::dense::Trans::None, alloc);
        }
        // vn = t1 viewed (rbl*n x rar)^T @ B_k unfold (rbl*n x rbr) -> (rar x rbr)
        {
            crd::hesap::dense::MatrixView<T, crd::hesap::dense::Layout::RowMajor> cv =
                ttdetail::mview_mut(vn, rar, rbr);
            crd::hesap::dense::gemm<T, crd::hesap::dense::Layout::RowMajor>(
                T(1), ttdetail::mview(t1, rbl * n, rar), ttdetail::mview(b.core(k), rbl * n, rbr), T(0), cv,
                crd::hesap::dense::Trans::Transpose, crd::hesap::dense::Trans::None, alloc);
        }
        T* tmp = v;
        v = vn;
        vn = tmp;
    }
    out = v[0];
    return TensorStatus::Ok;
}

template <typename T>
[[nodiscard]] TensorStatus tt_norm(crd::memory::IAllocator* alloc, const TtTensor<T>& a, T& out) noexcept
{
    T dot = T(0);
    const TensorStatus st = tt_dot(alloc, a, a, dot);
    if (st != TensorStatus::Ok)
    {
        return st;
    }
    out = dot > T(0) ? std::sqrt(dot) : T(0);
    return TensorStatus::Ok;
}

// -----------------------------------------------------------------------
// tt_contract — materialize the TT into a dense (row-major) Tensor.
// One gemm per core: P (M x r_k) @ unfold_k (r_k x n_k*r_{k+1}).
// -----------------------------------------------------------------------
template <typename T>
[[nodiscard]] TensorStatus tt_contract(crd::memory::IAllocator* alloc, const TtTensor<T>& a,
                                       Tensor<T>& out) noexcept
{
    if (alloc == nullptr || a.dims() == 0U)
    {
        return TensorStatus::BadInput;
    }
    const crd::u32 d = a.dims();
    TensorStatus st = out.resize(a.shape());
    if (st != TensorStatus::Ok)
    {
        return st;
    }
    // ping-pong buffers sized to the largest intermediate (prefix M * r)
    crd::u64 maxint = a.shape(0) * a.rank(1);
    {
        crd::u64 m = a.shape(0);
        for (crd::u32 k = 1; k < d; ++k)
        {
            m *= a.shape(k);
            const crd::u64 sz = m * a.rank(k + 1U);
            if (sz > maxint)
            {
                maxint = sz;
            }
        }
    }
    crd::containers::Array<T> buf(alloc);
    if (!buf.try_reserve(maxint * 2U))
    {
        return TensorStatus::AllocFailed;
    }
    buf.resize(maxint * 2U);
    T* cur = buf.data();
    T* nxt = buf.data() + maxint;
    crd::u64 m = a.shape(0);
    crd::u64 r = a.rank(1);
    for (crd::u64 i = 0; i < m * r; ++i)
    {
        cur[i] = a.core(0)[i];
    }
    for (crd::u32 k = 1; k < d; ++k)
    {
        const crd::u64 n = a.shape(k);
        const crd::u64 rn = a.rank(k + 1U);
        ttdetail::gemm_rm(static_cast<const T*>(cur), a.core(k), nxt, m, r, n * rn, alloc);
        m *= n;
        r = rn;
        T* tmp = cur;
        cur = nxt;
        nxt = tmp;
    }
    for (crd::u64 i = 0; i < m; ++i)
    {
        out.data()[i] = cur[i];
    }
    return TensorStatus::Ok;
}

// -----------------------------------------------------------------------
// tt_eval — evaluate a single element. ALLOCATION-FREE: caller workspace of
// size >= tt_eval_workspace(tt) == 2 * max_rank(tt) (checked by assert; the
// formula is part of the contract). Left-to-right row-vector chain:
// v <- v @ G_k[:, i_k, :]. noexcept, no allocator anywhere on the path.
// -----------------------------------------------------------------------
template <typename T> [[nodiscard]] crd::u64 tt_eval_workspace(const TtTensor<T>& tt) noexcept
{
    return 2U * tt.max_rank();
}

template <typename T>
[[nodiscard]] T tt_eval(const TtTensor<T>& tt, crd::containers::ConstSpan<crd::u64> idx,
                        crd::containers::Span<T> work) noexcept
{
    const crd::u32 d = tt.dims();
    CRD_ASSERT_MSG(idx.size() == d, "tt_eval: index rank mismatch");
    CRD_ASSERT_MSG(work.size() >= tt_eval_workspace(tt), "tt_eval: workspace too small (2*max_rank)");
    const crd::u64 mr = tt.max_rank();
    T* v = work.data();
    T* w = work.data() + mr;
    {
        CRD_ASSERT_MSG(idx[0] < tt.shape(0), "tt_eval: index out of range");
        const crd::u64 r1 = tt.rank(1);
        const T* g = tt.core(0) + idx[0] * r1; // (1, n0, r1): row i0
        for (crd::u64 j = 0; j < r1; ++j)
        {
            v[j] = g[j];
        }
    }
    for (crd::u32 k = 1; k < d; ++k)
    {
        CRD_ASSERT_MSG(idx[k] < tt.shape(k), "tt_eval: index out of range");
        const crd::u64 rl = tt.rank(k);
        const crd::u64 rr = tt.rank(k + 1U);
        const crd::u64 n = tt.shape(k);
        const T* g = tt.core(k) + idx[k] * rr; // slice row a: g + a*n*rr
        for (crd::u64 j = 0; j < rr; ++j)
        {
            T s = T(0);
            for (crd::u64 x = 0; x < rl; ++x)
            {
                s = std::fma(v[x], g[x * n * rr + j], s);
            }
            w[j] = s;
        }
        T* tmp = v;
        v = w;
        w = tmp;
    }
    return v[0];
}

// Batched span evaluator: idx_flat = npts * dims() indices (row-major
// points); out receives npts values. ALLOCATION-FREE (same workspace,
// reused across points). Returns BadInput on size mismatches.
template <typename T>
[[nodiscard]] TensorStatus tt_eval_many(const TtTensor<T>& tt, crd::containers::ConstSpan<crd::u64> idx_flat,
                                        crd::containers::Span<T> out,
                                        crd::containers::Span<T> work) noexcept
{
    const crd::u32 d = tt.dims();
    if (d == 0U || idx_flat.size() != out.size() * d || work.size() < tt_eval_workspace(tt))
    {
        return TensorStatus::BadInput;
    }
    const crd::u64 npts = out.size();
    for (crd::u64 p = 0; p < npts; ++p)
    {
        out[p] = tt_eval(tt, {idx_flat.data() + p * d, d}, work);
    }
    return TensorStatus::Ok;
}

// -----------------------------------------------------------------------
// tt_eval_lerp — multilinear-interpolated point evaluation: cell base index
// i0[k] (i0[k]+1 < shape(k) required unless w[k] == 0) + fractional weights
// w[k] in [0,1]. EQUALS multilinear interpolation of the dense grid (the
// interpolation functional is a tensor product of per-dim linear maps, which
// factors through the cores) — gated. ALLOCATION-FREE, same workspace
// formula. The v13-interp LUT hot path: d fused slice-blend matvecs.
// -----------------------------------------------------------------------
template <typename T>
[[nodiscard]] T tt_eval_lerp(const TtTensor<T>& tt, crd::containers::ConstSpan<crd::u64> i0,
                             crd::containers::ConstSpan<T> w, crd::containers::Span<T> work) noexcept
{
    const crd::u32 d = tt.dims();
    CRD_ASSERT_MSG(i0.size() == d && w.size() == d, "tt_eval_lerp: index/weight rank mismatch");
    CRD_ASSERT_MSG(work.size() >= tt_eval_workspace(tt), "tt_eval_lerp: workspace too small (2*max_rank)");
    const crd::u64 mr = tt.max_rank();
    T* v = work.data();
    T* wk = work.data() + mr;
    {
        const crd::u64 r1 = tt.rank(1);
        const crd::u64 i = i0[0];
        const T t = w[0];
        CRD_ASSERT_MSG(i < tt.shape(0) && (t == T(0) || i + 1U < tt.shape(0)),
                       "tt_eval_lerp: cell out of range");
        const T* g0 = tt.core(0) + i * r1;
        const T* g1 = t == T(0) ? g0 : g0 + r1;
        for (crd::u64 j = 0; j < r1; ++j)
        {
            v[j] = std::fma(t, g1[j] - g0[j], g0[j]);
        }
    }
    for (crd::u32 k = 1; k < d; ++k)
    {
        const crd::u64 rl = tt.rank(k);
        const crd::u64 rr = tt.rank(k + 1U);
        const crd::u64 n = tt.shape(k);
        const crd::u64 i = i0[k];
        const T t = w[k];
        CRD_ASSERT_MSG(i < n && (t == T(0) || i + 1U < n), "tt_eval_lerp: cell out of range");
        const T* g0 = tt.core(k) + i * rr;
        const T* g1 = t == T(0) ? g0 : g0 + rr;
        for (crd::u64 j = 0; j < rr; ++j)
        {
            T s = T(0);
            for (crd::u64 x = 0; x < rl; ++x)
            {
                const T a0 = g0[x * n * rr + j];
                const T blended = std::fma(t, g1[x * n * rr + j] - a0, a0);
                s = std::fma(v[x], blended, s);
            }
            wk[j] = s;
        }
        T* tmp = v;
        v = wk;
        wk = tmp;
    }
    return v[0];
}

namespace ttdetail
{

// TT-cross scratch geometry: index-set offsets for the flat lset/rset pools
// (fixed ranks => fixed sizes; buffers are pre-sized ONCE before any span is
// taken — the reserve-before-spans rule).
struct CrossLayout
{
    crd::u64 rs[kMaxRank + 1U];      // clamped TT ranks
    crd::u64 lset_off[kMaxRank + 1U]; // lsets[j]: rs[j] rows of length j
    crd::u64 rset_off[kMaxRank + 1U]; // rsets[j]: rs[j+1] rows of length d-1-j
    crd::u64 core_off[kMaxRank + 1U]; // cores[j]: rs[j]*n_j*rs[j+1]
    crd::u64 lset_total = 0;
    crd::u64 rset_total = 0;
    crd::u64 core_total = 0;
    crd::u64 max_fiber = 0;          // max_j rs[j]*n_j*rs[j+1]
    crd::u64 max_rank = 0;
};

inline void cross_layout(crd::containers::ConstSpan<crd::u64> shape, crd::u64 max_rank,
                         CrossLayout& lay) noexcept
{
    const crd::u32 d = static_cast<crd::u32>(shape.size());
    lay.rs[0] = 1U;
    lay.rs[d] = 1U;
    for (crd::u32 k = 1; k < d; ++k)
    {
        lay.rs[k] = max_rank;
    }
    for (crd::u32 k = 1; k < d; ++k) // clamp L2R then R2L (the tntorch rule)
    {
        const crd::u64 cap = lay.rs[k - 1U] * shape[k - 1U];
        if (lay.rs[k] > cap)
        {
            lay.rs[k] = cap;
        }
    }
    for (crd::u32 k = d - 1U; k >= 1U; --k)
    {
        const crd::u64 cap = shape[k] * lay.rs[k + 1U];
        if (lay.rs[k] > cap)
        {
            lay.rs[k] = cap;
        }
    }
    lay.lset_total = 0;
    lay.rset_total = 0;
    lay.core_total = 0;
    lay.max_fiber = 0;
    lay.max_rank = 1;
    for (crd::u32 j = 0; j < d; ++j)
    {
        lay.lset_off[j] = lay.lset_total;
        lay.lset_total += lay.rs[j] * j;
        lay.rset_off[j] = lay.rset_total;
        lay.rset_total += lay.rs[j + 1U] * (d - 1U - j);
        lay.core_off[j] = lay.core_total;
        const crd::u64 fib = lay.rs[j] * shape[j] * lay.rs[j + 1U];
        lay.core_total += fib;
        if (fib > lay.max_fiber)
        {
            lay.max_fiber = fib;
        }
        if (lay.rs[j + 1U] > lay.max_rank)
        {
            lay.max_rank = lay.rs[j + 1U];
        }
    }
    lay.lset_off[d] = lay.lset_total;
    lay.rset_off[d] = lay.rset_total;
    lay.core_off[d] = lay.core_total;
}

} // namespace ttdetail

// -----------------------------------------------------------------------
// tt_cross — build a TT approximation of f over an integer index grid WITHOUT
// materializing the tensor. f: callable T(ConstSpan<u64> idx) with
// idx.size() == shape.size(). Fixed-rank ALS sweeps with QR + maxvol pivot
// selection (the tntorch/cross.py scheme, oracle-verified):
//   left-to-right:  fibers -> left-unfold QR -> maxvol -> core = Q*Qhat^-1,
//                   nested left index sets grow one mode;
//   right-to-left:  mirrored on the right unfolding;
//   first core = raw fibers (the cross interpolation is exact on the sets).
// Deterministic: initial right sets from PhiloxRng(seed, stream 0), the
// validation set from PhiloxRng(seed, stream 1) — same seed => bit-identical
// TT (gated). BOUNDED: max_sweeps sweep pairs; converged = validation
// relative error < tol (info->converged; the status stays Ok — the
// batched_svd_small info precedent, TensorStatus is frozen this slice).
// -----------------------------------------------------------------------
template <typename T, typename F>
[[nodiscard]] TensorStatus tt_cross(crd::memory::IAllocator* alloc, crd::containers::ConstSpan<crd::u64> shape,
                                    F&& f, const TtCrossParams<T>& params, TtTensor<T>& out,
                                    TtCrossInfo<T>* info) noexcept
{
    namespace dn = crd::hesap::dense;
    if (alloc == nullptr || shape.size() == 0U || shape.size() > kMaxRank || params.max_rank == 0U ||
        params.max_sweeps == 0U || params.val_size == 0U || !(params.tol > T(0)))
    {
        return TensorStatus::BadInput;
    }
    const crd::u32 d = static_cast<crd::u32>(shape.size());
    for (crd::u32 k = 0; k < d; ++k)
    {
        if (shape[k] == 0U)
        {
            return TensorStatus::BadInput;
        }
    }
    TtCrossInfo<T> local;
    ttdetail::CrossLayout lay;
    ttdetail::cross_layout(shape, params.max_rank, lay);
    // ---- pools (pre-sized ONCE; reserve-before-spans) ---------------------
    crd::containers::Array<crd::u64> ipool(alloc);
    const crd::u64 val_idx_total = params.val_size * d;
    if (!ipool.try_reserve(lay.lset_total + lay.rset_total + val_idx_total + kMaxRank + lay.max_rank))
    {
        return TensorStatus::AllocFailed;
    }
    ipool.resize(lay.lset_total + lay.rset_total + val_idx_total + kMaxRank + lay.max_rank);
    crd::u64* lsets = ipool.data();
    crd::u64* rsets = ipool.data() + lay.lset_total;
    crd::u64* val_idx = rsets + lay.rset_total;
    crd::u64* idxbuf = val_idx + val_idx_total;
    crd::u64* selbuf = idxbuf + kMaxRank;
    crd::containers::Array<T> fpool(alloc);
    const crd::u64 qcap = lay.max_fiber;  // thin Q (rows x r): rows*r == fiber size
    const crd::u64 btcap = lay.max_fiber; // solve RHS (r x rows) / transposed fiber
    const crd::u64 fpool_total = lay.core_total + lay.max_fiber + qcap + btcap + params.val_size * 2U +
                                 2U * lay.max_rank + lay.max_fiber /*colbuf*/;
    if (!fpool.try_reserve(fpool_total))
    {
        return TensorStatus::AllocFailed;
    }
    fpool.resize(fpool_total);
    T* cores = fpool.data();
    T* fiber = cores + lay.core_total;
    T* qbuf = fiber + lay.max_fiber;
    T* solvebuf = qbuf + qcap;
    T* val_true = solvebuf + btcap;
    T* val_pred = val_true + params.val_size;
    T* evwork = val_pred + params.val_size;
    T* colbuf = evwork + 2U * lay.max_rank;
    // ---- deterministic starts: nested random right sets -------------------
    {
        crd::hesap::stats::PhiloxRng rng(params.seed, 0);
        // the shared random matrix (maxR rows x d cols; col n ~ U[0, shape[n+1]))
        // materialized column-nested exactly like the oracle: rsets[j] row b =
        // randmat[b][j .. d-2]
        crd::u64 randmat[kMaxRank]; // one row at a time
        for (crd::u64 b = 0; b < lay.max_rank; ++b)
        {
            for (crd::u32 n = 0; n + 1U < d; ++n)
            {
                randmat[n] = rng.next_below(shape[n + 1U]);
            }
            for (crd::u32 j = 0; j + 1U < d; ++j)
            {
                if (b < lay.rs[j + 1U])
                {
                    const crd::u64 cols = d - 1U - j;
                    for (crd::u64 t = 0; t < cols; ++t)
                    {
                        rsets[lay.rset_off[j] + b * cols + t] = randmat[j + t];
                    }
                }
            }
        }
    }
    // ---- deterministic validation set -------------------------------------
    {
        crd::hesap::stats::PhiloxRng rng(params.seed, 1);
        for (crd::u64 p = 0; p < params.val_size; ++p)
        {
            for (crd::u32 k = 0; k < d; ++k)
            {
                val_idx[p * d + k] = rng.next_below(shape[k]);
            }
        }
        for (crd::u64 p = 0; p < params.val_size; ++p)
        {
            val_true[p] = f(crd::containers::ConstSpan<crd::u64>{val_idx + p * d, d});
        }
        local.val_evals = params.val_size;
    }
    T val_norm = ttdetail::fro_norm(val_true, params.val_size);
    if (val_norm == T(0))
    {
        val_norm = T(1);
    }
    // ---- fiber evaluation (idx = lset row ++ i ++ rset row) ---------------
    const auto eval_fibers = [&](crd::u32 j) noexcept
    {
        const crd::u64 rl = lay.rs[j];
        const crd::u64 n = shape[j];
        const crd::u64 rr = lay.rs[j + 1U];
        const crd::u64 rcols = d - 1U - j;
        for (crd::u64 a2 = 0; a2 < rl; ++a2)
        {
            const crd::u64* lrow = lsets + lay.lset_off[j] + a2 * j;
            for (crd::u64 t = 0; t < j; ++t)
            {
                idxbuf[t] = lrow[t];
            }
            for (crd::u64 i = 0; i < n; ++i)
            {
                idxbuf[j] = i;
                for (crd::u64 b = 0; b < rr; ++b)
                {
                    const crd::u64* rrow = rsets + lay.rset_off[j] + b * rcols;
                    for (crd::u64 t = 0; t < rcols; ++t)
                    {
                        idxbuf[j + 1U + t] = rrow[t];
                    }
                    fiber[(a2 * n + i) * rr + b] =
                        f(crd::containers::ConstSpan<crd::u64>{idxbuf, d});
                }
            }
        }
        local.evals += rl * n * rr;
    };
    // thin-QR of an (m x r) buffer, m >= r, into qbuf (m x r orthonormal cols)
    const auto thin_q = [&](const T* m, crd::u64 rows, crd::u64 r) noexcept -> TensorStatus
    {
        dn::QR<T> qr(alloc, static_cast<crd::usize>(rows), static_cast<crd::usize>(r));
        dn::Matrix<T>& p = qr.packed();
        for (crd::u64 i = 0; i < rows; ++i)
        {
            for (crd::u64 j2 = 0; j2 < r; ++j2)
            {
                p.at(static_cast<crd::usize>(i), static_cast<crd::usize>(j2)) = m[i * r + j2];
            }
        }
        dn::factor_qr(qr);
        ttdetail::form_thin_q(qr, qbuf, rows, r, colbuf);
        return TensorStatus::Ok;
    };
    // core := Q @ inv(Q[sel]) via LU solve of Qsel^T X = Q^T (recomputed, not
    // the maxvol-iterated coefficients — the tntorch lstsq accuracy choice)
    const auto interp_core = [&](crd::u64 rows, crd::u64 r, T* dst) noexcept -> TensorStatus
    {
        dn::LU<T> lu(alloc, static_cast<crd::usize>(r));
        dn::Matrix<T>& p = lu.packed();
        for (crd::u64 i = 0; i < r; ++i)
        {
            for (crd::u64 j2 = 0; j2 < r; ++j2)
            {
                // Qsel^T: entry (i, j2) = Q[sel[j2]][i]
                p.at(static_cast<crd::usize>(i), static_cast<crd::usize>(j2)) = qbuf[selbuf[j2] * r + i];
            }
        }
        dn::factor_lu(lu, alloc);
        if (lu.info() != 0U)
        {
            return TensorStatus::Unsupported; // maxvol guarantees nonsingular; defensive
        }
        for (crd::u64 i = 0; i < r; ++i) // B = Q^T (r x rows)
        {
            for (crd::u64 t = 0; t < rows; ++t)
            {
                solvebuf[i * rows + t] = qbuf[t * r + i];
            }
        }
        dn::MatrixView<T, dn::Layout::RowMajor> bview = ttdetail::mview_mut(solvebuf, r, rows);
        dn::solve_lu(lu, bview);
        for (crd::u64 t = 0; t < rows; ++t) // dst = X^T (rows x r)
        {
            for (crd::u64 i = 0; i < r; ++i)
            {
                dst[t * r + i] = solvebuf[i * rows + t];
            }
        }
        return TensorStatus::Ok;
    };
    // ---- sweeps ------------------------------------------------------------
    TensorStatus st = TensorStatus::Ok;
    for (crd::u32 sweep = 0; sweep < params.max_sweeps && !local.converged; ++sweep)
    {
        // left-to-right: set cores 0..d-2, grow lsets 1..d-1
        for (crd::u32 j = 0; j + 1U < d; ++j)
        {
            eval_fibers(j);
            const crd::u64 rl = lay.rs[j];
            const crd::u64 n = shape[j];
            const crd::u64 rr = lay.rs[j + 1U];
            const crd::u64 rows = rl * n;
            st = thin_q(fiber, rows, rr);
            if (st != TensorStatus::Ok)
            {
                return st;
            }
            MaxvolInfo mvi;
            st = maxvol<T>(alloc, qbuf, rows, rr, T(1.05), 200U,
                           crd::containers::Span<crd::u64>{selbuf, static_cast<crd::usize>(rr)}, nullptr,
                           &mvi);
            if (st != TensorStatus::Ok)
            {
                return st;
            }
            st = interp_core(rows, rr, cores + lay.core_off[j]);
            if (st != TensorStatus::Ok)
            {
                return st;
            }
            // lsets[j+1] row s = lsets[j][sel/n] ++ (sel % n)
            for (crd::u64 s = 0; s < rr; ++s)
            {
                const crd::u64 a2 = selbuf[s] / n;
                const crd::u64 i = selbuf[s] % n;
                const crd::u64* srcrow = lsets + lay.lset_off[j] + a2 * j;
                crd::u64* dstrow = lsets + lay.lset_off[j + 1U] + s * (j + 1U);
                for (crd::u64 t = 0; t < j; ++t)
                {
                    dstrow[t] = srcrow[t];
                }
                dstrow[j] = i;
            }
        }
        // right-to-left: set cores d-1..1, grow rsets d-2..0
        for (crd::u32 j = d - 1U; j >= 1U; --j)
        {
            eval_fibers(j);
            const crd::u64 rl = lay.rs[j];
            const crd::u64 n = shape[j];
            const crd::u64 rr = lay.rs[j + 1U];
            const crd::u64 rows = n * rr;
            // right unfolding transposed: (n*rr x rl); fiber is (rl x n*rr)
            for (crd::u64 a2 = 0; a2 < rl; ++a2)
            {
                for (crd::u64 t = 0; t < rows; ++t)
                {
                    solvebuf[t * rl + a2] = fiber[a2 * rows + t];
                }
            }
            st = thin_q(solvebuf, rows, rl);
            if (st != TensorStatus::Ok)
            {
                return st;
            }
            MaxvolInfo mvi;
            st = maxvol<T>(alloc, qbuf, rows, rl, T(1.05), 200U,
                           crd::containers::Span<crd::u64>{selbuf, static_cast<crd::usize>(rl)}, nullptr,
                           &mvi);
            if (st != TensorStatus::Ok)
            {
                return st;
            }
            // core j = (Q inv(Q[sel]))^T -> (rl x n*rr) directly
            {
                dn::LU<T> lu(alloc, static_cast<crd::usize>(rl));
                dn::Matrix<T>& p = lu.packed();
                for (crd::u64 i = 0; i < rl; ++i)
                {
                    for (crd::u64 j2 = 0; j2 < rl; ++j2)
                    {
                        p.at(static_cast<crd::usize>(i), static_cast<crd::usize>(j2)) =
                            qbuf[selbuf[j2] * rl + i];
                    }
                }
                dn::factor_lu(lu, alloc);
                if (lu.info() != 0U)
                {
                    return TensorStatus::Unsupported;
                }
                T* dst = cores + lay.core_off[j];
                for (crd::u64 i = 0; i < rl; ++i) // RHS = Q^T (rl x rows)
                {
                    for (crd::u64 t = 0; t < rows; ++t)
                    {
                        dst[i * rows + t] = qbuf[t * rl + i];
                    }
                }
                dn::MatrixView<T, dn::Layout::RowMajor> bview = ttdetail::mview_mut(dst, rl, rows);
                dn::solve_lu(lu, bview);
            }
            // rsets[j-1] row s = (sel / rr) ++ rsets[j][sel % rr]
            const crd::u64 rcols = d - 1U - j;
            for (crd::u64 s = 0; s < rl; ++s)
            {
                const crd::u64 i = selbuf[s] / rr;
                const crd::u64 b = selbuf[s] % rr;
                const crd::u64* srcrow = rsets + lay.rset_off[j] + b * rcols;
                crd::u64* dstrow = rsets + lay.rset_off[j - 1U] + s * (rcols + 1U);
                dstrow[0] = i;
                for (crd::u64 t = 0; t < rcols; ++t)
                {
                    dstrow[1U + t] = srcrow[t];
                }
            }
        }
        // first core = raw fibers at the final left/right sets
        eval_fibers(0);
        {
            T* dst = cores + lay.core_off[0];
            const crd::u64 cs = lay.rs[0] * shape[0] * lay.rs[1];
            for (crd::u64 i = 0; i < cs; ++i)
            {
                dst[i] = fiber[i];
            }
        }
        local.sweeps = sweep + 1U;
        // validation error via the (not yet copied-out) cores
        {
            T errsq = T(0);
            for (crd::u64 p = 0; p < params.val_size; ++p)
            {
                const crd::u64* ix = val_idx + p * d;
                T* v = evwork;
                T* w = evwork + lay.max_rank;
                const crd::u64 r1 = lay.rs[1];
                const T* g = cores + lay.core_off[0] + ix[0] * r1;
                for (crd::u64 t = 0; t < r1; ++t)
                {
                    v[t] = g[t];
                }
                for (crd::u32 k = 1; k < d; ++k)
                {
                    const crd::u64 rl = lay.rs[k];
                    const crd::u64 rr = lay.rs[k + 1U];
                    const crd::u64 n = shape[k];
                    const T* gk = cores + lay.core_off[k] + ix[k] * rr;
                    for (crd::u64 t = 0; t < rr; ++t)
                    {
                        T s = T(0);
                        for (crd::u64 x = 0; x < rl; ++x)
                        {
                            s = std::fma(v[x], gk[x * n * rr + t], s);
                        }
                        w[t] = s;
                    }
                    T* tmp = v;
                    v = w;
                    w = tmp;
                }
                const T dv = v[0] - val_true[p];
                errsq = std::fma(dv, dv, errsq);
            }
            local.val_error = std::sqrt(errsq) / val_norm;
            if (local.val_error < params.tol)
            {
                local.converged = true;
            }
        }
    }
    // ---- copy out ----------------------------------------------------------
    st = out.init(shape, {lay.rs, static_cast<crd::usize>(d) + 1U});
    if (st != TensorStatus::Ok)
    {
        return st;
    }
    for (crd::u32 k = 0; k < d; ++k)
    {
        const T* src = cores + lay.core_off[k];
        T* dst = out.core(k);
        for (crd::u64 i = 0; i < out.core_size(k); ++i)
        {
            dst[i] = src[i];
        }
    }
    if (info != nullptr)
    {
        *info = local;
    }
    return TensorStatus::Ok;
}

} // namespace crd::hesap::tensor
