// v14-b gates: the elementwise + broadcasting engine is BIT-EXACT vs NumPy
// (ref_elementwise.inc, generated by scripts/v14b_elementwise_corpus.py) on a
// broadcast/stride-adversarial corpus: 4-D broadcasting across all six binary
// ops (incl. div-by-zero → inf), strided/sliced sources, rank-0 scalars,
// sign-bit neg/abs (±0 + NaN payloads), compare + three-way-broadcast where,
// and f32↔f64 casts (RNE overflow → inf). Plus status-contract adversaries.

#include "ref_elementwise.inc"

#include <crd/hesap/tensor/elementwise.hpp>
#include <crd/memory/allocators/tlsf_allocator.hpp>

#include <bit>
#include <catch2/catch_test_macros.hpp>

using namespace crd::hesap::tensor;

namespace
{

template <typename T> struct BitsOf;
template <> struct BitsOf<crd::f64>
{
    using B = crd::u64;
};
template <> struct BitsOf<crd::f32>
{
    using B = crd::u32;
};

// Load a corpus bit array into an owning tensor of the given shape.
template <typename T, typename BitT>
Tensor<T> from_bits(crd::memory::IAllocator* alloc, crd::containers::ConstSpan<crd::u64> shape, const BitT* bits)
{
    Tensor<T> t(alloc, shape);
    for (crd::u64 i = 0; i < t.size(); ++i)
    {
        t.data()[i] = std::bit_cast<T>(bits[i]);
    }
    return t;
}

template <typename T, typename BitT> void check_bits(const Tensor<T>& t, const BitT* expected)
{
    for (crd::u64 i = 0; i < t.size(); ++i)
    {
        INFO("element " << i);
        CHECK(std::bit_cast<BitT>(t.data()[i]) == expected[i]);
    }
}

} // namespace

TEST_CASE("v14-b elementwise: 4-D broadcast binaries are bit-exact vs NumPy", "[hesap][tensor][v14][elementwise]")
{
    crd::memory::TlsfAllocator alloc(1U << 22U);
    const crd::u64 sa[] = {2U, 3U, 1U, 4U};
    const crd::u64 sb[] = {3U, 5U, 1U};
    const crd::u64 so[] = {2U, 3U, 5U, 4U};
    Tensor<crd::f64> a = from_bits<crd::f64>(&alloc, sa, kEwA1);
    Tensor<crd::f64> b = from_bits<crd::f64>(&alloc, sb, kEwB1);
    Tensor<crd::f64> r(&alloc, so);

    struct Row
    {
        BinaryOp op;
        const crd::u64* expected;
    };
    const Row rows[] = {{BinaryOp::Add, kEwR1Add}, {BinaryOp::Sub, kEwR1Sub}, {BinaryOp::Mul, kEwR1Mul},
                        {BinaryOp::Div, kEwR1Div}, {BinaryOp::Min, kEwR1Min}, {BinaryOp::Max, kEwR1Max}};
    for (const Row& row : rows)
    {
        INFO("op " << static_cast<int>(row.op));
        REQUIRE(ew_binary(row.op, TensorView<const crd::f64>(a.view()), TensorView<const crd::f64>(b.view()),
                          r.view()) == TensorStatus::Ok);
        check_bits(r, row.expected);
    }

    // broadcast_shapes rejects an incompatible pair with a status.
    const crd::u64 bad[] = {2U, 3U};
    crd::u64 out[kMaxRank];
    crd::u32 rank = 0;
    CHECK(broadcast_shapes({sa, 4U}, {bad, 2U}, {out, kMaxRank}, rank) == TensorStatus::ShapeMismatch);
}

TEST_CASE("v14-b elementwise: strided views + rank-0 scalar broadcast (f32)", "[hesap][tensor][v14][elementwise]")
{
    crd::memory::TlsfAllocator alloc(1U << 22U);
    const crd::u64 base_shape[] = {6U, 8U};
    Tensor<crd::f32> base = from_bits<crd::f32>(&alloc, base_shape, kEwA2);
    // a2[::2, 1:7] — the same view the corpus took.
    TensorView<const crd::f32> av = base.view().slice(0U, 0U, 6U, 2U).slice(1U, 1U, 7U);

    // rank-0 scalar operand
    Tensor<crd::f32> s(&alloc, {});
    s.data()[0] = 2.5F;
    const crd::u64 so[] = {3U, 6U};
    Tensor<crd::f32> r(&alloc, so);
    REQUIRE(ew_binary(BinaryOp::Mul, av, TensorView<const crd::f32>(s.view()), r.view()) == TensorStatus::Ok);
    check_bits(r, kEwR2MulScalar);

    // (3,6) + (6,) row broadcast
    const crd::u64 sc[] = {6U};
    Tensor<crd::f32> c = from_bits<crd::f32>(&alloc, sc, kEwC2);
    REQUIRE(ew_binary(BinaryOp::Add, av, TensorView<const crd::f32>(c.view()), r.view()) == TensorStatus::Ok);
    check_bits(r, kEwR2AddRow);
}

TEST_CASE("v14-b elementwise: neg/abs are sign-bit exact (+-0, NaN payloads)", "[hesap][tensor][v14][elementwise]")
{
    crd::memory::TlsfAllocator alloc(1U << 20U);
    const crd::u64 s9[] = {9U};
    Tensor<crd::f32> a = from_bits<crd::f32>(&alloc, s9, kEwA3);
    Tensor<crd::f32> r(&alloc, s9);
    REQUIRE(ew_unary(UnaryOp::Neg, TensorView<const crd::f32>(a.view()), r.view()) == TensorStatus::Ok);
    check_bits(r, kEwR3Neg);
    REQUIRE(ew_unary(UnaryOp::Abs, TensorView<const crd::f32>(a.view()), r.view()) == TensorStatus::Ok);
    check_bits(r, kEwR3Abs);
}

TEST_CASE("v14-b elementwise: compare + three-way-broadcast where (f64)", "[hesap][tensor][v14][elementwise]")
{
    crd::memory::TlsfAllocator alloc(1U << 20U);
    const crd::u64 sa[] = {4U, 1U};
    const crd::u64 sb[] = {1U, 5U};
    const crd::u64 so[] = {4U, 5U};
    Tensor<crd::f64> a = from_bits<crd::f64>(&alloc, sa, kEwA4);
    Tensor<crd::f64> b = from_bits<crd::f64>(&alloc, sb, kEwB4);

    Tensor<crd::u8> m(&alloc, so);
    REQUIRE(ew_compare(CompareOp::Lt, TensorView<const crd::f64>(a.view()), TensorView<const crd::f64>(b.view()),
                       m.view()) == TensorStatus::Ok);
    for (crd::u64 i = 0; i < m.size(); ++i)
    {
        INFO("mask " << i);
        CHECK(m.data()[i] == kEwR4Lt[i]);
    }

    Tensor<crd::f64> w(&alloc, so);
    REQUIRE(ew_where(TensorView<const crd::u8>(m.view()), TensorView<const crd::f64>(a.view()),
                     TensorView<const crd::f64>(b.view()), w.view()) == TensorStatus::Ok);
    check_bits(w, kEwR4Where);
}

TEST_CASE("v14-b elementwise: f32<->f64 casts (RNE narrowing, exact widening)", "[hesap][tensor][v14][elementwise]")
{
    crd::memory::TlsfAllocator alloc(1U << 20U);
    const crd::u64 s7[] = {7U};
    Tensor<crd::f64> a = from_bits<crd::f64>(&alloc, s7, kEwA5);
    Tensor<crd::f32> n(&alloc, s7);
    REQUIRE(ew_cast(TensorView<const crd::f64>(a.view()), n.view()) == TensorStatus::Ok);
    check_bits(n, kEwR5Cast32);

    Tensor<crd::f64> wgt(&alloc, s7);
    REQUIRE(ew_cast(TensorView<const crd::f32>(n.view()), wgt.view()) == TensorStatus::Ok);
    check_bits(wgt, kEwR5Cast64);
}

TEST_CASE("v14-b elementwise: status contract + collapse correctness + determinism",
          "[hesap][tensor][v14][elementwise]")
{
    crd::memory::TlsfAllocator alloc(1U << 22U);
    const crd::u64 s2[] = {4U, 6U};
    Tensor<crd::f64> a(&alloc, s2);
    Tensor<crd::f64> b(&alloc, s2);
    for (crd::u64 i = 0; i < 24U; ++i)
    {
        a.data()[i] = 0.25 * static_cast<crd::f64>(i) - 2.0;
        b.data()[i] = 1.5 - 0.125 * static_cast<crd::f64>(i);
    }

    // Wrong dst shape / non-contiguous dst are statuses, never UB.
    const crd::u64 bad[] = {6U, 4U};
    Tensor<crd::f64> r_bad(&alloc, bad);
    CHECK(ew_binary(BinaryOp::Add, TensorView<const crd::f64>(a.view()), TensorView<const crd::f64>(b.view()),
                    r_bad.view()) == TensorStatus::ShapeMismatch);

    // Same-shape dense operands collapse to one flat SIMD run — result equals
    // the scalar-reference elementwise loop bit-for-bit.
    Tensor<crd::f64> r(&alloc, s2);
    REQUIRE(ew_binary(BinaryOp::Add, TensorView<const crd::f64>(a.view()), TensorView<const crd::f64>(b.view()),
                      r.view()) == TensorStatus::Ok);
    for (crd::u64 i = 0; i < 24U; ++i)
    {
        CHECK(r.data()[i] == a.data()[i] + b.data()[i]);
    }

    // Run-twice bit-identity.
    Tensor<crd::f64> r2(&alloc, s2);
    REQUIRE(ew_binary(BinaryOp::Add, TensorView<const crd::f64>(a.view()), TensorView<const crd::f64>(b.view()),
                      r2.view()) == TensorStatus::Ok);
    for (crd::u64 i = 0; i < 24U; ++i)
    {
        CHECK(std::bit_cast<crd::u64>(r.data()[i]) == std::bit_cast<crd::u64>(r2.data()[i]));
    }

    // A permuted (non-canonical) SOURCE still evaluates correctly (P2 path).
    const crd::u32 order[] = {1U, 0U};
    TensorView<const crd::f64> ap = a.view().permute(order); // (6,4) strided
    const crd::u64 so[] = {6U, 4U};
    Tensor<crd::f64> rp(&alloc, so);
    REQUIRE(ew_binary(BinaryOp::Mul, ap, TensorView<const crd::f64>(a.view().permute(order)), rp.view()) ==
            TensorStatus::Ok);
    crd::u64 k = 0;
    ap.for_each(
        [&](const crd::u64*, const crd::f64& v)
        {
            CHECK(rp.data()[k] == v * v);
            ++k;
        });
}
