#!/usr/bin/env python3
"""scipy.signal.firwin reference taps for the v11-c FIR gates (the batch-once harness).

Run: python3 tests/hesap-dsp/gen_fir_refs.py > tests/hesap-dsp/fir_refs.inc
"""
from scipy.signal import firwin, firwin2


def emit(name, arr):
    san = name.replace(".", "_").replace("-", "_")
    vals = ", ".join(f"{x:.17g}" for x in arr)
    print(f"inline const double ref_{san}[] = {{{vals}}};")


def main():
    print("// GENERATED by gen_fir_refs.py — scipy.signal.firwin reference taps (v11-c). Plain C arrays (no STL).")
    print("#pragma once")
    # all default window = hamming, fs=2 (cutoff in [0,1]=Nyquist).
    emit("lowpass_0.3", firwin(35, 0.3))                                   # lowpass, hamming
    emit("highpass_0.4", firwin(35, 0.4, pass_zero=False))                 # highpass (odd taps)
    emit("bandpass_0.2_0.5", firwin(35, [0.2, 0.5], pass_zero=False))      # bandpass
    emit("bandstop_0.2_0.5", firwin(35, [0.2, 0.5], pass_zero=True))       # bandstop
    emit("lowpass_hann", firwin(31, 0.25, window="hann"))                  # lowpass, hann window
    emit("lowpass_blackman", firwin(31, 0.25, window="blackman"))          # lowpass, blackman
    emit("lowpass_noscale", firwin(31, 0.25, scale=False))                 # no normalization
    # firwin2 (frequency sampling), default hamming window.
    emit("firwin2_lp", firwin2(65, [0.0, 0.5, 1.0], [1.0, 1.0, 0.0]))      # lowpass-ish ramp
    emit("firwin2_bp", firwin2(65, [0.0, 0.2, 0.4, 0.6, 1.0], [0.0, 0.0, 1.0, 0.0, 0.0]))  # bandpass
    emit("firwin2_shelf", firwin2(65, [0.0, 0.3, 0.3, 1.0], [1.0, 1.0, 0.5, 0.5]))         # step/shelf


if __name__ == "__main__":
    main()
