#!/usr/bin/env python3
"""scipy IIR reference: analog prototype poles + digital design freqz response (v11-e).
Run: python3 tests/hesap-dsp/gen_iir_refs.py > tests/hesap-dsp/iir_refs.inc"""
import numpy as np
from scipy.signal import buttap, cheb1ap, cheb2ap, butter, cheby1, cheby2, sosfreqz


def emit(name, arr):
    san = name.replace(".", "_").replace("-", "_")
    print(f"inline const double ref_{san}[] = {{{', '.join(f'{x:.17g}' for x in arr)}}};")


def poles_flat(p):  # interleave re,im sorted by (re, im) for a stable set comparison
    ps = sorted(p, key=lambda c: (round(c.real, 9), round(c.imag, 9)))
    out = []
    for c in ps:
        out += [c.real, c.imag]
    return out


def main():
    print("// GENERATED by gen_iir_refs.py — scipy IIR analog poles + digital freqz magnitude (v11-e). C arrays (no STL).")
    print("#pragma once")
    # analog prototype poles (sorted, interleaved re/im).
    z, p, k = buttap(4);     emit("buttap4_poles", poles_flat(p))
    z, p, k = cheb1ap(4, 1); emit("cheb1ap4_poles", poles_flat(p))
    z, p, k = cheb2ap(4, 40); emit("cheb2ap4_poles", poles_flat(p))
    # digital design freqz MAGNITUDE at 64 points (response-equality gate, order-independent).
    for nm, sos in [("butter6", butter(6, 0.3, output='sos')),
                    ("cheby1_6", cheby1(6, 1, 0.3, output='sos')),
                    ("cheby2_6", cheby2(6, 40, 0.3, output='sos'))]:
        w, h = sosfreqz(sos, worN=64)
        emit(nm + "_mag", list(np.abs(h)))


if __name__ == "__main__":
    main()
