#!/usr/bin/env python3
"""scipy firls + remez reference taps for v11-d (batch-once harness).
Run: python3 tests/hesap-dsp/gen_firls_remez_refs.py > tests/hesap-dsp/firls_remez_refs.inc"""
from scipy.signal import firls, remez


def emit(name, arr):
    san = name.replace(".", "_").replace("-", "_")
    print(f"inline const double ref_{san}[] = {{{', '.join(f'{x:.17g}' for x in arr)}}};")


def main():
    print("// GENERATED by gen_firls_remez_refs.py — scipy firls + remez references (v11-d). Plain C arrays (no STL).")
    print("#pragma once")
    # firls (closed-form ⇒ 1e-10 match). bands/desired in [0,1] (Nyquist).
    emit("firls_lp", firls(65, [0, 0.3, 0.4, 1.0], [1, 1, 0, 0]))
    emit("firls_bp", firls(65, [0, 0.2, 0.3, 0.6, 0.7, 1.0], [0, 0, 1, 1, 0, 0]))
    emit("firls_weighted", firls(65, [0, 0.3, 0.4, 1.0], [1, 1, 0, 0], weight=[1, 5]))
    # remez (iterative ⇒ spec-compliance + ~N-digit coeffs). scipy remez bands in [0, 0.5] (fs=1 default!).
    emit("remez_lp", remez(65, [0, 0.15, 0.2, 0.5], [1, 0]))
    emit("remez_bp", remez(65, [0, 0.1, 0.15, 0.25, 0.3, 0.5], [0, 1, 0]))


if __name__ == "__main__":
    main()
