#!/usr/bin/env python3
"""scipy.signal.hilbert2 reference (v11-l). C arrays (no STL).
Run: python3 tests/hesap-dsp/gen_hilbert2_refs.py > tests/hesap-dsp/hilbert2_refs.inc"""
import numpy as np
from scipy.signal import hilbert2


def emit(name, arr):
    print(f"inline const double ref_{name}[] = {{{', '.join(f'{x:.17g}' for x in arr)}}};")


def main():
    print("// GENERATED by gen_hilbert2_refs.py — scipy.signal.hilbert2 (v11-l). C arrays (no STL).")
    print("#pragma once")
    r, c = 8, 8
    img = np.empty((r, c))
    for i in range(r):
        for j in range(c):
            img[i, j] = np.cos(0.4 * i + 0.2 * j) + 0.3 * np.sin(0.7 * j)
    a = hilbert2(img)
    emit("h2_re", list(a.real.ravel()))
    emit("h2_im", list(a.imag.ravel()))


if __name__ == "__main__":
    main()
