#!/usr/bin/env python3
"""Generate scipy.signal.windows reference vectors for the v11-b window gates.

The honest-gate harness (the SUNDIALS-tableau pattern): emit ALL references in ONE run to a committed
header the C++ test reads — never call Python per-test. scipy is the free primary; MATLAB R2026a is the
spec-compliance authority (cross-checked separately for the parametric/special windows).

Run (WSL):  python3 tests/hesap-dsp/gen_window_refs.py > tests/hesap-dsp/window_refs.inc
"""
import numpy as np
from scipy.signal import windows


def emit(name, arr):
    san = name.replace(".", "_").replace("-", "_")
    vals = ", ".join(f"{x:.17g}" for x in arr)
    print(f"inline const double ref_{san}[] = {{{vals}}};")


def main():
    print("// GENERATED by gen_window_refs.py — scipy.signal.windows reference vectors (v11-b). DO NOT EDIT.")
    print("// Plain C arrays (NO std containers — project rule). Symmetric (sym=True) unless name says _periodic.")
    print("#pragma once")

    N = 16
    # cosine-sum + simple analytic windows (symmetric).
    emit("hann", windows.hann(N, sym=True))
    emit("hamming", windows.hamming(N, sym=True))
    emit("blackman", windows.blackman(N, sym=True))
    emit("blackmanharris", windows.blackmanharris(N, sym=True))
    emit("nuttall", windows.nuttall(N, sym=True))
    emit("flattop", windows.flattop(N, sym=True))
    emit("bartlett", windows.bartlett(N, sym=True))
    emit("triang", windows.triang(N, sym=True))
    emit("bohman", windows.bohman(N, sym=True))
    emit("parzen", windows.parzen(N, sym=True))
    emit("barthann", windows.barthann(N, sym=True))
    emit("cosine", windows.cosine(N, sym=True))
    emit("lanczos", windows.lanczos(N, sym=True))
    emit("boxcar", windows.boxcar(N))
    # periodic variants (fftbins) — the spectral-analysis convention.
    emit("hann_periodic", windows.hann(N, sym=False))
    emit("hamming_periodic", windows.hamming(N, sym=False))
    # parametric.
    emit("kaiser_8", windows.kaiser(N, beta=8.0, sym=True))
    emit("kaiser_14", windows.kaiser(N, beta=14.0, sym=True))
    emit("gaussian_2", windows.gaussian(N, std=2.0, sym=True))
    emit("tukey_05", windows.tukey(N, alpha=0.5, sym=True))
    emit("general_gaussian", windows.general_gaussian(N, p=1.5, sig=2.0, sym=True))
    emit("exponential", windows.exponential(N, sym=True))
    emit("taylor", windows.taylor(N, nbar=4, sll=30, norm=False, sym=True))
    # special (equiripple + eigenvalue).
    emit("chebwin_100", windows.chebwin(N, at=100.0, sym=True))
    emit("dpss_nw3", windows.dpss(N, NW=3.0, Kmax=None))  # first Slepian sequence (Kmax=None ⇒ 1-D)


if __name__ == "__main__":
    main()
