#!/usr/bin/env python3
"""scipy waveform reference (v11-r): chirp/sawtooth/square/gausspulse/sweep_poly/unit_impulse. C arrays (no STL).
Run: python3 tests/hesap-dsp/gen_waveforms_refs.py > tests/hesap-dsp/waveforms_refs.inc"""
import numpy as np
from scipy.signal import chirp, sawtooth, square, gausspulse, sweep_poly, unit_impulse


def emit(name, arr):
    print(f"inline const double ref_{name}[] = {{{', '.join(f'{x:.17g}' for x in arr)}}};")


def main():
    print("// GENERATED by gen_waveforms_refs.py — scipy waveforms (v11-r). C arrays (no STL).")
    print("#pragma once")
    tc = np.arange(256) / 255.0
    for m in ("linear", "quadratic", "logarithmic", "hyperbolic"):
        emit("chirp_" + m, list(chirp(tc, 6.0, 1.0, 60.0, method=m)))
    ts = np.arange(256) * 0.1
    emit("sawtooth_1", list(sawtooth(ts, 1.0)))
    emit("sawtooth_05", list(sawtooth(ts, 0.5)))
    emit("square_05", list(square(ts, 0.5)))
    emit("square_03", list(square(ts, 0.3)))
    tg = (np.arange(256) - 128) / 256.0
    emit("gausspulse", list(gausspulse(tg, fc=5.0, bw=0.5)))
    emit("sweep_poly", list(sweep_poly(tc, np.poly1d([0.05, -0.75, 2.5, 8.0]))))
    emit("unit_impulse", list(unit_impulse(16, 5)))


if __name__ == "__main__":
    main()
