#!/usr/bin/env python3
"""scipy.special elliptic-function references (v11-f). Plain C arrays (no STL).
Run: python3 tests/hesap-dsp/gen_elliptic_refs.py > tests/hesap-dsp/elliptic_refs.inc"""
import numpy as np
from scipy import special


def main():
    print("// GENERATED by gen_elliptic_refs.py — scipy.special ellipk/ellipj + _ellipdeg refs (v11-f). C arrays.")
    print("#pragma once")
    # ellipk(m) at several m.
    ms = [0.1, 0.3, 0.5, 0.7, 0.9, 0.99]
    print(f"inline const double ref_ellipk_m[] = {{{', '.join(f'{x:.17g}' for x in ms)}}};")
    print(f"inline const double ref_ellipk[] = {{{', '.join(f'{special.ellipk(x):.17g}' for x in ms)}}};")
    # ellipj(u, m): sn, cn, dn at (u, m) pairs.
    us = [0.5, 1.0, 1.5, 2.0]
    m = 0.36
    sn, cn, dn, _ = special.ellipj(np.array(us), m * np.ones(len(us)))
    print(f"inline const double ref_ellipj_u[] = {{{', '.join(f'{x:.17g}' for x in us)}}};")
    print(f"inline const double ref_ellipj_m = {m:.17g};")
    print(f"inline const double ref_ellipj_sn[] = {{{', '.join(f'{x:.17g}' for x in sn)}}};")
    print(f"inline const double ref_ellipj_cn[] = {{{', '.join(f'{x:.17g}' for x in cn)}}};")
    print(f"inline const double ref_ellipj_dn[] = {{{', '.join(f'{x:.17g}' for x in dn)}}};")
    # _ellipdeg(N, m1): the degree equation.
    from scipy.signal._filter_design import _ellipdeg
    cases = [(3, 0.001), (5, 0.0001), (7, 1e-5)]
    print(f"inline const double ref_ellipdeg_N[] = {{{', '.join(str(n) for n, _ in cases)}}};")
    print(f"inline const double ref_ellipdeg_m1[] = {{{', '.join(f'{m1:.17g}' for _, m1 in cases)}}};")
    print(f"inline const double ref_ellipdeg[] = {{{', '.join(f'{_ellipdeg(n, m1):.17g}' for n, m1 in cases)}}};")


if __name__ == "__main__":
    main()
