#!/usr/bin/env python3
"""scipy Hilbert / analytic-signal reference (v11-l). C arrays only (no STL).
Run: python3 tests/hesap-dsp/gen_hilbert_refs.py > tests/hesap-dsp/hilbert_refs.inc"""
import numpy as np
from scipy.signal import hilbert


def emit(name, arr):
    print(f"inline const double ref_{name}[] = {{{', '.join(f'{x:.17g}' for x in arr)}}};")


def sig(n):
    i = np.arange(n)
    return np.sin(2 * np.pi * 5 * i / n) + 0.5 * np.cos(2 * np.pi * 12 * i / n)


def am(n):
    i = np.arange(n)
    return (1 + 0.5 * np.cos(2 * np.pi * 3 * i / n)) * np.cos(2 * np.pi * 40 * i / n)


def chirp(n, fs, f0, f1):
    t = np.arange(n) / fs
    T = n / fs
    return np.cos(2 * np.pi * (f0 * t + 0.5 * (f1 - f0) / T * t * t))


def main():
    print("// GENERATED by gen_hilbert_refs.py — scipy hilbert/envelope/inst-freq (v11-l). C arrays (no STL).")
    print("#pragma once")
    for n in (64, 63):
        a = hilbert(sig(n))
        emit(f"hilbert_x{n}_re", list(a.real))
        emit(f"hilbert_x{n}_im", list(a.imag))
    emit("envelope_am", list(np.abs(hilbert(am(256)))))
    # instantaneous frequency of a linear chirp (compared on the interior; edges have Hilbert artifacts).
    a = hilbert(chirp(512, 512.0, 20.0, 100.0))
    inst = np.diff(np.unwrap(np.angle(a))) / (2 * np.pi) * 512.0
    emit("instfreq_chirp", list(inst))


if __name__ == "__main__":
    main()
