#!/usr/bin/env python3
"""scipy detection + measurements reference (v11-s). C arrays (no STL).
Run: python3 tests/hesap-dsp/gen_measurements_refs.py > tests/hesap-dsp/measurements_refs.inc"""
import numpy as np
from scipy.signal import find_peaks, peak_prominences, peak_widths, argrelextrema, detrend


def emit(name, arr):
    print(f"inline const double ref_{name}[] = {{{', '.join(f'{x:.17g}' for x in np.atleast_1d(arr))}}};")


def emit_i(name, arr):
    print(f"inline const unsigned long ref_{name}[] = {{{', '.join(str(int(x)) for x in np.atleast_1d(arr))}}};")
    print(f"inline const unsigned long ref_{name}_n = {len(np.atleast_1d(arr))};")


def sig(n):
    i = np.arange(n)
    return np.sin(2 * np.pi * 0.05 * i) + 0.4 * np.sin(2 * np.pi * 0.21 * i) + 0.2 * np.cos(2 * np.pi * 0.017 * i)


def main():
    print("// GENERATED by gen_measurements_refs.py — scipy find_peaks/detrend/argrelextrema (v11-s). C arrays (no STL).")
    print("#pragma once")
    x = sig(240)
    peaks, _ = find_peaks(x)
    emit_i("fp_peaks", peaks)
    prom = peak_prominences(x, peaks)[0]
    emit("fp_prom", prom)
    widths = peak_widths(x, peaks, rel_height=0.5)[0]
    emit("fp_widths", widths)
    # height + distance filter
    pk2, _ = find_peaks(x, height=0.3, distance=10)
    emit_i("fp_hd", pk2)
    # argrelextrema (maxima, order 2)
    amax = argrelextrema(x, np.greater, order=2)[0]
    emit_i("argrel_max", amax)
    # detrend
    i = np.arange(120)
    xt = 0.5 + 0.02 * i + np.sin(2 * np.pi * 0.1 * i)
    emit("detrend_const", detrend(xt, type='constant'))
    emit("detrend_linear", detrend(xt, type='linear'))


if __name__ == "__main__":
    main()
