#!/usr/bin/env python3
"""scipy multirate reference (v11-k): upfirdn / resample_poly / decimate. C arrays (no STL).
Run: python3 tests/hesap-dsp/gen_multirate_refs.py > tests/hesap-dsp/multirate_refs.inc"""
import numpy as np
from scipy.signal import upfirdn, resample_poly, decimate


def emit(name, arr):
    print(f"inline const double ref_{name}[] = {{{', '.join(f'{x:.17g}' for x in arr)}}};")


def sig(n):
    i = np.arange(n)
    return np.sin(2 * np.pi * 0.05 * i) + 0.5 * np.sin(2 * np.pi * 0.13 * i)


def main():
    print("// GENERATED by gen_multirate_refs.py — scipy upfirdn/resample_poly/decimate (v11-k). C arrays (no STL).")
    print("#pragma once")
    h = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
    x = np.arange(1.0, 21.0)
    emit("upfirdn_3_2", list(upfirdn(h, x, 3, 2)))
    emit("resample_3_2", list(resample_poly(sig(500), 3, 2)))
    emit("resample_2_3", list(resample_poly(sig(500), 2, 3)))
    emit("decimate_q4", list(decimate(sig(600), 4, ftype='fir')))


if __name__ == "__main__":
    main()
