#!/usr/bin/env python3
"""scipy IIR-design reference: frequency-transformed designs (response mag) + order
estimation (N, Wn) + notch/peak/comb coeffs (v11-g). C arrays only (no STL).
Run: python3 tests/hesap-dsp/gen_iir_design_refs.py > tests/hesap-dsp/iir_design_refs.inc"""
import numpy as np
from scipy.signal import (butter, cheby1, cheby2, ellip, sosfreqz,
                          buttord, cheb1ord, cheb2ord, ellipord,
                          iirnotch, iirpeak, iircomb)


def emit(name, arr):
    san = name.replace(".", "_").replace("-", "_")
    print(f"inline const double ref_{san}[] = {{{', '.join(f'{x:.17g}' for x in np.atleast_1d(arr))}}};")


def emit_int(name, v):
    print(f"inline const int ref_{name} = {int(v)};")


def main():
    print("// GENERATED by gen_iir_design_refs.py — scipy IIR-design refs (v11-g). C arrays (no STL).")
    print("#pragma once")

    # --- frequency-transformed designs: |H(e^jw)| at 64 points (response-equality gate) ---
    designs = [
        ("butter_hp", butter(6, 0.3, 'highpass', output='sos')),
        ("butter_bp", butter(4, [0.2, 0.4], 'bandpass', output='sos')),
        ("butter_bs", butter(4, [0.2, 0.4], 'bandstop', output='sos')),
        ("cheby1_hp", cheby1(6, 1.0, 0.3, 'highpass', output='sos')),
        ("cheby2_bp", cheby2(6, 40.0, [0.2, 0.4], 'bandpass', output='sos')),
        ("ellip_bs", ellip(5, 1.0, 40.0, [0.25, 0.45], 'bandstop', output='sos')),
    ]
    for nm, sos in designs:
        w, h = sosfreqz(sos, worN=64)
        emit(nm + "_mag", list(np.abs(h)))

    # --- order estimation: N (exact) + Wn (1 or 2 elements) ---
    ords = [
        ("buttord_lp", buttord(0.2, 0.3, 1.0, 40.0)),
        ("buttord_hp", buttord(0.3, 0.2, 1.0, 40.0)),
        ("buttord_bp", buttord([0.2, 0.5], [0.1, 0.6], 1.0, 40.0)),
        ("buttord_bs", buttord([0.1, 0.6], [0.2, 0.5], 1.0, 40.0)),
        ("cheb1ord_lp", cheb1ord(0.2, 0.3, 1.0, 40.0)),
        ("cheb1ord_bp", cheb1ord([0.2, 0.5], [0.1, 0.6], 1.0, 40.0)),
        ("cheb2ord_lp", cheb2ord(0.2, 0.3, 1.0, 40.0)),
        ("cheb2ord_bp", cheb2ord([0.2, 0.5], [0.1, 0.6], 1.0, 40.0)),
        ("ellipord_lp", ellipord(0.2, 0.3, 1.0, 40.0)),
        ("ellipord_bs", ellipord([0.1, 0.6], [0.2, 0.5], 1.0, 40.0)),
    ]
    for nm, (N, Wn) in ords:
        emit_int(nm + "_n", N)
        emit(nm + "_wn", list(np.atleast_1d(Wn)))

    # --- notch / peak / comb coefficients (b, a) ---
    for nm, (b, a) in [("notch", iirnotch(0.25, 30.0)),
                       ("peak", iirpeak(0.25, 30.0)),
                       ("comb_notch", iircomb(0.25, 30.0, ftype='notch')),
                       ("comb_peak", iircomb(0.25, 30.0, ftype='peak'))]:
        emit(nm + "_b", list(b))
        emit(nm + "_a", list(a))


if __name__ == "__main__":
    main()
