#!/usr/bin/env python3
"""RBJ Audio-EQ-Cookbook reference (v11-h). An INDEPENDENT transcription of the
cookbook (https://www.w3.org/TR/audio-eq-cookbook/) used to cross-check the C++
coefficients (~1e-12). f0 = Nyquist fraction ⇒ w0 = pi*f0; shelves use the Q form.
Run: python3 tests/hesap-dsp/gen_rbj_refs.py > tests/hesap-dsp/rbj_refs.inc"""
import math


def emit(name, coeffs):  # coeffs = [b0,b1,b2,a1,a2] (normalized, a0=1)
    print(f"inline const double ref_rbj_{name}[] = {{{', '.join(f'{x:.17g}' for x in coeffs)}}};")


def common(f0, q):
    w0 = math.pi * f0
    return w0, math.cos(w0), math.sin(w0), math.sin(w0) / (2.0 * q)


def norm(b0, b1, b2, a0, a1, a2):
    return [b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0]


def main():
    print("// GENERATED by gen_rbj_refs.py — independent RBJ-cookbook coeffs (v11-h). C arrays (no STL).")
    print("#pragma once")
    f0, q, g = 0.25, 0.7071067811865476, 6.0
    w0, cw, sw, al = common(f0, q)
    emit("lowpass", norm((1 - cw) / 2, 1 - cw, (1 - cw) / 2, 1 + al, -2 * cw, 1 - al))
    emit("highpass", norm((1 + cw) / 2, -(1 + cw), (1 + cw) / 2, 1 + al, -2 * cw, 1 - al))
    emit("bandpass", norm(al, 0.0, -al, 1 + al, -2 * cw, 1 - al))
    emit("notch", norm(1.0, -2 * cw, 1.0, 1 + al, -2 * cw, 1 - al))
    emit("allpass", norm(1 - al, -2 * cw, 1 + al, 1 + al, -2 * cw, 1 - al))
    A = 10 ** (g / 40.0)
    emit("peaking", norm(1 + al * A, -2 * cw, 1 - al * A, 1 + al / A, -2 * cw, 1 - al / A))
    sa = math.sqrt(A)
    ap1, am1 = A + 1, A - 1
    emit("lowshelf", norm(A * (ap1 - am1 * cw + 2 * sa * al), 2 * A * (am1 - ap1 * cw),
                          A * (ap1 - am1 * cw - 2 * sa * al), ap1 + am1 * cw + 2 * sa * al,
                          -2 * (am1 + ap1 * cw), ap1 + am1 * cw - 2 * sa * al))
    emit("highshelf", norm(A * (ap1 + am1 * cw + 2 * sa * al), -2 * A * (am1 + ap1 * cw),
                           A * (ap1 + am1 * cw - 2 * sa * al), ap1 - am1 * cw + 2 * sa * al,
                           2 * (am1 - ap1 * cw), ap1 - am1 * cw - 2 * sa * al))


if __name__ == "__main__":
    main()
