#!/usr/bin/env python3
"""Generated-source provenance guard (REPO.DEV.10; contract in docs/CONTRIBUTING.md).

Every committed generated file is named once in scripts/generated-sources.json with its generator, its status and
the SHA-256 of its bytes. The guard fails when a listed file changed without a manifest refresh, when a file that
carries a generation marker is not listed, when a named generator is missing without the generator-absent status,
when a status is unknown, or when an entry that cannot be regenerated has no owning ROADMAP row.

  python scripts/check-generated.py                  # manifest and hash checks (every lane; stdlib only)
  python scripts/check-generated.py --scan           # list marker-carrying files the manifest does not name
  python scripts/check-generated.py --regenerate     # rerun the generators that emit to stdout and byte-compare
  python scripts/check-generated.py --refresh <path> # record the current bytes of the named entries (after a
                                                     # deliberate regeneration; the diff and the session say why)

Hashes are taken over LF-normalized bytes so a Windows and a Linux checkout agree; line-ending policy itself is
check-repository.py's contract. Statuses (every one but `drifted` is a declared, permanent property of the file
and needs no owner; a `drifted` entry names the ROADMAP row that decides whether the file or the generator is the
truth):
  reproducible      the generator is present and a run on the reference host reproduced the committed bytes
  formatted         the generator's output passed through the repository's clang-format (`format`) reproduces the
                    committed bytes; --regenerate applies the same formatter when one is available
  host-dependent    reproducible on the reference host only (float constants come from the host's libm)
  network-sourced   the generator fetches upstream tables; reproducible while upstream serves the same bytes
  hand-maintained   the generator was the origin but the committed file is the truth (maintained by hand since);
                    the generator stays as provenance and a regeneration is a decision recorded against a row
  drifted           the generator is present but no longer emits the committed bytes and no decision has been
                    taken; the owning row decides (REPO.DEV.11 audit: only test references remain drifted)
  generator-absent  the file names a generator that is not in the repository (a scratch script that was never
                    committed); the bytes are the only artifact, recorded here with their hash
  measured          produced from measurements (a GPU tuning run); regeneration needs the instrument, not a script
"""
from pathlib import Path
import argparse
import hashlib
import json
import os
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'scripts' / 'generated-sources.json'
SCHEMA = 'cerid-generated-sources/1'
STATUSES = ('reproducible', 'formatted', 'host-dependent', 'network-sourced', 'hand-maintained', 'drifted',
            'generator-absent', 'measured')
OWNED_STATUSES = ('drifted',)
FORMATTERS = ('clang-format',)
PINNED_WINDOWS_CLANG_FORMAT = 'C:/LLVM-20.1.8/bin/clang-format.exe'  # the pinned LLVM the tidy gate uses
SCAN_DIRS = ('engine', 'tests', 'tools', 'docs/generated')
SCAN_SUFFIXES = {'.hpp', '.cpp', '.inl', '.h', '.inc', '.md'}
# A file is generated when one of its first three lines is a comment that opens with GENERATED (optionally after
# the file's own name, as in "erk_tableaus.hpp -- GENERATED by ..."), says "GENERATED by" anywhere, or opens with
# "generated by <script>.py" as a statement. A hand-written file that merely discusses generated things ("the
# GENERATED-dialect gate", "reference vectors GENERATED from scipy") does not match.
MARKER = re.compile(r'^\s*(?://|#|<!--|/\*|;)\s*(?:[\w.-]+\s*(?:--|—|-)\s*)?(?:AUTO-)?GENERATED\b'
                    r'|\bGENERATED by\b'
                    r'|^\s*(?://|#)\s*[Gg]enerated by\s+[\w./-]+\.py\s*(?:[—\-:.,]|$)', re.M)


def sha256(path):
    data = path.read_bytes().replace(b'\r\n', b'\n')
    return hashlib.sha256(data).hexdigest()


def load(manifest):
    data = json.loads(manifest.read_text(encoding='utf-8'))
    if data.get('schema') != SCHEMA:
        raise ValueError(f'{manifest}: schema must be {SCHEMA}')
    return data


def save(manifest, data):
    manifest.write_bytes((json.dumps(data, indent=2, ensure_ascii=False) + '\n').encode('utf-8'))


def head_lines(path, count=3):
    try:
        with path.open('rb') as handle:
            raw = b''.join(handle.readline() for _ in range(count))
    except OSError:
        return ''
    return raw.decode('utf-8', errors='replace')


def marked_files(root):
    """Files whose first three lines carry a generation marker; sorted repository-relative POSIX paths."""
    found = []
    for directory in SCAN_DIRS:
        base = root / directory
        if not base.is_dir():
            continue
        for path in sorted(base.rglob('*')):
            if path.suffix.lower() in SCAN_SUFFIXES and path.is_file() and MARKER.search(head_lines(path)):
                found.append(path.relative_to(root).as_posix())
    return found


def hand_written(data):
    """Files whose opening comment reads like a marker but which are written by hand: path -> reason."""
    return data.get('not_generated', {})


def check(root, manifest):
    errors = []
    data = load(manifest)
    entries = data.get('entries', [])
    listed = {}
    for path, reason in hand_written(data).items():
        if not (root / path).is_file():
            errors.append(f'{path}: not_generated names a file that does not exist')
        if not isinstance(reason, str) or not reason.strip():
            errors.append(f'{path}: not_generated needs a reason')
    for entry in entries:
        path = entry.get('path')
        if not path or path in listed:
            errors.append(f'entry without a unique path: {entry}')
            continue
        listed[path] = entry
        status = entry.get('status')
        if status not in STATUSES:
            errors.append(f'{path}: unknown status {status!r}')
        target = root / path
        if not target.is_file():
            errors.append(f'{path}: listed file does not exist')
            continue
        digest = entry.get('sha256')
        if not re.fullmatch(r'[0-9a-f]{64}', digest or ''):
            errors.append(f'{path}: sha256 missing or malformed')
        elif sha256(target) != digest:
            errors.append(f'{path}: bytes changed since the manifest was refreshed (regenerate deliberately, then '
                          f'`check-generated.py --refresh {path}`)')
        generator = entry.get('generator')
        if status == 'generator-absent':
            if generator and (root / generator).exists():
                errors.append(f'{path}: status generator-absent but {generator} exists')
        elif status == 'hand-maintained':
            if generator and not (root / generator).is_file():
                errors.append(f'{path}: generator {generator} is not in the repository (status generator-absent?)')
        elif status != 'measured':
            if not generator:
                errors.append(f'{path}: status {status} needs a generator path')
            elif not (root / generator).is_file():
                errors.append(f'{path}: generator {generator} is not in the repository (status generator-absent?)')
        if status == 'formatted' and entry.get('format') not in FORMATTERS:
            errors.append(f'{path}: status formatted names its formatter in `format` (one of {", ".join(FORMATTERS)})')
        if status in OWNED_STATUSES and not re.fullmatch(r'[A-Z][A-Z0-9.-]*', entry.get('owner') or ''):
            errors.append(f'{path}: status {status} needs an owning ROADMAP row')
    excluded = hand_written(data)
    for path in marked_files(root):
        if path in excluded and path in listed:
            errors.append(f'{path}: both an entry and not_generated')
        elif path not in listed and path not in excluded:
            errors.append(f'{path}: carries a generation marker but the manifest does not name it')
    generated_docs = root / 'docs' / 'generated'
    if generated_docs.is_dir():
        for path in sorted(generated_docs.glob('*.md')):
            relative = path.relative_to(root).as_posix()
            if relative not in listed:
                errors.append(f'{relative}: every docs/generated document is a manifest entry')
    return errors


def clang_format_tool():
    """CRD_CLANG_FORMAT, then PATH, then the pinned Windows LLVM; None when no formatter is available."""
    explicit = os.environ.get('CRD_CLANG_FORMAT')
    if explicit and Path(explicit).is_file():
        return explicit
    from shutil import which
    found = which('clang-format')
    if found:
        return found
    if sys.platform == 'win32' and Path(PINNED_WINDOWS_CLANG_FORMAT).is_file():
        return PINNED_WINDOWS_CLANG_FORMAT
    return None


def formatted_output(root, path, raw, tool):
    """The generator's stdout through the repository's clang-format, as the committed file was produced."""
    target = (root / path).resolve()
    result = subprocess.run([tool, '--style=file', f'--assume-filename={target.as_posix()}'], cwd=str(root),
                            input=raw, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.decode('utf-8', errors='replace').strip()[-400:])
    return result.stdout


def regenerate(root, manifest):
    """Rerun every generator that emits to stdout (or ships its own --check) and compare with the committed bytes."""
    data = load(manifest)
    failures = []
    ran = skipped = 0
    checked_commands = set()
    formatter = None
    for entry in data.get('entries', []):
        path, status = entry['path'], entry['status']
        if status not in ('reproducible', 'formatted', 'host-dependent', 'network-sourced'):
            skipped += 1
            continue
        if status == 'formatted':
            formatter = formatter or clang_format_tool()
            if formatter is None:
                print(f'skip {path}: formatted, no clang-format on this host (CRD_CLANG_FORMAT names one)')
                skipped += 1
                continue
        if status == 'host-dependent' and sys.platform != data.get('reference_host', {}).get('platform', 'linux'):
            print(f'skip {path}: host-dependent, compare on the reference host')
            skipped += 1
            continue
        command = entry.get('check_command') or entry.get('command')
        if not command or entry.get('writes') == 'in-place':
            print(f'skip {path}: {"writes in place; run its script and inspect git diff" if command else "no command"}')
            skipped += 1
            continue
        if entry.get('check_command') and tuple(command) in checked_commands:
            continue  # one --check run covers every file the generator owns
        argv = [sys.executable if token in ('python', 'python3') else token for token in command]
        result = subprocess.run(argv, cwd=str(root), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        stderr = result.stderr.decode('utf-8', errors='replace')
        if result.returncode != 0 and 'ModuleNotFoundError' in stderr:
            module = re.search(r"No module named '([^']+)'", stderr)
            print(f'skip {path}: requirement not installed on this host ({module[1] if module else "module"})')
            skipped += 1
            continue
        ran += 1
        if result.returncode != 0:
            failures.append(f'{path}: {" ".join(command)} exited {result.returncode}: {stderr.strip()[-400:]}')
            continue
        if entry.get('check_command'):
            checked_commands.add(tuple(command))
            print(f'ok   {path}: {" ".join(command)}')
            continue
        output = result.stdout
        if status == 'formatted':
            try:
                output = formatted_output(root, path, output, formatter)
            except (OSError, RuntimeError) as error:
                failures.append(f'{path}: {entry["format"]} failed: {error}')
                continue
        produced = hashlib.sha256(output.replace(b'\r\n', b'\n')).hexdigest()
        if produced != sha256(root / path):
            failures.append(f'{path}: the generator output differs from the committed bytes')
        else:
            print(f'ok   {path}: byte-identical')
    print(f'regenerate: {ran} generators ran, {skipped} entries skipped, {len(failures)} failures')
    return failures


def refresh(root, manifest, paths):
    """Record the current bytes of the named entries; a directory names every entry beneath it, so a regenerated
    dialect (104 files) or a re-rendered document is one command. Returns the refreshed paths."""
    data = load(manifest)
    known = {entry['path']: entry for entry in data.get('entries', [])}
    selected = []
    for wanted in paths:
        prefix = wanted.rstrip('/') + '/'
        matches = [path for path in known if path == wanted or path.startswith(prefix)]
        if not matches:
            raise SystemExit(f'not in the manifest: {wanted}')
        selected.extend(path for path in matches if path not in selected)
    for path in selected:
        known[path]['sha256'] = sha256(root / path)
        print(f'refreshed {path}')
    save(manifest, data)
    return selected


def main():
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8')
    parser = argparse.ArgumentParser(description='Generated-source provenance guard')
    parser.add_argument('--root', default=str(ROOT), help='repository root (tests use a fixture)')
    parser.add_argument('--manifest', help='manifest path (default: <root>/scripts/generated-sources.json)')
    group = parser.add_mutually_exclusive_group()
    group.add_argument('--scan', action='store_true', help='list marker-carrying files the manifest does not name')
    group.add_argument('--regenerate', action='store_true', help='rerun stdout generators and byte-compare')
    group.add_argument('--refresh', nargs='+', metavar='PATH', help='record the current bytes of named entries')
    args = parser.parse_args()
    root = Path(args.root).resolve()
    manifest = Path(args.manifest).resolve() if args.manifest else root / 'scripts' / 'generated-sources.json'
    if args.scan:
        data = load(manifest) if manifest.is_file() else {}
        listed = {entry['path'] for entry in data.get('entries', [])} | set(hand_written(data))
        for path in marked_files(root):
            if path not in listed:
                print(path)
        return 0
    if args.refresh:
        refresh(root, manifest, [Path(p).as_posix() for p in args.refresh])
        return 0
    if args.regenerate:
        failures = regenerate(root, manifest)
        for failure in failures:
            print('FAIL: ' + failure)
        return 1 if failures else 0
    errors = check(root, manifest)
    for error in errors:
        print('FAIL: ' + error)
    if errors:
        return 1
    count = len(load(manifest).get('entries', []))
    print(f'PASS: {count} generated sources named with their provenance and bytes')
    return 0


if __name__ == '__main__':
    sys.exit(main())
