#!/usr/bin/env python3
"""Generate the crd-hesap-wavelet ENGINE coefficient table from PyWavelets.

This is the canonical wavelet filter-bank data (like the FFT generated codelets
and the ODE SUNDIALS tableaus) — NOT test data. Stored verbatim from pywt so the
engine matches pywt to machine precision. Plain C arrays (no STL).

Run from repo root:
  python3 scripts/gen_wavelet_coeffs.py > \
    engine/hesap-wavelet/include/crd/hesap/wavelet/detail/wavelet_coeffs.inc
"""
import pywt

# The complete discrete-wavelet catalog (orthogonal + biorthogonal families).
FAMILIES = (
    ["haar"]
    + [f"db{i}" for i in range(1, 21)]
    + [f"sym{i}" for i in range(2, 21)]
    + [f"coif{i}" for i in range(1, 6)]
    + ["bior1.1", "bior1.3", "bior1.5", "bior2.2", "bior2.4", "bior2.6", "bior2.8",
       "bior3.1", "bior3.3", "bior3.5", "bior3.7", "bior3.9", "bior4.4", "bior5.5", "bior6.8"]
    + ["rbio1.1", "rbio1.3", "rbio1.5", "rbio2.2", "rbio2.4", "rbio2.6", "rbio2.8",
       "rbio3.1", "rbio3.3", "rbio3.5", "rbio3.7", "rbio3.9", "rbio4.4", "rbio5.5", "rbio6.8"]
    + ["dmey"]
)


def san(name: str) -> str:
    return name.replace(".", "_").replace("-", "_")


def emit_arr(ident: str, arr) -> None:
    body = ", ".join(f"{x:.17g}" for x in arr)
    print(f"inline constexpr double {ident}[] = {{{body}}};")


def main() -> None:
    print("// GENERATED by scripts/gen_wavelet_coeffs.py — DO NOT EDIT.")
    print("// Wavelet filter banks sourced verbatim from PyWavelets (canonical coefficients).")
    print("// The engine matches pywt to machine precision. Plain C arrays (no STL).")
    print("#pragma once")
    print()
    print("namespace crd::hesap::wavelet::detail")
    print("{")
    print()

    entries = []
    for name in FAMILIES:
        w = pywt.Wavelet(name)
        dec_lo, dec_hi, rec_lo, rec_hi = w.filter_bank
        ln = len(dec_lo)
        assert len(dec_hi) == ln and len(rec_lo) == ln and len(rec_hi) == ln, name
        s = san(name)
        emit_arr(f"wco_{s}_dec_lo", dec_lo)
        emit_arr(f"wco_{s}_dec_hi", dec_hi)
        emit_arr(f"wco_{s}_rec_lo", rec_lo)
        emit_arr(f"wco_{s}_rec_hi", rec_hi)
        entries.append((name, s, ln, bool(w.orthogonal)))

    print()
    print("struct WaveletTableEntry")
    print("{")
    print("    const char* name;")
    print("    const double* dec_lo;")
    print("    const double* dec_hi;")
    print("    const double* rec_lo;")
    print("    const double* rec_hi;")
    print("    int len;")
    print("    bool orthogonal;")
    print("};")
    print()
    print("inline constexpr WaveletTableEntry kWaveletTable[] = {")
    for name, s, ln, orth in entries:
        o = "true" if orth else "false"
        print(f'    {{"{name}", wco_{s}_dec_lo, wco_{s}_dec_hi, wco_{s}_rec_lo, wco_{s}_rec_hi, {ln}, {o}}},')
    print("};")
    print()
    print(f"inline constexpr int kWaveletTableSize = {len(entries)};")
    print()
    print("} // namespace crd::hesap::wavelet::detail")


if __name__ == "__main__":
    main()
