#!/usr/bin/env python3
"""Generate erk_tableaus.hpp from the INSTALLED scipy's Butcher tableaus (v9-b, ADR-0091).

Run (WSL): python3 scripts/gen_erk_tableaus.py > engine/hesap-ode/include/crd/hesap/ode/detail/erk_tableaus.hpp

Extraction beats transcription: RK23/RK45/DOP853 constants are read from scipy's own arrays
(the trajectory-exactness oracle), printed at 17 significant digits (f64 round-trip exact).
Tsit5 / Cash-Karp are NOT in scipy — they live hand-written in erk.hpp with order-slope gates.
"""

import numpy as np
import scipy
from scipy.integrate._ivp import rk
from scipy.integrate._ivp import dop853_coefficients as dc


def fmt(x):
    if x == int(x) and abs(x) < 1e15:
        return f"{x:.1f}"
    return f"{x:.17g}"


def emit_array(name, arr):
    flat = np.asarray(arr, dtype=np.float64).ravel()
    vals = ", ".join(fmt(v) for v in flat)
    print(f"inline constexpr crd::f64 {name}[{len(flat)}] = {{{vals}}};")


print("#pragma once")
print()
print("// erk_tableaus.hpp -- GENERATED by scripts/gen_erk_tableaus.py. DO NOT EDIT BY HAND.")
print(f"// Source: scipy {scipy.__version__} (scipy/integrate/_ivp/rk.py + dop853_coefficients.py),")
print("// printed at 17 significant digits (exact f64 round-trip). A row-major (stages x stages),")
print("// E vectors length stages+1 (the last slot weights f_new). ADR-0091 / v9-b.")
print()
print("#include <crd/core/types.hpp>")
print()
print("namespace crd::hesap::ode::detail")
print("{")
print()
print("// --- RK23 (Bogacki-Shampine 3(2)), scipy class RK23: order 3, error estimator order 2 ---")
emit_array("rk23_c", rk.RK23.C)
A = np.zeros((3, 3))
A[: rk.RK23.A.shape[0], : rk.RK23.A.shape[1]] = rk.RK23.A
emit_array("rk23_a", A)
emit_array("rk23_b", rk.RK23.B)
emit_array("rk23_e", rk.RK23.E)
print()
print("// --- RK45 (Dormand-Prince 5(4)), scipy class RK45: order 5, error estimator order 4 ---")
emit_array("rk45_c", rk.RK45.C)
A = np.zeros((6, 6))
A[: rk.RK45.A.shape[0], : rk.RK45.A.shape[1]] = rk.RK45.A
emit_array("rk45_a", A)
emit_array("rk45_b", rk.RK45.B)
emit_array("rk45_e", rk.RK45.E)
print()
print("// --- DOP853 (Hairer 8(5,3)), scipy class DOP853: order 8, error estimator order 7;")
print("//     the 5th/3rd correction pair E5/E3 feeds the special combined error norm ---")
emit_array("dop853_c", dc.C[: dc.N_STAGES])
emit_array("dop853_a", np.asarray(dc.A[: dc.N_STAGES, : dc.N_STAGES]))
emit_array("dop853_b", dc.B)
emit_array("dop853_e3", rk.DOP853.E3)
emit_array("dop853_e5", rk.DOP853.E5)
print()
print("} // namespace crd::hesap::ode::detail")
