#!/usr/bin/env python3
"""Generate ark_tableaus.hpp from ARKODE's OWN Butcher tables (v9-i, ADR-0091).

Run (WSL): python3 scripts/gen_ark_tableaus.py > engine/hesap/ode/include/crd/hesap/ode/detail/ark_tableaus.hpp
  (path: engine/hesap-ode/include/crd/hesap/ode/detail/ark_tableaus.hpp)

Extraction beats transcription. The IMEX additive-RK pairs (Kennedy & Carpenter 2003 — the
ARK[2]SA family ARKODE's ARKStep IMEX integrator ships) are parsed straight out of SUNDIALS'
X-macro coefficient files at the PINNED v6.4.1 tag (the installed oracle). Each `RCONST(p)/RCONST(q)`
is emitted as the exact f64 expression `p.0 / q.0`: both p and q are < 2^53 so they are represented
exactly, and IEEE division round-to-nearest reproduces ARKODE's coefficient bit-for-bit. That makes
the v9-z work-precision comparison vs ARKODE apples-to-apples by construction.

The ARK[2]SA property: the explicit and implicit halves share b (solution), d (embedded), and c
(abscissae); only A differs. The script ASSERTS this shared-coefficient identity as a parse check.
"""

import re
import sys
import urllib.request

TAG = "v6.4.1"
BASE = f"https://raw.githubusercontent.com/LLNL/sundials/{TAG}/src/arkode"

# (key, erk_table_name, dirk_table_name, stages, human label)
METHODS = [
    ("ark3", "ARKODE_ARK324L2SA_ERK_4_2_3", "ARKODE_ARK324L2SA_DIRK_4_2_3", 4, "ARK3(2)4L[2]SA (Kennedy-Carpenter 2003)"),
    ("ark4", "ARKODE_ARK436L2SA_ERK_6_3_4", "ARKODE_ARK436L2SA_DIRK_6_3_4", 6, "ARK4(3)6L[2]SA (Kennedy-Carpenter 2003)"),
    ("ark5", "ARKODE_ARK548L2SA_ERK_8_4_5", "ARKODE_ARK548L2SA_DIRK_8_4_5", 8, "ARK5(4)8L[2]SA (Kennedy-Carpenter 2003)"),
]


def fetch(name):
    with urllib.request.urlopen(f"{BASE}/{name}", timeout=30) as r:
        return r.read().decode("utf-8")


def block(text, table_name):
    """Return the body between `ARK_BUTCHER_TABLE(name, {` and its matching `})`."""
    start = text.index(f"ARK_BUTCHER_TABLE({table_name},")
    i = text.index("{", start)
    depth = 0
    j = i
    while j < len(text):
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
            if depth == 0:
                return text[i : j + 1]
        j += 1
    raise RuntimeError(f"unterminated block for {table_name}")


# A coefficient RHS is either `RCONST(x)/RCONST(y)` or `RCONST(x)`. Emit the exact f64 expression.
_rc = r"RCONST\(([-0-9.eE]+)\)"


def _lit(tok):
    # `1767732205903.0` style already; ensure a trailing `.0` for plain integers.
    return tok if ("." in tok or "e" in tok or "E" in tok) else tok + ".0"


def rhs_expr(rhs):
    m = re.fullmatch(rf"\s*{_rc}\s*/\s*{_rc}\s*", rhs)
    if m:
        return f"{_lit(m.group(1))} / {_lit(m.group(2))}"
    m = re.fullmatch(rf"\s*{_rc}\s*", rhs)
    if m:
        return _lit(m.group(1))
    raise RuntimeError(f"unparsable coefficient rhs: {rhs!r}")


def parse(body, s):
    A = [["0.0"] * s for _ in range(s)]
    b = ["0.0"] * s
    d = ["0.0"] * s
    c = ["0.0"] * s
    for line in body.splitlines():
        line = line.split("//")[0].strip().rstrip(";").strip()
        m = re.match(r"B->A\[(\d+)\]\[(\d+)\]\s*=\s*(.+)$", line)
        if m:
            A[int(m.group(1))][int(m.group(2))] = rhs_expr(m.group(3))
            continue
        m = re.match(r"B->b\[(\d+)\]\s*=\s*(.+)$", line)
        if m:
            b[int(m.group(1))] = rhs_expr(m.group(2))
            continue
        m = re.match(r"B->d\[(\d+)\]\s*=\s*(.+)$", line)
        if m:
            d[int(m.group(1))] = rhs_expr(m.group(2))
            continue
        m = re.match(r"B->c\[(\d+)\]\s*=\s*(.+)$", line)
        if m:
            c[int(m.group(1))] = rhs_expr(m.group(2))
            continue
    return A, b, d, c


def flat(A):
    return [x for row in A for x in row]


def emit(name, vals):
    body = ", ".join(vals)
    print(f"inline constexpr crd::f64 {name}[{len(vals)}] = {{{body}}};")


def main():
    erk_text = fetch("arkode_butcher_erk.def")
    dirk_text = fetch("arkode_butcher_dirk.def")

    print("#pragma once")
    print()
    print("// ark_tableaus.hpp -- GENERATED by scripts/gen_ark_tableaus.py. DO NOT EDIT BY HAND.")
    print(f"// Source: SUNDIALS ARKODE {TAG} (src/arkode/arkode_butcher_{{erk,dirk}}.def), the installed")
    print("// IMEX oracle. Each RCONST(p)/RCONST(q) emitted as the exact f64 expression p.0/q.0 (p,q < 2^53)")
    print("// => coefficients are bit-identical to ARKODE. A is row-major stages x stages; *_ae = explicit")
    print("// half, *_ai = implicit (ESDIRK, A[i][i]=gamma) half; b = solution, d = embedded, c = abscissae")
    print("// (the ERK and DIRK halves SHARE b/d/c -- the ARK[2]SA property, asserted at generation). v9-i.")
    print()
    print("#include <crd/core/types.hpp>")
    print()
    print("namespace crd::hesap::ode::detail")
    print("{")
    for key, erk_name, dirk_name, s, label in METHODS:
        Ae, be, de, ce = parse(block(erk_text, erk_name), s)
        Ai, bi, di, ci = parse(block(dirk_text, dirk_name), s)
        # ARK[2]SA: shared b/d/c across halves (parse self-check).
        assert be == bi, f"{key}: b mismatch ERK vs DIRK"
        assert de == di, f"{key}: d mismatch ERK vs DIRK"
        assert ce == ci, f"{key}: c mismatch ERK vs DIRK"
        print()
        print(f"// --- {label}: stages={s} ---")
        emit(f"{key}_c", ce)
        emit(f"{key}_ae", flat(Ae))
        emit(f"{key}_ai", flat(Ai))
        emit(f"{key}_b", bi)
        emit(f"{key}_d", di)
    print()
    print("} // namespace crd::hesap::ode::detail")


if __name__ == "__main__":
    sys.exit(main())
