#!/usr/bin/env python3
# v14-a dtype reference corpus (reconstruct-verify-first):
#   1. f32 -> {f16, bf16, fp8e4m3fn, fp8e5m2} RNE conversion pairs from ml_dtypes/numpy
#      (the JAX/safetensors frontier semantics), incl. denormals / RNE ties / saturation /
#      inf / nan edge classes + seeded random values.
#   2. Exhaustive 256-entry fp8 -> f32 decode tables (both formats) + 96-entry f16/bf16 -> f32.
#   3. ggml Q8_0 / Q4_0 block-quant parity vectors — the quantize_row_*_ref algorithms
#      transcribed EXACTLY from ggml-org/ggml src/ggml-quants.c (fetched 2026-07-02).
# Emits tests/hesap-tensor/ref_dtypes.inc as plain C arrays (no std containers in refs).
import numpy as np
import ml_dtypes

OUT = "/mnt/d/Dev/cerid/tests/hesap-tensor/ref_dtypes.inc"

f32 = np.float32


def f32_bits(x):
    return np.frombuffer(np.asarray(x, dtype=np.float32).tobytes(), dtype=np.uint32)[0]


def bits_to_f32(b):
    return np.frombuffer(np.asarray(b, dtype=np.uint32).tobytes(), dtype=np.float32)[0]


# --- the adversarial f32 source corpus (shared by all four formats) ---
edge = [
    0.0, -0.0, 1.0, -1.0, 2.0, 0.5, 1.5, 0.1, -0.1, 3.14159265, -2.71828182,
    # f16 RNE tie: 1 + 2^-11 is exactly halfway between 1.0 and 1+2^-10
    1.0 + 2.0**-11, 1.0 + 3 * 2.0**-11, 1.0 + 2.0**-12,
    # bf16 tie: 1 + 2^-8 halfway
    1.0 + 2.0**-8, 1.0 + 3 * 2.0**-8,
    # f16 range edges
    65504.0, 65520.0, 65535.0, 70000.0, 1e6, -65504.0, -70000.0,
    6.1035156e-05, 6.0975552e-05, 5.9604645e-08, 2.9802322e-08, 1e-8, 1e-10, -1e-10,
    # fp8 e4m3fn edges: max 448, subnormal min 2^-9; e5m2: max 57344, subnorm min 2^-16
    448.0, 449.0, 464.0, 480.0, 500.0, -448.0, -500.0, 1e4,
    57344.0, 61439.0, 61440.0, 65536.0, 1e5, -57344.0, -1e5,
    2.0**-6, 2.0**-7, 2.0**-8, 2.0**-9, 2.0**-10, 3 * 2.0**-10, 2.0**-16, 2.0**-17, 2.0**-18,
    0.0625, 0.0703125, 0.068, 240.0, 232.0, 236.0,
    float("inf"), float("-inf"), float("nan"),
]
rng = np.random.default_rng(1402)
rand = list(rng.normal(0, 10, 40).astype(np.float32)) + \
       list(rng.normal(0, 1e4, 12).astype(np.float32)) + \
       list((rng.random(12) * 1e-4).astype(np.float32))
src = np.array(edge + [float(x) for x in rand], dtype=np.float32)

fmts = [
    ("f16", np.float16, np.uint16),
    ("bf16", ml_dtypes.bfloat16, np.uint16),
    ("e4m3", ml_dtypes.float8_e4m3fn, np.uint8),
    ("e5m2", ml_dtypes.float8_e5m2, np.uint8),
]

lines = []
lines.append("// GENERATED by scripts/v14a_dtypes_corpus.py — ml_dtypes %s / numpy %s reference bits." %
             (ml_dtypes.__version__, np.__version__))
lines.append("// DO NOT hand-edit; regenerate. Plain C arrays (no std containers in refs).")
lines.append("#pragma once")
lines.append("#include <crd/core/types.hpp>")
lines.append("")
lines.append("inline constexpr crd::u32 kRefSrcCount = %dU;" % len(src))
lines.append("inline const crd::u32 kRefSrcF32[] = {")
lines.append("    " + ", ".join("0x%08XU" % f32_bits(v) for v in src))
lines.append("};")

for name, dt, ut in fmts:
    tgt = src.astype(dt)
    bits = np.frombuffer(tgt.tobytes(), dtype=ut)
    suffix = "U"
    lines.append("// f32 -> %s (RNE, ml_dtypes semantics)" % name)
    lines.append("inline const crd::u%d kRefTo_%s[] = {" % (16 if ut == np.uint16 else 8, name))
    lines.append("    " + ", ".join(("0x%04X" + suffix) % b if ut == np.uint16 else ("0x%02X" + suffix) % b
                                    for b in bits))
    lines.append("};")

# --- exhaustive decode tables: every fp8 pattern -> f32 bits ---
for name, dt in [("e4m3", ml_dtypes.float8_e4m3fn), ("e5m2", ml_dtypes.float8_e5m2)]:
    pats = np.arange(256, dtype=np.uint8)
    vals = pats.view(dt).astype(np.float32)
    vbits = np.frombuffer(vals.tobytes(), dtype=np.uint32)
    lines.append("// exhaustive %s -> f32 decode (256 patterns; NaNs canonicalized by the test)" % name)
    lines.append("inline const crd::u32 kRefFrom_%s[256] = {" % name)
    for i in range(0, 256, 8):
        lines.append("    " + ", ".join("0x%08XU" % b for b in vbits[i:i + 8]) + ",")
    lines.append("};")

# --- f16/bf16 -> f32 corpus: edge patterns + seeded random u16 ---
h_edge = [0x0000, 0x8000, 0x0001, 0x8001, 0x03FF, 0x0400, 0x7BFF, 0x7C00, 0xFC00,
          0x7C01, 0x7E00, 0xFE00, 0x3C00, 0xBC00, 0x3555, 0x0200]
h_rand = list(rng.integers(0, 65536, 80).astype(np.uint16))
for name, dt in [("f16", np.float16), ("bf16", ml_dtypes.bfloat16)]:
    pats = np.array(h_edge + [int(x) for x in h_rand], dtype=np.uint16)
    vals = pats.view(dt).astype(np.float32)
    vbits = np.frombuffer(vals.tobytes(), dtype=np.uint32)
    lines.append("inline constexpr crd::u32 kRefHalfCount = %dU;" % len(pats)) if name == "f16" else None
    lines.append("// %s pattern -> f32 bits" % name)
    lines.append("inline const crd::u16 kRefPat_%s[] = {" % name)
    lines.append("    " + ", ".join("0x%04XU" % p for p in pats))
    lines.append("};")
    lines.append("inline const crd::u32 kRefVal_%s[] = {" % name)
    for i in range(0, len(vbits), 8):
        lines.append("    " + ", ".join("0x%08XU" % b for b in vbits[i:i + 8]) + ",")
    lines.append("};")

# --- ggml Q8_0 / Q4_0 reference (transcribed exactly from ggml-quants.c) ---
QK = 32
x = rng.normal(0, 2.5, 128).astype(np.float32)  # 4 blocks
x[5] = 0.0
x[36:68] = 0.0  # an all-zero block: d == 0 path


def fp16_bits(v):
    return int(np.frombuffer(np.float16(v).tobytes(), dtype=np.uint16)[0])


q8_d, q8_qs = [], []
for i in range(4):
    blk = x[i * QK:(i + 1) * QK]
    amax = float(np.max(np.abs(blk)))
    d = f32(amax / 127.0)
    idv = f32(1.0 / d) if d != 0 else f32(0.0)
    q8_d.append(fp16_bits(d))
    for j in range(QK):
        # roundf = round half away from zero
        v = float(f32(blk[j] * idv))
        q = int(np.floor(v + 0.5)) if v >= 0 else int(np.ceil(v - 0.5))
        q8_qs.append(q & 0xFF)

q4_d, q4_qs = [], []
for i in range(4):
    blk = x[i * QK:(i + 1) * QK]
    amax, mx = 0.0, 0.0
    for v in blk:
        if abs(float(v)) > amax:
            amax, mx = abs(float(v)), float(v)
    d = f32(mx / -8.0)
    idv = f32(1.0 / d) if d != 0 else f32(0.0)
    q4_d.append(fp16_bits(d))
    for j in range(QK // 2):
        x0 = float(f32(float(blk[j]) * float(idv))) + 8.5
        x1 = float(f32(float(blk[j + QK // 2]) * float(idv))) + 8.5
        xi0 = min(15, int(x0))  # (int8_t) truncation toward zero (values are >= 0 here)
        xi1 = min(15, int(x1))
        q4_qs.append((xi0 | (xi1 << 4)) & 0xFF)

lines.append("// ggml Q8_0/Q4_0 parity (quantize_row_q8_0_ref / q4_0_ref transcription; 4 blocks of 32)")
lines.append("inline const crd::u32 kGgmlSrcF32[] = {")
for i in range(0, 128, 8):
    lines.append("    " + ", ".join("0x%08XU" % f32_bits(v) for v in x[i:i + 8]) + ",")
lines.append("};")
lines.append("inline const crd::u16 kGgmlQ8Scale[4] = {%s};" % ", ".join("0x%04XU" % b for b in q8_d))
lines.append("inline const crd::u8 kGgmlQ8Qs[128] = {")
for i in range(0, 128, 16):
    lines.append("    " + ", ".join("0x%02XU" % b for b in q8_qs[i:i + 16]) + ",")
lines.append("};")
lines.append("inline const crd::u16 kGgmlQ4Scale[4] = {%s};" % ", ".join("0x%04XU" % b for b in q4_d))
lines.append("inline const crd::u8 kGgmlQ4Qs[64] = {")
for i in range(0, 64, 16):
    lines.append("    " + ", ".join("0x%02XU" % b for b in q4_qs[i:i + 16]) + ",")
lines.append("};")
lines.append("")

with open(OUT, "w") as f:
    f.write("\n".join(l for l in lines if l is not None))
print("wrote", OUT, "src corpus", len(src), "values")

# sanity echoes for the session log
for name, dt, _ in fmts:
    print(name, "448->", np.float32(np.asarray([448.0], np.float32).astype(dt)[0]),
          " 500->", np.float32(np.asarray([500.0], np.float32).astype(dt)[0]))
