#!/usr/bin/env python3
# v14-b elementwise/broadcast reference corpus (reconstruct-verify-first):
# NumPy is the semantics oracle — inputs + EXPECTED OUTPUT BITS for a set of
# broadcast/stride-adversarial cases across add/sub/mul/div/min/max, neg/abs,
# compare(lt), where, and f32<->f64 casts. Emits plain C arrays to
# tests/hesap-tensor/ref_elementwise.inc (no std containers in refs).
import numpy as np

OUT = "/mnt/d/Dev/cerid/tests/hesap-tensor/ref_elementwise.inc"
rng = np.random.default_rng(1407)

lines = [
    "// GENERATED by scripts/v14b_elementwise_corpus.py — numpy %s reference bits." % np.__version__,
    "// DO NOT hand-edit; regenerate. Plain C arrays.",
    "#pragma once",
    "#include <crd/core/types.hpp>",
    "",
]


def emit_u64(name, arr):
    b = np.frombuffer(np.ascontiguousarray(arr, dtype=np.float64).tobytes(), dtype=np.uint64)
    lines.append("inline const crd::u64 %s[] = {" % name)
    for i in range(0, len(b), 6):
        lines.append("    " + ", ".join("0x%016XULL" % x for x in b[i:i + 6]) + ",")
    lines.append("};")


def emit_u32(name, arr):
    b = np.frombuffer(np.ascontiguousarray(arr, dtype=np.float32).tobytes(), dtype=np.uint32)
    lines.append("inline const crd::u32 %s[] = {" % name)
    for i in range(0, len(b), 8):
        lines.append("    " + ", ".join("0x%08XU" % x for x in b[i:i + 8]) + ",")
    lines.append("};")


def emit_u8(name, arr):
    b = np.ascontiguousarray(arr, dtype=np.uint8).reshape(-1)
    lines.append("inline const crd::u8 %s[] = {" % name)
    for i in range(0, len(b), 16):
        lines.append("    " + ", ".join("%uU" % x for x in b[i:i + 16]) + ",")
    lines.append("};")


# ---- case 1 (f64): (2,3,1,4) op (3,5,1) -> (2,3,5,4), all six binaries ----
a1 = rng.normal(0, 3, (2, 3, 1, 4))
b1 = rng.normal(0, 3, (3, 5, 1))
b1.flat[3] = 0.0  # a div-by-zero lane -> inf (bit-exact gate incl. inf)
emit_u64("kEwA1", a1)
emit_u64("kEwB1", b1)
for tag, res in [("Add", a1 + b1), ("Sub", a1 - b1), ("Mul", a1 * b1), ("Div", a1 / b1),
                 ("Min", np.fmin(a1, b1)), ("Max", np.fmax(a1, b1))]:
    emit_u64("kEwR1" + tag, res)

# ---- case 2 (f32): scalar (rank-0) + strided/sliced views ----
a2 = rng.normal(0, 2, (6, 8)).astype(np.float32)
a2v = a2[::2, 1:7]          # (3,6) strided view
b2 = np.float32(2.5)        # rank-0 broadcast
emit_u32("kEwA2", a2)       # full base buffer; the C++ side re-slices identically
emit_u32("kEwR2MulScalar", (a2v * b2))
c2 = rng.normal(0, 2, (6,)).astype(np.float32)
emit_u32("kEwC2", c2)
emit_u32("kEwR2AddRow", (a2v + c2[:6]))   # (3,6)+(6,) row broadcast

# ---- case 3: neg/abs bit semantics incl. +-0 and NaN payloads (f32) ----
special = np.array([0.0, -0.0, 1.5, -1.5, np.inf, -np.inf], dtype=np.float32)
nanpay = np.frombuffer(np.array([0x7FC00001, 0xFFC00001, 0x7F800001], dtype=np.uint32).tobytes(),
                       dtype=np.float32)
a3 = np.concatenate([special, nanpay])
emit_u32("kEwA3", a3)
emit_u32("kEwR3Neg", np.negative(a3))
emit_u32("kEwR3Abs", np.abs(a3))

# ---- case 4: compare(lt) + where, three-way broadcast (f64) ----
a4 = rng.normal(0, 1, (4, 1))
b4 = rng.normal(0, 1, (1, 5))
m4 = (a4 < b4)
emit_u64("kEwA4", a4)
emit_u64("kEwB4", b4)
emit_u8("kEwR4Lt", m4.astype(np.uint8))
emit_u64("kEwR4Where", np.where(m4, a4, b4))

# ---- case 5: casts ----
a5 = np.array([1.0000001, -3.5e38, 3.5e38, 1e-45, 0.1, -0.1, np.pi], dtype=np.float64)
emit_u32("kEwR5Cast32", a5.astype(np.float32))   # RNE incl overflow->inf, denormal
emit_u64("kEwA5", a5)
a5f = a5.astype(np.float32)
emit_u64("kEwR5Cast64", a5f.astype(np.float64))  # exact widening

lines.append("")
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print("wrote", OUT)
