"""v14-d permute-copy corpus generator (ADR-0096 verification protocol).

Emits tests/hesap-tensor/ref_permute.inc: NumPy `np.transpose(...).copy()` reference
bits (f64 as crd::u64 bit patterns, plain C arrays — no std containers in refs) for
three representative permute_copy cases, gated bit-exact by test_permute.cpp:

  A. 2-D odd-size transpose:      (7,13) f64, order (1,0)  [+ the fused alpha=1.5 scale]
  B. rank-4 general permutation:  (2,3,4,5) f64, order (3,0,2,1)
  C. permuted SLICED view source: base (6,7,8) f64, view = base[0:6:2, 1:6, :], order (2,1,0)

Run from the repo root (WSL): python3 scripts/v14d_permute_corpus.py
"""

import os

import numpy as np

OUT = os.path.join(os.path.dirname(__file__), "..", "tests", "hesap-tensor", "ref_permute.inc")


def bits(a):
    """Row-major f64 element bits of `a` as a flat uint64 array."""
    return np.ascontiguousarray(a, dtype=np.float64).view(np.uint64).reshape(-1)


def c_array(name, u64s, per_line=8):
    lines = [f"inline const crd::u64 {name}[] = {{"]
    vals = [f"0x{v:016X}ULL" for v in u64s]
    for i in range(0, len(vals), per_line):
        lines.append("    " + ", ".join(vals[i : i + per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    rng = np.random.default_rng(0xC3D14D)
    blocks = [
        "// GENERATED by scripts/v14d_permute_corpus.py — NumPy "
        + np.__version__
        + " reference bits.",
        "// DO NOT hand-edit; regenerate. Plain C arrays (no std containers in refs).",
        "#pragma once",
        "#include <crd/core/types.hpp>",
        "",
    ]

    # Case A — 2-D odd-size transpose (7,13) -> (13,7), plus the fused scale.
    a = rng.standard_normal((7, 13))
    blocks.append(c_array("kV14dASrc", bits(a)))
    blocks.append(c_array("kV14dAOut", bits(np.transpose(a, (1, 0)).copy())))
    blocks.append(c_array("kV14dAOutScaled", bits((np.float64(1.5) * np.transpose(a, (1, 0))).copy())))

    # Case B — rank-4 (2,3,4,5) with order (3,0,2,1) -> shape (5,2,4,3).
    b = rng.standard_normal((2, 3, 4, 5))
    blocks.append(c_array("kV14dBSrc", bits(b)))
    blocks.append(c_array("kV14dBOut", bits(np.transpose(b, (3, 0, 2, 1)).copy())))

    # Case C — sliced view source: base (6,7,8), view = base[0:6:2, 1:6, :] shape (3,5,8),
    # then order (2,1,0) -> shape (8,5,3).
    c = rng.standard_normal((6, 7, 8))
    blocks.append(c_array("kV14dCBase", bits(c)))
    blocks.append(c_array("kV14dCOut", bits(np.transpose(c[0:6:2, 1:6, :], (2, 1, 0)).copy())))

    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(blocks) + "\n")
    print(f"wrote {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
