#!/usr/bin/env python3
# v14-e path-optimizer corpus (python-verified BEFORE the port, per protocol):
# opt_einsum 3.4.0 is the oracle — for each expression: the greedy path FLOPs
# and the optimal path FLOPs (their own cost model: prod(union) x (1+inner)
# per pairwise step). The C++ gate: our greedy <= their greedy (parity-or-
# better), our optimal == their optimal. Plain C arrays out.
import random
import opt_einsum as oe

OUT = "/mnt/d/Dev/cerid/tests/hesap-tensor/ref_einsum_paths.inc"
rng = random.Random(1407)

cases = []
# classic chains: ij,jk->ik ... up to 7 matrices, mixed sizes
for n in range(2, 8):
    letters = "abcdefgh"
    subs = ",".join(letters[i] + letters[i + 1] for i in range(n))
    out = letters[0] + letters[n]
    sizes = {letters[i]: rng.choice([8, 16, 24, 32, 48, 64]) for i in range(n + 1)}
    cases.append((subs + "->" + out, sizes))
# opt_einsum docs / classic networks
fixed = [
    ("ab,bc,cd->ad", {"a": 32, "b": 16, "c": 64, "d": 8}),
    ("ijk,jkl,klm->im", {"i": 8, "j": 16, "k": 8, "l": 16, "m": 8}),
    ("ea,fb,abcd,gc,hd->efgh", {c: 8 for c in "abcdefgh"}),  # the tensor-network classic
    ("ab,ab->", {"a": 64, "b": 64}),
    ("ab,cd->abcd", {"a": 8, "b": 8, "c": 8, "d": 8}),  # pure outer
    ("abc,bad->dc", {"a": 16, "b": 24, "c": 32, "d": 8}),
    ("ij,jk,kl,li->", {"i": 16, "j": 24, "k": 32, "l": 8}),  # trace ring
]
cases.extend(fixed)
# random networks n=3..7 operands
letters = "abcdefghijklmn"
for trial in range(20):
    n = rng.randint(3, 7)
    nidx = rng.randint(n + 1, min(len(letters), 2 * n + 2))
    idx = letters[:nidx]
    sizes = {c: rng.choice([4, 8, 12, 16, 32]) for c in idx}
    terms = []
    for t in range(n):
        k = rng.randint(2, 4)
        terms.append("".join(rng.sample(idx, k)))
    used = sorted(set("".join(terms)))
    outn = rng.randint(0, min(4, len(used)))
    out = "".join(rng.sample(used, outn))
    expr = ",".join(terms) + "->" + out
    cases.append((expr, sizes))

lines = [
    "// GENERATED by scripts/v14e_einsum_corpus.py — opt_einsum %s oracle paths." % oe.__version__,
    "// DO NOT hand-edit. exprs / per-case dims / greedy+optimal FLOP counts.",
    "#pragma once",
    "#include <crd/core/types.hpp>",
    "",
    "struct EinsumPathCase",
    "{",
    "    const char* expr;",
    "    const char* idx_names;   // index letters, same order as idx_sizes",
    "    const crd::u64* idx_sizes;",
    "    crd::u32 n_idx;",
    "    crd::u64 greedy_flops;   // opt_einsum greedy",
    "    crd::u64 optimal_flops;  // opt_einsum optimal (0 = not computed)",
    "};",
    "",
]

rows = []
for ci, (expr, sizes) in enumerate(cases):
    lhs, rhs = expr.split("->")
    shapes = [tuple(sizes[c] for c in term) for term in lhs.split(",")]
    views = [oe.contract_expression]  # placeholder to keep linters quiet
    gpath, ginfo = oe.contract_path(expr, *shapes, shapes=True, optimize="greedy")
    n_ops = len(lhs.split(","))
    if n_ops <= 7:
        opath, oinfo = oe.contract_path(expr, *shapes, shapes=True, optimize="optimal")
        oflops = int(oinfo.opt_cost)
    else:
        oflops = 0
    names = "".join(sorted(sizes))
    lines.append("inline const crd::u64 kEinSizes%d[] = {%s};"
                 % (ci, ", ".join(str(sizes[c]) + "ULL" for c in names)))
    rows.append('    {"%s", "%s", kEinSizes%d, %dU, %dULL, %dULL},'
                % (expr, names, ci, len(names), int(ginfo.opt_cost), oflops))

lines.append("")
lines.append("inline const EinsumPathCase kEinsumPathCases[] = {")
lines.extend(rows)
lines.append("};")
lines.append("inline constexpr crd::u32 kEinsumPathCaseCount = %dU;" % len(rows))
lines.append("")
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print("wrote", OUT, len(rows), "cases")
