#!/usr/bin/env python3
# v14-g corpus export: freeze the benchmark networks + peer results into a
# plain-C-array .inc for the C++ quality gates (NO std containers in refs —
# the house rule). Peer numbers are RE-MEASURED here (seeded, reproducible)
# so the .inc records exactly what the C++ must beat:
#   - ctg_log10_flops: cotengra HyperOptimizer(greedy+kahypar, 64 trials,
#     seeded 'random' optlib, reconf) — their hq default at its best.
#   - greedy_log10_flops: cotengra T=0 greedy (the sanity floor).
# Run (WSL): python3 scripts/v14g_export_corpus.py
import math
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from v14g_hyperopt_recon import bench_networks

import cotengra as ctg

# their nested random-greedy glue segfaults its loky workers on this host —
# force serial (same trials, no crashes; fairness note in the bench doc)
import cotengra.pathfinders.path_basic as pb

_orig_init = pb.RandomGreedyOptimizer.__init__


def _serial_init(self, *a, **k):
    k["parallel"] = False
    _orig_init(self, *a, **k)


pb.RandomGreedyOptimizer.__init__ = _serial_init

OUT = "/mnt/d/Dev/cerid/tests/hesap-tensor/ref_hyperopt.inc"


def main():
    nets = bench_networks()
    lines = []
    lines.append("// GENERATED by scripts/v14g_export_corpus.py — the v14-g benchmark corpus:")
    lines.append("// cotengra 0.8.2 benchmark networks (rand_equation/lattice_equation, seed")
    lines.append("// 1407) + FROZEN peer results (cotengra greedy+kahypar @64 seeded trials +")
    lines.append("// reconf; their hq default). The C++ gate: hyper_optimize at the same trial")
    lines.append("// budget must land log10(flops) <= ctg_log10_flops per network.")
    total_terms = 0
    total_ids = 0
    for (tag, inputs, output, size_dict) in nets:
        # peer 1: their T=0 greedy floor
        path = ctg.array_contract_path(inputs, output, size_dict=size_dict, optimize="greedy")
        tree = ctg.ContractionTree.from_path(inputs, output, size_dict, path=path)
        greedy_l10 = math.log10(max(int(tree.contraction_cost()), 1))
        # peer 2: their hyper default at matched budget
        opt = ctg.HyperOptimizer(methods=["greedy", "kahypar"], max_repeats=64,
                                 parallel=False, optlib="random",
                                 optlib_opts={"seed": 3}, minimize="flops",
                                 reconf_opts={})
        ct = opt.search(inputs, output, size_dict)
        st = ct.contract_stats()
        ctg_l10 = math.log10(max(int(st["flops"]), 1))
        ctg_l2sz = math.log2(max(int(st["size"]), 1))
        # index interning: name -> id in first-appearance order
        idmap = {}
        for term in inputs:
            for ind in term:
                if ind not in idmap:
                    idmap[ind] = len(idmap)
        for ind in output:
            if ind not in idmap:
                idmap[ind] = len(idmap)
        nix = len(idmap)
        sizes = [0] * nix
        for ind, ix in idmap.items():
            sizes[ix] = int(size_dict[ind])
        term_ids = []
        term_off = [0]
        for term in inputs:
            term_ids.extend(idmap[ind] for ind in term)
            term_off.append(len(term_ids))
        out_ids = [idmap[ind] for ind in output]
        total_terms += len(inputs)
        total_ids += len(term_ids)
        c = tag.replace("-", "_")
        lines.append(f"// --- {tag}: {len(inputs)} tensors, {nix} indices ---")
        lines.append(f"inline constexpr crd::u32 kHy_{c}_n_terms = {len(inputs)}U;")
        lines.append(f"inline constexpr crd::u32 kHy_{c}_n_indices = {nix}U;")
        lines.append(f"inline constexpr crd::u64 kHy_{c}_sizes[] = {{{', '.join(str(s) + 'U' for s in sizes)}}};")
        lines.append(f"inline constexpr crd::u32 kHy_{c}_term_off[] = {{{', '.join(str(o) + 'U' for o in term_off)}}};")
        lines.append(f"inline constexpr crd::u32 kHy_{c}_term_ids[] = {{{', '.join(str(i) + 'U' for i in term_ids)}}};")
        if out_ids:
            lines.append(f"inline constexpr crd::u32 kHy_{c}_out_ids[] = {{{', '.join(str(i) + 'U' for i in out_ids)}}};")
            lines.append(f"inline constexpr crd::u32 kHy_{c}_n_out = {len(out_ids)}U;")
        else:
            lines.append(f"inline constexpr crd::u32 kHy_{c}_out_ids[] = {{0U}}; // unused (closed network)")
            lines.append(f"inline constexpr crd::u32 kHy_{c}_n_out = 0U;")
        lines.append(f"inline constexpr double kHy_{c}_greedy_log10 = {greedy_l10!r};")
        lines.append(f"inline constexpr double kHy_{c}_ctg_log10 = {ctg_l10!r};")
        lines.append(f"inline constexpr double kHy_{c}_ctg_log2size = {ctg_l2sz!r};")
        print(f"[{tag:9s}] greedy {greedy_l10:.4f}  ctg-hq {ctg_l10:.4f}  log2sz {ctg_l2sz:.2f}", flush=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}: {len(nets)} networks, {total_terms} terms, {total_ids} ids", flush=True)


if __name__ == "__main__":
    main()
