#!/usr/bin/env python3
# v14-i SPARSE tensor oracle — reconstruct-verify-first (SANITY doctrine).
#
# Default mode: generate tests/hesap-tensor/ref_sparse.inc — frozen corpora
# (random COO rank-3/4 with duplicate raw triplets, a structured FROSTT-like
# fiber pattern with an all-empty mode-0 slice, a dense-as-sparse cube) plus
# expected values computed with numpy DENSE semantics (the scipy/torch
# reference semantics): canonical dedup COO, MTTKRP per mode, mode-n
# sparse x dense contraction (tensor layout, mode replaced), sparse
# elementwise add/mul (union/intersection) + sparse x dense hadamard +
# sparse + dense -> dense, and sum/max reductions (total + per mode,
# implicit zeros participate in max exactly like a densified array).
#
# --bench: write the big bench corpora as binary files under
# $HOME/cerid-bench-data/ (shared bit-exact with the C++ harness) and run the
# python peer timings (scipy.sparse csr + torch.sparse, matched 1 thread,
# best-of-5). Run pinned: taskset -c 4 python3 scripts/v14i_sparse_oracle.py --bench
#
# Values are emitted as u64 hex bit patterns (the house ref_*.inc convention)
# so the C++ side consumes the exact bits numpy used.
import argparse
import os
import struct
import sys
import time

import numpy as np

SEED = 20260705
OUT_INC = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "tests", "hesap-tensor", "ref_sparse.inc")
BENCH_DIR = os.path.join(os.path.expanduser("~"), "cerid-bench-data")


# ---------------------------------------------------------------------------
# corpus helpers
# ---------------------------------------------------------------------------

def canonicalize(idx_raw, val_raw, shape):
    """Stable lexicographic sort (mode 0 major) + duplicate sum in insertion
    order (np.lexsort is stable; reduceat sums left-to-right) — the exact
    contract of the C++ builder, so canonical values are BIT-comparable."""
    rank = len(shape)
    keys = tuple(idx_raw[:, m] for m in range(rank - 1, -1, -1))
    order = np.lexsort(keys)
    si = idx_raw[order]
    sv = val_raw[order]
    if len(sv) == 0:
        return si.reshape(0, rank), sv
    new = np.ones(len(sv), dtype=bool)
    new[1:] = np.any(si[1:] != si[:-1], axis=1)
    starts = np.flatnonzero(new)
    vals = np.add.reduceat(sv, starts)
    return si[starts], vals


def densify(idx, val, shape):
    x = np.zeros(shape, dtype=np.float64)
    x[tuple(idx[:, m] for m in range(len(shape)))] = val
    return x


def make_random_coo(rng, shape, n_unique, n_raw):
    """raw triplets drawn WITH replacement from a unique cell pool -> dups."""
    total = int(np.prod(shape))
    flat = rng.choice(total, size=n_unique, replace=False)
    pool = np.stack(np.unravel_index(flat, shape), axis=1).astype(np.uint32)
    pick = rng.integers(0, n_unique, size=n_raw)
    idx_raw = pool[pick]
    val_raw = rng.uniform(-1.0, 1.0, size=n_raw)
    return idx_raw, val_raw


def make_frostt_like(rng, shape, n_fibers, skip_mode0):
    """FROSTT-like: (i,j) fiber pairs with short k runs; i zipf-skewed;
    mode-0 index `skip_mode0` left completely empty (the all-zeros-slice
    adversary)."""
    rows = []
    for _ in range(n_fibers):
        i = int(shape[0] * rng.random() ** 2.0)
        i = min(i, shape[0] - 1)
        if i == skip_mode0:
            i = (i + 1) % shape[0]
        j = int(rng.integers(0, shape[1]))
        length = int(rng.integers(2, 11))
        k0 = int(rng.integers(0, shape[2]))
        for t in range(length):
            k = (k0 + t) % shape[2]
            rows.append((i, j, k))
    idx_raw = np.array(rows, dtype=np.uint32)
    val_raw = rng.uniform(-1.0, 1.0, size=len(rows))
    return idx_raw, val_raw


# ---------------------------------------------------------------------------
# .inc emission
# ---------------------------------------------------------------------------

def f64_bits(a):
    return np.asarray(a, dtype=np.float64).reshape(-1).view(np.uint64)


class Inc:
    def __init__(self):
        self.lines = [
            "// GENERATED by scripts/v14i_sparse_oracle.py -- numpy {} reference bits.".format(np.__version__),
            "// DO NOT hand-edit; regenerate. Plain C arrays; f64 values as u64 bit patterns.",
            "#pragma once",
            "#include <crd/core/types.hpp>",
            "",
        ]

    def u32(self, name, arr):
        arr = np.asarray(arr, dtype=np.uint64).reshape(-1)
        self._arr(name, "crd::u32", ["{}U".format(int(v)) for v in arr], 16)

    def u64(self, name, arr):
        arr = np.asarray(arr, dtype=np.uint64).reshape(-1)
        self._arr(name, "crd::u64", ["{}ULL".format(int(v)) for v in arr], 12)

    def f64(self, name, arr):
        bits = f64_bits(arr)
        self._arr(name, "crd::u64", ["0x{:016X}ULL".format(int(v)) for v in bits], 6)

    def scalar_u32(self, name, v):
        self.lines.append("inline constexpr crd::u32 {} = {}U;".format(name, int(v)))

    def _arr(self, name, ctype, toks, per_line):
        self.lines.append("inline const {} {}[] = {{".format(ctype, name))
        for i in range(0, len(toks), per_line):
            self.lines.append("    " + ", ".join(toks[i:i + per_line]) + ",")
        if not toks:
            self.lines.append("    0,  // empty array placeholder (count constant is 0)")
        self.lines.append("};")

    def write(self, path):
        with open(path, "w", newline="\n") as f:
            f.write("\n".join(self.lines) + "\n")


MTT_EINSUM = {
    (3, 0): "ijk,jr,kr->ir", (3, 1): "ijk,ir,kr->jr", (3, 2): "ijk,ir,jr->kr",
    (4, 0): "ijkl,jr,kr,lr->ir", (4, 2): "ijkl,ir,jr,lr->kr",
}
TTM_EINSUM = {
    (3, 0): "ijk,if->fjk", (3, 1): "ijk,jf->ifk", (3, 2): "ijk,kf->ijf",
    (4, 3): "ijkl,lf->ijkf",
}


def emit_corpus(inc, rng, tag, shape, idx_raw, val_raw, fac_r, mtt_modes, ttm_modes,
                sum_modes, max_modes, totals):
    rank = len(shape)
    idx, val = canonicalize(idx_raw, val_raw, shape)
    dense = densify(idx, val, shape)
    inc.scalar_u32("kSp{}Rank".format(tag), rank)
    inc.u64("kSp{}Shape".format(tag), np.array(shape, dtype=np.uint64))
    inc.scalar_u32("kSp{}RawNnz".format(tag), len(val_raw))
    inc.u32("kSp{}RawIdx".format(tag), idx_raw.reshape(-1))          # triplet-major
    inc.f64("kSp{}RawVal".format(tag), val_raw)
    inc.scalar_u32("kSp{}Nnz".format(tag), len(val))
    inc.u32("kSp{}Idx".format(tag), idx.T.reshape(-1))               # mode-major planes
    inc.f64("kSp{}Val".format(tag), val)

    facs = [rng.uniform(-1.0, 1.0, size=(shape[m], fac_r)) for m in range(rank)]
    inc.scalar_u32("kSp{}FacR".format(tag), fac_r)
    for m in range(rank):
        inc.f64("kSp{}Fac{}".format(tag, m), facs[m])
    for m in mtt_modes:
        args = [facs[q] for q in range(rank) if q != m]
        out = np.einsum(MTT_EINSUM[(rank, m)], dense, *args)
        inc.f64("kSp{}Mtt{}".format(tag, m), out)
    for m, fdim in ttm_modes:
        u = rng.uniform(-1.0, 1.0, size=(shape[m], fdim))
        out = np.einsum(TTM_EINSUM[(rank, m)], dense, u)
        inc.scalar_u32("kSp{}TtmF{}".format(tag, m), fdim)
        inc.f64("kSp{}TtmU{}".format(tag, m), u)
        inc.f64("kSp{}Ttm{}".format(tag, m), out)
    for m in sum_modes:
        axes = tuple(q for q in range(rank) if q != m)
        inc.f64("kSp{}SumMode{}".format(tag, m), dense.sum(axis=axes))
    for m in max_modes:
        axes = tuple(q for q in range(rank) if q != m)
        inc.f64("kSp{}MaxMode{}".format(tag, m), dense.max(axis=axes))
    if totals:
        inc.f64("kSp{}SumTotal".format(tag), [dense.sum()])
        inc.f64("kSp{}MaxTotal".format(tag), [dense.max()])
    return idx, val, dense


def generate_inc():
    rng = np.random.default_rng(SEED)
    inc = Inc()

    # R3a: rank-3 random with duplicate raw triplets
    shape3 = (14, 12, 10)
    idx_raw, val_raw = make_random_coo(rng, shape3, n_unique=360, n_raw=400)
    r3a_idx, r3a_val, r3a_dense = emit_corpus(
        inc, rng, "R3a", shape3, idx_raw, val_raw, fac_r=8,
        mtt_modes=[0, 1, 2], ttm_modes=[(0, 6), (1, 5)],
        sum_modes=[0, 1, 2], max_modes=[0, 1, 2], totals=True)

    # R3b: second rank-3 tensor for elementwise; pattern overlaps R3a
    n_overlap = 120
    pick = rng.choice(len(r3a_val), size=n_overlap, replace=False)
    fresh_flat = rng.choice(int(np.prod(shape3)), size=260, replace=False)
    fresh = np.stack(np.unravel_index(fresh_flat, shape3), axis=1).astype(np.uint32)
    idx_raw_b = np.concatenate([r3a_idx[pick].astype(np.uint32), fresh], axis=0)
    val_raw_b = rng.uniform(-1.0, 1.0, size=len(idx_raw_b))
    r3b_idx, r3b_val, r3b_dense = emit_corpus(
        inc, rng, "R3b", shape3, idx_raw_b, val_raw_b, fac_r=8,
        mtt_modes=[], ttm_modes=[], sum_modes=[], max_modes=[], totals=False)

    # elementwise expectations (union add / intersection mul / dense ops)
    a_set = {tuple(t) for t in r3a_idx}
    b_set = {tuple(t) for t in r3b_idx}
    union = sorted(a_set | b_set)
    inter = sorted(a_set & b_set)
    add_idx = np.array(union, dtype=np.uint32)
    add_val = np.array([r3a_dense[t] + r3b_dense[t] for t in union])
    mul_idx = np.array(inter, dtype=np.uint32)
    mul_val = np.array([r3a_dense[t] * r3b_dense[t] for t in inter])
    inc.scalar_u32("kSpEwAddNnz", len(add_val))
    inc.u32("kSpEwAddIdx", add_idx.T.reshape(-1))
    inc.f64("kSpEwAddVal", add_val)
    inc.scalar_u32("kSpEwMulNnz", len(mul_val))
    inc.u32("kSpEwMulIdx", mul_idx.T.reshape(-1))
    inc.f64("kSpEwMulVal", mul_val)
    dmat = rng.uniform(-1.0, 1.0, size=shape3)
    inc.f64("kSpEwDenseD", dmat)
    hadamard = np.array([r3a_dense[tuple(t)] * dmat[tuple(t)] for t in r3a_idx])
    inc.f64("kSpEwMulDenseVal", hadamard)   # pattern of R3a canonical
    inc.f64("kSpEwAddDenseOut", r3a_dense + dmat)

    # R4a: rank-4 random with dups
    shape4 = (9, 8, 7, 6)
    idx_raw4, val_raw4 = make_random_coo(rng, shape4, n_unique=320, n_raw=350)
    emit_corpus(inc, rng, "R4a", shape4, idx_raw4, val_raw4, fac_r=8,
                mtt_modes=[0, 2], ttm_modes=[(3, 4)],
                sum_modes=[1], max_modes=[2], totals=True)

    # Fro: structured FROSTT-like fibers, mode-0 slice 7 completely empty
    shapef = (32, 24, 16)
    idx_rawf, val_rawf = make_frostt_like(rng, shapef, n_fibers=90, skip_mode0=7)
    emit_corpus(inc, rng, "Fro", shapef, idx_rawf, val_rawf, fac_r=16,
                mtt_modes=[0, 1], ttm_modes=[],
                sum_modes=[0], max_modes=[0], totals=True)

    # Dns: dense-as-sparse cube (every cell present -> max branches without
    # implicit zeros; negative maxima possible)
    shaped = (4, 3, 2)
    cells = np.stack(np.unravel_index(np.arange(24), shaped), axis=1).astype(np.uint32)
    valsd = rng.uniform(-1.0, -0.05, size=24)  # all negative: max_total < 0
    emit_corpus(inc, rng, "Dns", shaped, cells, valsd, fac_r=3,
                mtt_modes=[0], ttm_modes=[(2, 3)],
                sum_modes=[], max_modes=[0], totals=True)

    inc.write(OUT_INC)
    print("wrote", OUT_INC, "({} lines)".format(len(inc.lines)))


# ---------------------------------------------------------------------------
# bench: shared binary corpora + python peer timings
# ---------------------------------------------------------------------------

def write_coo_bin(path, idx, val, shape):
    """header: u64 rank, u64 shape[rank], u64 nnz; then mode-major u32 index
    planes; then f64 values."""
    rank = len(shape)
    with open(path, "wb") as f:
        f.write(struct.pack("<Q", rank))
        f.write(struct.pack("<{}Q".format(rank), *shape))
        f.write(struct.pack("<Q", len(val)))
        for m in range(rank):
            f.write(idx[:, m].astype(np.uint32).tobytes())
        f.write(val.astype(np.float64).tobytes())


def write_mat_bin(path, a):
    with open(path, "wb") as f:
        f.write(struct.pack("<QQ", a.shape[0], a.shape[1]))
        f.write(np.ascontiguousarray(a, dtype=np.float64).tobytes())


def best_of(fn, n=5):
    best = None
    for _ in range(n):
        t0 = time.perf_counter()
        r = fn()
        dt = (time.perf_counter() - t0) * 1e3
        best = dt if best is None or dt < best else best
    return best, r


def run_bench():
    import scipy.sparse as sp
    import torch
    torch.set_num_threads(1)

    os.makedirs(BENCH_DIR, exist_ok=True)
    rng = np.random.default_rng(SEED + 1)
    I = J = K = 1024
    NNZ_RAW = 5_000_000
    R = 16
    F = 16
    shape = (I, J, K)

    print("== bench corpus: shape ({},{},{}), raw nnz {}, R={}, F={} ==".format(I, J, K, NNZ_RAW, R, F))
    flat = rng.choice(I * J * K, size=NNZ_RAW, replace=False)
    idx = np.stack(np.unravel_index(flat, shape), axis=1).astype(np.uint32)
    val = rng.uniform(-1.0, 1.0, size=NNZ_RAW)
    idx, val = canonicalize(idx, val, shape)
    nnz = len(val)
    print("canonical nnz:", nnz)

    fb = rng.uniform(-1.0, 1.0, size=(J, R))
    fc = rng.uniform(-1.0, 1.0, size=(K, R))
    u1 = rng.uniform(-1.0, 1.0, size=(J, F))
    u2 = rng.uniform(-1.0, 1.0, size=(K, F))

    # second tensor for elementwise (same size, ~50% pattern overlap)
    keep = rng.random(nnz) < 0.5
    flat2 = rng.choice(I * J * K, size=NNZ_RAW // 2, replace=False)
    idx2 = np.concatenate([idx[keep],
                           np.stack(np.unravel_index(flat2, shape), axis=1).astype(np.uint32)], axis=0)
    val2 = rng.uniform(-1.0, 1.0, size=len(idx2))
    idx2, val2 = canonicalize(idx2, val2, shape)

    write_coo_bin(os.path.join(BENCH_DIR, "v14i_t1.bin"), idx, val, shape)
    write_coo_bin(os.path.join(BENCH_DIR, "v14i_t2.bin"), idx2, val2, shape)
    write_mat_bin(os.path.join(BENCH_DIR, "v14i_fb.bin"), fb)
    write_mat_bin(os.path.join(BENCH_DIR, "v14i_fc.bin"), fc)
    write_mat_bin(os.path.join(BENCH_DIR, "v14i_u1.bin"), u1)
    write_mat_bin(os.path.join(BENCH_DIR, "v14i_u2.bin"), u2)
    # SPLATT text format (1-indexed .tns)
    tns = os.path.join(BENCH_DIR, "v14i_t1.tns")
    if not os.path.exists(tns):
        with open(tns, "w") as f:
            for t in range(nnz):
                f.write("{} {} {} {:.17g}\n".format(idx[t, 0] + 1, idx[t, 1] + 1, idx[t, 2] + 1, val[t]))
    print("bench data written to", BENCH_DIR)

    i32 = idx.astype(np.int64)
    # ---- scipy peers (prep outside timers: csr unfoldings) ----
    x0 = sp.csr_matrix((val, (i32[:, 0], i32[:, 1] * K + i32[:, 2])), shape=(I, J * K))
    x1r = sp.csr_matrix((val, (i32[:, 0] * K + i32[:, 2], i32[:, 1])), shape=(I * K, J))  # rows=(i,k), cols=j
    kr = np.einsum("jr,kr->jkr", fb, fc).reshape(J * K, R)

    t, m_sci = best_of(lambda: x0 @ kr)
    print("scipy  mttkrp-mode0      : {:9.2f} ms   checksum {:.17g}".format(t, float(m_sci.sum())))

    def sci_ttm1():
        y = x1r @ u1                       # [(i,k), f]
        y = y.reshape(I, K, F)
        return np.ascontiguousarray(np.moveaxis(y, 2, 1))  # fold to (i, f, k)
    t, y_sci = best_of(sci_ttm1)
    print("scipy  ttm-mode1 (fold)  : {:9.2f} ms   checksum {:.17g}".format(t, float(y_sci.sum())))

    def sci_ttm2():
        # mode-2 (last): unfold rows=(i,j), cols=k -> result [(i,j), f] IS the folded (i,j,f)
        return x2r @ u2
    x2r = sp.csr_matrix((val, (i32[:, 0] * J + i32[:, 1], i32[:, 2])), shape=(I * J, K))
    t, y2_sci = best_of(sci_ttm2)
    print("scipy  ttm-mode2         : {:9.2f} ms   checksum {:.17g}".format(t, float(y2_sci.sum())))

    i32b = idx2.astype(np.int64)
    a2d = sp.csr_matrix((val, (i32[:, 0], i32[:, 1] * K + i32[:, 2])), shape=(I, J * K))
    b2d = sp.csr_matrix((val2, (i32b[:, 0], i32b[:, 1] * K + i32b[:, 2])), shape=(I, J * K))
    t, s_add = best_of(lambda: a2d + b2d)
    print("scipy  sparse add        : {:9.2f} ms   checksum {:.17g}".format(t, float(s_add.sum())))
    t, s_mul = best_of(lambda: a2d.multiply(b2d))
    print("scipy  sparse mul        : {:9.2f} ms   checksum {:.17g}".format(t, float(s_mul.sum())))
    t, s_sum = best_of(lambda: a2d.sum())
    print("scipy  reduce sum-total  : {:9.2f} ms   checksum {:.17g}".format(t, float(s_sum)))
    t, s_sum0 = best_of(lambda: np.asarray(a2d.sum(axis=1)).ravel())
    print("scipy  reduce sum-mode0  : {:9.2f} ms   checksum {:.17g}".format(t, float(s_sum0.sum())))
    t, s_max0 = best_of(lambda: a2d.max(axis=1).toarray().ravel())
    print("scipy  reduce max-mode0  : {:9.2f} ms   checksum {:.17g}".format(t, float(s_max0.sum())))

    # ---- torch peers (sparse csr where supported, matched 1 thread) ----
    tx0 = torch.sparse_coo_tensor(
        np.stack([i32[:, 0], i32[:, 1] * K + i32[:, 2]]), val, (I, J * K)).coalesce().to_sparse_csr()
    tkr = torch.from_numpy(kr)
    t, tm = best_of(lambda: torch.mm(tx0, tkr))
    print("torch  mttkrp-mode0      : {:9.2f} ms   checksum {:.17g}".format(t, float(tm.sum())))

    tx1 = torch.sparse_coo_tensor(
        np.stack([i32[:, 0] * K + i32[:, 2], i32[:, 1]]), val, (I * K, J)).coalesce().to_sparse_csr()
    tu1 = torch.from_numpy(u1)

    def tor_ttm1():
        y = torch.mm(tx1, tu1).reshape(I, K, F)
        return y.permute(0, 2, 1).contiguous()
    t, ty = best_of(tor_ttm1)
    print("torch  ttm-mode1 (fold)  : {:9.2f} ms   checksum {:.17g}".format(t, float(ty.sum())))

    tx2 = torch.sparse_coo_tensor(
        np.stack([i32[:, 0] * J + i32[:, 1], i32[:, 2]]), val, (I * J, K)).coalesce().to_sparse_csr()
    tu2 = torch.from_numpy(u2)
    t, ty2 = best_of(lambda: torch.mm(tx2, tu2))
    print("torch  ttm-mode2         : {:9.2f} ms   checksum {:.17g}".format(t, float(ty2.sum())))

    ta = torch.sparse_coo_tensor(i32.T, val, shape).coalesce()
    tb = torch.sparse_coo_tensor(i32b.T, val2, shape).coalesce()
    t, t_add = best_of(lambda: torch.add(ta, tb).coalesce())
    print("torch  sparse add        : {:9.2f} ms   checksum {:.17g}".format(t, float(t_add.values().sum())))
    try:
        t, t_mul = best_of(lambda: torch.mul(ta, tb).coalesce())
        print("torch  sparse mul        : {:9.2f} ms   checksum {:.17g}".format(t, float(t_mul.values().sum())))
    except Exception as e:  # noqa: BLE001 — peer capability probe
        print("torch  sparse mul        : N/A ({})".format(type(e).__name__))
    t, t_sum = best_of(lambda: torch.sparse.sum(ta))
    print("torch  reduce sum-total  : {:9.2f} ms   checksum {:.17g}".format(t, float(t_sum)))
    t, t_sum0 = best_of(lambda: torch.sparse.sum(ta, dim=(1, 2)))
    print("torch  reduce sum-mode0  : {:9.2f} ms   checksum {:.17g}".format(t, float(t_sum0.to_dense().sum())))
    print("(torch sparse max reduction: unsupported by torch.sparse — N/A row)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bench", action="store_true")
    args = ap.parse_args()
    if args.bench:
        run_bench()
    else:
        generate_inc()


if __name__ == "__main__":
    sys.exit(main())
