# Pinned CPM bootstrap: the version, URL and SHA-256 live in cmake/pins.json (tools/cpm); the file is verified
# whether it was just downloaded or already present, and re-downloaded when it does not match.
include("${CMAKE_CURRENT_LIST_DIR}/CrdPins.cmake")

crd_pin(CPM_DOWNLOAD_VERSION tools cpm version)
crd_pin(_crd_cpm_hash tools cpm sha256)
crd_pinned_source(_crd_cpm_source tools cpm)

if(CPM_SOURCE_CACHE)
    set(CPM_DOWNLOAD_LOCATION "${CPM_SOURCE_CACHE}/cpm/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
elseif(DEFINED ENV{CPM_SOURCE_CACHE})
    set(CPM_DOWNLOAD_LOCATION "$ENV{CPM_SOURCE_CACHE}/cpm/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
else()
    set(CPM_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
endif()

get_filename_component(CPM_DOWNLOAD_LOCATION ${CPM_DOWNLOAD_LOCATION} ABSOLUTE)

function(download_cpm)
    message(STATUS "Downloading CPM.cmake ${CPM_DOWNLOAD_VERSION} to ${CPM_DOWNLOAD_LOCATION}")
    set(partial "${CPM_DOWNLOAD_LOCATION}.partial")
    get_filename_component(directory "${CPM_DOWNLOAD_LOCATION}" DIRECTORY)
    file(MAKE_DIRECTORY "${directory}")
    file(REMOVE "${partial}")
    if(IS_ABSOLUTE "${_crd_cpm_source}" AND EXISTS "${_crd_cpm_source}")
        file(COPY_FILE "${_crd_cpm_source}" "${partial}")
        file(SHA256 "${partial}" actual)
        if(NOT actual STREQUAL _crd_cpm_hash)
            file(REMOVE "${partial}")
            message(FATAL_ERROR "Local CPM.cmake ${_crd_cpm_source} does not match cmake/pins.json: ${actual}")
        endif()
    else()
        file(DOWNLOAD "${_crd_cpm_source}" "${partial}" EXPECTED_HASH "SHA256=${_crd_cpm_hash}" STATUS status)
        list(GET status 0 code)
        if(NOT code EQUAL 0)
            file(REMOVE "${partial}")
            message(FATAL_ERROR "Downloading CPM.cmake ${CPM_DOWNLOAD_VERSION} failed or did not match cmake/pins.json: ${status}")
        endif()
    endif()
    file(RENAME "${partial}" "${CPM_DOWNLOAD_LOCATION}")
endfunction()

set(_crd_cpm_present FALSE)
if(EXISTS "${CPM_DOWNLOAD_LOCATION}")
    file(SHA256 "${CPM_DOWNLOAD_LOCATION}" _crd_cpm_actual)
    if(_crd_cpm_actual STREQUAL _crd_cpm_hash)
        set(_crd_cpm_present TRUE)
    else()
        message(STATUS "CPM.cmake at ${CPM_DOWNLOAD_LOCATION} does not match cmake/pins.json; refreshing")
    endif()
endif()
if(NOT _crd_cpm_present)
    download_cpm()
endif()
unset(_crd_cpm_present)
unset(_crd_cpm_actual)

include(${CPM_DOWNLOAD_LOCATION})
