# The native solution projects the canonical MSVC presets; Ninja presets remain unchanged.
include_guard(GLOBAL)
option(CRD_NATIVE_PROFILES "Expose canonical MSVC profiles in a native Visual Studio solution" OFF)

if(CRD_NATIVE_PROFILES)
    if(NOT CMAKE_GENERATOR MATCHES "^Visual Studio" OR NOT CMAKE_CXX_COMPILER_ID STREQUAL "MSVC"
       OR NOT CMAKE_GENERATOR_PLATFORM STREQUAL "x64")
        message(FATAL_ERROR "CRD_NATIVE_PROFILES requires a native MSVC x64 Visual Studio generator")
    endif()
    if(CRD_ENABLE_CLANG_TIDY)
        message(FATAL_ERROR "Visual Studio generators do not run CMAKE_CXX_CLANG_TIDY; use the win-tidy preset")
    endif()
    find_package(Python3 3.12 REQUIRED COMPONENTS Interpreter)
    set(_crd_profiles "${CMAKE_BINARY_DIR}/cerid-native-profiles.cmake")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
        "${PROJECT_SOURCE_DIR}/CMakePresets.json" "${PROJECT_SOURCE_DIR}/scripts/native_build_profiles.py")
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/scripts/native_build_profiles.py"
        "${PROJECT_SOURCE_DIR}/CMakePresets.json" "${_crd_profiles}" COMMAND_ERROR_IS_FATAL ANY)
    include("${_crd_profiles}")
    set(CMAKE_CONFIGURATION_TYPES "${CRD_NATIVE_CONFIGS}" CACHE STRING "Native MSVC configurations" FORCE)
    set(CMAKE_BUILD_TYPE "" CACHE STRING "Unused by native multi-config builds" FORCE)
    # Apply IPO after target creation: global per-config defaults would override explicit target OFF scars.
    unset(CMAKE_INTERPROCEDURAL_OPTIMIZATION CACHE)
    unset(CMAKE_INTERPROCEDURAL_OPTIMIZATION)
    set(_crd_debug_crt)
    set(_crd_debug_info)
    foreach(config IN LISTS CRD_NATIVE_CONFIGS)
        string(TOUPPER "${config}" upper)
        set(base "${CRD_PROFILE_${config}_CMAKE_BUILD_TYPE}")
        string(TOUPPER "${base}" base_upper)
        unset(CMAKE_INTERPROCEDURAL_OPTIMIZATION_${upper} CACHE)
        unset(CMAKE_INTERPROCEDURAL_OPTIMIZATION_${upper})
        if(base STREQUAL "Debug")
            list(APPEND _crd_debug_crt "${config}")
        endif()
        if(NOT base STREQUAL "Release" OR CRD_PROFILE_${config}_CRD_SHIPPING)
            list(APPEND _crd_debug_info "${config}")
        endif()
        if(NOT config STREQUAL base)
            foreach(language C CXX)
                # C is enabled later by some dependencies, so fall back to the equivalent C++ base flags.
                if(DEFINED CMAKE_${language}_FLAGS_${base_upper})
                    set(flags "${CMAKE_${language}_FLAGS_${base_upper}}")
                else()
                    set(flags "${CMAKE_CXX_FLAGS_${base_upper}}")
                endif()
                if(CRD_PROFILE_${config}_CRD_ENABLE_ASAN)
                    string(REGEX REPLACE "[/|-]RTC[^ ]*" "" flags "${flags}")
                    # Edit-and-continue is incompatible with MSVC AddressSanitizer.
                    string(REPLACE "/ZI" "/Zi" flags "${flags}")
                endif()
                set(CMAKE_${language}_FLAGS_${upper} "${flags}" CACHE STRING "${config} compiler flags" FORCE)
            endforeach()
            foreach(kind EXE SHARED MODULE STATIC)
                set(CMAKE_${kind}_LINKER_FLAGS_${upper} "${CMAKE_${kind}_LINKER_FLAGS_${base_upper}}"
                    CACHE STRING "${config} linker flags" FORCE)
            endforeach()
        endif()
    endforeach()
    list(JOIN _crd_debug_crt "," _crd_debug_crt)
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:${_crd_debug_crt}>:Debug>DLL")
    list(JOIN _crd_debug_info "," _crd_debug_info)
    set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "$<$<CONFIG:${_crd_debug_info}>:ProgramDatabase>")
endif()

# A Boolean generator expression, derived from the same flags as the corresponding Ninja preset.
function(crd_profile_condition output setting)
    if(CRD_NATIVE_PROFILES)
        set(configs)
        foreach(config IN LISTS CRD_NATIVE_CONFIGS)
            if(CRD_PROFILE_${config}_${setting})
                list(APPEND configs "${config}")
            endif()
        endforeach()
        if(configs)
            list(JOIN configs "," configs)
            set(${output} "$<CONFIG:${configs}>" PARENT_SCOPE)
        else()
            set(${output} "0" PARENT_SCOPE)
        endif()
    else()
        set(${output} "$<BOOL:${${setting}}>" PARENT_SCOPE)
    endif()
endfunction()

function(crd_configure_build_header input output)
    if(CRD_NATIVE_PROFILES)
        foreach(config IN LISTS CRD_NATIVE_CONFIGS)
            set(CRD_ENABLE_ASSERTS "${CRD_PROFILE_${config}_CRD_ENABLE_ASSERTS}")
            set(CRD_ENABLE_PROFILING "${CRD_PROFILE_${config}_CRD_ENABLE_PROFILING}")
            set(CRD_DEBUG 0)
            set(CRD_RELEASE 0)
            if(CRD_PROFILE_${config}_CMAKE_BUILD_TYPE MATCHES "^(Debug|RelWithDebInfo)$")
                set(CRD_DEBUG 1)
                set(automatic_log 0)
            else()
                set(CRD_RELEASE 1)
                set(automatic_log 2)
            endif()
            if(CRD_LOG_MIN_LEVEL STREQUAL "")
                set(CRD_LOG_MIN_LEVEL_NUM ${automatic_log})
            endif()
            configure_file("${input}" "${output}/${config}/crd/core/build_config.hpp" @ONLY)
        endforeach()
    else()
        set(CRD_DEBUG 0)
        set(CRD_RELEASE 0)
        if(CMAKE_BUILD_TYPE MATCHES "^(Debug|RelWithDebInfo)$")
            set(CRD_DEBUG 1)
        else()
            set(CRD_RELEASE 1)
        endif()
        configure_file("${input}" "${output}/crd/core/build_config.hpp" @ONLY)
    endif()
endfunction()

function(crd_apply_native_profiles directory)
    if(NOT CRD_NATIVE_PROFILES)
        return()
    endif()
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(target IN LISTS targets)
        get_target_property(kind "${target}" TYPE)
        if(kind MATCHES "^(STATIC_LIBRARY|SHARED_LIBRARY|MODULE_LIBRARY|OBJECT_LIBRARY|EXECUTABLE)$")
            get_property(explicit_ipo TARGET "${target}" PROPERTY INTERPROCEDURAL_OPTIMIZATION SET)
            get_property(ipo TARGET "${target}" PROPERTY INTERPROCEDURAL_OPTIMIZATION)
            foreach(config IN LISTS CRD_NATIVE_CONFIGS)
                string(TOUPPER "${config}" upper)
                if(explicit_ipo AND NOT ipo)
                    set(enabled OFF)
                else()
                    set(enabled "${CRD_PROFILE_${config}_CMAKE_INTERPROCEDURAL_OPTIMIZATION}")
                endif()
                set_property(TARGET "${target}" PROPERTY INTERPROCEDURAL_OPTIMIZATION_${upper} "${enabled}")
                if(directory MATCHES "/tests/bench($|/)" AND NOT CRD_PROFILE_${config}_CRD_BUILD_BENCHMARKS)
                    set_property(TARGET "${target}" PROPERTY EXCLUDE_FROM_DEFAULT_BUILD_${upper} ON)
                endif()
            endforeach()
        endif()
    endforeach()
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        crd_apply_native_profiles("${child}")
    endforeach()
endfunction()
