# Target navigation follows physical source ownership, independent of generator/OS.
include_guard(GLOBAL)
set_property(GLOBAL PROPERTY USE_FOLDERS ON)
set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER "CMake")

function(crd_organize_targets directory)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    file(RELATIVE_PATH relative "${PROJECT_SOURCE_DIR}" "${directory}")
    foreach(target IN LISTS targets)
        if(relative MATCHES "^tests/bench($|/)")
            set(folder "benchmarks")
        elseif(relative MATCHES "^(engine|tests)/([^/]+)/")
            set(folder "${CMAKE_MATCH_1}/${CMAKE_MATCH_2}")
        elseif(relative MATCHES "^(tools|runtime|sandbox)($|/)")
            set(folder "applications/${CMAKE_MATCH_1}")
        elseif(relative STREQUAL "")
            if(target MATCHES "^crd-|^cook$")
                set(folder "build")
            else()
                set(folder "dependencies")
            endif()
        else()
            set(folder "dependencies")
        endif()
        set_property(TARGET "${target}" PROPERTY FOLDER "${folder}")
        if(TARGET crd-project-sync-check AND NOT target STREQUAL "crd-project-sync-check"
           AND relative MATCHES "^(engine|tests|tools|runtime|sandbox)(/|$)")
            add_dependencies("${target}" crd-project-sync-check)
        endif()
    endforeach()
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        crd_organize_targets("${child}")
    endforeach()
endfunction()
