# Cerid module registry: opt-in, dependency-closed module selection (REPO.DEV.4).
#
# Every directory the build registers (engine module, host tool, runtime, sandbox, test directory) is a node with
# declared direct dependencies. `CRD_MODULES` empty, the default of every preset, configures everything exactly as
# a literal add_subdirectory list would. A selection configures the transitive closure of the named modules or
# families, the tests of the named modules with their declared extra dependencies, and the third-party packages
# those need; nothing else is configured. Omitted directories are absent, never stubbed. crd_verify_modules() runs
# at the end of every configure, in every mode, and turns any crd-* or package link the declarations do not cover
# into a configure error, so the registry cannot drift from the real graph.
#
# Registration forms (one literal call per line; the structure synchronizer and the hygiene guard parse them):
#   crd_module(<source-dir> [<binary-dir>] [NAME <module>] [HOST] [EXECUTABLES <exe>...] [DEPENDS <module>...]
#              [PACKAGES <pkg>...] [TESTS <tests-dir>...] [TEST_DEPENDS <module>...] [TEST_PACKAGES <pkg>...])
#   crd_tests(<tests-dir> [<binary-dir>])          in tests/CMakeLists.txt
# Module names default to the last path component of the source directory (engine/numerics/hesap-fft -> hesap-fft);
# NAME resolves collisions such as tools/shader-cook (shader_cook) against engine/assets/shader-cook.
# Families: engine/<family>/<module> -> <family>; tools/<tool> -> tools (alias host-tools); runtime; sandbox.
include_guard(GLOBAL)

set(CRD_MODULES "" CACHE STRING
    "Opt-in module selection (module names, families, tools, runtime, sandbox, all); empty = full configuration")
set(CRD_HOST_TOOLS_DIR "" CACHE PATH
    "Directory holding prebuilt host tools; when set, HOST modules are imported from it instead of built")
set(CRD_KNOWN_PACKAGES glfw zstd tomlplusplus stb cgltf mikktspace imgui)

set_property(GLOBAL PROPERTY CRD_MODULE_NAMES "")
set_property(GLOBAL PROPERTY CRD_MODULES_RESOLVED FALSE)
set_property(GLOBAL PROPERTY CRD_MODULE_SELECTION FALSE)
set_property(GLOBAL PROPERTY CRD_SELECTED_MODULES "")
set_property(GLOBAL PROPERTY CRD_SELECTED_TESTS "")
set_property(GLOBAL PROPERTY CRD_SELECTED_PACKAGES "")
set_property(GLOBAL PROPERTY CRD_REGISTERED_TESTS "")
set_property(GLOBAL PROPERTY CRD_OMITTED_TESTS "")

function(_crd_test_key source out_var)
    string(REPLACE "/" "__" key "${source}")
    set(${out_var} "${key}" PARENT_SCOPE)
endfunction()

function(crd_module source)
    cmake_parse_arguments(ARG "HOST" "NAME" "EXECUTABLES;DEPENDS;PACKAGES;TESTS;TEST_DEPENDS;TEST_PACKAGES" ${ARGN})
    list(LENGTH ARG_UNPARSED_ARGUMENTS positional)
    if(positional GREATER 1)
        message(FATAL_ERROR "crd_module(${source}): unexpected arguments '${ARG_UNPARSED_ARGUMENTS}'")
    endif()
    set(binary "")
    if(positional EQUAL 1)
        list(GET ARG_UNPARSED_ARGUMENTS 0 binary)
    endif()
    if(NOT IS_DIRECTORY "${CMAKE_SOURCE_DIR}/${source}")
        message(FATAL_ERROR "crd_module(${source}): directory does not exist")
    endif()
    string(REGEX REPLACE ".*/" "" name "${source}")
    if(ARG_NAME)
        set(name "${ARG_NAME}")
    endif()
    if(NOT name MATCHES "^[A-Za-z][A-Za-z0-9_-]*$")
        message(FATAL_ERROR "crd_module(${source}): module name '${name}' is not a plain identifier")
    endif()
    if(source MATCHES "^engine/([^/]+)/[^/]+$")
        set(family "${CMAKE_MATCH_1}")
    elseif(source MATCHES "^tools/[^/]+$")
        set(family "tools")
    else()
        set(family "${name}")
    endif()
    get_property(names GLOBAL PROPERTY CRD_MODULE_NAMES)
    if(name IN_LIST names)
        message(FATAL_ERROR "crd_module(${source}): module '${name}' is already registered")
    endif()
    if(name IN_LIST ARG_DEPENDS OR name IN_LIST ARG_TEST_DEPENDS)
        message(FATAL_ERROR "crd_module(${source}): module '${name}' depends on itself")
    endif()
    foreach(package IN LISTS ARG_PACKAGES ARG_TEST_PACKAGES)
        if(NOT package IN_LIST CRD_KNOWN_PACKAGES)
            message(FATAL_ERROR "crd_module(${source}): unknown package '${package}'; known: ${CRD_KNOWN_PACKAGES}")
        endif()
    endforeach()
    get_property(resolved GLOBAL PROPERTY CRD_MODULES_RESOLVED)
    if(resolved)
        message(FATAL_ERROR "crd_module(${source}): registered after crd_resolve_modules(); move it before that call")
    endif()
    set_property(GLOBAL APPEND PROPERTY CRD_MODULE_NAMES "${name}")
    set_property(GLOBAL PROPERTY CRD_MODULE_${name}_SOURCE "${source}")
    set_property(GLOBAL PROPERTY CRD_MODULE_${name}_BINARY "${binary}")
    set_property(GLOBAL PROPERTY CRD_MODULE_${name}_FAMILY "${family}")
    set_property(GLOBAL PROPERTY CRD_MODULE_${name}_HOST "${ARG_HOST}")
    set_property(GLOBAL PROPERTY CRD_MODULE_${name}_EXECUTABLES "${ARG_EXECUTABLES}")
    set_property(GLOBAL PROPERTY CRD_MODULE_${name}_DEPENDS "${ARG_DEPENDS}")
    set_property(GLOBAL PROPERTY CRD_MODULE_${name}_PACKAGES "${ARG_PACKAGES}")
    set_property(GLOBAL PROPERTY CRD_MODULE_${name}_TESTS "${ARG_TESTS}")
    set_property(GLOBAL PROPERTY CRD_MODULE_${name}_TEST_DEPENDS "${ARG_TEST_DEPENDS}")
    set_property(GLOBAL PROPERTY CRD_MODULE_${name}_TEST_PACKAGES "${ARG_TEST_PACKAGES}")
    foreach(test IN LISTS ARG_TESTS)
        _crd_test_key("${test}" key)
        set_property(GLOBAL APPEND PROPERTY CRD_TEST_OWNERS_${key} "${name}")
    endforeach()
endfunction()

# Transitive closure over DEPENDS of the seed modules, returned in registration order.
function(_crd_module_closure out_var)
    get_property(names GLOBAL PROPERTY CRD_MODULE_NAMES)
    set(pending ${ARGN})
    set(seen "")
    while(pending)
        list(POP_FRONT pending name)
        if(name IN_LIST seen)
            continue()
        endif()
        list(APPEND seen "${name}")
        get_property(depends GLOBAL PROPERTY CRD_MODULE_${name}_DEPENDS)
        list(APPEND pending ${depends})
    endwhile()
    set(ordered "")
    foreach(name IN LISTS names)
        if(name IN_LIST seen)
            list(APPEND ordered "${name}")
        endif()
    endforeach()
    set(${out_var} "${ordered}" PARENT_SCOPE)
endfunction()

function(_crd_check_declared_edges)
    get_property(names GLOBAL PROPERTY CRD_MODULE_NAMES)
    foreach(name IN LISTS names)
        get_property(depends GLOBAL PROPERTY CRD_MODULE_${name}_DEPENDS)
        get_property(test_depends GLOBAL PROPERTY CRD_MODULE_${name}_TEST_DEPENDS)
        foreach(dep IN LISTS depends test_depends)
            if(NOT dep IN_LIST names)
                message(FATAL_ERROR "crd_module(${name}) depends on '${dep}', which is not a registered module")
            endif()
        endforeach()
    endforeach()
endfunction()

# Resolve CRD_MODULES into the selected modules, enabled test directories and required packages.
function(crd_resolve_modules)
    _crd_check_declared_edges()
    get_property(names GLOBAL PROPERTY CRD_MODULE_NAMES)
    string(REPLACE "," ";" tokens "${CRD_MODULES}")
    string(REPLACE " " ";" tokens "${tokens}")
    list(FILTER tokens EXCLUDE REGEX "^$")
    set(families "")
    foreach(name IN LISTS names)
        get_property(family GLOBAL PROPERTY CRD_MODULE_${name}_FAMILY)
        list(APPEND families "${family}")
    endforeach()
    list(REMOVE_DUPLICATES families)
    if(NOT tokens OR "all" IN_LIST tokens)
        set(selection FALSE)
        set(selected "${names}")
        set(explicit "${names}")
    else()
        set(selection TRUE)
        set(explicit "")
        foreach(token IN LISTS tokens)
            if(token STREQUAL "host-tools")
                set(token "tools")
            endif()
            if(token IN_LIST names)
                list(APPEND explicit "${token}")
            elseif(token IN_LIST families)
                foreach(name IN LISTS names)
                    get_property(family GLOBAL PROPERTY CRD_MODULE_${name}_FAMILY)
                    if(family STREQUAL token)
                        list(APPEND explicit "${name}")
                    endif()
                endforeach()
            else()
                list(JOIN names ", " known_modules)
                list(JOIN families ", " known_families)
                message(FATAL_ERROR "CRD_MODULES names unknown module or family '${token}'.\n"
                                    "  Modules: ${known_modules}\n  Families: ${known_families}, host-tools, all")
            endif()
        endforeach()
        list(REMOVE_DUPLICATES explicit)
        set(seeds ${explicit})
        if(CRD_BUILD_TESTS)
            foreach(name IN LISTS explicit)
                get_property(test_depends GLOBAL PROPERTY CRD_MODULE_${name}_TEST_DEPENDS)
                list(APPEND seeds ${test_depends})
            endforeach()
        endif()
        _crd_module_closure(selected ${seeds})
    endif()
    set(tests "")
    set(packages "")
    foreach(name IN LISTS selected)
        get_property(module_packages GLOBAL PROPERTY CRD_MODULE_${name}_PACKAGES)
        list(APPEND packages ${module_packages})
    endforeach()
    if(CRD_BUILD_TESTS)
        foreach(name IN LISTS explicit)
            get_property(module_tests GLOBAL PROPERTY CRD_MODULE_${name}_TESTS)
            get_property(test_packages GLOBAL PROPERTY CRD_MODULE_${name}_TEST_PACKAGES)
            list(APPEND tests ${module_tests})
            list(APPEND packages ${test_packages})
        endforeach()
    endif()
    if(NOT selection)
        set(packages ${CRD_KNOWN_PACKAGES})
    endif()
    list(REMOVE_DUPLICATES tests)
    list(REMOVE_DUPLICATES packages)
    set_property(GLOBAL PROPERTY CRD_MODULES_RESOLVED TRUE)
    set_property(GLOBAL PROPERTY CRD_MODULE_SELECTION "${selection}")
    set_property(GLOBAL PROPERTY CRD_SELECTED_MODULES "${selected}")
    set_property(GLOBAL PROPERTY CRD_SELECTED_TESTS "${tests}")
    set_property(GLOBAL PROPERTY CRD_SELECTED_PACKAGES "${packages}")
    set(CRD_MODULE_SELECTION "${selection}" PARENT_SCOPE)
    set(CRD_SELECTED_MODULES "${selected}" PARENT_SCOPE)
    set(CRD_SELECTED_TESTS "${tests}" PARENT_SCOPE)
    set(CRD_SELECTED_PACKAGES "${packages}" PARENT_SCOPE)
    list(LENGTH names total)
    list(LENGTH selected count)
    if(selection)
        set(omitted "")
        foreach(name IN LISTS names)
            if(NOT name IN_LIST selected)
                list(APPEND omitted "${name}")
            endif()
        endforeach()
        list(JOIN selected " " selected_text)
        list(JOIN tests " " tests_text)
        list(JOIN packages " " packages_text)
        list(JOIN omitted " " omitted_text)
        message(STATUS "[crd] modules: ${count} of ${total} configured for CRD_MODULES='${CRD_MODULES}'")
        message(STATUS "[crd]   closure: ${selected_text}")
        message(STATUS "[crd]   tests: ${tests_text}")
        message(STATUS "[crd]   packages: ${packages_text}")
        message(STATUS "[crd]   omitted: ${omitted_text}")
    else()
        message(STATUS "[crd] modules: ${count} of ${total} configured (full configuration)")
    endif()
endfunction()

# Import a HOST module's executables from CRD_HOST_TOOLS_DIR instead of configuring its sources.
function(_crd_import_host_tools name)
    get_property(executables GLOBAL PROPERTY CRD_MODULE_${name}_EXECUTABLES)
    if(NOT executables)
        message(FATAL_ERROR "crd_module(${name}) is HOST but declares no EXECUTABLES to import from CRD_HOST_TOOLS_DIR")
    endif()
    foreach(executable IN LISTS executables)
        set(location "${CRD_HOST_TOOLS_DIR}/${executable}${CMAKE_HOST_EXECUTABLE_SUFFIX}")
        if(NOT EXISTS "${location}")
            message(FATAL_ERROR "Host tool '${executable}' of module ${name} is missing: ${location}")
        endif()
        add_executable("${executable}" IMPORTED GLOBAL)
        set_target_properties("${executable}" PROPERTIES IMPORTED_LOCATION "${location}")
        message(STATUS "[crd] host tool ${executable} imported from ${location}")
    endforeach()
endfunction()

# Add every selected registration in registration order. A macro so the subdirectories keep the caller's scope.
macro(crd_add_modules)
    get_property(_crd_am_resolved GLOBAL PROPERTY CRD_MODULES_RESOLVED)
    if(NOT _crd_am_resolved)
        crd_resolve_modules()
    endif()
    get_property(_crd_am_names GLOBAL PROPERTY CRD_MODULE_NAMES)
    get_property(_crd_am_selected GLOBAL PROPERTY CRD_SELECTED_MODULES)
    foreach(_crd_am_name IN LISTS _crd_am_names)
        if(_crd_am_name IN_LIST _crd_am_selected)
            get_property(_crd_am_source GLOBAL PROPERTY CRD_MODULE_${_crd_am_name}_SOURCE)
            get_property(_crd_am_binary GLOBAL PROPERTY CRD_MODULE_${_crd_am_name}_BINARY)
            get_property(_crd_am_host GLOBAL PROPERTY CRD_MODULE_${_crd_am_name}_HOST)
            if(_crd_am_host AND CRD_HOST_TOOLS_DIR)
                _crd_import_host_tools("${_crd_am_name}")
            elseif(_crd_am_binary)
                add_subdirectory("${_crd_am_source}" "${_crd_am_binary}")
            else()
                add_subdirectory("${_crd_am_source}")
            endif()
        endif()
    endforeach()
    unset(_crd_am_resolved)
    unset(_crd_am_names)
    unset(_crd_am_selected)
    unset(_crd_am_name)
    unset(_crd_am_source)
    unset(_crd_am_binary)
    unset(_crd_am_host)
endmacro()

# Register a test directory (relative to tests/). Added when its owning module was named in the selection or the
# configuration is full; an unowned registration is a configure error in every mode.
macro(crd_tests source)
    _crd_test_key("${source}" _crd_t_key)
    get_property(_crd_t_owners GLOBAL PROPERTY CRD_TEST_OWNERS_${_crd_t_key})
    if(NOT _crd_t_owners)
        message(FATAL_ERROR "tests/${source} is registered but no crd_module() declares it in TESTS")
    endif()
    get_property(_crd_t_registered GLOBAL PROPERTY CRD_REGISTERED_TESTS)
    if("${source}" IN_LIST _crd_t_registered)
        message(FATAL_ERROR "tests/${source} is registered twice")
    endif()
    set_property(GLOBAL APPEND PROPERTY CRD_REGISTERED_TESTS "${source}")
    get_property(_crd_t_selection GLOBAL PROPERTY CRD_MODULE_SELECTION)
    get_property(_crd_t_enabled GLOBAL PROPERTY CRD_SELECTED_TESTS)
    if(NOT _crd_t_selection OR "${source}" IN_LIST _crd_t_enabled)
        if("${ARGN}" STREQUAL "")
            add_subdirectory("${source}")
        else()
            add_subdirectory("${source}" ${ARGN})
        endif()
    else()
        set_property(GLOBAL APPEND PROPERTY CRD_OMITTED_TESTS "${source}")
    endif()
    unset(_crd_t_key)
    unset(_crd_t_owners)
    unset(_crd_t_registered)
    unset(_crd_t_selection)
    unset(_crd_t_enabled)
endmacro()

function(_crd_collect_build_targets directory out_var)
    set(collected "")
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    list(APPEND collected ${targets})
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        _crd_collect_build_targets("${child}" nested)
        list(APPEND collected ${nested})
    endforeach()
    set(${out_var} "${collected}" PARENT_SCOPE)
endfunction()

# Owner of a source directory: "module:<name>", "tests:<dir>", "root" (repository root or cmake/) or "" (outside).
function(_crd_owner_of_directory directory out_var)
    file(RELATIVE_PATH relative "${CMAKE_SOURCE_DIR}" "${directory}")
    if(relative MATCHES "^\\.\\." OR IS_ABSOLUTE "${relative}")
        set(${out_var} "" PARENT_SCOPE)
        return()
    endif()
    if(relative STREQUAL "" OR relative MATCHES "^cmake(/|$)")
        set(${out_var} "root" PARENT_SCOPE)
        return()
    endif()
    get_property(names GLOBAL PROPERTY CRD_MODULE_NAMES)
    foreach(name IN LISTS names)
        get_property(source GLOBAL PROPERTY CRD_MODULE_${name}_SOURCE)
        if(relative STREQUAL source OR relative MATCHES "^${source}/")
            set(${out_var} "module:${name}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    get_property(tests GLOBAL PROPERTY CRD_REGISTERED_TESTS)
    foreach(test IN LISTS tests)
        if(relative STREQUAL "tests/${test}" OR relative MATCHES "^tests/${test}/")
            set(${out_var} "tests:${test}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    set(${out_var} "" PARENT_SCOPE)
endfunction()

function(_crd_package_of item out_var)
    set(package "")
    if(item STREQUAL "glfw")
        set(package glfw)
    elseif(item MATCHES "^(lib)?zstd_static$")
        set(package zstd)
    elseif(item MATCHES "^tomlplusplus(::tomlplusplus)?$")
        set(package tomlplusplus)
    elseif(item MATCHES "^(stb|cgltf|mikktspace)$")
        set(package "${item}")
    endif()
    set(${out_var} "${package}" PARENT_SCOPE)
endfunction()

# Every actual crd-* and package link must be covered by the declarations: a module's direct links by its own
# DEPENDS/PACKAGES, a test directory's links by an owner's closure, TESTS or TEST_DEPENDS/TEST_PACKAGES.
function(crd_verify_modules)
    _crd_collect_build_targets("${CMAKE_SOURCE_DIR}" targets)
    set(problems "")
    foreach(target IN LISTS targets)
        get_target_property(type "${target}" TYPE)
        if(type STREQUAL "UTILITY")
            continue()
        endif()
        get_target_property(imported "${target}" IMPORTED)
        if(imported)
            continue()
        endif()
        get_target_property(source_dir "${target}" SOURCE_DIR)
        _crd_owner_of_directory("${source_dir}" owner)
        if(NOT owner OR owner STREQUAL "root")
            continue()
        endif()
        set(items "")
        foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
            get_target_property(value "${target}" ${property})
            if(value)
                list(APPEND items ${value})
            endif()
        endforeach()
        # A name inside a generator expression other than LINK_ONLY is conditional (for example
        # $<$<BOOL:${WIN32}>:crd-gpu-context-dx12>): its declaration is checked when the target exists, and its
        # absence on a platform that does not build it is not a missing edge.
        set(links "")
        set(conditional "")
        foreach(item IN LISTS items)
            if(item MATCHES "^::@")
                continue()
            endif()
            string(REGEX REPLACE "::@\\(.*\\)$" "" item "${item}")
            if(item MATCHES "^\\$<LINK_ONLY:(.+)>$")
                set(item "${CMAKE_MATCH_1}")
            endif()
            if(item MATCHES "^\\$<")
                string(REGEX MATCHALL "crd-[A-Za-z0-9_-]+" nested "${item}")
                list(APPEND links ${nested})
                list(APPEND conditional ${nested})
                continue()
            endif()
            list(APPEND links "${item}")
        endforeach()
        list(REMOVE_DUPLICATES links)
        string(REGEX REPLACE "^(module|tests):" "" owner_name "${owner}")
        if(owner MATCHES "^module:")
            get_property(allowed_modules GLOBAL PROPERTY CRD_MODULE_${owner_name}_DEPENDS)
            get_property(allowed_packages GLOBAL PROPERTY CRD_MODULE_${owner_name}_PACKAGES)
            list(APPEND allowed_modules "${owner_name}")
            set(allowed_tests "")
            set(declaration "crd_module(${owner_name})")
        else()
            _crd_test_key("${owner_name}" key)
            get_property(owners GLOBAL PROPERTY CRD_TEST_OWNERS_${key})
            set(allowed_modules "")
            set(allowed_packages "")
            set(allowed_tests "${owner_name}")
            foreach(module IN LISTS owners)
                _crd_module_closure(closure "${module}")
                get_property(test_depends GLOBAL PROPERTY CRD_MODULE_${module}_TEST_DEPENDS)
                get_property(module_tests GLOBAL PROPERTY CRD_MODULE_${module}_TESTS)
                get_property(packages GLOBAL PROPERTY CRD_MODULE_${module}_PACKAGES)
                get_property(test_packages GLOBAL PROPERTY CRD_MODULE_${module}_TEST_PACKAGES)
                list(APPEND allowed_modules ${closure} ${test_depends})
                list(APPEND allowed_tests ${module_tests})
                list(APPEND allowed_packages ${packages} ${test_packages})
            endforeach()
            list(JOIN owners ", " owner_list)
            set(declaration "the crd_module() owners of tests/${owner_name} (${owner_list})")
        endif()
        foreach(link IN LISTS links)
            if(link MATCHES "^crd-")
                if(NOT TARGET "${link}")
                    if(NOT link IN_LIST conditional)
                        list(APPEND problems "${target} (${owner}) links ${link}, which is not a configured target; add its module to DEPENDS/TEST_DEPENDS of ${declaration} or to CRD_MODULES")
                    endif()
                    continue()
                endif()
                get_target_property(link_dir "${link}" SOURCE_DIR)
                _crd_owner_of_directory("${link_dir}" link_owner)
                if(NOT link_owner OR link_owner STREQUAL "root")
                    continue()
                endif()
                string(REGEX REPLACE "^(module|tests):" "" link_name "${link_owner}")
                if(link_owner MATCHES "^module:" AND NOT link_name IN_LIST allowed_modules)
                    list(APPEND problems "${target} (${owner}) links ${link} of module ${link_name}, which ${declaration} does not declare (DEPENDS or TEST_DEPENDS)")
                elseif(link_owner MATCHES "^tests:" AND NOT link_name IN_LIST allowed_tests)
                    list(APPEND problems "${target} (${owner}) links ${link} of tests/${link_name}, which ${declaration} does not list in TESTS")
                endif()
            else()
                _crd_package_of("${link}" package)
                if(package AND NOT package IN_LIST allowed_packages)
                    list(APPEND problems "${target} (${owner}) links ${link}; ${declaration} must declare PACKAGES/TEST_PACKAGES ${package}")
                endif()
            endif()
        endforeach()
    endforeach()
    if(problems)
        list(JOIN problems "\n  " text)
        message(FATAL_ERROR "Module declarations disagree with the build graph:\n  ${text}")
    endif()
endfunction()
