# CMake owns test discovery. Preserve Catch2's properties while making unbuilt ownership explicit.
include_guard(GLOBAL)
include(Catch)
include(CrdTestOwnership)

function(_crd_test_quote OUTPUT VALUE)
    set(_equals "=")
    while("${VALUE}" MATCHES "]${_equals}]")
        string(APPEND _equals "=")
    endwhile()
    set(${OUTPUT} "[${_equals}[${VALUE}]${_equals}]" PARENT_SCOPE)
endfunction()

function(crd_discover_tests TARGET)
    if(NOT TARGET "${TARGET}")
        message(FATAL_ERROR "crd_discover_tests requires an existing executable target: ${TARGET}")
    endif()
    get_target_property(_type "${TARGET}" TYPE)
    if(NOT _type STREQUAL "EXECUTABLE")
        message(FATAL_ERROR "Test discovery requires an executable: ${TARGET}")
    endif()
    cmake_parse_arguments(PARSE_ARGV 1 _crd "SKIP_IS_FAILURE"
        "TEST_PREFIX;TEST_SUFFIX;WORKING_DIRECTORY;TEST_LIST;REPORTER;OUTPUT_DIR;OUTPUT_PREFIX;OUTPUT_SUFFIX;DISCOVERY_MODE"
        "TEST_SPEC;EXTRA_ARGS;PROPERTIES;DL_PATHS;DL_FRAMEWORK_PATHS")
    if(_crd_DISCOVERY_MODE AND NOT _crd_DISCOVERY_MODE STREQUAL "PRE_TEST")
        message(FATAL_ERROR "Cerid discovery must be PRE_TEST to retain configuration-specific inventories")
    endif()
    set(CMAKE_CATCH_DISCOVER_TESTS_DISCOVERY_MODE PRE_TEST)
    if(_crd_UNPARSED_ARGUMENTS OR _crd_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "Unsupported or incomplete discovery arguments: ${_crd_UNPARSED_ARGUMENTS};${_crd_KEYWORDS_MISSING_VALUES}")
    endif()
    # Catch2 3.7.1 flattens list-valued PROPERTIES. Apply those through its TEST_LIST after inclusion instead.
    set(_forward "")
    if(_crd_SKIP_IS_FAILURE)
        list(APPEND _forward SKIP_IS_FAILURE)
    endif()
    foreach(_key TEST_PREFIX TEST_SUFFIX WORKING_DIRECTORY TEST_LIST REPORTER OUTPUT_DIR OUTPUT_PREFIX OUTPUT_SUFFIX
            DISCOVERY_MODE TEST_SPEC EXTRA_ARGS DL_PATHS DL_FRAMEWORK_PATHS)
        if(DEFINED _crd_${_key})
            list(APPEND _forward "${_key}" "${_crd_${_key}}")
        endif()
    endforeach()
    get_property(_before DIRECTORY PROPERTY TEST_INCLUDE_FILES)
    catch_discover_tests("${TARGET}" ${_forward})
    get_property(_after DIRECTORY PROPERTY TEST_INCLUDE_FILES)
    set(_added "${_after}")
    if(_before)
        list(REMOVE_ITEM _added ${_before})
    endif()
    list(LENGTH _added _count)
    if(NOT _count EQUAL 1)
        message(FATAL_ERROR "Catch2 must contribute exactly one unique include per discovery registration")
    endif()
    list(GET _added 0 _catch_include)
    # Derive identity from the actual include contributed by Catch2, not a duplicate of its argument hash algorithm.
    string(SHA256 _identity "${_catch_include}")
    set(_pending "cerid-pending-${_identity}")
    set(_wrapper "${_catch_include}.cerid")
    _crd_test_quote(_executable "$<TARGET_FILE:${TARGET}>")
    _crd_test_quote(_original "${_catch_include}")
    _crd_test_quote(_name "${_pending}")
    if(NOT _crd_WORKING_DIRECTORY)
        set(_crd_WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
    endif()
    _crd_test_quote(_working "${_crd_WORKING_DIRECTORY}")
    set(_properties "")
    set(_labels "")
    set(_has_labels FALSE)
    list(LENGTH _crd_PROPERTIES _property_count)
    math(EXPR _odd "${_property_count} % 2")
    if(_odd)
        message(FATAL_ERROR "Test PROPERTIES must contain name/value pairs")
    endif()
    set(_property_index 0)
    while(_property_index LESS _property_count)
        list(GET _crd_PROPERTIES ${_property_index} _key)
        math(EXPR _value_index "${_property_index} + 1")
        list(GET _crd_PROPERTIES ${_value_index} _value)
        if(_key STREQUAL "LABELS")
            set(_labels "${_value}")
            set(_has_labels TRUE)
        else()
            _crd_test_quote(_quoted_key "${_key}")
            _crd_test_quote(_quoted_value "${_value}")
            string(APPEND _properties " ${_quoted_key} ${_quoted_value}")
        endif()
        math(EXPR _property_index "${_property_index} + 2")
    endwhile()
    set(_actual_properties "${_properties}")
    if(_has_labels)
        _crd_test_quote(_original_labels "${_labels}")
        string(APPEND _actual_properties " LABELS ${_original_labels}")
    endif()
    list(APPEND _labels "cerid.discovery.pending" "cerid.discovery.target=${TARGET}"
        "cerid.discovery.executable=$<TARGET_FILE:${TARGET}>")
    _crd_test_quote(_label "${_labels}")
    # A missing executable remains a failing CTest. The annotation only permits the planner to find its build owner.
    if(NOT _crd_TEST_LIST)
        set(_crd_TEST_LIST "${TARGET}_TESTS")
    endif()
    _crd_test_quote(_test_list "${_crd_TEST_LIST}")
    set(_apply "")
    if(_actual_properties)
        string(CONCAT _apply "  foreach(_crd_test IN LISTS ${_test_list})\n"
            "    set_tests_properties(\"\${_crd_test}\" PROPERTIES${_actual_properties})\n  endforeach()\n")
    endif()
    string(CONCAT _content
        "if(EXISTS ${_executable})\n  include(${_original})\n${_apply}else()\n"
        "  add_test(${_name} ${_executable})\n"
        "  set_tests_properties(${_name} PROPERTIES WORKING_DIRECTORY ${_working}${_properties})\n"
        "  set_tests_properties(${_name} PROPERTIES LABELS ${_label})\nendif()\n")
    file(GENERATE OUTPUT "${_wrapper}-$<CONFIG>.cmake" CONTENT "${_content}")
    get_property(_multi GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
    if(_multi)
        _crd_test_quote(_configurations "${CMAKE_CONFIGURATION_TYPES}")
        file(WRITE "${_wrapper}.cmake"
            "set(_crd_configurations ${_configurations})\n"
            "list(FIND _crd_configurations \"\${CTEST_CONFIGURATION_TYPE}\" _crd_configuration_index)\n"
            "if(_crd_configuration_index EQUAL -1)\n"
            "  message(FATAL_ERROR \"Select a configured test profile with CTest -C\")\nendif()\n"
            "include(\"${_wrapper}-\${CTEST_CONFIGURATION_TYPE}.cmake\")\n")
    else()
        file(WRITE "${_wrapper}.cmake" "include(\"${_wrapper}-${CMAKE_BUILD_TYPE}.cmake\")\n")
    endif()
    list(REMOVE_ITEM _after "${_catch_include}")
    list(APPEND _after "${_wrapper}.cmake")
    set_property(DIRECTORY PROPERTY TEST_INCLUDE_FILES "${_after}")
endfunction()
