#!/usr/bin/env python3
"""PyWavelets reference data for the crd-hesap-wavelet tests (v11w-a/b).
Emits PLAIN C ARRAYS (no STL) per the project rule. Run from repo root:
  python3 tests/hesap-wavelet/gen_wavelet_refs.py > tests/hesap-wavelet/wavelet_refs.inc
"""
import numpy as np
import pywt


def san(s: str) -> str:
    return s.replace(".", "_").replace("-", "_")


def emit(name, arr):
    body = ", ".join(f"{float(x):.17g}" for x in np.asarray(arr).ravel())
    print(f"inline const double ref_{name}[] = {{{body}}};")


# A deterministic NON-LINEAR signal so smooth != antireflect (and reflect != symmetric) are distinguished.
def make_signal(n):
    i = np.arange(n, dtype=float)
    return np.sin(0.3 * i) + 0.5 * np.cos(0.07 * i * i) + 0.01 * i * i


WAVELETS = ["haar", "db2", "db4", "sym4", "coif1", "bior2.2", "rbio2.2"]
MODES = ["zero", "symmetric", "periodic", "periodization", "reflect", "constant",
         "smooth", "antisymmetric", "antireflect"]


def main():
    print("// GENERATED by gen_wavelet_refs.py — PyWavelets reference (v11w-a/b). C arrays (no STL).")
    print("#pragma once")

    N = 37  # odd, non-power-of-two — exercises the general length arithmetic
    x = make_signal(N)
    emit("input", x)

    # filter banks (gate wavelet_by_name + the generated engine table independently).
    for w in WAVELETS:
        wav = pywt.Wavelet(w)
        dec_lo, dec_hi, rec_lo, rec_hi = wav.filter_bank
        emit(f"fb_{san(w)}_dec_lo", dec_lo)
        emit(f"fb_{san(w)}_dec_hi", dec_hi)
        emit(f"fb_{san(w)}_rec_lo", rec_lo)
        emit(f"fb_{san(w)}_rec_hi", rec_hi)

    # per-mode single-level DWT coefficients (the core convention gate).
    for w in WAVELETS:
        for m in MODES:
            cA, cD = pywt.dwt(x, w, mode=m)
            emit(f"{san(w)}_{m}_cA", cA)
            emit(f"{san(w)}_{m}_cD", cD)

    # direct IDWT references (gate the inverse convention independently of round-trip).
    for w, m in [("db4", "symmetric"), ("db4", "periodization"), ("bior2.2", "symmetric")]:
        cA, cD = pywt.dwt(x, w, mode=m)
        y = pywt.idwt(cA, cD, w, mode=m)
        emit(f"idwt_{san(w)}_{m}", y)

    # multilevel wavedec (db4, level 3, symmetric) — structure + values.
    coeffs = pywt.wavedec(x, "db4", mode="symmetric", level=3)
    print(f"inline const int ref_wd_db4_l3_ncoef = {len(coeffs)};")
    for i, c in enumerate(coeffs):
        emit(f"wd_db4_l3_c{i}", c)

    # a power-of-two periodization case for exact non-redundant round trip (N=64, db4, level 4).
    xp = make_signal(64)
    emit("input64", xp)
    cper = pywt.wavedec(xp, "db4", mode="periodization", level=4)
    print(f"inline const int ref_wd_db4_per_ncoef = {len(cper)};")
    for i, c in enumerate(cper):
        emit(f"wd_db4_per_c{i}", c)


if __name__ == "__main__":
    main()
