#!/usr/bin/env python3
"""PyWavelets 2-D DWT + threshold reference data (v11w-e). Plain C arrays (no STL).
Run: python3 tests/hesap-wavelet/gen_dwt2_refs.py > tests/hesap-wavelet/dwt2_refs.inc"""
import numpy as np
import pywt


def san(s):
    return s.replace(".", "_").replace("-", "_")


def emit(name, arr):
    print(f"inline const double ref_{name}[] = {{{', '.join(f'{float(x):.17g}' for x in np.asarray(arr).ravel())}}};")


def main():
    print("// GENERATED by gen_dwt2_refs.py — pywt dwt2 + threshold (v11w-e). C arrays (no STL).")
    print("#pragma once")

    R, C = 8, 12  # non-square, even
    k = np.arange(R * C, dtype=float)
    img = (np.sin(0.1 * k) + 0.5 * np.cos(0.03 * k) + 0.01 * k).reshape(R, C)
    emit("img", img)
    print(f"inline const int ref_img_rows = {R};")
    print(f"inline const int ref_img_cols = {C};")

    for wn in ["haar", "db2"]:
        for mode in ["periodization", "symmetric"]:
            cA, (cH, cV, cD) = pywt.dwt2(img, wn, mode=mode)
            tag = f"{san(wn)}_{mode}"
            emit(f"dwt2_{tag}_cA", cA)
            emit(f"dwt2_{tag}_cH", cH)
            emit(f"dwt2_{tag}_cV", cV)
            emit(f"dwt2_{tag}_cD", cD)
            print(f"inline const int ref_dwt2_{tag}_rows = {cA.shape[0]};")
            print(f"inline const int ref_dwt2_{tag}_cols = {cA.shape[1]};")

    # threshold references
    d = np.array([-3.0, -1.2, -0.7, 0.0, 0.4, 1.0, 1.5, 3.3])
    emit("thr_in", d)
    emit("thr_soft", pywt.threshold(d, 1.0, "soft"))
    emit("thr_hard", pywt.threshold(d, 1.0, "hard"))
    emit("thr_garrote", pywt.threshold(d, 1.0, "garrote"))


if __name__ == "__main__":
    main()
