#!/usr/bin/env python3
"""PyWavelets reference data for SWT + Wavelet Packets (v11w-c). Plain C arrays (no STL).
Run: python3 tests/hesap-wavelet/gen_swt_wpt_refs.py > tests/hesap-wavelet/swt_wpt_refs.inc"""
import numpy as np
import pywt


def san(s):
    return s.replace(".", "_").replace("-", "_")


def emit(name, arr):
    print(f"inline const double ref_{name}[] = {{{', '.join(f'{float(x):.17g}' for x in np.asarray(arr).ravel())}}};")


def make(n):
    i = np.arange(n, dtype=float)
    return np.sin(0.21 * i) + 0.4 * np.cos(0.09 * i) + 0.1 * np.sin(0.013 * i)


def main():
    print("// GENERATED by gen_swt_wpt_refs.py — pywt SWT + WaveletPacket (v11w-c). C arrays (no STL).")
    print("#pragma once")

    N = 64
    x = make(N)
    emit("swt_input", x)

    # SWT (à trous), pywt returns [(cA_n,cD_n), ..., (cA_1,cD_1)] coarse-first.
    for wn in ["haar", "db2", "db4", "sym3"]:
        level = 3
        coeffs = pywt.swt(x, wn, level=level)  # defaults: norm=False, trim_approx=False, start_level=0
        # store fine-first as cA_1,cD_1,...,cA_level,cD_level for easy indexing
        for lvl in range(level):
            cA, cD = coeffs[level - 1 - lvl]  # level-1 first
            emit(f"swt_{san(wn)}_L{lvl + 1}_cA", cA)
            emit(f"swt_{san(wn)}_L{lvl + 1}_cD", cD)
        # iswt round trip check value
        rec = pywt.iswt(coeffs, wn)
        emit(f"iswt_{san(wn)}", rec)

    # Wavelet Packet (full tree), mode='periodization'.
    for wn in ["db2", "sym3"]:
        wp = pywt.WaveletPacket(data=x, wavelet=wn, mode="periodization", maxlevel=3)
        for node in ["a", "d", "aa", "ad", "da", "dd", "aaa", "aad", "ada", "add", "daa", "dad", "dda", "ddd"]:
            emit(f"wp_{san(wn)}_{node}", wp[node].data)


if __name__ == "__main__":
    main()
