#!/usr/bin/env python3
"""PyWavelets CWT reference data (v11w-d). Plain C arrays (no STL). Complex coeffs as interleaved re,im.
Run: python3 tests/hesap-wavelet/gen_cwt_refs.py > tests/hesap-wavelet/cwt_refs.inc"""
import numpy as np
import pywt


def san(s):
    return s.replace(".", "_").replace("-", "_")


def emit(name, arr):
    print(f"inline const double ref_{name}[] = {{{', '.join(f'{float(x):.17g}' for x in np.asarray(arr).ravel())}}};")


def emit_cplx(name, arr):
    flat = np.asarray(arr).ravel()
    inter = np.empty(flat.size * 2)
    inter[0::2] = np.real(flat)
    inter[1::2] = np.imag(flat)
    emit(name, inter)


def main():
    print("// GENERATED by gen_cwt_refs.py — pywt.cwt reference (v11w-d). C arrays (no STL). Complex = interleaved re,im.")
    print("#pragma once")

    n = 96
    i = np.arange(n, dtype=float)
    x = np.sin(0.2 * i) + 0.3 * np.cos(0.05 * i)
    emit("cwt_input", x)
    scales = np.array([2.0, 4.0, 8.0, 16.0])
    emit("cwt_scales", scales)

    # real wavelets
    for wn in ["mexh", "morl", "gaus2", "gaus4"]:
        coef, freqs = pywt.cwt(x, scales, wn)
        emit(f"cwt_{san(wn)}", np.real(coef))
        emit(f"cwt_{san(wn)}_freqs", freqs)

    # complex wavelets
    for wn in ["cmor1.5-1.0", "cgau2", "shan1.0-0.5", "fbsp2-1.0-0.5"]:
        coef, freqs = pywt.cwt(x, scales, wn)
        emit_cplx(f"cwt_{san(wn)}", coef)
        emit(f"cwt_{san(wn)}_freqs", freqs)


if __name__ == "__main__":
    main()
